import {RegionalMaterialCostEngine} from "@/components/regional-material-cost-engine";
import {CostSavingRuleEngine} from "@/components/cost-saving-rule-engine";
import {CostControlIntegrationWorkbench} from "@/components/cost-control-integration-workbench";
import {CostOptionComparisonWorkbench} from "@/components/cost-option-comparison-workbench";
import {LandCostWorkbench} from "@/components/land-cost-workbench";
import {ProjectIntegrityWorkbench} from "@/components/project-integrity-workbench";
import {ConstructionControlCenter} from "@/components/construction-control-center";import {ConstructionDocumentControl} from "@/components/construction-document-control";import {ConstructionSequenceWorkspace} from "@/components/construction-sequence-workspace";import {ConstructionLog} from "@/components/construction-log";import {ConstructionPackageBuilder} from "@/components/construction-package-builder";import {ConstructionDeliveryWorkspace} from "@/components/construction-delivery-workspace";import {FieldSyncWorkspace} from "@/components/field-sync-workspace";import {ProjectSchedulePlanner} from "@/components/project-schedule-planner";import {MaterialSelectionWorkbench} from "@/components/material-selection-workbench";import {ProductAreaPage} from "@/components/product-area-page";import areas from "@/data/product-areas.json";
export const metadata={title:"Construction progress workspace",description:"Capture device-local construction updates while preserving evidence and review boundaries."};
export default function Page(){const area=areas.find(item=>item.slug==="construction")!;return <ProductAreaPage area={area} insert={<><ProjectSchedulePlanner/><ConstructionSequenceWorkspace/><ConstructionDeliveryWorkspace/><ProjectIntegrityWorkbench/><ConstructionControlCenter/><ConstructionDocumentControl/><MaterialSelectionWorkbench/><LandCostWorkbench/><CostSavingRuleEngine/><CostControlIntegrationWorkbench/><RegionalMaterialCostEngine/><CostOptionComparisonWorkbench/><ConstructionPackageBuilder/><ConstructionLog/><FieldSyncWorkspace/></>}/>}
