import Image from "next/image";
import Link from "next/link";
import {HeroBuildTimelapse} from "@/components/hero-build-timelapse";
import {LandingProductShowcase} from "@/components/landing-product-showcase";
import {SiteFooter} from "@/components/site-footer";
import {SiteHeader} from "@/components/site-header";
import areas from "@/data/product-areas.json";

const lifecycle=[["01","Understand the need","Community, capacity, programs, governance and the operating future."],["02","Choose the place","Land or an existing building, access, utilities, climate and risk."],["03","Shape the mosque","Qibla, prayer rows, wudu, inclusion, learning, parking and growth."],["04","Prepare approvals","Jurisdiction, current sources, submissions, comments and inspections."],["05","Build the financial plan","Cost assumptions, funding, waqf, opening needs and reserves."],["06","Prepare sourcing","Scopes, suppliers, comparisons, samples, delivery and installation."],["07","Coordinate the build","Progress, questions, changes, inspections and handover evidence."],["08","Open and care for it","Commissioning, assets, maintenance, governance and learning."]];
const previews=[["/assets/mockups/mosque_interior_design_studio_mockup.png","Interior planning","Compare rooms, finishes and spatial choices."],["/assets/mockups/mosque_parking_compliance_dashboard.png","Access and approvals","Explore peak demand and likely local requirements."],["/assets/mockups/mosque.build_waqf_library_dashboard_mockup.png","Waqf and library","Coordinate community needs, giving and stewardship."],["/assets/mockups/mosque_construction_progress_dashboard.png","Construction coordination","Keep progress, questions, inspections and handover together."]];
const questions=[["Does this replace architects or engineers?","No. It helps communities prepare, compare and coordinate work around qualified professionals."],["Can we begin before owning land?","Yes. Clarifying community need and site criteria early can prevent expensive lock-in."],["Can we convert an existing building?","Yes. Explore fit, qibla, access, services, risk and review needs before committing."],["Is permit information guaranteed?","No. The workspace keeps likely requirements separate from verified authority decisions."],["Will my draft be uploaded?","The current public workspace saves project drafts on this device unless you choose to export them."]];

export default function Home(){return <><SiteHeader/><main>
<section className="landingHero"><div className="heroCopy"><div className="eyebrow">FROM COMMUNITY NEED TO A LIVING INSTITUTION</div><h1>Bring mosques<br/><em>to life.</em></h1><p className="heroLead">Plan the journey from community brief and site choice through design, approvals, funding, construction, opening and long-term care.</p><div className="heroActions"><Link className="button" href="/start">Start your mosque project ↗</Link><Link className="secondaryButton" href="/features">See how it works</Link></div><div className="trustLine"><span>Clear sources</span><span>Qualified review</span><span>Community-centered</span><span>Whole journey</span></div></div><div className="heroVisual"><HeroBuildTimelapse/></div></section>
<section className="principleStrip"><span>Plan before you render.</span><span>Verify before you claim.</span><span>Cost before you commit.</span><span>Maintain after you open.</span></section>
<section className="section splitIntro"><div><div className="eyebrow dark">ONE CONNECTED JOURNEY</div><h2>A mosque project is a chain of decisions.</h2></div><p className="sectionLead">A change to capacity, site or materials can affect cost, approvals, sourcing, construction and long-term care. Keep those decisions together.</p></section>
<section className="lifecycle sectionNarrow">{lifecycle.map(([number,title,body])=><article className="lifeStep" key={number}><span className="stepNo">{number}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</section>
<LandingProductShowcase/>
<section className="darkSection"><div className="section"><div className="eyebrow gold">YOUR PROJECT JOURNEY</div><h2>Open the right workspace when you need it.</h2><div className="areaCardGrid">{areas.map(area=><Link href={`/${area.slug}`} className="areaCard" key={area.slug}><span>{area.eyebrow}</span><h3>{area.title}</h3><p>{area.summary}</p><b>Open this workspace ↗</b></Link>)}</div></div></section>
<section className="section"><div className="sectionHeading"><div><div className="eyebrow dark">MOSQUE PROJECT CONCEPTS</div><h2>See different ways the journey could work.</h2></div><Link href="/prototypes" className="secondaryButton">Browse all 63 concepts</Link></div><div className="previewGrid">{previews.map((preview,index)=><article className={`previewCard p${index+1}`} key={preview[0]}><div className="previewMedia"><Image src={preview[0]} alt={`${preview[1]} concept`} width={1600} height={1000}/></div><div className="previewCopy"><span className="miniTag">{String(index+1).padStart(2,"0")}</span><h3>{preview[1]}</h3><p>{preview[2]}</p></div></article>)}</div></section>
<section className="featureSpotlight sectionNarrow"><div className="spotVisual"><div className="phoneMock"><div className="phoneTop">mosque.build</div><div className="phoneHero">Existing-space study</div><div className="scanRoom"><div className="scanGrid"/><div className="qiblaArrow">Qibla ↗</div></div><div className="phoneStats"><div><b>Capacity</b><span>Compare after dimensions are verified</span></div><div><b>Review next</b><span>Use · structure · fire · services</span></div></div></div></div><div className="spotCopy"><div className="eyebrow dark">ADAPTIVE REUSE</div><h2>Explore an existing space before committing.</h2><p>Record dimensions, study qibla and prayer rows, and compare conversion approaches while keeping professional reviews visible.</p><ul><li>Manual measurement and plan-import paths</li><li>Existing, remove, add and services layers</li><li>Wudu and accessible-route questions</li><li>Small, balanced and phased approaches</li></ul><Link href="/design" className="secondaryButton">Open design workspace</Link></div></section>
<section className="section"><div className="eyebrow dark">MAKE UNCERTAINTY VISIBLE</div><h2>Know what still needs checking.</h2><div className="truthCallout"><div><span className="statusDot"/><b>A permit checklist is not an approval.</b></div><div><span className="statusDot"/><b>A concept image is not a construction drawing.</b></div><div><span className="statusDot"/><b>A price needs its source, date and scope.</b></div><div><span className="statusDot"/><b>Qualified people make regulated decisions.</b></div></div><div className="centerActions"><Link href="/trust" className="secondaryButton">How mosque.build handles trust</Link></div></section>
<section className="section faq"><div className="eyebrow dark">COMMON QUESTIONS</div><h2>Questions worth asking early.</h2><div className="faqGrid">{questions.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
<section className="ctaSection"><div className="ctaInner"><div className="eyebrow gold">START WITH CLARITY</div><h2>Tell us what your community is trying to make real.</h2><p>New mosque, expansion, existing-space conversion, prayer room, madrasa, community center or phased campus.</p><div className="heroActions"><Link href="/start" className="button">Create your first brief ↗</Link><Link href="/resources" className="secondaryButton lightButton">Find a useful next step</Link></div></div></section>
</main><SiteFooter/></>}
