import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import{ARCHITECTURE_KIT_SCHEMA,architectureKitChecks,componentTypes,createArchitectureComponent,createArchitectureKit,createFullMosqueStarter,safeArchitectureKit}from"../apps/web/lib/architectural-components.ts";
test("architecture kit is renderer neutral bounded and portable",()=>{const kit=createArchitectureKit();assert.equal(kit.schema,ARCHITECTURE_KIT_SCHEMA);assert.ok(safeArchitectureKit(kit));assert.equal(safeArchitectureKit({...kit,components:Array(81).fill(kit.components[0])}),null);assert.doesNotMatch(fs.readFileSync("apps/web/lib/architectural-components.ts","utf8"),/from ["']three|THREE\./)});
test("every supported component creates finite semantic geometry inputs",()=>{for(const type of componentTypes){const c=createArchitectureComponent(type);assert.equal(c.type,type);assert.equal(c.editable,true);assert.ok([...c.position,...Object.values(c.dimensions)].every(Number.isFinite))}});
test("full mosque starter coordinates envelope structure access worship water and energy",()=>{const kit=createFullMosqueStarter(),types=new Set(kit.components.map(c=>c.type));for(const type of ["flat-roof","column-grid","external-wall","accessible-door","mihrab","prayer-rows","wudu-line","ramp","service-riser","courtyard","solar-array"])assert.ok(types.has(type),type);assert.ok(safeArchitectureKit(kit));assert.ok(kit.components.every(c=>c.position.some(value=>value!==0)))});
test("review engine catches slender minarets steep ramps and missing prayer rows",()=>{const kit=createArchitectureKit();kit.components=[createArchitectureComponent("minaret"),createArchitectureComponent("ramp")];kit.components[0].dimensions={widthM:1,heightM:30,depthM:1,count:3};kit.components[1].dimensions={widthM:1.5,heightM:2,depthM:10,count:1};const messages=architectureKitChecks(kit).map(x=>x.message).join(" ");assert.match(messages,/slenderness/);assert.match(messages,/steeper than 1:12/);assert.match(messages,/prayer-row/)});
test("Three adapter uses lathe extrude and instancing with semantic metadata",()=>{const adapter=fs.readFileSync("apps/web/lib/architecture-kit-three-adapter.ts","utf8");for(const token of["LatheGeometry","ExtrudeGeometry","InstancedMesh","componentId","layer:\"architecture\""])assert.match(adapter,new RegExp(token))});
test("workspace is integrated with design project export and lifecycle",()=>{const page=fs.readFileSync("apps/web/app/design/page.tsx","utf8"),pkg=fs.readFileSync("apps/web/lib/project-package.ts","utf8"),flow=fs.readFileSync("apps/web/lib/workflow-integration.ts","utf8");assert.match(page,/ArchitectureKitStudio/);assert.match(pkg,/architectureKit/);assert.match(flow,/Architectural component kit/)});
test("saved components join the primary model as a toggleable layer",()=>{const viewer=fs.readFileSync("apps/web/components/three-schematic-viewer.tsx","utf8"),inspection=fs.readFileSync("apps/web/lib/model-inspection.ts","utf8");assert.match(viewer,/buildArchitectureKitGroup/);assert.match(viewer,/mosque-build:architecture-kit-change/);assert.match(inspection,/architecture/)});
test("interior systems join unified scene export and update flow",()=>{const viewer=fs.readFileSync("apps/web/components/three-schematic-viewer.tsx","utf8"),inspection=fs.readFileSync("apps/web/lib/model-inspection.ts","utf8");assert.match(viewer,/buildInteriorSystemsGroup/);assert.match(viewer,/mosque-build:interior-systems-change/);assert.match(viewer,/intersectObjects\([^\n]+true\)/);assert.match(inspection,/"interiors"/)})
