import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import lineages from"../apps/web/data/architecture-lineages.json" with{type:"json"};import{createCulturalGuides}from"../apps/web/lib/cultural-model-guides.ts";
const ids=["maghrebi-kairouan-court","swahili-coral-lime","maldivian-coral-timber","bengal-brick-multibay"];
const continuedIds=["djenne-earthen-stewardship","malay-relocatable-timber","mostar-compact-restoration"];
test("new regional studies carry institutional provenance and current observation dates",()=>{const added=lineages.filter(x=>ids.includes(x.id));assert.equal(added.length,4);for(const x of added){assert.match(x.source.url,/^https:\/\/whc\.unesco\.org\//);assert.equal(x.source.observedAt,"2026-09-09");assert.equal(x.status,"source_backed");assert.ok(x.source.rights);assert.ok(x.spatialPrinciples.length>=3);assert.ok(x.climateAndMaterial.length>=3);assert.ok(x.avoid.length>=3)}});
test("heritage records do not become unsafe material or authenticity claims",()=>{const text=JSON.stringify(lineages.filter(x=>ids.includes(x.id)));assert.match(text,/Do not quarry living reef coral/);assert.match(text,/tentative-list record/);assert.match(text,/lawful sourcing/);assert.doesNotMatch(text,/authentic template|construction-ready|approved design/i)});
test("new lineages produce analytical model guides rather than reconstructed geometry",()=>{for(const id of ids){const guides=createCulturalGuides(id,30,36);assert.ok(guides.length>=1);assert.ok(guides.every(x=>x.note&&!x.note.toLowerCase().includes("replica")))}});
test("continued regional studies carry provenance, design consequences and cautions",()=>{const added=lineages.filter(x=>continuedIds.includes(x.id));assert.equal(added.length,3);for(const x of added){assert.equal(x.source.observedAt,"2026-09-09");assert.equal(x.status,"source_backed");assert.match(x.source.url,/^https:\/\/(whc\.unesco\.org|www\.archnet\.org)\//);assert.ok(x.designMoves.length>=3);assert.ok(x.avoid.every(y=>y.startsWith("Do not")))}});
test("continued studies keep care reuse and restoration boundaries explicit",()=>{const text=JSON.stringify(lineages.filter(x=>continuedIds.includes(x.id)));for(const term of["unpaid or guaranteed labour","reuse percentage predicts","post-conflict reconstruction","not reproduced"])assert.match(text,new RegExp(term))});
test("comparison feature supports saved project briefs and evidence lenses",()=>{const ui=fs.readFileSync("apps/web/components/architecture-comparison.tsx","utf8"),pkg=fs.readFileSync("apps/web/lib/project-package.ts","utf8");for(const term of["Select up to three","Spatial system","Climate + material","Moves to test","Do not infer","Provenance","Export brief","Why might these precedents be relevant","Accountable review role"])assert.ok(ui.includes(term));assert.match(ui,/not a design recommendation/);assert.match(ui,/mosque-build:project-change/);assert.match(pkg,/architecturePrecedentBrief/)});
