import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {campusChecks,campusMetrics,campusPrimitives,campusZoneKinds,createCampusPlan,safeCampusPlan,CAMPUS_PLANNING_SCHEMA} from "../apps/web/lib/campus-planning.ts";
import {projectSections} from "../apps/web/lib/project-package.ts";
import {workflowNodes} from "../apps/web/lib/workflow-integration.ts";

const domain=fs.readFileSync(new URL("../apps/web/lib/campus-planning.ts",import.meta.url),"utf8");
const ui=fs.readFileSync(new URL("../apps/web/components/campus-planning-studio.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../apps/web/components/campus-planning-studio.css",import.meta.url),"utf8");

test("campus plan is complete, bounded and renderer neutral",()=>{const plan=createCampusPlan("2026-01-01");assert.equal(plan.schema,CAMPUS_PLANNING_SCHEMA);assert.deepEqual(new Set(plan.zones.map(zone=>zone.kind)),new Set(campusZoneKinds));assert.equal(safeCampusPlan({...plan,arrivalWindowMinutes:0,grossAreaPerParkingSpaceM2:999})?.arrivalWindowMinutes,5);assert.equal(safeCampusPlan({...plan,schema:"wrong"}),null);assert.doesNotMatch(domain,/from ["']three|THREE\.|localStorage/)});
test("road and parking arithmetic is deterministic and assumption-labelled",()=>{const metrics=campusMetrics(createCampusPlan());assert.equal(metrics.parkingNeed,113);assert.equal(metrics.parkingStudyCapacity,31);assert.equal(metrics.parkingGap,82);assert.equal(metrics.accessibleStudySpaces,6);assert.equal(metrics.dropOffPeople,108);assert.equal(metrics.dropOffVehicles,45);assert.equal(metrics.dropOffBays,2);assert.equal(metrics.arrivalVehiclesPerMinute,2.5);assert.equal(metrics.departureVehiclesPerMinute,3.8);assert.equal(metrics.modeShareTotal,100)});
test("coordination checks catch site, movement and programme conflicts",()=>{const plan=createCampusPlan();plan.siteWidthM=40;plan.zones.find(zone=>zone.kind==="road").xM=30;plan.zones.find(zone=>zone.kind==="pedestrian").xM=31;const titles=campusChecks(plan).map(check=>check.title);assert.ok(titles.includes("Zone extends beyond working site"));assert.ok(titles.includes("Pedestrian and vehicle conflict"));assert.ok(titles.includes("Parking study gap"))});
test("travel planning exposes incomplete mode and shared-transport assumptions",()=>{const plan=createCampusPlan();plan.activeTravelSharePercent=20;plan.transitSharePercent=10;plan.bicycleSpaces=0;plan.coachSpaces=0;const titles=campusChecks(plan).map(check=>check.title);assert.ok(titles.includes("Travel shares do not total 100%"));assert.ok(titles.includes("No bicycle parking in the study"));assert.ok(titles.includes("Coach and shared-transport arrival unresolved"))});
test("portable primitives preserve semantic ids without renderer objects",()=>{const primitives=campusPrimitives(createCampusPlan());assert.equal(primitives.length,10);assert.ok(primitives.every(item=>item.id&&item.size.every(Number.isFinite)));assert.ok(primitives.some(item=>item.kind==="daycare"))});
test("studio supports interaction, persistence, export, responsive use and review gates",()=>{for(const token of ["OrbitControls","pointerdown","Export campus study","patchProgram","school","daycare","madrasa","recreation","not local requirements","authority review","Working travel-mode split","Bicycle spaces","Departure vehicles / min"])assert.match(ui,new RegExp(token,"i"));for(const token of ["min-height:44px",":focus-visible","@media(max-width:700px)","scroll-snap-type"])assert.match(css,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});
test("campus plan participates in project package and workflow",()=>{assert.equal(projectSections.find(section=>section.id==="campusPlanning")?.key,"mosque-build.campus-planning.v1");assert.equal(workflowNodes.find(node=>node.id==="campusPlanning")?.href,"/design#campus-title")});
