import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";
import{blankRuleReview,COST_RULE_KEY,COST_RULE_SCHEMA,costRuleCategories,costRuleSummary,costSavingRules,createCostRuleStudy,modelFocusForRule,rankedCostRules,ruleReviewGaps,safeCostRuleStudy}from"../apps/web/lib/cost-saving-rules.ts";
import{projectSections}from"../apps/web/lib/project-package.ts";import{workflowNodes}from"../apps/web/lib/workflow-integration.ts";
test("all supplied cost rules are preserved with unique stable identifiers",()=>{assert.equal(costSavingRules.length,100);assert.equal(new Set(costSavingRules.map(x=>x.id)).size,100);assert.equal(costRuleCategories.length,11);for(const rule of costSavingRules){assert.match(rule.id,/^COST-\d{3}$/);for(const key of["strategy","how_it_saves_money","threejs_parameter","architecture_construction_rule","tradeoff_or_risk"])assert.ok(rule[key].trim())}});
test("cost rule study is bounded portable and project integrated",()=>{const study=createCostRuleStudy();assert.equal(study.schema,COST_RULE_SCHEMA);assert.equal(safeCostRuleStudy(study)?.status,"executable");assert.equal(safeCostRuleStudy({...study,reviews:Array(101).fill(blankRuleReview("COST-001"))}),null);assert.equal(projectSections.find(x=>x.id==="costSavingRules")?.key,COST_RULE_KEY);assert.deepEqual(workflowNodes.find(x=>x.id==="costRules")?.dependencies,["brief","landCost"])});
test("rule signals rank transparently without inventing savings",()=>{const ranked=rankedCostRules({keywords:["roof drainage waterproof roof"],sources:["roof study"]});assert.equal(ranked[0].rule.category,"Roof");assert.ok(ranked[0].matchedTerms.length);assert.equal("savingPercent"in ranked[0],false)});
test("review readiness requires applicability ownership evidence and rationale",()=>{const rule=costSavingRules[0],blank=blankRuleReview(rule.id);assert.ok(ruleReviewGaps(rule,blank).includes("applicability"));const accepted={...blank,applicability:"applicable",decision:"accepted-user-record",ownerRole:"Quantity surveyor",evidenceRef:"Option estimate A",notes:"Baseline and safeguards recorded"};assert.deepEqual(ruleReviewGaps(rule,accepted),[]);assert.equal(costRuleSummary({...createCostRuleStudy(),reviews:[accepted]}).accepted,1)});
test("3D handoff remains renderer neutral and does not claim geometry change",()=>{const focus=modelFocusForRule(costSavingRules[0]);assert.equal(focus.schema,"mosque.build/cost-rule-model-focus@1");assert.ok(focus.layers.length);assert.match(focus.boundary,/does not calculate savings, alter geometry/);assert.equal(JSON.stringify(focus).includes("THREE.Mesh"),false)});
test("interface links cost rules to design construction and Three coordination",()=>{const ui=fs.readFileSync(new URL("../apps/web/components/cost-saving-rule-engine.tsx",import.meta.url),"utf8"),viewer=fs.readFileSync(new URL("../apps/web/components/three-schematic-viewer.tsx",import.meta.url),"utf8"),design=fs.readFileSync(new URL("../apps/web/app/design/page.tsx",import.meta.url),"utf8"),construction=fs.readFileSync(new URL("../apps/web/app/construction/page.tsx",import.meta.url),"utf8");for(const term of["100 design and delivery strategies","Accountable role","Evidence reference","Inspect parameter in 3D","Cost-plan gate","Construction gate","do not predict savings"])assert.match(ui,new RegExp(term));assert.match(viewer,/cost-rule-model-focus/);assert.match(viewer,/No saving or geometry change is inferred/);assert.match(design,/CostSavingRuleEngine/);assert.match(construction,/CostSavingRuleEngine/)});
