import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import * as engine from "../apps/web/lib/islamic-geometry-engine.ts";

test("geometry engine generates a portable repeat with metrics",()=>{const result=engine.generateIslamicGeometry(engine.defaultGeometryParameters);assert.equal(result.schema,"mosque.build/islamic-geometry@1");assert.ok(result.segments.length>20);assert.ok(result.metrics.shortestSegmentM>0);assert.equal(result.repeatCell.widthM,1.2);assert.ok(result.crossings.length>0);assert.match(result.boundary,/Not a heritage reconstruction/)});
test("all geometric families produce finite points",()=>{for(const family of engine.geometryFamilies){const result=engine.generateIslamicGeometry({...engine.defaultGeometryParameters,family});assert.ok(result.segments.length);for(const segment of result.segments)for(const point of [segment.from,segment.to])assert.ok(point.every(Number.isFinite))}});
test("circle clipping keeps segment endpoints inside the normalized panel",()=>{const result=engine.generateIslamicGeometry({...engine.defaultGeometryParameters,clip:"circle",repeatX:4,repeatY:4});for(const segment of result.segments)for(const point of [segment.from,segment.to])assert.ok(Math.hypot(...point)<=.500001)});
test("safe workspace parser rejects malformed or oversized values",()=>{const valid=engine.createGeometryWorkspace();assert.ok(engine.safeGeometryWorkspace(valid));assert.equal(engine.safeGeometryWorkspace({...valid,parameters:{...valid.parameters,strapWidthM:9}}),null);assert.equal(engine.safeGeometryWorkspace({...valid,name:"x".repeat(161)}),null)});
test("SVG export is accessible, clipped and contains no script",()=>{const result=engine.generateIslamicGeometry(engine.defaultGeometryParameters),svg=engine.geometryToSvg(result,"Study <one>");assert.match(svg,/<title id="title">Study &lt;one&gt;<\/title>/);assert.match(svg,/clipPath/);assert.doesNotMatch(svg,/<script/i)});
test("symmetry operations alter geometry without changing the domain shape",()=>{const a=engine.generateIslamicGeometry({...engine.defaultGeometryParameters,symmetry:"p4m"}),b=engine.generateIslamicGeometry({...engine.defaultGeometryParameters,symmetry:"frieze"});assert.equal(a.segments.length,b.segments.length);assert.notDeepEqual(a.segments.map(x=>x.from),b.segments.map(x=>x.from))});
test("geometry workspace is included in project export and lifecycle",()=>{const pkg=fs.readFileSync("apps/web/lib/project-package.ts","utf8"),flow=fs.readFileSync("apps/web/lib/workflow-integration.ts","utf8");assert.match(pkg,/islamicGeometry/);assert.match(flow,/Geometry construction study/)});
