import test from "node:test";
import assert from "node:assert/strict";
import ts from "../apps/web/node_modules/typescript/lib/typescript.js";
import fs from "node:fs";
import vm from "node:vm";
const source=fs.readFileSync(new URL("../apps/web/lib/project-planning.ts",import.meta.url),"utf8").replace('import {durationDays,taskBlockers,type ScheduleTask} from "@/lib/project-schedule";','const durationDays=(task)=>Math.round((Date.parse(task.finish)-Date.parse(task.start))/86400000)+1; const taskBlockers=(task,tasks)=>task.dependsOn.filter(id=>tasks.find(x=>x.id===id)?.status!=="complete");');
const js=ts.transpile(source,{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}),module={exports:{}};
vm.runInNewContext(js,{module,exports:module.exports,Date,Map,Set});const api=module.exports;
const task=(patch={})=>({id:"a",name:"Brief",phase:"Brief",start:"2026-01-01",finish:"2026-01-10",progress:50,status:"in-progress",dependsOn:[],responsibleRole:"Lead",evidenceRef:"",notes:"",...patch});
test("phase rollups expose progress and readiness gaps",()=>{const rows=api.phaseRollups([task(),task({id:"b",progress:100,status:"complete",responsibleRole:"",start:"2026-01-11",finish:"2026-01-20"})]);assert.equal(rows[0].progress,75);assert.equal(rows[0].missingOwner,1);assert.equal(rows[0].missingEvidence,1)});
test("lookahead includes activities intersecting the window",()=>{const rows=api.lookahead([task(),task({id:"b",start:"2026-03-01",finish:"2026-03-10"})],"2026-01-05",30);assert.deepEqual(rows.map(x=>x.id),["a"])});
test("role load groups scheduled duration",()=>{const rows=api.roleLoad([task(),task({id:"b",responsibleRole:"",start:"2026-01-11",finish:"2026-01-12"})]);assert.equal(rows.find(x=>x.role==="Lead").days,10);assert.equal(rows.find(x=>x.role==="Unassigned").tasks,1)});
test("accepted milestones require evidence",()=>{const milestone={id:"m",title:"Review",targetDate:"2026-02-01",phase:"Design",ownerRole:"Design lead",status:"accepted",evidenceRef:"",acceptanceCriteria:"Recorded review"};assert.equal([...api.milestoneGaps(milestone)].join(","),"acceptance evidence");milestone.evidenceRef="record-1";assert.equal(api.milestoneGaps(milestone).length,0)});
test("safe parser rejects oversized and unsafe state",()=>{const state=api.createProjectPlanning("2026-01-01");assert.equal(api.safeProjectPlanning(state).schema,api.PROJECT_PLANNING_SCHEMA);assert.equal(api.safeProjectPlanning({...state,scenarioShiftDays:999}),null);assert.equal(api.safeProjectPlanning({...state,milestones:Array(101).fill({})}),null)});
