import features from "../data/architecture-feature-plan.json" with {type:"json"};
import modernFeatures from "../data/modern-architecture-feature-plan.json" with {type:"json"};
export const ARCHITECTURE_FEATURE_PLAN_SCHEMA="mosque.build/architecture-feature-plan@1" as const;
export const ARCHITECTURE_FEATURE_PLAN_KEY="mosque-build.architecture-feature-plan.v1";
export const featureStatuses=["concept","specified","scaffolded","executable","source_backed","beta","production_ready"] as const;
export type FeatureStatus=typeof featureStatuses[number];
export type ArchitectureFeature={id:string;number:number;source_number?:number;category:string;feature:string;what_it_adds:string;threejs_integration:string;threejs_implementation:string;status:string;source:{kind:string;observedAt:string;rights:string;confidence:string};review_gate:string};
export type PlannedFeature={featureId:string;priority:"now"|"next"|"later";status:FeatureStatus;ownerRole:string;evidenceRef:string;acceptanceNotes:string;updatedAt:string};
export type ArchitectureFeaturePlan={schema:typeof ARCHITECTURE_FEATURE_PLAN_SCHEMA;status:"executable";items:PlannedFeature[];updatedAt:string};
export const architectureFeatures=[...features,...modernFeatures] as ArchitectureFeature[];
export const createArchitectureFeaturePlan=():ArchitectureFeaturePlan=>({schema:ARCHITECTURE_FEATURE_PLAN_SCHEMA,status:"executable",items:[],updatedAt:""});
export const featureById=(id:string)=>architectureFeatures.find(x=>x.id===id);
export function safeArchitectureFeaturePlan(value:unknown):ArchitectureFeaturePlan|null{if(!value||typeof value!=="object")return null;const x=value as ArchitectureFeaturePlan;if(x.schema!==ARCHITECTURE_FEATURE_PLAN_SCHEMA||x.status!=="executable"||!Array.isArray(x.items)||x.items.length>200)return null;const ids=new Set<string>();for(const item of x.items){if(!item||!featureById(item.featureId)||ids.has(item.featureId)||!["now","next","later"].includes(item.priority)||!featureStatuses.includes(item.status)||typeof item.ownerRole!=="string"||item.ownerRole.length>160||typeof item.evidenceRef!=="string"||item.evidenceRef.length>1000||typeof item.acceptanceNotes!=="string"||item.acceptanceNotes.length>3000||typeof item.updatedAt!=="string")return null;ids.add(item.featureId)}return x}
export function planSummary(plan:ArchitectureFeaturePlan){return{selected:plan.items.length,now:plan.items.filter(x=>x.priority==="now").length,executable:plan.items.filter(x=>x.status==="executable"||x.status==="source_backed"||x.status==="beta"||x.status==="production_ready").length,owned:plan.items.filter(x=>x.ownerRole.trim()).length,evidenced:plan.items.filter(x=>x.evidenceRef.trim()).length}}
export function featureTestPlan(feature:ArchitectureFeature){const gate=feature.review_gate.replaceAll("-",", ");return["Unit: deterministic domain rules and bounded numeric inputs","Integration: portable project state → renderer adapter → export","Accessibility: keyboard, labels, non-color signals and reduced motion","Responsive: mobile editor and desktop model parity","Provenance: source, observed date, rights, confidence and review state",`Review: ${gate} gate; outputs remain conceptual until accepted`]}
