export const ARCHITECTURE_KIT_SCHEMA="mosque.build/architecture-kit@1" as const;
export const ARCHITECTURE_KIT_KEY="mosque-build.architecture-kit.v1";
export const componentTypes=["dome","minaret","arcade","mihrab","prayer-rows","wudu-line","ramp","courtyard"]as const;
export type ArchitectureComponentType=typeof componentTypes[number];
export type ArchitecturePrimitive="box"|"cylinder"|"cone"|"lathe"|"arch"|"lines"|"instances";
export type ArchitectureComponent={id:string;type:ArchitectureComponentType;name:string;family:string;position:[number,number,number];rotationDeg:number;dimensions:{widthM:number;heightM:number;depthM:number;count:number};primitive:ArchitecturePrimitive;materialRole:"structure"|"envelope"|"sacred"|"water"|"access"|"landscape";phase:1|2|3;status:"concept"|"specified";editable:true;sourceBasis:string;reviewRole:string;notes:string};
export type ArchitectureKit={schema:typeof ARCHITECTURE_KIT_SCHEMA;status:"executable";name:string;qiblaBearingDeg:number;qiblaAlignment:"building-axis"|"internal-rotation"|"hybrid";components:ArchitectureComponent[];updatedAt:string;boundary:string};
const definitions:Record<ArchitectureComponentType,{family:string;primitive:ArchitecturePrimitive;size:[number,number,number,number];role:ArchitectureComponent["materialRole"]}>={
 dome:{family:"hemispherical",primitive:"lathe",size:[12,5,12,1],role:"envelope"},minaret:{family:"staged",primitive:"cylinder",size:[3,24,3,3],role:"structure"},arcade:{family:"pointed",primitive:"instances",size:[18,4.5,1,7],role:"structure"},mihrab:{family:"recessed arch",primitive:"arch",size:[2.4,3.6,.45,1],role:"sacred"},"prayer-rows":{family:"saff guide",primitive:"lines",size:[18,.02,14,10],role:"sacred"},"wudu-line":{family:"seated stations",primitive:"instances",size:[8,1.1,1.2,6],role:"water"},ramp:{family:"straight concept",primitive:"box",size:[1.5,.9,10,1],role:"access"},courtyard:{family:"climate court",primitive:"box",size:[18,.12,16,1],role:"landscape"}};
export function createArchitectureComponent(type:ArchitectureComponentType,index=1):ArchitectureComponent{const d=definitions[type];return{id:`architecture-${type}-${Date.now()}-${index}`,type,name:`${type.replaceAll("-"," ")} study ${index}`,family:d.family,position:[0,d.size[1]/2,0],rotationDeg:0,dimensions:{widthM:d.size[0],heightM:d.size[1],depthM:d.size[2],count:d.size[3]},primitive:d.primitive,materialRole:d.role,phase:type==="prayer-rows"||type==="ramp"?1:2,status:"concept",editable:true,sourceBasis:"",reviewRole:"",notes:""}}
export function createArchitectureKit():ArchitectureKit{return{schema:ARCHITECTURE_KIT_SCHEMA,status:"executable",name:"Architectural component study",qiblaBearingDeg:0,qiblaAlignment:"building-axis",components:[createArchitectureComponent("dome",1),createArchitectureComponent("minaret",2),createArchitectureComponent("prayer-rows",3)],updatedAt:"",boundary:"Conceptual component geometry only. Not a historical reconstruction, structural or MEP design, accessibility or fire check, fabrication model, cost, permit finding or approval."}}
const finite=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max,txt=(v:unknown,n:number)=>typeof v==="string"&&v.length<=n;
export function safeArchitectureKit(value:unknown):ArchitectureKit|null{if(!value||typeof value!=="object")return null;const x=value as ArchitectureKit;if(x.schema!==ARCHITECTURE_KIT_SCHEMA||x.status!=="executable"||!txt(x.name,160)||!finite(x.qiblaBearingDeg,-360,360)||!["building-axis","internal-rotation","hybrid"].includes(x.qiblaAlignment)||!Array.isArray(x.components)||x.components.length>80)return null;if(!x.components.every(c=>txt(c.id,180)&&componentTypes.includes(c.type)&&txt(c.name,160)&&txt(c.family,100)&&Array.isArray(c.position)&&c.position.length===3&&c.position.every(v=>finite(v,-500,500))&&finite(c.rotationDeg,-360,360)&&finite(c.dimensions?.widthM,.05,200)&&finite(c.dimensions?.heightM,.01,300)&&finite(c.dimensions?.depthM,.05,200)&&finite(c.dimensions?.count,1,200)&&[1,2,3].includes(c.phase)&&["concept","specified"].includes(c.status)&&txt(c.sourceBasis,1000)&&txt(c.reviewRole,200)&&txt(c.notes,3000)))return null;return x}
export function architectureKitChecks(kit:ArchitectureKit){const checks:{level:"warning"|"blocker";componentId?:string;message:string}[]=[];for(const c of kit.components){if(c.type==="minaret"&&c.dimensions.heightM/Math.max(c.dimensions.widthM,c.dimensions.depthM)>10)checks.push({level:"blocker",componentId:c.id,message:`${c.name}: slenderness exceeds 10:1; structural, wind, seismic, foundation and maintenance-access design are unresolved.`});if(c.type==="dome"&&!c.sourceBasis)checks.push({level:"warning",componentId:c.id,message:`${c.name}: geometry and support-system basis are not recorded.`});if(c.type==="wudu-line"&&!/drain|wet|dry/i.test(c.notes))checks.push({level:"warning",componentId:c.id,message:`${c.name}: record wet/dry separation, drainage and accessible-station coordination.`});if(c.type==="ramp"&&c.dimensions.heightM/Math.max(c.dimensions.depthM,.01)>1/12)checks.push({level:"blocker",componentId:c.id,message:`${c.name}: conceptual rise/run is steeper than 1:12; verify the applicable accessibility route, landings and handrails.`});if(!c.reviewRole)checks.push({level:"warning",componentId:c.id,message:`${c.name}: accountable review role is missing.`})}if(!kit.components.some(c=>c.type==="prayer-rows"))checks.push({level:"warning",message:"No prayer-row guide is present to coordinate columns, doors and sightlines."});return checks}
