export type ConsiderationCategory="Worship"|"Arrival"|"Accessibility"|"Water"|"Community"|"Climate"|"Delivery";
export type ArchitecturalConsideration={id:string;category:ConsiderationCategory;title:string;question:string;connections:string[];gate:"community"|"professional"|"authority"};
export const architecturalConsiderations:ArchitecturalConsideration[]=[
 {id:"qibla-source",category:"Worship",title:"Qibla evidence",question:"What source, accuracy and reviewer support the working bearing?",connections:["Site","Prayer rows"],gate:"professional"},{id:"saff-geometry",category:"Worship",title:"Prayer-row geometry",question:"How do columns, doors and circulation affect complete rows?",connections:["Structure","Egress"],gate:"professional"},{id:"overflow",category:"Worship",title:"Peak overflow",question:"Where can peak attendance expand without blocking safe routes?",connections:["Landscape","Operations"],gate:"professional"},{id:"imam-zone",category:"Worship",title:"Imam and minbar zone",question:"How will visibility, audibility and accessible approach be reviewed?",connections:["Acoustics","Accessibility"],gate:"community"},
 {id:"threshold",category:"Arrival",title:"Legible welcome threshold",question:"Can a first-time visitor understand entry, shoes, wudu and prayer routes?",connections:["Wayfinding","Shoes"],gate:"community"},{id:"surge",category:"Arrival",title:"Friday surge",question:"Where do arrival and departure flows cross or queue?",connections:["Drop-off","Egress"],gate:"professional"},{id:"shoes",category:"Arrival",title:"Shoe transition",question:"Can storage expand without narrowing accessible circulation?",connections:["Prayer hall","Cleaning"],gate:"community"},{id:"after-hours",category:"Arrival",title:"After-hours zoning",question:"Can community rooms operate while worship and secure areas remain legible?",connections:["Security","Energy"],gate:"community"},
 {id:"continuous-route",category:"Accessibility",title:"Continuous accessible route",question:"Is there a step-free journey from arrival through every priority space?",connections:["Parking","Prayer","Wudu"],gate:"professional"},{id:"prayer-positions",category:"Accessibility",title:"Integrated prayer positions",question:"Are mobility-device positions distributed with families rather than isolated?",connections:["Saff","Circulation"],gate:"community"},{id:"sensory",category:"Accessibility",title:"Sensory legibility",question:"Do lighting, acoustics, signage and quiet retreat support varied needs?",connections:["Interiors","Wayfinding"],gate:"community"},{id:"accessible-wudu",category:"Accessibility",title:"Accessible wudu journey",question:"Can a user reach, use and leave wudu safely and with dignity?",connections:["Water","Toilets"],gate:"professional"},
 {id:"wet-dry",category:"Water",title:"Wet and dry separation",question:"Where are splash, drainage and footwear transitions resolved?",connections:["Cleaning","Circulation"],gate:"professional"},{id:"wudu-maintenance",category:"Water",title:"Wudu maintenance access",question:"Can traps, valves and finishes be inspected and repaired safely?",connections:["MEP","Operations"],gate:"professional"},{id:"water-evidence",category:"Water",title:"Water assumptions",question:"Which demand, supply, storage and reuse assumptions still need evidence?",connections:["Utilities","Climate"],gate:"professional"},
 {id:"youth",category:"Community",title:"Connected youth space",question:"Is youth territory visible and connected without disrupting prayer?",connections:["Courtyard","Acoustics"],gate:"community"},{id:"family",category:"Community",title:"Family dignity",question:"Do family routes offer proximity, choice and equitable amenity quality?",connections:["Prayer","Toilets"],gate:"community"},{id:"care",category:"Community",title:"Private care route",question:"Can counseling, aid and bereavement support happen without public exposure?",connections:["Office","Janazah"],gate:"community"},{id:"food",category:"Community",title:"Food and hospitality",question:"How do deliveries, storage, serving, waste and licensing affect the plan?",connections:["Kitchen","Service yard"],gate:"authority"},
 {id:"orientation",category:"Climate",title:"Orientation evidence",question:"Have sun, wind, rain and neighboring conditions been recorded rather than assumed?",connections:["Site","Envelope"],gate:"professional"},{id:"outdoor-room",category:"Climate",title:"Useful outdoor room",question:"When is outdoor social space shaded, sheltered and operationally usable?",connections:["Courtyard","Landscape"],gate:"community"},{id:"envelope",category:"Climate",title:"Maintainable envelope",question:"Can roofs, openings and façades be accessed, cleaned and repaired locally?",connections:["Materials","Drainage"],gate:"professional"},
 {id:"phasing",category:"Delivery",title:"Complete first phase",question:"Does phase one work safely and with dignity before later expansion?",connections:["Structure","MEP"],gate:"professional"},{id:"future-zone",category:"Delivery",title:"Protected expansion zone",question:"Which future connections and land must remain unobstructed?",connections:["Site","Operations"],gate:"professional"},{id:"review-map",category:"Delivery",title:"Review responsibility map",question:"Who owns community, professional and authority decisions at each gate?",connections:["Governance","Records"],gate:"authority"}
];
