import * as THREE from "three";
import type{ArchitectureComponent,ArchitectureKit}from"@/lib/architectural-components";
const colors={structure:0x9c8059,envelope:0x315f54,sacred:0xc18d32,water:0x2f7883,access:0x617484,landscape:0x78936d};
const material=(c:ArchitectureComponent)=>new THREE.MeshStandardMaterial({color:colors[c.materialRole],roughness:.72,transparent:c.type==="courtyard",opacity:c.type==="courtyard"?.55:1});
function domeGeometry(c:ArchitectureComponent){const {widthM:w,heightM:h}=c.dimensions,pts:THREE.Vector2[]=[];for(let i=0;i<=24;i++){const t=i/24,r=c.family.includes("bulb")?Math.sin(Math.PI*t)*w*.52*(.75+.35*t):c.family.includes("point")?Math.sin(Math.PI*t*.5)*w*.5:Math.sin(Math.PI*t*.5)*w*.5,y=t*h;pts.push(new THREE.Vector2(Math.max(.02,r),y-h/2))}return new THREE.LatheGeometry(pts,32)}
function archGeometry(c:ArchitectureComponent){const w=c.dimensions.widthM,h=c.dimensions.heightM,d=c.dimensions.depthM,shape=new THREE.Shape();shape.moveTo(-w/2,-h/2);shape.lineTo(-w/2,h*.08);shape.quadraticCurveTo(-w*.25,h/2,0,h/2);shape.quadraticCurveTo(w*.25,h/2,w/2,h*.08);shape.lineTo(w/2,-h/2);shape.closePath();return new THREE.ExtrudeGeometry(shape,{depth:d,bevelEnabled:false})}
function meshFor(c:ArchitectureComponent){const {widthM:w,heightM:h,depthM:d}=c.dimensions;if(c.type==="dome")return new THREE.Mesh(domeGeometry(c),material(c));if(c.type==="mihrab")return new THREE.Mesh(archGeometry(c),material(c));if(c.type==="minaret"){const g=new THREE.Group();for(let i=0;i<Math.max(1,Math.min(5,c.dimensions.count));i++){const scale=1-i*.08,part=new THREE.Mesh(c.family.includes("square")?new THREE.BoxGeometry(w*scale,h/c.dimensions.count,d*scale):new THREE.CylinderGeometry(w*.36*scale,w*.48*scale,h/c.dimensions.count,20),material(c));part.position.y=-h/2+(i+.5)*h/c.dimensions.count;g.add(part)}const cap=new THREE.Mesh(new THREE.ConeGeometry(w*.42,Math.min(h*.12,3),20),material(c));cap.position.y=h/2+Math.min(h*.06,1.5);g.add(cap);return g}if(c.type==="arcade"||c.type==="wudu-line"){const count=Math.max(1,Math.round(c.dimensions.count)),geometry=c.type==="arcade"?new THREE.CylinderGeometry(Math.min(.22,w/count*.12),Math.min(.26,w/count*.14),h,12):new THREE.BoxGeometry(Math.min(.75,w/count*.7),h*.55,d*.65),m=material(c),instances=new THREE.InstancedMesh(geometry,m,count),matrix=new THREE.Matrix4();for(let i=0;i<count;i++){const x=-w/2+(i+.5)*w/count;matrix.makeTranslation(x,c.type==="arcade"?0:-h*.2,0);instances.setMatrixAt(i,matrix)}return instances}if(c.type==="prayer-rows"){const points:number[]=[];for(let i=0;i<c.dimensions.count;i++){const z=-d/2+(i+.5)*d/c.dimensions.count;points.push(-w/2,0,z,w/2,0,z)}const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(points,3));return new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({color:colors.sacred}))}const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c));if(c.type==="ramp")mesh.rotation.x=-Math.atan2(h,d);return mesh}
export function buildArchitectureKitGroup(kit:ArchitectureKit){const group=new THREE.Group();group.name="mosque.build architectural component kit";group.userData={schema:kit.schema,status:kit.status,qiblaBearingDeg:kit.qiblaBearingDeg,qiblaAlignment:kit.qiblaAlignment,boundary:kit.boundary};for(const c of kit.components){const object=meshFor(c);object.name=c.name;object.position.set(...c.position);object.rotation.y=c.rotationDeg*Math.PI/180;object.userData={layer:"architecture",componentId:c.id,sourceId:c.id,type:c.type,family:c.family,dimensions:c.dimensions,materialRole:c.materialRole,phase:c.phase,status:c.status,editable:c.editable,sourceBasis:c.sourceBasis,reviewRole:c.reviewRole,baseY:c.position[1]};object.traverse(x=>{x.castShadow=true;x.receiveShadow=true});group.add(object)}return group}
export function disposeArchitectureKitGroup(group:THREE.Object3D){group.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.LineSegments){o.geometry.dispose();const m=o.material;(Array.isArray(m)?m:[m]).forEach(x=>x.dispose())}})}
