export const CAMPUS_PLANNING_SCHEMA = "mosque.build/campus-planning@1";
export const CAMPUS_PLANNING_KEY = "mosque-build.campus-planning.v1";
export const campusZoneKinds = ["mosque", "pedestrian", "courtyard", "parking", "road", "recreation", "school", "daycare", "madrasa", "service"] as const;
export type CampusZoneKind = (typeof campusZoneKinds)[number];
export type CampusZone = { id:string; kind:CampusZoneKind; label:string; enabled:boolean; xM:number; zM:number; widthM:number; depthM:number; heightM:number; capacity:number; notes:string };
export type CampusPlan = { schema:typeof CAMPUS_PLANNING_SCHEMA; status:"executable"; updatedAt:string; siteWidthM:number; siteDepthM:number; peakPeople:number; vehicleSharePercent:number; activeTravelSharePercent:number; transitSharePercent:number; peoplePerVehicle:number; parkingTurnover:number; accessibleParkingSharePercent:number; bicycleSpaces:number; coachSpaces:number; dropOffSharePercent:number; arrivalWindowMinutes:number; departureWindowMinutes:number; dropOffDwellMinutes:number; grossAreaPerParkingSpaceM2:number; schoolLearners:number; daycareChildren:number; madrasaLearners:number; pedestrianClearWidthM:number; courtyardShadePercent:number; zones:CampusZone[]; reviewNotes:string };

const clamp=(n:number,min:number,max:number,fallback=min)=>Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;
const zone=(id:string,kind:CampusZoneKind,label:string,xM:number,zM:number,widthM:number,depthM:number,heightM:number,capacity:number):CampusZone=>({id,kind,label,enabled:true,xM,zM,widthM,depthM,heightM,capacity,notes:""});

export function createCampusPlan(now=""):CampusPlan{return {schema:CAMPUS_PLANNING_SCHEMA,status:"executable",updatedAt:now,siteWidthM:72,siteDepthM:92,peakPeople:600,vehicleSharePercent:45,activeTravelSharePercent:35,transitSharePercent:20,peoplePerVehicle:2.4,parkingTurnover:1,accessibleParkingSharePercent:5,bicycleSpaces:24,coachSpaces:2,dropOffSharePercent:18,arrivalWindowMinutes:45,departureWindowMinutes:30,dropOffDwellMinutes:2,grossAreaPerParkingSpaceM2:30,schoolLearners:120,daycareChildren:30,madrasaLearners:160,pedestrianClearWidthM:2.4,courtyardShadePercent:45,reviewNotes:"",zones:[
 zone("mosque","mosque","Mosque + prayer hall",20,22,34,30,8,600),zone("arrival-walk","pedestrian","Car-free arrival spine",31,2,8,74,.12,600),zone("court","courtyard","Shaded community courtyard",20,54,34,20,.16,260),zone("parking","parking","Parking study",2,12,15,62,.1,0),zone("road","road","Vehicle access loop",56,5,12,78,.12,0),zone("recreation","recreation","Recreation + play",2,76,22,13,.35,80),zone("school","school","School classrooms",42,55,12,18,5,120),zone("daycare","daycare","Daycare + secure play",26,76,14,12,4,30),zone("madrasa","madrasa","Madrasa learning wing",56,55,12,18,5,160),zone("service","service","Service + deliveries",56,30,12,16,3,0)]};}

export function safeCampusPlan(value:unknown):CampusPlan|null{
 if(!value||typeof value!=="object")return null; const raw=value as Partial<CampusPlan>; if(raw.schema!==CAMPUS_PLANNING_SCHEMA||!Array.isArray(raw.zones))return null; const base=createCampusPlan();
 return {...base,...raw,status:"executable",siteWidthM:clamp(Number(raw.siteWidthM),30,500,base.siteWidthM),siteDepthM:clamp(Number(raw.siteDepthM),30,500,base.siteDepthM),peakPeople:clamp(Number(raw.peakPeople),0,20000,base.peakPeople),vehicleSharePercent:clamp(Number(raw.vehicleSharePercent),0,100,base.vehicleSharePercent),activeTravelSharePercent:clamp(Number(raw.activeTravelSharePercent),0,100,base.activeTravelSharePercent),transitSharePercent:clamp(Number(raw.transitSharePercent),0,100,base.transitSharePercent),peoplePerVehicle:clamp(Number(raw.peoplePerVehicle),1,10,base.peoplePerVehicle),parkingTurnover:clamp(Number(raw.parkingTurnover),.2,5,base.parkingTurnover),accessibleParkingSharePercent:clamp(Number(raw.accessibleParkingSharePercent),0,100,base.accessibleParkingSharePercent),bicycleSpaces:clamp(Number(raw.bicycleSpaces),0,5000,base.bicycleSpaces),coachSpaces:clamp(Number(raw.coachSpaces),0,200,base.coachSpaces),dropOffSharePercent:clamp(Number(raw.dropOffSharePercent),0,100,base.dropOffSharePercent),arrivalWindowMinutes:clamp(Number(raw.arrivalWindowMinutes),5,240,base.arrivalWindowMinutes),departureWindowMinutes:clamp(Number(raw.departureWindowMinutes),5,240,base.departureWindowMinutes),dropOffDwellMinutes:clamp(Number(raw.dropOffDwellMinutes),.25,30,base.dropOffDwellMinutes),grossAreaPerParkingSpaceM2:clamp(Number(raw.grossAreaPerParkingSpaceM2),10,100,base.grossAreaPerParkingSpaceM2),schoolLearners:clamp(Number(raw.schoolLearners),0,5000,base.schoolLearners),daycareChildren:clamp(Number(raw.daycareChildren),0,1000,base.daycareChildren),madrasaLearners:clamp(Number(raw.madrasaLearners),0,5000,base.madrasaLearners),pedestrianClearWidthM:clamp(Number(raw.pedestrianClearWidthM),.8,20,base.pedestrianClearWidthM),courtyardShadePercent:clamp(Number(raw.courtyardShadePercent),0,100,base.courtyardShadePercent),reviewNotes:typeof raw.reviewNotes==="string"?raw.reviewNotes.slice(0,2000):"",zones:raw.zones.slice(0,30).map((z,index)=>{const item=z as Partial<CampusZone>,kind=campusZoneKinds.includes(item.kind as CampusZoneKind)?item.kind as CampusZoneKind:"service";return {id:typeof item.id==="string"&&item.id?item.id:`zone-${index+1}`,kind,label:typeof item.label==="string"&&item.label?item.label.slice(0,100):`Campus zone ${index+1}`,enabled:item.enabled!==false,xM:clamp(Number(item.xM),0,500,0),zM:clamp(Number(item.zM),0,500,0),widthM:clamp(Number(item.widthM),1,200,8),depthM:clamp(Number(item.depthM),1,200,8),heightM:clamp(Number(item.heightM),.05,80,.2),capacity:clamp(Number(item.capacity),0,20000,0),notes:typeof item.notes==="string"?item.notes.slice(0,500):""}})};
}

export function campusMetrics(plan:CampusPlan){
 const active=plan.zones.filter(z=>z.enabled),usedArea=active.reduce((sum,z)=>sum+z.widthM*z.depthM,0),siteArea=plan.siteWidthM*plan.siteDepthM;
 const vehicles=plan.peakPeople*plan.vehicleSharePercent/100/Math.max(1,plan.peoplePerVehicle),parkingNeed=Math.ceil(vehicles/Math.max(.2,plan.parkingTurnover)),dropOffPeople=Math.ceil(plan.peakPeople*plan.dropOffSharePercent/100),dropOffVehicles=Math.ceil(dropOffPeople/Math.max(1,plan.peoplePerVehicle)),dropOffBays=Math.ceil(dropOffVehicles*plan.dropOffDwellMinutes/Math.max(5,plan.arrivalWindowMinutes));
 const parkingArea=active.filter(z=>z.kind==="parking").reduce((sum,z)=>sum+z.widthM*z.depthM,0),parkingStudyCapacity=Math.floor(parkingArea/Math.max(10,plan.grossAreaPerParkingSpaceM2)),educationCapacity=active.filter(z=>["school","daycare","madrasa"].includes(z.kind)).reduce((sum,z)=>sum+z.capacity,0),pedestrianCapacity=active.filter(z=>z.kind==="pedestrian").reduce((sum,z)=>sum+z.capacity,0);
 const modeShareTotal=plan.vehicleSharePercent+plan.activeTravelSharePercent+plan.transitSharePercent,accessibleStudySpaces=Math.ceil(parkingNeed*plan.accessibleParkingSharePercent/100),arrivalVehiclesPerMinute=Number((vehicles/Math.max(5,plan.arrivalWindowMinutes)).toFixed(1)),departureVehiclesPerMinute=Number((vehicles/Math.max(5,plan.departureWindowMinutes)).toFixed(1));
 return {siteArea,usedArea,openArea:Math.max(0,siteArea-usedArea),coveragePercent:Math.round(usedArea/siteArea*100),parkingNeed,parkingStudyCapacity,parkingGap:Math.max(0,parkingNeed-parkingStudyCapacity),accessibleStudySpaces,dropOffPeople,dropOffVehicles,dropOffBays,arrivalVehiclesPerMinute,departureVehiclesPerMinute,modeShareTotal,unassignedModeSharePercent:Math.max(0,100-modeShareTotal),educationCapacity,pedestrianCapacity};
}

const overlap=(a:CampusZone,b:CampusZone)=>a.xM<b.xM+b.widthM&&a.xM+a.widthM>b.xM&&a.zM<b.zM+b.depthM&&a.zM+a.depthM>b.zM;
export function campusChecks(plan:CampusPlan){
 const active=plan.zones.filter(z=>z.enabled),checks:{level:"review"|"caution";title:string;detail:string}[]=[];
 for(const item of active)if(item.xM+item.widthM>plan.siteWidthM||item.zM+item.depthM>plan.siteDepthM)checks.push({level:"caution",title:"Zone extends beyond working site",detail:`${item.label} exceeds the entered site boundary. Confirm the survey boundary or move and resize the zone.`});
 for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++)if(overlap(active[i],active[j]))checks.push({level:"caution",title:"Overlapping study zones",detail:`${active[i].label} overlaps ${active[j].label}. Confirm whether this is intentional or separate levels.`});
 const walk=active.find(z=>z.kind==="pedestrian"),road=active.find(z=>z.kind==="road"),parking=active.find(z=>z.kind==="parking"),daycare=active.find(z=>z.kind==="daycare"),recreation=active.find(z=>z.kind==="recreation"),court=active.find(z=>z.kind==="courtyard"),metrics=campusMetrics(plan);
 if(walk&&road&&overlap(walk,road))checks.push({level:"caution",title:"Pedestrian and vehicle conflict",detail:"The primary walking spine intersects the road study. Add a controlled crossing, grade separation, or revise the layout."});
 if(daycare&&road&&overlap(daycare,road))checks.push({level:"caution",title:"Daycare beside vehicle movement",detail:"Separate secure child space from moving vehicles, queuing, exhaust, deliveries, and uncontrolled access."});
 if(recreation&&parking&&overlap(recreation,parking))checks.push({level:"caution",title:"Play and parking conflict",detail:"Protect recreation space from vehicle movement and parking manoeuvres."});
 if(metrics.parkingGap>0)checks.push({level:"review",title:"Parking study gap",detail:`The drawn parking area holds about ${metrics.parkingStudyCapacity} spaces using the entered gross-area assumption, ${metrics.parkingGap} fewer than the arithmetic demand study. Test transport demand management before adding land.`});
 if(metrics.modeShareTotal!==100)checks.push({level:"caution",title:"Travel shares do not total 100%",detail:`Vehicle, active-travel and public-transport assumptions total ${metrics.modeShareTotal}%. Reconcile the travel plan before relying on flow arithmetic.`});
 if(plan.bicycleSpaces===0&&plan.activeTravelSharePercent>0)checks.push({level:"review",title:"No bicycle parking in the study",detail:"Active travel is expected, but no bicycle spaces are entered. Confirm local demand, secure placement, weather protection and accessible walking links."});
 if(plan.coachSpaces===0&&plan.transitSharePercent>0)checks.push({level:"review",title:"Coach and shared-transport arrival unresolved",detail:"Public or shared transport is expected. Confirm whether buses, coaches or community vans need a safe stop, waiting area and turning plan."});
 if(!walk)checks.push({level:"caution",title:"No pedestrian-priority zone",detail:"Add a continuous walking route from the public edge to prayer, learning, wudu, recreation, and parking."});
 if(plan.pedestrianClearWidthM<1.5)checks.push({level:"caution",title:"Narrow working route",detail:"The entered clear width needs project-specific accessibility and crowd review."});
 if(court&&plan.courtyardShadePercent<30)checks.push({level:"review",title:"Courtyard heat and shade",detail:"Test shade by season and use time, plus glare, wind, rain, drainage, acoustics, planting, and maintenance."});
 if(!active.some(z=>z.kind==="service"))checks.push({level:"review",title:"No service zone",detail:"Plan deliveries, waste, maintenance, kitchens, funeral logistics, and emergency access away from primary pedestrian routes."}); return checks;
}

export type CampusPrimitive={id:string;kind:CampusZoneKind;label:string;position:[number,number,number];size:[number,number,number];capacity:number};
export function campusPrimitives(plan:CampusPlan):CampusPrimitive[]{return plan.zones.filter(z=>z.enabled).map(z=>({id:z.id,kind:z.kind,label:z.label,position:[z.xM+z.widthM/2,z.heightM/2,z.zM+z.depthM/2],size:[z.widthM,z.heightM,z.depthM],capacity:z.capacity}))}
