export type HazardLevel="not_assessed"|"monitor"|"priority";
export type ClimateHazard={id:string;title:string;prompt:string;designChecks:string[];operationsChecks:string[];source:{label:string;url:string;observedAt:string;confidence:"source_backed"}};
export const climateHazards:ClimateHazard[]=[
 {id:"extreme-heat",title:"Extreme heat + heatwaves",prompt:"Could occupied spaces remain safe and usable during hotter conditions or cooling failure?",designChecks:["Future-weather overheating study","Solar control, envelope and safe ventilation strategy","Cool refuge with accessible route","Heat-safe external waiting and gathering"],operationsChecks:["Heat action thresholds and responsible role","Drinking water and welfare checks","Power-outage operating mode"],source:{label:"IPCC AR6 WGII Chapter 6",url:"https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-6/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"surface-flood",title:"Intense rain + surface flooding",prompt:"What happens when rainfall exceeds normal drainage capacity?",designChecks:["Catchment and finished-level survey","Safe exceedance and overland flow routes","Critical equipment above reviewed flood levels","Water-resistant and recoverable lower-level materials"],operationsChecks:["Flood warning and closure trigger","Safe evacuation without entering floodwater","Post-flood inspection and sanitation plan"],source:{label:"IPCC AR6 WGII Chapter 6",url:"https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-6/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"water-scarcity",title:"Drought + water scarcity",prompt:"Can worship, sanitation and community support continue through constrained supply?",designChecks:["Evidence-based demand and storage study","Low-demand fixtures with inclusive usability review","Safe non-potable reuse separation where lawful","Leak isolation and monitoring access"],operationsChecks:["Prioritized water-use plan","Water-quality and stored-water management","Alternative supply authority review"],source:{label:"IPCC AR6 WGII Chapter 18",url:"https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-18/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"smoke-air",title:"Smoke + hazardous outdoor air",prompt:"Can indoor air and gathering decisions respond to smoke or severe pollution episodes?",designChecks:["Filtered-air strategy and envelope leakage study","Outdoor-air intake location review","Accessible indoor refuge capacity","Controls that prevent unsafe ventilation modes"],operationsChecks:["Air-quality monitoring source and thresholds","Event modification or closure protocol","Filter stock and replacement responsibility"],source:{label:"IPCC AR6 WGII Chapter 16",url:"https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-16/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"wind-storm",title:"Severe wind + storm",prompt:"Are envelope, external elements and continuity plans reviewed for relevant future extremes?",designChecks:["Local wind and debris-risk basis","Roof, screen and canopy fixing design","Safe glazing and entrance strategy","Drainage and backup-power interfaces"],operationsChecks:["Pre-storm securing checklist","Shelter or closure decision owner","Post-event structural inspection gate"],source:{label:"IPCC AR6 WGIII Chapter 9",url:"https://www.ipcc.ch/report/ar6/wg3/chapter/chapter-9/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"coastal",title:"Coastal flooding + salt exposure",prompt:"If relevant, how do surge, rising water and chloride exposure affect siting and durability?",designChecks:["Authority-backed coastal hazard evidence","Safe access and evacuation study","Material durability and corrosion strategy","No critical equipment in exposed zones"],operationsChecks:["Warning source and evacuation trigger","Inspection after inundation or salt exposure","Long-term adaptation decision points"],source:{label:"IPCC AR6 WGIII Chapter 9",url:"https://www.ipcc.ch/report/ar6/wg3/chapter/chapter-9/",observedAt:"2026-09-08",confidence:"source_backed"}},
 {id:"utility-disruption",title:"Power, water + communications disruption",prompt:"Which essential functions must continue when connected systems fail together?",designChecks:["Essential-load and passive-survivability study","Safe backup power and storage scope","Gravity-safe drainage and water isolation","Redundant communications provision"],operationsChecks:["Minimum safe operating mode","Named shutdown and welfare responsibilities","Accessible community communication plan"],source:{label:"IPCC AR6 WGII Chapter 18",url:"https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-18/",observedAt:"2026-09-08",confidence:"source_backed"}}
];
export function assessClimateResilience(levels:Record<string,HazardLevel>){const priority=climateHazards.filter(x=>levels[x.id]==="priority"),unassessed=climateHazards.filter(x=>(levels[x.id]||"not_assessed")==="not_assessed");return {priority,unassessed,compound:priority.length>1,coverage:Math.round((climateHazards.length-unassessed.length)/climateHazards.length*100),status:"executable" as const,boundary:"User-directed scenario coverage only; not a site-specific hazard forecast, climate projection, engineering assessment or authority approval."}}
