export const CONCEPT_SELECTION_KEY="mosque-build.concept-features.v1";
export type ConceptFrame={id:string;slug:string;title:string;asset_path:string;width:number;height:number;orientation?:string;family:string;canonical_route:string;prototype_route:string;feature_tags:string[];implementation_status?:string;notes?:string};
export type ConceptCapability={id:string;label:string;description:string;workspace:string;status:"executable"|"scaffolded"};
const routeRules:[RegExp,string][]=[[/permit|compliance|jurisdiction/,"/permits"],[/fund|waqf|donor/,"/funding"],[/construction|engineering|progress|phasing/,"/construction"],[/procure|vendor|market|material/,"/marketplace"],[/operation|facilit|maintenance|event|kitchen|library/,"/operations"],[/community|participation/,"/start"],[/parking|wudu|interior|design|courtyard|facade|qibla|masterplan|madrasa|prayer|musalla/,"/design"],[/brand|marketing|landing|showcase/,"/features"]];
const executableRoutes=new Set(["/design","/permits","/funding","/construction","/marketplace","/operations","/start","/features"]);
export const friendly=(value:string)=>value.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,l=>l.toUpperCase());
export function conceptWorkspace(frame:ConceptFrame){const text=`${frame.family} ${frame.title} ${frame.feature_tags.join(" ")}`.toLowerCase();return routeRules.find(([pattern])=>pattern.test(text))?.[1]??"/my-project"}
export function conceptCapabilities(frame:ConceptFrame):ConceptCapability[]{const workspace=conceptWorkspace(frame);return frame.feature_tags.map((tag,index)=>({id:`${frame.id}:${tag}`,label:friendly(tag),description:`Explore ${friendly(tag).toLowerCase()} as a project decision with saved inputs, evidence gaps and review boundaries.`,workspace,status:executableRoutes.has(workspace)?"executable":"scaffolded"}))}
export function safeConceptSelections(value:unknown){if(!Array.isArray(value))return[] as string[];return [...new Set(value.filter(x=>typeof x==="string"&&x.length<=180))].slice(0,500)}
