import type {BimCoordinationModel,BimElement} from "@/lib/bim-coordination";import type {DeliveryActivity,DeliveryConstraint} from "@/lib/construction-delivery";import type {ScheduleTask} from "@/lib/project-schedule";
export const CONSTRUCTION_SEQUENCE_SCHEMA="mosque.build/construction-sequence@1" as const;
export const gateKinds=["building","fire life safety","accessibility","energy","environment","business operations","authority","contract"] as const;export const gateStates=["not-assessed","likely-applicable-verify","evidence-recorded","reviewed-user-record"] as const;
export type GateKind=typeof gateKinds[number];export type GateState=typeof gateStates[number];
export type ElementAssignment={elementId:string;activityId:string;packageId:string;notes:string};
export type ComplianceGate={id:string;kind:GateKind;title:string;jurisdictionLabel:string;requirementRef:string;sourceUrl:string;observedAt:string;reviewRole:string;status:GateState;evidenceRef:string;appliesToActivityIds:string[];notes:string};
export type ConstructionSequenceState={schema:typeof CONSTRUCTION_SEQUENCE_SCHEMA;status:"executable";viewDate:string;assignments:ElementAssignment[];gates:ComplianceGate[];updatedAt:string};
export type SequenceElement={element:BimElement;activityId:string;state:"unmapped"|"future"|"planned"|"active-user-record"|"held"|"installed-user-record";reason:string};
const date=(v:string)=>v===""||/^\d{4}-\d{2}-\d{2}$/.test(v),text=(v:unknown,n:number)=>typeof v==="string"&&v.length<=n;
export const blankSequence=(viewDate=new Date().toISOString().slice(0,10)):ConstructionSequenceState=>({schema:CONSTRUCTION_SEQUENCE_SCHEMA,status:"executable",viewDate,assignments:[],gates:[],updatedAt:""});
export function sequenceElements(model:BimCoordinationModel,state:ConstructionSequenceState,delivery:DeliveryActivity[],schedule:ScheduleTask[],constraints:DeliveryConstraint[]):SequenceElement[]{return model.elements.filter(e=>e.ifcClass!=="IfcBuildingStorey").map(element=>{const assignment=state.assignments.find(a=>a.elementId===element.id);if(!assignment)return{element,activityId:"",state:"unmapped",reason:"No construction activity mapped"};const short=delivery.find(a=>a.id===assignment.activityId),base=schedule.find(a=>a.id===assignment.activityId)||schedule.find(a=>a.id===short?.scheduleTaskId),start=short?.weekStart||base?.start||"",finish=short?.weekFinish||base?.finish||"",held=constraints.some(c=>c.activityId===assignment.activityId&&c.status==="open")||state.gates.some(g=>g.appliesToActivityIds.includes(assignment.activityId)&&g.status!=="reviewed-user-record");if(held)return{element,activityId:assignment.activityId,state:"held",reason:"Open constraint or review gate"};if(start&&state.viewDate<start)return{element,activityId:assignment.activityId,state:"future",reason:`Planned after ${state.viewDate}`};if(finish&&state.viewDate>finish)return{element,activityId:assignment.activityId,state:short?.state==="done-user-record"||base?.status==="complete"?"installed-user-record":"planned",reason:"Date passed; completion evidence not necessarily recorded"};if(short?.state==="in-progress"||base?.status==="in-progress")return{element,activityId:assignment.activityId,state:"active-user-record",reason:"User-recorded activity state"};return{element,activityId:assignment.activityId,state:"planned",reason:"Within mapped activity window"}})}
export function gateGaps(g:ComplianceGate){const gaps:string[]=[];if(!g.title.trim())gaps.push("requirement title");if(!g.jurisdictionLabel.trim())gaps.push("jurisdiction");if(!g.requirementRef.trim()||!g.sourceUrl.trim()||!g.observedAt)gaps.push("dated official-source reference");if(!g.reviewRole.trim())gaps.push("accountable review role");if(g.status==="reviewed-user-record"&&!g.evidenceRef.trim())gaps.push("review evidence");if(!g.appliesToActivityIds.length)gaps.push("linked activity");return gaps}
export function canReviewGate(g:ComplianceGate){return gateGaps({...g,status:"reviewed-user-record"}).length===0}
export function sequenceSummary(items:SequenceElement[],gates:ComplianceGate[]){return{elements:items.length,unmapped:items.filter(x=>x.state==="unmapped").length,future:items.filter(x=>x.state==="future").length,planned:items.filter(x=>x.state==="planned").length,active:items.filter(x=>x.state==="active-user-record").length,held:items.filter(x=>x.state==="held").length,installed:items.filter(x=>x.state==="installed-user-record").length,gateGaps:gates.filter(g=>gateGaps(g).length).length}}
export function safeConstructionSequence(value:unknown):ConstructionSequenceState|null{if(!value||typeof value!=="object")return null;const x=value as Partial<ConstructionSequenceState>;if(x.schema!==CONSTRUCTION_SEQUENCE_SCHEMA||x.status!=="executable"||!date(x.viewDate||"")||!Array.isArray(x.assignments)||x.assignments.length>2000||!Array.isArray(x.gates)||x.gates.length>300)return null;const assignments=x.assignments.filter(a=>a&&text(a.elementId,160)&&text(a.activityId,160)&&text(a.packageId,160)&&text(a.notes,2000)),gates=x.gates.filter(g=>g&&text(g.id,100)&&gateKinds.includes(g.kind)&&text(g.title,300)&&text(g.jurisdictionLabel,200)&&text(g.requirementRef,1000)&&text(g.sourceUrl,2000)&&text(g.observedAt,10)&&date(g.observedAt)&&text(g.reviewRole,160)&&gateStates.includes(g.status)&&text(g.evidenceRef,1000)&&Array.isArray(g.appliesToActivityIds)&&g.appliesToActivityIds.length<=100&&g.appliesToActivityIds.every(v=>text(v,160))&&text(g.notes,4000));return assignments.length===x.assignments.length&&gates.length===x.gates.length?{schema:CONSTRUCTION_SEQUENCE_SCHEMA,status:"executable",viewDate:x.viewDate||"",assignments,gates,updatedAt:typeof x.updatedAt==="string"?x.updatedAt:""}:null}
