export const CONSTRUCTION_CONTROL_SCHEMA="mosque.build/construction-controls@1" as const;
export const constructionKinds=["rfi","submittal","inspection","change","risk","delivery","handover"] as const;
export const constructionStatuses=["draft","open","waiting","ready-for-review","closed"] as const;
export const constructionPriorities=["low","normal","high","critical"] as const;
export type ConstructionKind=typeof constructionKinds[number];export type ConstructionStatus=typeof constructionStatuses[number];export type ConstructionPriority=typeof constructionPriorities[number];
export type ConstructionControl={id:string;kind:ConstructionKind;title:string;packageId:string;area:string;responsibleRole:string;dueAt:string;status:ConstructionStatus;priority:ConstructionPriority;evidenceRef:string;decisionRef:string;timeImpactDays:number;notes:string;createdAt:string;updatedAt:string};
export type ConstructionControlState={schema:typeof CONSTRUCTION_CONTROL_SCHEMA;records:ConstructionControl[];updatedAt:string};
const validDate=(value:string)=>value===""||/^\d{4}-\d{2}-\d{2}$/.test(value);
export function controlGaps(record:ConstructionControl){const gaps:string[]=[];if(!record.title.trim())gaps.push("title");if(!record.packageId.trim())gaps.push("work package");if(!record.responsibleRole.trim())gaps.push("responsible role");if(!validDate(record.dueAt))gaps.push("valid due date");if(record.status==="closed"&&!record.evidenceRef.trim())gaps.push("closure evidence");if(record.status==="closed"&&["rfi","change","submittal"].includes(record.kind)&&!record.decisionRef.trim())gaps.push("decision reference");if(record.timeImpactDays<0||!Number.isFinite(record.timeImpactDays))gaps.push("valid time impact");return gaps}
export function canCloseControl(record:ConstructionControl){return controlGaps({...record,status:"closed"}).length===0}
export function controlSummary(records:ConstructionControl[],today:string){const active=records.filter(x=>x.status!=="closed"),overdue=active.filter(x=>x.dueAt&&x.dueAt<today),critical=active.filter(x=>x.priority==="critical"),waiting=active.filter(x=>x.status==="waiting"),ready=active.filter(x=>x.status==="ready-for-review"),closed=records.filter(x=>x.status==="closed"),evidenced=closed.filter(x=>x.evidenceRef.trim());return {total:records.length,active:active.length,overdue:overdue.length,critical:critical.length,waiting:waiting.length,ready:ready.length,closed:closed.length,evidenceCoverage:closed.length?Math.round(evidenced.length/closed.length*100):0,enteredTimeImpactDays:records.filter(x=>x.kind==="change"&&x.status!=="closed").reduce((sum,x)=>sum+x.timeImpactDays,0)}}
export function safeConstructionControls(value:unknown):ConstructionControlState|null{if(!value||typeof value!=="object")return null;const source=value as Partial<ConstructionControlState>;if(source.schema!==CONSTRUCTION_CONTROL_SCHEMA||!Array.isArray(source.records)||source.records.length>300)return null;const records=source.records.filter((x):x is ConstructionControl=>!!x&&typeof x.id==="string"&&x.id.length<=100&&constructionKinds.includes(x.kind)&&typeof x.title==="string"&&x.title.length<=240&&typeof x.packageId==="string"&&x.packageId.length<=100&&typeof x.area==="string"&&x.area.length<=160&&typeof x.responsibleRole==="string"&&x.responsibleRole.length<=160&&typeof x.dueAt==="string"&&validDate(x.dueAt)&&constructionStatuses.includes(x.status)&&constructionPriorities.includes(x.priority)&&typeof x.evidenceRef==="string"&&x.evidenceRef.length<=1000&&typeof x.decisionRef==="string"&&x.decisionRef.length<=1000&&typeof x.timeImpactDays==="number"&&Number.isFinite(x.timeImpactDays)&&x.timeImpactDays>=0&&x.timeImpactDays<=3650&&typeof x.notes==="string"&&x.notes.length<=5000&&typeof x.createdAt==="string"&&typeof x.updatedAt==="string");return records.length===source.records.length?{schema:CONSTRUCTION_CONTROL_SCHEMA,records,updatedAt:typeof source.updatedAt==="string"?source.updatedAt:""}:null}
