import type {ScheduleTask} from "@/lib/project-schedule";
export const CONSTRUCTION_DELIVERY_SCHEMA="mosque.build/construction-delivery@1" as const;
export const deliveryStates=["planned","ready","committed","in-progress","done-user-record","missed"] as const;
export const constraintKinds=["design","information","authority","material","labor","plant","access","predecessor","safety","quality","weather","community","other"] as const;
export type DeliveryState=typeof deliveryStates[number];export type ConstraintKind=typeof constraintKinds[number];
export type DeliveryActivity={id:string;scheduleTaskId:string;title:string;packageId:string;area:string;weekStart:string;weekFinish:string;responsibleRole:string;state:DeliveryState;plannedQuantity:number;unit:string;completedQuantity:number;evidenceRef:string;qualityGate:string;safetyBriefRef:string;notes:string;createdAt:string;updatedAt:string};
export type DeliveryConstraint={id:string;activityId:string;kind:ConstraintKind;title:string;ownerRole:string;neededBy:string;status:"open"|"cleared-user-record";evidenceRef:string;response:string};
export type CoordinationMeeting={id:string;date:string;type:"daily-huddle"|"weekly-plan"|"coordination"|"progress-review";facilitatorRole:string;attendeeRoles:string;decisions:string;actions:string;evidenceRef:string};
export type ConstructionDeliveryState={schema:typeof CONSTRUCTION_DELIVERY_SCHEMA;status:"executable";anchorDate:string;activities:DeliveryActivity[];constraints:DeliveryConstraint[];meetings:CoordinationMeeting[];updatedAt:string};
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`)),text=(v:unknown,n:number)=>typeof v==="string"&&v.length<=n,finite=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max;
export const addDeliveryDays=(date:string,days:number)=>new Date(Date.parse(`${date}T00:00:00Z`)+days*86_400_000).toISOString().slice(0,10);
export const createConstructionDelivery=(anchorDate:string):ConstructionDeliveryState=>({schema:CONSTRUCTION_DELIVERY_SCHEMA,status:"executable",anchorDate,activities:[],constraints:[],meetings:[],updatedAt:""});
export function activityGaps(x:DeliveryActivity,constraints:DeliveryConstraint[]){const gaps:string[]=[];if(!x.title.trim())gaps.push("title");if(!x.packageId.trim())gaps.push("work package");if(!x.responsibleRole.trim())gaps.push("responsible role");if(!validDate(x.weekStart)||!validDate(x.weekFinish)||x.weekFinish<x.weekStart)gaps.push("valid dates");if(x.state==="ready"||x.state==="committed")for(const value of [[x.qualityGate,"quality gate"],[x.safetyBriefRef,"safety brief"]] as const)if(!value[0].trim())gaps.push(value[1]);if(["ready","committed","in-progress","done-user-record"].includes(x.state)&&constraints.some(c=>c.activityId===x.id&&c.status==="open"))gaps.push("open constraints");if(x.state==="done-user-record"&&(!x.evidenceRef.trim()||x.completedQuantity<x.plannedQuantity))gaps.push("completion evidence and quantity");return gaps}
export function canSetDeliveryState(x:DeliveryActivity,state:DeliveryState,constraints:DeliveryConstraint[]){return activityGaps({...x,state},constraints).length===0}
export function deliverySummary(state:ConstructionDeliveryState,today:string){const committed=state.activities.filter(x=>x.state==="committed"||x.state==="done-user-record"||x.state==="missed"),done=committed.filter(x=>x.state==="done-user-record"),open=state.constraints.filter(x=>x.status==="open"),overdue=open.filter(x=>x.neededBy<today),ready=state.activities.filter(x=>canSetDeliveryState(x,"ready",state.constraints));return{activities:state.activities.length,committed:committed.length,done:done.length,missed:committed.filter(x=>x.state==="missed").length,ppc:committed.length?Math.round(done.length/committed.length*100):null,openConstraints:open.length,overdueConstraints:overdue.length,ready:ready.length,evidenced:state.activities.filter(x=>x.evidenceRef.trim()).length}}
export function sixWeekBuckets(state:ConstructionDeliveryState){return Array.from({length:6},(_,index)=>{const start=addDeliveryDays(state.anchorDate,index*7),finish=addDeliveryDays(start,6),activities=state.activities.filter(x=>x.weekFinish>=start&&x.weekStart<=finish);return{index:index+1,start,finish,activities,committed:activities.filter(x=>x.state==="committed").length,done:activities.filter(x=>x.state==="done-user-record").length,blocked:activities.filter(x=>state.constraints.some(c=>c.activityId===x.id&&c.status==="open")).length}})}
export function scheduleCandidates(tasks:ScheduleTask[],anchorDate:string){const finish=addDeliveryDays(anchorDate,41);return tasks.filter(x=>x.finish>=anchorDate&&x.start<=finish&&x.status!=="complete").sort((a,b)=>a.start.localeCompare(b.start))}
export function safeConstructionDelivery(value:unknown):ConstructionDeliveryState|null{if(!value||typeof value!=="object")return null;const x=value as Partial<ConstructionDeliveryState>;if(x.schema!==CONSTRUCTION_DELIVERY_SCHEMA||x.status!=="executable"||!validDate(x.anchorDate??"")||!Array.isArray(x.activities)||x.activities.length>500||!Array.isArray(x.constraints)||x.constraints.length>1000||!Array.isArray(x.meetings)||x.meetings.length>300)return null;const activities=x.activities.filter(v=>v&&text(v.id,100)&&text(v.scheduleTaskId,100)&&text(v.title,240)&&text(v.packageId,160)&&text(v.area,160)&&validDate(v.weekStart)&&validDate(v.weekFinish)&&text(v.responsibleRole,160)&&deliveryStates.includes(v.state)&&finite(v.plannedQuantity,0,1e9)&&text(v.unit,40)&&finite(v.completedQuantity,0,1e9)&&text(v.evidenceRef,1000)&&text(v.qualityGate,1000)&&text(v.safetyBriefRef,1000)&&text(v.notes,5000)&&text(v.createdAt,100)&&text(v.updatedAt,100)),constraints=x.constraints.filter(v=>v&&text(v.id,100)&&text(v.activityId,100)&&constraintKinds.includes(v.kind)&&text(v.title,240)&&text(v.ownerRole,160)&&validDate(v.neededBy)&&["open","cleared-user-record"].includes(v.status)&&text(v.evidenceRef,1000)&&text(v.response,3000)),meetings=x.meetings.filter(v=>v&&text(v.id,100)&&validDate(v.date)&&["daily-huddle","weekly-plan","coordination","progress-review"].includes(v.type)&&text(v.facilitatorRole,160)&&text(v.attendeeRoles,1000)&&text(v.decisions,5000)&&text(v.actions,5000)&&text(v.evidenceRef,1000));return activities.length===x.activities.length&&constraints.length===x.constraints.length&&meetings.length===x.meetings.length?x as ConstructionDeliveryState:null}
