export const DOCUMENT_CONTROL_SCHEMA="mosque.build/construction-document-control@1" as const;
export const documentKinds=["drawing","specification","schedule","method-statement","product-data","test-record","inspection-record","handover-record"] as const;
export const reviewOutcomes=["not-issued","issued-for-review","comments-recorded","revise-and-resubmit","recorded-for-stated-purpose","superseded"] as const;
export type DocumentKind=typeof documentKinds[number];export type ReviewOutcome=typeof reviewOutcomes[number];
export type DocumentRecord={id:string;reference:string;title:string;kind:DocumentKind;discipline:string;revision:string;revisionDate:string;purpose:string;packageId:string;originatorRole:string;reviewerRole:string;outcome:ReviewOutcome;evidenceRef:string;previousRevisionRef:string;responseDue:string;distributionRoles:string[];notes:string;createdAt:string;updatedAt:string};
export type DocumentControlState={schema:typeof DOCUMENT_CONTROL_SCHEMA;records:DocumentRecord[];updatedAt:string};
const date=(x:string)=>x===""||/^\d{4}-\d{2}-\d{2}$/.test(x),text=(x:unknown,n:number)=>typeof x==="string"&&x.length<=n;
export function documentGaps(r:DocumentRecord){const gaps:string[]=[];if(!r.reference.trim())gaps.push("document reference");if(!r.title.trim())gaps.push("title");if(!r.revision.trim())gaps.push("revision");if(!r.revisionDate)gaps.push("revision date");if(!r.purpose.trim())gaps.push("stated purpose");if(!r.originatorRole.trim())gaps.push("originator role");if(r.outcome!=="not-issued"&&!r.reviewerRole.trim())gaps.push("reviewer role");if(["comments-recorded","revise-and-resubmit","recorded-for-stated-purpose","superseded"].includes(r.outcome)&&!r.evidenceRef.trim())gaps.push("review evidence");if(r.outcome==="superseded"&&!r.previousRevisionRef.trim())gaps.push("replacement reference");if(r.outcome==="issued-for-review"&&!r.responseDue)gaps.push("response due date");if(r.outcome!=="not-issued"&&!r.distributionRoles.length)gaps.push("distribution roles");return gaps}
export function canSetOutcome(r:DocumentRecord,outcome:ReviewOutcome){return documentGaps({...r,outcome}).length===0}
export function documentSummary(records:DocumentRecord[],today:string){const current=records.filter(r=>r.outcome!=="superseded"),overdue=current.filter(r=>r.outcome==="issued-for-review"&&r.responseDue&&r.responseDue<today),revisionCollisions=current.filter((r,i)=>current.findIndex(x=>x.reference.toLowerCase()===r.reference.toLowerCase()&&x.revision.toLowerCase()===r.revision.toLowerCase())!==i);return {total:records.length,current:current.length,superseded:records.length-current.length,awaiting:current.filter(r=>r.outcome==="issued-for-review").length,revise:current.filter(r=>r.outcome==="revise-and-resubmit").length,recorded:current.filter(r=>r.outcome==="recorded-for-stated-purpose").length,overdue:overdue.length,gaps:current.filter(r=>documentGaps(r).length).length,revisionCollisions:revisionCollisions.length}}
export function safeDocumentControl(value:unknown):DocumentControlState|null{if(!value||typeof value!=="object")return null;const x=value as Partial<DocumentControlState>;if(x.schema!==DOCUMENT_CONTROL_SCHEMA||!Array.isArray(x.records)||x.records.length>500)return null;const records=x.records.filter((r):r is DocumentRecord=>!!r&&typeof r==="object"&&text(r.id,100)&&text(r.reference,160)&&text(r.title,240)&&documentKinds.includes(r.kind)&&text(r.discipline,100)&&text(r.revision,60)&&text(r.revisionDate,10)&&date(r.revisionDate)&&text(r.purpose,500)&&text(r.packageId,120)&&text(r.originatorRole,160)&&text(r.reviewerRole,160)&&reviewOutcomes.includes(r.outcome)&&text(r.evidenceRef,1000)&&text(r.previousRevisionRef,240)&&text(r.responseDue,10)&&date(r.responseDue)&&Array.isArray(r.distributionRoles)&&r.distributionRoles.length<=20&&r.distributionRoles.every(v=>text(v,160))&&text(r.notes,5000)&&text(r.createdAt,40)&&text(r.updatedAt,40));return records.length===x.records.length?{schema:DOCUMENT_CONTROL_SCHEMA,records,updatedAt:typeof x.updatedAt==="string"&&x.updatedAt.length<=40?x.updatedAt:""}:null}
