export const CONTRIBUTOR_CAPACITY_SCHEMA="mosque.build/contributor-capacity@1" as const;
export const CONTRIBUTOR_CAPACITY_KEY="mosque-build.contributor-capacity.v1" as const;
export const contributorDisciplines=["Project coordination","Community engagement","Architecture","Structural engineering","Civil engineering","Building services","Cost planning","Planning and permits","Construction","Facilities operations","Accessibility","Sustainability","Research and sources","Software engineering","Product design","Documentation","Translation","Religious content review","Fundraising and governance"] as const;
export const contributorPhases=["Define","Understand","Design","Approve + resource","Build","Open + care"] as const;
export type ContributorDiscipline=typeof contributorDisciplines[number];
export type ContributorPhase=typeof contributorPhases[number];
export type CapacityNeed={id:string;outcome:string;discipline:ContributorDiscipline;phase:ContributorPhase;hoursPerMonth:number;urgency:"later"|"soon"|"now";ownerRole:string;status:"open"|"covered"|"paused";evidenceRef:string};
export type CapacityOffer={id:string;roleLabel:string;disciplines:ContributorDiscipline[];phases:ContributorPhase[];hoursPerMonth:number;participation:"remote"|"on-site"|"hybrid";availabilityNote:string;status:"available"|"limited"|"unavailable";capabilityEvidenceRef:string};
export type CapacityAllocation={id:string;needId:string;offerId:string;hoursPerMonth:number;status:"proposed"|"confirmed"|"ended";reviewEvidenceRef:string};
export type Partnership={id:string;partnerType:string;sharedOutcome:string;contribution:string;projectContribution:string;ownerRole:string;status:"prospect"|"permission-recorded"|"due-diligence"|"ready-for-team-review";consentEvidenceRef:string;dueDiligenceRef:string};
export type ContributorCapacityPlan={schema:typeof CONTRIBUTOR_CAPACITY_SCHEMA;status:"executable";updatedAt:string;needs:CapacityNeed[];offers:CapacityOffer[];allocations:CapacityAllocation[];partnerships:Partnership[]};
const now=()=>new Date().toISOString(),id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export function createContributorCapacityPlan():ContributorCapacityPlan{return{schema:CONTRIBUTOR_CAPACITY_SCHEMA,status:"executable",updatedAt:now(),needs:[{id:"need-coordination",outcome:"Maintain the integrated decision and delivery plan",discipline:"Project coordination",phase:"Define",hoursPerMonth:16,urgency:"now",ownerRole:"Project sponsor",status:"open",evidenceRef:"Project brief"},{id:"need-community",outcome:"Run accessible community listening and report aggregate findings",discipline:"Community engagement",phase:"Understand",hoursPerMonth:12,urgency:"soon",ownerRole:"Community review group",status:"open",evidenceRef:"Community-needs study"},{id:"need-cost",outcome:"Review quantities, assumptions and cost evidence",discipline:"Cost planning",phase:"Approve + resource",hoursPerMonth:8,urgency:"soon",ownerRole:"Finance working group",status:"open",evidenceRef:"Cost plan"}],offers:[],allocations:[],partnerships:[]}}
export const newNeed=():CapacityNeed=>({id:id("need"),outcome:"",discipline:"Project coordination",phase:"Define",hoursPerMonth:4,urgency:"soon",ownerRole:"",status:"open",evidenceRef:""});
export const newOffer=():CapacityOffer=>({id:id("offer"),roleLabel:"",disciplines:["Project coordination"],phases:["Define"],hoursPerMonth:4,participation:"remote",availabilityNote:"",status:"available",capabilityEvidenceRef:""});
export const newPartnership=():Partnership=>({id:id("partner"),partnerType:"",sharedOutcome:"",contribution:"",projectContribution:"",ownerRole:"",status:"prospect",consentEvidenceRef:"",dueDiligenceRef:""});
const object=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==="object"&&!Array.isArray(value);
const bounded=(value:unknown,max=200)=>typeof value==="string"?value.trim().slice(0,max):"";
const hours=(value:unknown)=>Math.min(1000,Math.max(0,Number.isFinite(Number(value))?Number(value):0));
export function safeContributorCapacityPlan(value:unknown):ContributorCapacityPlan|null{if(!object(value)||value.schema!==CONTRIBUTOR_CAPACITY_SCHEMA||!Array.isArray(value.needs)||!Array.isArray(value.offers)||!Array.isArray(value.allocations)||!Array.isArray(value.partnerships)||value.needs.length>200||value.offers.length>200||value.allocations.length>400||value.partnerships.length>100)return null;const base=createContributorCapacityPlan();try{return{...base,updatedAt:bounded(value.updatedAt,40)||base.updatedAt,needs:value.needs.map(raw=>{if(!object(raw))throw 0;return{...newNeed(),...raw,id:bounded(raw.id,80),outcome:bounded(raw.outcome),ownerRole:bounded(raw.ownerRole,100),evidenceRef:bounded(raw.evidenceRef,300),hoursPerMonth:hours(raw.hoursPerMonth)}}) as CapacityNeed[],offers:value.offers.map(raw=>{if(!object(raw))throw 0;return{...newOffer(),...raw,id:bounded(raw.id,80),roleLabel:bounded(raw.roleLabel,100),availabilityNote:bounded(raw.availabilityNote,200),capabilityEvidenceRef:bounded(raw.capabilityEvidenceRef,300),hoursPerMonth:hours(raw.hoursPerMonth),disciplines:Array.isArray(raw.disciplines)?raw.disciplines.filter(x=>contributorDisciplines.includes(x as ContributorDiscipline)).slice(0,8) as ContributorDiscipline[]:[],phases:Array.isArray(raw.phases)?raw.phases.filter(x=>contributorPhases.includes(x as ContributorPhase)).slice(0,6) as ContributorPhase[]:[]}}) as CapacityOffer[],allocations:value.allocations.map(raw=>{if(!object(raw))throw 0;return{...raw,id:bounded(raw.id,80),needId:bounded(raw.needId,80),offerId:bounded(raw.offerId,80),hoursPerMonth:hours(raw.hoursPerMonth),reviewEvidenceRef:bounded(raw.reviewEvidenceRef,300)}}) as CapacityAllocation[],partnerships:value.partnerships.map(raw=>{if(!object(raw))throw 0;return{...newPartnership(),...raw,id:bounded(raw.id,80),partnerType:bounded(raw.partnerType,100),sharedOutcome:bounded(raw.sharedOutcome),contribution:bounded(raw.contribution),projectContribution:bounded(raw.projectContribution),ownerRole:bounded(raw.ownerRole,100),consentEvidenceRef:bounded(raw.consentEvidenceRef,300),dueDiligenceRef:bounded(raw.dueDiligenceRef,300)}}) as Partnership[]}}catch{return null}}
export function capacitySummary(plan:ContributorCapacityPlan){const activeNeeds=plan.needs.filter(x=>x.status==="open"),activeOffers=plan.offers.filter(x=>x.status!=="unavailable"),live=plan.allocations.filter(x=>x.status!=="ended");const required=activeNeeds.reduce((sum,x)=>sum+x.hoursPerMonth,0),available=activeOffers.reduce((sum,x)=>sum+x.hoursPerMonth,0),allocated=live.reduce((sum,x)=>sum+x.hoursPerMonth,0);const disciplines=contributorDisciplines.map(discipline=>{const needed=activeNeeds.filter(x=>x.discipline===discipline).reduce((sum,x)=>sum+x.hoursPerMonth,0),offered=activeOffers.filter(x=>x.disciplines.includes(discipline)).reduce((sum,x)=>sum+x.hoursPerMonth,0);return{discipline,needed,offered,gap:Math.max(0,needed-offered)}}).filter(x=>x.needed||x.offered);return{required,available,allocated,openNeeds:activeNeeds.length,uncovered:disciplines.filter(x=>x.gap>0).length,disciplines}}
export function potentialAlignments(plan:ContributorCapacityPlan){return plan.needs.filter(x=>x.status==="open").flatMap(need=>plan.offers.filter(offer=>offer.status!=="unavailable"&&offer.disciplines.includes(need.discipline)&&offer.phases.includes(need.phase)).map(offer=>({needId:need.id,offerId:offer.id,hoursPerMonth:Math.min(need.hoursPerMonth,offer.hoursPerMonth),label:`${offer.roleLabel||"Unnamed role"} may align with ${need.outcome||"this need"}`}))).sort((a,b)=>b.hoursPerMonth-a.hoursPerMonth)}
export function capacityChecks(plan:ContributorCapacityPlan){const checks:{level:"attention"|"ready";title:string;detail:string}[]=[];for(const gap of capacitySummary(plan).disciplines.filter(x=>x.gap>0))checks.push({level:"attention",title:"Capability gap remains",detail:`${gap.discipline} needs ${gap.needed} hours per month and has ${gap.offered} hours offered in this working plan.`});for(const need of plan.needs.filter(x=>x.status==="open")){if(!need.outcome||!need.ownerRole)checks.push({level:"attention",title:"Need definition incomplete",detail:"Add an outcome and accountable owner role before seeking help."});if(!need.evidenceRef)checks.push({level:"attention",title:"Need lacks project evidence",detail:`Link ${need.outcome||"this need"} to a brief, decision, schedule item or other project record.`})}for(const offer of plan.offers.filter(x=>x.status!=="unavailable")){if(!offer.roleLabel||!offer.capabilityEvidenceRef)checks.push({level:"attention",title:"Capability review incomplete",detail:"Use a non-identifying role label and record how the project team will review capability."});const used=plan.allocations.filter(x=>x.offerId===offer.id&&x.status!=="ended").reduce((sum,x)=>sum+x.hoursPerMonth,0);if(used>offer.hoursPerMonth)checks.push({level:"attention",title:"Proposed capacity is overcommitted",detail:`${offer.roleLabel||"One role"} has ${used} allocated hours against ${offer.hoursPerMonth} available.`})}for(const allocation of plan.allocations.filter(x=>x.status==="confirmed")){if(!allocation.reviewEvidenceRef)checks.push({level:"attention",title:"Confirmed allocation lacks review evidence",detail:"Record the team decision or consent reference; a match is not an assignment."})}for(const partner of plan.partnerships){if(!partner.ownerRole||!partner.sharedOutcome)checks.push({level:"attention",title:"Partnership brief incomplete",detail:"Add a shared outcome and accountable project role."});if(partner.status!=="prospect"&&!partner.consentEvidenceRef)checks.push({level:"attention",title:"Partnership permission is not evidenced",detail:"Do not present a prospect as participating until permission is recorded."});if(partner.status==="ready-for-team-review"&&!partner.dueDiligenceRef)checks.push({level:"attention",title:"Due diligence is not evidenced",detail:"Record governance, conflicts, capability, safeguarding and delivery checks."})}if(!checks.length)checks.push({level:"ready",title:"No automatic gaps detected",detail:"The project team must still review capability, consent, conflicts, safeguarding and professional limits."});return checks}
