import{costSavingRules}from"./cost-saving-rules";import{lineCost,type CostPlan}from"./regional-material-cost";
export const COST_OPTION_SCHEMA="mosque.build/cost-option-comparison@1" as const;export const COST_OPTION_KEY="mosque-build.cost-option-comparison.v1";
export type CostOptionRecord={id:string;ruleId:string;title:string;baselineLabel:string;alternativeLabel:string;baselineLineIds:string[];alternativeLineIds:string[];modelRevisionRef:string;scopeRef:string;ownerRole:string;evidenceRef:string;lifecycleNotes:string;exclusions:string;decision:"draft"|"ready-for-review"|"accepted-user-record"|"rejected-user-record";updatedAt:string};
export type CostOptionStudy={schema:typeof COST_OPTION_SCHEMA;status:"executable";records:CostOptionRecord[];updatedAt:string};
const text=(x:unknown,n=500)=>typeof x==="string"?x.trim().slice(0,n):"",ids=(x:unknown)=>Array.isArray(x)?[...new Set(x.filter(v=>typeof v==="string").map(v=>v.slice(0,100)))].slice(0,500):[];
export function blankCostOptionStudy():CostOptionStudy{return{schema:COST_OPTION_SCHEMA,status:"executable",records:[],updatedAt:""}}
export function newCostOptionRecord(ruleId=costSavingRules[0].id):CostOptionRecord{return{id:`option-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,ruleId,title:"Baseline and alternative study",baselineLabel:"Current baseline",alternativeLabel:"Design alternative",baselineLineIds:[],alternativeLineIds:[],modelRevisionRef:"",scopeRef:"",ownerRole:"",evidenceRef:"",lifecycleNotes:"",exclusions:"",decision:"draft",updatedAt:""}}
export function safeCostOptionStudy(value:unknown):CostOptionStudy|null{if(!value||typeof value!=="object")return null;const x=value as Record<string,unknown>;if(x.schema!==COST_OPTION_SCHEMA||x.status!=="executable"||!Array.isArray(x.records)||x.records.length>100)return null;const validRules=new Set(costSavingRules.map(r=>r.id)),decisions=new Set(["draft","ready-for-review","accepted-user-record","rejected-user-record"]);const records=x.records.flatMap(raw=>{if(!raw||typeof raw!=="object")return[];const r=raw as Record<string,unknown>,ruleId=text(r.ruleId,20),id=text(r.id,100);if(!id||!validRules.has(ruleId)||!decisions.has(r.decision as string))return[];return[{id,ruleId,title:text(r.title,160),baselineLabel:text(r.baselineLabel,120),alternativeLabel:text(r.alternativeLabel,120),baselineLineIds:ids(r.baselineLineIds),alternativeLineIds:ids(r.alternativeLineIds),modelRevisionRef:text(r.modelRevisionRef,200),scopeRef:text(r.scopeRef,200),ownerRole:text(r.ownerRole,100),evidenceRef:text(r.evidenceRef,300),lifecycleNotes:text(r.lifecycleNotes,1000),exclusions:text(r.exclusions,1000),decision:r.decision as CostOptionRecord["decision"],updatedAt:text(r.updatedAt,40)}]});return{schema:COST_OPTION_SCHEMA,status:"executable",records:records.filter((r,i)=>records.findIndex(x=>x.id===r.id)===i),updatedAt:text(x.updatedAt,40)}}
function optionTotal(plan:CostPlan,lineIds:string[]){const selected=plan.lines.filter(line=>lineIds.includes(line.id)),currencies=[...new Set(selected.map(line=>(line.currency||plan.market.currency||"").toUpperCase()).filter(Boolean))],gaps:string[]=[];if(!selected.length)gaps.push("no cost lines selected");if(currencies.length!==1)gaps.push(currencies.length?"selected lines use multiple currencies":"currency missing");for(const line of selected){if(line.quantity<=0)gaps.push(`${line.label}: measured quantity missing`);if(line.baseUnitPrice<=0)gaps.push(`${line.label}: base rate missing`);if(!line.sourceId||!plan.sources.some(s=>s.id===line.sourceId))gaps.push(`${line.label}: price source missing`)}return{lines:selected.length,currency:currencies.length===1?currencies[0]:"",total:gaps.length?null:selected.reduce((sum,line)=>sum+lineCost(line,"base").total,0),gaps}}
export function compareCostOptions(plan:CostPlan,record:CostOptionRecord){const baseline=optionTotal(plan,record.baselineLineIds),alternative=optionTotal(plan,record.alternativeLineIds),gaps=[...baseline.gaps.map(x=>`Baseline: ${x}`),...alternative.gaps.map(x=>`Alternative: ${x}`)];if(!plan.basisDate)gaps.push("Cost-plan basis date missing");if(!plan.priceLevelDate)gaps.push("Price-level date missing");if(!record.scopeRef)gaps.push("Comparable scope reference missing");if(!record.ownerRole)gaps.push("Accountable review role missing");if(record.decision!=="draft"&&!record.evidenceRef)gaps.push("Decision evidence reference missing");if(baseline.currency&&alternative.currency&&baseline.currency!==alternative.currency)gaps.push("Baseline and alternative currencies differ; no conversion is inferred");const comparable=!gaps.length&&baseline.total!==null&&alternative.total!==null&&baseline.currency===alternative.currency,delta=comparable?alternative.total!-baseline.total!:null;return{baseline,alternative,comparable,delta,deltaPercent:comparable&&baseline.total!>0?delta!/baseline.total!*100:null,gaps:[...new Set(gaps)],label:delta===null?"Unavailable":delta<0?"Lower entered cost":delta>0?"Higher entered cost":"No entered cost difference",boundary:"Entered option-cost difference only. Not a saving forecast, tender result, value judgment, recommendation or approval."}}

