import{costSavingRules,ruleReviewGaps,type CostRuleStudy,type CostSavingRule,type RuleReview}from"./cost-saving-rules";
export const COST_CONTROL_INTEGRATION_SCHEMA="mosque.build/cost-control-integration@1" as const;
export const COST_CONTROL_INTEGRATION_KEY="mosque-build.cost-control-integration.v1";
export type CostConnectionKind="design"|"quantity-cost"|"procurement"|"schedule"|"construction"|"operations";
export type CostControlConnection={kind:CostConnectionKind;label:string;href:string;storageKey:string;requirement:string;reviewRole:string};
export type CostControlPacket={schema:typeof COST_CONTROL_INTEGRATION_SCHEMA;createdAt:string;ruleId:string;strategy:string;category:string;parameter:string;review:RuleReview;connections:CostControlConnection[];gaps:string[];boundary:string};
const common:Record<CostConnectionKind,Omit<CostControlConnection,"requirement">>={
 design:{kind:"design",label:"Design model",href:"/design",storageKey:"mosque-build.schematic-plan.v1",reviewRole:"Design lead"},
 "quantity-cost":{kind:"quantity-cost",label:"Quantity and cost plan",href:"/construction#regional-cost-title",storageKey:"mosque-build.regional-material-cost.v1",reviewRole:"Cost adviser"},
 procurement:{kind:"procurement",label:"Procurement comparison",href:"/marketplace",storageKey:"mosque-build.procurement.v1",reviewRole:"Procurement lead"},
 schedule:{kind:"schedule",label:"Project schedule",href:"/construction",storageKey:"mosque-build.project-schedule.v1",reviewRole:"Project planner"},
 construction:{kind:"construction",label:"Construction controls",href:"/construction",storageKey:"mosque-build.construction-controls.v1",reviewRole:"Construction lead"},
 operations:{kind:"operations",label:"Operations and care",href:"/operations",storageKey:"mosque-build.asset-register.v1",reviewRole:"Facilities team"}
};
const requirements:Record<string,Partial<Record<CostConnectionKind,string>>>={
 Massing:{design:"Compare perimeter, area, circulation and phased-use geometry.","quantity-cost":"Measure affected wall, roof, foundation and floor quantities.",schedule:"Compare design and construction sequence effects.",operations:"Review usability, flexibility and cleaning implications."},
 Structure:{design:"Coordinate grid, spans, openings and load-path questions.","quantity-cost":"Compare measured structural quantities using sourced alternatives.",procurement:"Verify system capability, lead time and submittal evidence.",schedule:"Coordinate temporary works, inspections and sequence.",construction:"Record hold points and qualified structural review."},
 Roof:{design:"Coordinate form, drainage, wind, solar and access interfaces.","quantity-cost":"Measure roof area, edges, penetrations and drainage scope.",procurement:"Compare complete tested assemblies, not surface products alone.",schedule:"Coordinate enclosure, waterproofing and testing activities.",operations:"Record safe access, inspection and replacement implications."},
 Minaret:{design:"Test purpose, height, access, structure and skyline context.","quantity-cost":"Measure the complete structure, access and maintenance scope.",construction:"Coordinate lifting, temporary stability and inspection records.",operations:"Record safe inspection, access and long-term care."},
 Envelope:{design:"Compare openings, layers, shade, weather and maintenance access.","quantity-cost":"Measure wall, opening, screen and finish quantities separately.",procurement:"Compare samples, tested performance and replacement availability.",construction:"Record mockups, interfaces, weathering and acceptance checks.",operations:"Review cleaning, repair and replacement cycles."},
 Interior:{design:"Protect prayer use, dignity, accessibility, acoustics and changeover.","quantity-cost":"Measure floor, ceiling, joinery and equipment scope by room.",procurement:"Compare samples, emissions, durability, care and warranties.",construction:"Coordinate substrates, interfaces, mockups and protection.",operations:"Review cleaning, storage, replacement and event-mode labor."},
 Wudu:{design:"Coordinate dignity, flows, accessible use, water and drainage.","quantity-cost":"Measure fixtures, waterproofing, drainage and ventilation scope.",procurement:"Verify complete system fit and maintainable components.",construction:"Record waterproofing, falls, tests and concealed-work evidence.",operations:"Review water use, cleaning, slips, leaks and service access."},
 MEP:{design:"Coordinate loads, routes, controls, access and resilience.","quantity-cost":"Measure systems by capacity, route and installation scope.",procurement:"Compare performance evidence, controls, spares and commissioning.",schedule:"Coordinate first fix, testing, commissioning and training.",operations:"Review energy, water, consumables, skills and replacement."},
 Site:{design:"Coordinate access, ground, water, parking, landscape and phasing.","quantity-cost":"Measure external works and abnormal site scope separately.",schedule:"Coordinate enabling work, seasonal constraints and logistics.",construction:"Record surveys, permits, inspections and concealed conditions.",operations:"Review landscape, drainage, access and security care."},
 Development:{design:"Test the strategy against the brief, site and complete operating need.","quantity-cost":"Compare whole-project baselines with scope and exclusions visible.",procurement:"Preserve competition, capability evidence and conflict controls.",schedule:"Compare approval, funding, design and phased-delivery effects.",operations:"Include opening readiness and whole-life responsibilities."},
 Construction:{design:"Confirm buildability changes do not erode design intent.","quantity-cost":"Record baseline, alternative, change and measured outcome separately.",procurement:"Link scopes, bids, clarifications and substitutions.",schedule:"Link activities, dependencies, constraints and evidence gates.",construction:"Use accountable records for changes, inspections and completion evidence."}
};
export function connectionsForRule(rule:CostSavingRule){const category=requirements[rule.category]??requirements.Construction;return(Object.entries(category)as[CostConnectionKind,string][]).map(([kind,requirement])=>({...common[kind],requirement}))}
export function costControlIntegrationGaps(rule:CostSavingRule,review:RuleReview,has:(key:string)=>boolean){const gaps=ruleReviewGaps(rule,review).map(x=>`Rule review: ${x}`);for(const connection of connectionsForRule(rule))if(!has(connection.storageKey))gaps.push(`Missing linked ${connection.label.toLowerCase()} record`);return gaps}
export function createCostControlPacket(rule:CostSavingRule,review:RuleReview,has:(key:string)=>boolean,createdAt=new Date().toISOString()):CostControlPacket{return{schema:COST_CONTROL_INTEGRATION_SCHEMA,createdAt,ruleId:rule.id,strategy:rule.strategy,category:rule.category,parameter:rule.threejs_parameter,review,connections:connectionsForRule(rule),gaps:costControlIntegrationGaps(rule,review,has),boundary:"Coordination packet only. It contains no predicted saving, price, specification, approval, professional acceptance or instruction to build."}}
export function integratedCostRules(study:CostRuleStudy,has:(key:string)=>boolean){return study.reviews.filter(r=>r.applicability==="applicable").flatMap(review=>{const rule=costSavingRules.find(r=>r.id===review.ruleId);return rule?[{rule,review,connections:connectionsForRule(rule),gaps:costControlIntegrationGaps(rule,review,has)}]:[]})}

