export const DESIGN_STUDIO_PROFILE_KEY="mosque-build.design-studio-profile.v1" as const;
export const DESIGN_STUDIO_PROFILE_SCHEMA="mosque.build/design-studio-profile@1" as const;
export type StudioProjectStatus="idea"|"briefing"|"designing"|"review"|"paused";
export type StudioProject={id:string;title:string;type:string;status:StudioProjectStatus;summary:string;updatedAt:string};
export type DesignStudioProfile={schema:typeof DESIGN_STUDIO_PROFILE_SCHEMA;status:"executable";practiceLabel:string;role:string;bio:string;skills:string[];projects:StudioProject[];updatedAt:string};
const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
export function blankDesignStudioProfile():DesignStudioProfile{return{schema:DESIGN_STUDIO_PROFILE_SCHEMA,status:"executable",practiceLabel:"My design practice",role:"Project design team",bio:"",skills:[],projects:[],updatedAt:""}}
export function safeDesignStudioProfile(value:unknown):DesignStudioProfile|null{if(!value||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)return null;const x=value as DesignStudioProfile;if(x.schema!==DESIGN_STUDIO_PROFILE_SCHEMA||x.status!=="executable"||!Array.isArray(x.skills)||x.skills.length>12||!Array.isArray(x.projects)||x.projects.length>24)return null;const ids=new Set<string>(),projects:StudioProject[]=[];for(const item of x.projects){if(!item||typeof item!=="object")return null;const id=clean(item.id,80),title=clean(item.title,120),type=clean(item.type,80),summary=clean(item.summary,600),updatedAt=clean(item.updatedAt,40);if(!id||!title||ids.has(id)||!["idea","briefing","designing","review","paused"].includes(item.status))return null;ids.add(id);projects.push({id,title,type,status:item.status,summary,updatedAt})}return{schema:DESIGN_STUDIO_PROFILE_SCHEMA,status:"executable",practiceLabel:clean(x.practiceLabel,120)||"My design practice",role:clean(x.role,120)||"Project design team",bio:clean(x.bio,600),skills:[...new Set(x.skills.map(v=>clean(v,60)).filter(Boolean))],projects,updatedAt:clean(x.updatedAt,40)}}
export function profileCompletion(profile:DesignStudioProfile){return Math.round(([profile.practiceLabel,profile.role,profile.bio,profile.skills.length,profile.projects.length].filter(Boolean).length/5)*100)}
