export const DESIGN_STUDIO_PROFILE_KEY="mosque-build.design-studio-profile.v1" as const;
export const DESIGN_STUDIO_PROFILE_SCHEMA="mosque.build/design-studio-profile@1" as const;
export type StudioProjectStatus="idea"|"briefing"|"designing"|"review"|"paused";
export const studioProjectStatuses=["idea","briefing","designing","review","paused"]as const;
export const studioProjectTypes=["New build","Adaptive reuse","Expansion","Renovation","Campus planning","Interior renewal"]as const;
export type StudioProject={id:string;title:string;type:string;status:StudioProjectStatus;summary:string;updatedAt:string};
export type DesignStudioProfile={schema:typeof DESIGN_STUDIO_PROFILE_SCHEMA;status:"executable";practiceLabel:string;role:string;bio:string;skills:string[];projects:StudioProject[];updatedAt:string};
const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
export function blankDesignStudioProfile():DesignStudioProfile{return{schema:DESIGN_STUDIO_PROFILE_SCHEMA,status:"executable",practiceLabel:"My design practice",role:"Project design team",bio:"",skills:[],projects:[],updatedAt:""}}
export function safeDesignStudioProfile(value:unknown):DesignStudioProfile|null{if(!value||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)return null;const x=value as DesignStudioProfile;if(x.schema!==DESIGN_STUDIO_PROFILE_SCHEMA||x.status!=="executable"||!Array.isArray(x.skills)||x.skills.length>12||!Array.isArray(x.projects)||x.projects.length>24)return null;const ids=new Set<string>(),projects:StudioProject[]=[];for(const item of x.projects){if(!item||typeof item!=="object"||Object.getPrototypeOf(item)!==Object.prototype)return null;const id=clean(item.id,80),title=clean(item.title,120)||"Untitled mosque project",rawType=clean(item.type,80),type=studioProjectTypes.includes(rawType as typeof studioProjectTypes[number])?rawType:"New build",summary=clean(item.summary,600),updatedAt=clean(item.updatedAt,40);if(!id||ids.has(id)||!studioProjectStatuses.includes(item.status))return null;ids.add(id);projects.push({id,title,type,status:item.status,summary,updatedAt})}return{schema:DESIGN_STUDIO_PROFILE_SCHEMA,status:"executable",practiceLabel:clean(x.practiceLabel,120)||"My design practice",role:clean(x.role,120)||"Project design team",bio:clean(x.bio,600),skills:[...new Set(x.skills.map(v=>clean(v,60)).filter(Boolean))],projects,updatedAt:clean(x.updatedAt,40)}}
export function profileCompletion(profile:DesignStudioProfile){return Math.round(([profile.practiceLabel!=="My design practice",profile.role!=="Project design team",!!profile.bio,!!profile.skills.length,!!profile.projects.length].filter(Boolean).length/5)*100)}
export function studioPortfolioSummary(profile:DesignStudioProfile){return{total:profile.projects.length,active:profile.projects.filter(x=>x.status==="designing"||x.status==="review").length,needsSummary:profile.projects.filter(x=>!x.summary).length,byStatus:Object.fromEntries(studioProjectStatuses.map(status=>[status,profile.projects.filter(x=>x.status===status).length]))}}
export function exportDesignStudioProfile(profile:DesignStudioProfile){return JSON.stringify({...profile,exportedAt:new Date().toISOString(),scope:"private-on-device-portfolio",boundary:"Planning profile only; not a professional credential, commission, public directory or shared model database."},null,2)}
export function importDesignStudioProfile(text:string):{profile:DesignStudioProfile|null;error:string|null}{if(text.length>256_000)return{profile:null,error:"Profile import exceeds the 256 KB safety limit."};let value:unknown;try{value=JSON.parse(text)}catch{return{profile:null,error:"The selected file is not valid JSON."}}const profile=safeDesignStudioProfile(value);return profile?{profile:{...profile,updatedAt:new Date().toISOString()},error:null}:{profile:null,error:"The file does not match the supported studio profile schema."}}
