export const DOME_DESIGN_SCHEMA="mosque.build/dome-design@1"as const, DOME_DESIGN_KEY="mosque-build.dome-design.v1";
export const domeProfiles=["hemispherical","segmental","pointed","onion-study","ribbed-study","shallow-cap"]as const,transitionTypes=["pendentive-study","squinch-study","ring-beam-study","direct-drum-study"]as const,structureTypes=["reinforced-concrete-study","steel-space-frame-study","timber-grid-study","masonry-study","lightweight-shell-study"]as const;
export type DomeDesign={schema:typeof DOME_DESIGN_SCHEMA;status:"executable";profile:typeof domeProfiles[number];diameterM:number;riseM:number;drumHeightM:number;drumWallM:number;baseElevationM:number;ribCount:number;ringCount:number;oculusDiameterM:number;openingCount:number;transition:typeof transitionTypes[number];structure:typeof structureTypes[number];innerLining:string;outerCovering:string;insulation:string;waterproofing:string;acousticStrategy:string;daylightStrategy:string;drainageStrategy:string;maintenanceAccess:string;fallProtection:string;lightningProtection:string;temporaryWorks:string;liftingStrategy:string;surveyReference:string;structureReference:string;windReference:string;seismicReference:string;fireReference:string;moistureReference:string;materialSource:string;costLineRef:string;scheduleActivityId:string;reviewRole:string;notes:string;updatedAt:string};
export const blankDomeDesign=():DomeDesign=>({schema:DOME_DESIGN_SCHEMA,status:"executable",profile:"hemispherical",diameterM:12,riseM:5,drumHeightM:1.5,drumWallM:.3,baseElevationM:6,ribCount:16,ringCount:3,oculusDiameterM:0,openingCount:8,transition:"ring-beam-study",structure:"steel-space-frame-study",innerLining:"",outerCovering:"",insulation:"",waterproofing:"",acousticStrategy:"",daylightStrategy:"",drainageStrategy:"",maintenanceAccess:"",fallProtection:"",lightningProtection:"",temporaryWorks:"",liftingStrategy:"",surveyReference:"",structureReference:"",windReference:"",seismicReference:"",fireReference:"",moistureReference:"",materialSource:"",costLineRef:"",scheduleActivityId:"",reviewRole:"",notes:"",updatedAt:""});
const finite=(x:unknown,min:number,max:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=min&&x<=max,text=(x:unknown,n=2000)=>typeof x==="string"&&x.length<=n;
export function safeDomeDesign(value:unknown):DomeDesign|null{if(!value||typeof value!=="object")return null;const x=value as DomeDesign;if(x.schema!==DOME_DESIGN_SCHEMA||x.status!=="executable"||!domeProfiles.includes(x.profile)||!transitionTypes.includes(x.transition)||!structureTypes.includes(x.structure)||!finite(x.diameterM,.5,300)||!finite(x.riseM,.1,150)||!finite(x.drumHeightM,0,100)||!finite(x.drumWallM,.05,10)||!finite(x.baseElevationM,0,300)||!finite(x.ribCount,0,240)||!finite(x.ringCount,0,60)||!finite(x.oculusDiameterM,0,100)||!finite(x.openingCount,0,120))return null;return Object.values(x).every(v=>typeof v!=="string"||text(v))?x:null}
export function domeGeometry(d:DomeDesign){const radius=d.diameterM/2,sphereRadius=(radius*radius+d.riseM*d.riseM)/(2*d.riseM),surfaceArea=2*Math.PI*sphereRadius*d.riseM,baseCircumference=Math.PI*d.diameterM,openingRatio=d.oculusDiameterM>0?Math.min(1,(d.oculusDiameterM/d.diameterM)**2):0;return{radius,sphereRadius,surfaceArea,baseCircumference,openingRatio,approxVolume:Math.PI*d.riseM*(3*radius*radius+d.riseM*d.riseM)/6,metricBasis:"Spherical-cap reference; resolve non-spherical profiles before quantity takeoff."}}
export function domeChecks(d:DomeDesign){const gaps:string[]=[];if(d.riseM>d.diameterM)gaps.push("unusual rise-to-span proportion requires explicit geometry and structural review");if(d.oculusDiameterM>=d.diameterM)gaps.push("oculus must be smaller than dome diameter");if(d.ribCount>0&&d.ribCount<4)gaps.push("rib count is too low for a meaningful radial study");for(const[k,label]of[[d.surveyReference,"survey basis"],[d.structureReference,"structural basis"],[d.windReference,"wind basis"],[d.seismicReference,"seismic basis"],[d.fireReference,"fire basis"],[d.moistureReference,"moisture basis"],[d.waterproofing,"waterproofing assembly"],[d.drainageStrategy,"drainage strategy"],[d.maintenanceAccess,"maintenance access"],[d.temporaryWorks,"temporary works"],[d.scheduleActivityId,"schedule link"],[d.reviewRole,"accountable review role"]]as const)if(!k.trim())gaps.push(label);return gaps}
export function domeProfileRadius(profile:DomeDesign["profile"],t:number,radius:number){const s=Math.cos(Math.PI*Math.max(0,Math.min(1,t))/2);if(profile==="pointed")return radius*Math.pow(s,.72);if(profile==="onion-study")return radius*s*(.76+.38*(1-t));if(profile==="shallow-cap")return radius*Math.pow(s,1.8);if(profile==="segmental")return radius*Math.pow(s,1.35);if(profile==="ribbed-study")return radius*s;return radius*s}
