export const emergencyModes=[
 {id:"heat",title:"Extreme heat",trigger:"Define a current official warning source and locally approved activation threshold.",actions:["Confirm a cooler accessible refuge and safe occupancy decision","Check drinking water, wudu demand and power dependencies","Prepare plain-language and non-digital event-change messages"],recovery:["Record indoor conditions and welfare concerns","Inspect heat-stressed equipment and finishes","Review whether the operating threshold protected people"]},
 {id:"flood",title:"Flooding",trigger:"Define official warnings, observed site conditions and who may restrict access.",actions:["Protect step-free egress and do not route people through floodwater","Isolate exposed utilities only through competent authorized roles","Preserve a remote communication and reunification route"],recovery:["Keep affected areas closed pending competent inspection","Record water extent and evidence references","Review contamination, electrical and fabric recovery decisions"]},
 {id:"smoke",title:"Smoke + hazardous air",trigger:"Define the accountable local air-quality source and reviewed action thresholds.",actions:["Confirm filtered refuge, ventilation mode and capacity","Provide accessible event-change or closure communication","Check filters, medicines policy and vulnerable-person support without collecting diagnoses"],recovery:["Record source readings and decisions","Review filters and affected equipment","Update the clean-air operating plan"]},
 {id:"storm",title:"Severe storm",trigger:"Define official warnings and a role authorized to pause access or activities.",actions:["Secure outdoor and overhead hazards through competent roles","Protect safe internal refuge and accessible routes","Plan for power, communications and transport disruption"],recovery:["Restrict damaged areas pending inspection","Record observed damage without declaring structural safety","Review warning reach and continuity gaps"]},
 {id:"water",title:"Water scarcity",trigger:"Define utility or authority notices and an approved water-use response.",actions:["Protect safe drinking, hygiene and accessible wudu alternatives","Communicate temporary arrangements respectfully and accessibly","Track stored-water safety and replenishment responsibilities"],recovery:["Confirm restored supply through accountable checks","Record exceptional consumption and welfare impacts","Review storage, leakage and demand measures"]},
 {id:"compound",title:"Compound utility disruption",trigger:"Define who coordinates when power, water, access or communications fail together.",actions:["Prioritize life safety, accessible communication and welfare checks","Identify services that must stop rather than operate without safeguards","Use offline contact and decision records that avoid unnecessary personal data"],recovery:["Recommission affected systems with competent reviewers","Reconcile offline decisions and evidence","Run a cross-team after-action review"]}
] as const;
export type EmergencyModeId=typeof emergencyModes[number]["id"];
export type EmergencyPlan={leadRole:string;warningSource:string;accessibleChannel:string;backupChannel:string;checks:string[];notes:string;reviewedAt:string};
export type DrillRecord={id:string;modeId:EmergencyModeId;date:string;facilitatorRole:string;scenario:string;outcome:string;evidenceRef:string;createdAt:string};
export function planCoverage(plan:EmergencyPlan,checkCount:number){const core=[plan.leadRole,plan.warningSource,plan.accessibleChannel,plan.backupChannel].filter(value=>value.trim()).length;return Math.round((core+Math.min(plan.checks.length,checkCount))/(4+checkCount)*100)}
export function drillGaps(drill:Pick<DrillRecord,"date"|"facilitatorRole"|"scenario"|"outcome">){const gaps:string[]=[];if(!drill.date)gaps.push("drill date");if(!drill.facilitatorRole.trim())gaps.push("facilitator role");if(!drill.scenario.trim())gaps.push("scenario tested");if(!drill.outcome.trim())gaps.push("observed outcome");return gaps}
