export const ENERGY_SCENARIO_SCHEMA="mosque.build/energy-scenario@1" as const;
export const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const;
export type MonthRecord={month:typeof months[number];demandKwh:number;resourceHours:number;evidenceRef:string};
export type LoadRecord={id:string;label:string;group:string;dailyKwh:number;peakKw:number;critical:boolean;operatingWindow:string;evidenceRef:string};
export type Option={id:string;label:string;pvKw:number;lossPercent:number;batteryKwh:number;usablePercent:number;inverterKw:number;notes:string};
export type EnergyScenario={schema:typeof ENERGY_SCENARIO_SCHEMA;status:"executable";updatedAt:string;months:MonthRecord[];loads:LoadRecord[];options:Option[];reviewRole:string;notes:string};
const finite=(v:unknown,max:number)=>typeof v==="number"&&Number.isFinite(v)?Math.min(max,Math.max(0,v)):0;
export function blankEnergyScenario():EnergyScenario{return{schema:ENERGY_SCENARIO_SCHEMA,status:"executable",updatedAt:new Date(0).toISOString(),months:months.map(month=>({month,demandKwh:0,resourceHours:0,evidenceRef:""})),loads:[],options:[{id:"option-a",label:"Option A",pvKw:0,lossPercent:14,batteryKwh:0,usablePercent:80,inverterKw:0,notes:""}],reviewRole:"",notes:""}}
export function safeEnergyScenario(value:unknown):EnergyScenario{const base=blankEnergyScenario();if(!value||typeof value!=="object")return base;const x=value as Partial<EnergyScenario>;const inputMonths=Array.isArray(x.months)?new Map(x.months.map(m=>[m.month,m])):new Map();return{...base,...x,schema:ENERGY_SCENARIO_SCHEMA,status:"executable",months:months.map(month=>{const m=inputMonths.get(month)as Partial<MonthRecord>|undefined;return{month,demandKwh:finite(m?.demandKwh,10_000_000),resourceHours:finite(m?.resourceHours,12),evidenceRef:typeof m?.evidenceRef==="string"?m.evidenceRef.slice(0,200):""}}),loads:Array.isArray(x.loads)?x.loads.slice(0,50).map((l,i)=>({id:typeof l.id==="string"?l.id:`load-${i}`,label:String(l.label||"").slice(0,100),group:String(l.group||"").slice(0,60),dailyKwh:finite(l.dailyKwh,100_000),peakKw:finite(l.peakKw,100_000),critical:Boolean(l.critical),operatingWindow:String(l.operatingWindow||"").slice(0,120),evidenceRef:String(l.evidenceRef||"").slice(0,200)})):[],options:Array.isArray(x.options)?x.options.slice(0,4).map((o,i)=>({id:typeof o.id==="string"?o.id:`option-${i}`,label:String(o.label||`Option ${i+1}`).slice(0,60),pvKw:finite(o.pvKw,100_000),lossPercent:finite(o.lossPercent,99),batteryKwh:finite(o.batteryKwh,1_000_000),usablePercent:finite(o.usablePercent,100),inverterKw:finite(o.inverterKw,100_000),notes:String(o.notes||"").slice(0,500)})):base.options}}
export function optionSummary(state:EnergyScenario,option:Option){const annualDemand=state.months.reduce((s,m)=>s+m.demandKwh,0),monthly=state.months.map(m=>({month:m.month,demand:m.demandKwh,generation:option.pvKw*m.resourceHours*new Date(2024,months.indexOf(m.month)+1,0).getDate()*(1-option.lossPercent/100)})),annualGeneration=monthly.reduce((s,m)=>s+m.generation,0),coverage=annualDemand?annualGeneration/annualDemand*100:0,criticalDaily=state.loads.filter(l=>l.critical).reduce((s,l)=>s+l.dailyKwh,0),criticalPeak=state.loads.filter(l=>l.critical).reduce((s,l)=>s+l.peakKw,0),usableBattery=option.batteryKwh*option.usablePercent/100,staticHours=criticalDaily?usableBattery/(criticalDaily/24):0;return{annualDemand,monthly,annualGeneration,coverage,criticalDaily,criticalPeak,usableBattery,staticHours,inverterGap:Math.max(0,criticalPeak-option.inverterKw)}}
export function scenarioGaps(state:EnergyScenario){const gaps:string[]=[];if(!state.months.some(m=>m.demandKwh&&m.evidenceRef))gaps.push("monthly demand evidence");if(!state.months.some(m=>m.resourceHours&&m.evidenceRef))gaps.push("monthly resource evidence");if(!state.loads.length)gaps.push("load register");if(!state.loads.some(l=>l.critical&&l.evidenceRef))gaps.push("evidenced critical loads");if(!state.options.some(o=>o.pvKw&&o.inverterKw))gaps.push("PV and inverter option");if(!state.reviewRole)gaps.push("accountable review role");return gaps}
