export const FLOOR_PLAN_SCHEMA="mosque.build/floor-plan-workspace@1" as const;
export const spaceKinds=["prayer","circulation","wudu","learning","community","office","service","storage","courtyard","parking","other"] as const;
export const openingKinds=["door","window","screen","service-penetration"] as const;
export const annotationKinds=["dimension","qibla","route","note","hazard","review"] as const;
export type SpaceKind=typeof spaceKinds[number];export type OpeningKind=typeof openingKinds[number];export type AnnotationKind=typeof annotationKinds[number];
export type FloorLevel={id:string;name:string;elevationM:number;floorToFloorM:number;status:"working"|"review"|"frozen-user-record"};
export type PlanSpace={id:string;levelId:string;name:string;kind:SpaceKind;xM:number;yM:number;widthM:number;depthM:number;clearHeightM:number;capacityInput:number;accessibleJourney:boolean;privacy:"public"|"transition"|"private";adjacentTo:string[];separateFrom:string[];finishRef:string;notes:string};
export type PlanOpening={id:string;levelId:string;spaceId:string;kind:OpeningKind;label:string;hostEdge:"north"|"east"|"south"|"west";offsetM:number;widthM:number;heightM:number;operation:string;fireEvidenceRef:string;accessEvidenceRef:string;notes:string};
export type PlanAnnotation={id:string;levelId:string;spaceId:string;kind:AnnotationKind;text:string;xM:number;yM:number;evidenceRef:string;status:"open"|"reviewed-user-record"};
export type FloorPlanState={schema:typeof FLOOR_PLAN_SCHEMA;status:"executable";units:"m";footprint:{widthM:number;depthM:number};levels:FloorLevel[];spaces:PlanSpace[];openings:PlanOpening[];annotations:PlanAnnotation[];activeLevelId:string;gridM:number;snap:boolean;updatedAt:string};
export const newFloorPlan=():FloorPlanState=>({schema:FLOOR_PLAN_SCHEMA,status:"executable",units:"m",footprint:{widthM:30,depthM:36},levels:[{id:"level-ground",name:"Ground floor",elevationM:0,floorToFloorM:3.6,status:"working"}],spaces:[],openings:[],annotations:[],activeLevelId:"level-ground",gridM:.5,snap:true,updatedAt:""});
const finite=(n:unknown,min:number,max:number)=>typeof n==="number"&&Number.isFinite(n)&&n>=min&&n<=max,text=(v:unknown,n:number)=>typeof v==="string"&&v.length<=n;
export function safeFloorPlan(value:unknown):FloorPlanState|null{if(!value||typeof value!=="object")return null;const x=value as Partial<FloorPlanState>;if(x.schema!==FLOOR_PLAN_SCHEMA||x.status!=="executable"||x.units!=="m"||!x.footprint||!finite(x.footprint.widthM,5,300)||!finite(x.footprint.depthM,5,300)||!Array.isArray(x.levels)||!Array.isArray(x.spaces)||!Array.isArray(x.openings)||!Array.isArray(x.annotations)||x.levels.length<1||x.levels.length>20||x.spaces.length>300||x.openings.length>1000||x.annotations.length>1000)return null;const levels=x.levels.filter(v=>v&&text(v.id,100)&&text(v.name,160)&&finite(v.elevationM,-100,1000)&&finite(v.floorToFloorM,1.8,20)&&["working","review","frozen-user-record"].includes(v.status)),spaces=x.spaces.filter(v=>v&&text(v.id,100)&&text(v.levelId,100)&&text(v.name,160)&&spaceKinds.includes(v.kind)&&finite(v.xM,-300,300)&&finite(v.yM,-300,300)&&finite(v.widthM,.2,300)&&finite(v.depthM,.2,300)&&finite(v.clearHeightM,1,30)&&finite(v.capacityInput,0,100000)&&typeof v.accessibleJourney==="boolean"&&["public","transition","private"].includes(v.privacy)&&Array.isArray(v.adjacentTo)&&v.adjacentTo.length<=100&&Array.isArray(v.separateFrom)&&v.separateFrom.length<=100&&text(v.finishRef,1000)&&text(v.notes,3000)),openings=x.openings.filter(v=>v&&text(v.id,100)&&text(v.levelId,100)&&text(v.spaceId,100)&&openingKinds.includes(v.kind)&&text(v.label,160)&&["north","east","south","west"].includes(v.hostEdge)&&finite(v.offsetM,0,300)&&finite(v.widthM,.2,30)&&finite(v.heightM,.2,30)&&text(v.operation,500)&&text(v.fireEvidenceRef,1000)&&text(v.accessEvidenceRef,1000)&&text(v.notes,2000)),annotations=x.annotations.filter(v=>v&&text(v.id,100)&&text(v.levelId,100)&&text(v.spaceId,100)&&annotationKinds.includes(v.kind)&&text(v.text,1000)&&finite(v.xM,-300,300)&&finite(v.yM,-300,300)&&text(v.evidenceRef,1000)&&["open","reviewed-user-record"].includes(v.status));if(levels.length!==x.levels.length||spaces.length!==x.spaces.length||openings.length!==x.openings.length||annotations.length!==x.annotations.length||!text(x.activeLevelId,100)||!finite(x.gridM,.1,10)||typeof x.snap!=="boolean")return null;return x as FloorPlanState}
const overlap=(a:PlanSpace,b:PlanSpace)=>a.xM<b.xM+b.widthM-.001&&a.xM+a.widthM>b.xM+.001&&a.yM<b.yM+b.depthM-.001&&a.yM+a.depthM>b.yM+.001;
export type PlanCheck={id:string;severity:"review"|"blocker";label:string;detail:string;spaceIds:string[]};
export function floorPlanChecks(state:FloorPlanState,levelId=state.activeLevelId){const spaces=state.spaces.filter(s=>s.levelId===levelId),checks:PlanCheck[]=[];for(const s of spaces){if(s.xM<0||s.yM<0||s.xM+s.widthM>state.footprint.widthM||s.yM+s.depthM>state.footprint.depthM)checks.push({id:`bounds:${s.id}`,severity:"blocker",label:"Outside footprint",detail:`${s.name} extends outside the working footprint.`,spaceIds:[s.id]});if(s.clearHeightM<2.1)checks.push({id:`height:${s.id}`,severity:"review",label:"Low entered clear height",detail:`Review the user-entered clear height for ${s.name}.`,spaceIds:[s.id]});for(const ref of [...s.adjacentTo,...s.separateFrom])if(!state.spaces.some(x=>x.id===ref))checks.push({id:`ref:${s.id}:${ref}`,severity:"blocker",label:"Broken room relationship",detail:`${s.name} references a missing space.`,spaceIds:[s.id]})}for(let i=0;i<spaces.length;i++)for(const b of spaces.slice(i+1))if(overlap(spaces[i],b))checks.push({id:`overlap:${spaces[i].id}:${b.id}`,severity:"blocker",label:"Space overlap",detail:`${spaces[i].name} overlaps ${b.name}.`,spaceIds:[spaces[i].id,b.id]});for(const o of state.openings.filter(x=>x.levelId===levelId))if(!spaces.some(s=>s.id===o.spaceId))checks.push({id:`opening:${o.id}`,severity:"blocker",label:"Unhosted opening",detail:`${o.label} does not reference a space on this level.`,spaceIds:[]});return checks}
export function floorPlanSummary(state:FloorPlanState,levelId=state.activeLevelId){const spaces=state.spaces.filter(s=>s.levelId===levelId),area=spaces.reduce((n,s)=>n+s.widthM*s.depthM,0),checks=floorPlanChecks(state,levelId);return{spaces:spaces.length,areaM2:Math.round(area*10)/10,openings:state.openings.filter(o=>o.levelId===levelId).length,annotations:state.annotations.filter(a=>a.levelId===levelId).length,accessibleSpaces:spaces.filter(s=>s.accessibleJourney).length,blockers:checks.filter(c=>c.severity==="blocker").length,reviews:checks.filter(c=>c.severity==="review").length}}
export function fromSchematic(plan:{inputs:{widthM:number;depthM:number};rooms:Array<{id:string;name:string;x:number;y:number;width:number;depth:number;kind:string}>},existing= newFloorPlan()){const levelId=existing.activeLevelId,allowed=new Set(spaceKinds);return{...existing,footprint:{widthM:plan.inputs.widthM,depthM:plan.inputs.depthM},spaces:[...existing.spaces.filter(s=>s.levelId!==levelId),...plan.rooms.map(r=>({id:`${levelId}:${r.id}`,levelId,name:r.name,kind:(allowed.has(r.kind as SpaceKind)?r.kind:"other") as SpaceKind,xM:r.x,yM:r.y,widthM:r.width,depthM:r.depth,clearHeightM:r.kind==="prayer"?4.8:3,capacityInput:0,accessibleJourney:r.kind!=="support",privacy:r.kind==="support"?"private" as const:"transition" as const,adjacentTo:[],separateFrom:[],finishRef:"",notes:"Imported from current conceptual schematic."}))],updatedAt:new Date().toISOString()}}
