export const INTEGRATED_SPACE_SCHEMA="mosque.build/integrated-space-plan@1" as const;
export type ZoneKind="prayer"|"wudu"|"women"|"circulation"|"community"|"courtyard"|"qibla-study"|"service";
export type Priority="essential"|"important"|"future";
export type SpaceZone={id:string;name:string;kind:ZoneKind;widthM:number;depthM:number;priority:Priority;accessibleJourney:boolean;privacy:"public"|"transition"|"private";notes:string};
export type SpacePlan={schema:typeof INTEGRATED_SPACE_SCHEMA;status:"executable";updatedAt:string;zones:SpaceZone[];selectedKitIds:string[];reviewNotes:string};
export type SpaceKit={id:string;title:string;family:"Worship"|"Wudu"|"Women + family"|"Climate + community"|"Islamic architectural study";summary:string;review:string;zones:Array<Omit<SpaceZone,"id">>};

const zone=(name:string,kind:ZoneKind,widthM:number,depthM:number,priority:Priority,accessibleJourney=true,privacy:SpaceZone["privacy"]="transition",notes=""):Omit<SpaceZone,"id">=>({name,kind,widthM,depthM,priority,accessibleJourney,privacy,notes});
export const spaceKits:SpaceKit[]=[
  {id:"inclusive-prayer-core",title:"Inclusive prayer core",family:"Worship",summary:"A prayer hall, step-free circulation and quiet support room planned as one journey.",review:"Confirm capacity, row geometry, qibla, egress, acoustics and inclusion with users and qualified reviewers.",zones:[zone("Main prayer hall","prayer",18,20,"essential"),zone("Accessible prayer route","circulation",2.4,20,"essential"),zone("Quiet support room","community",4,5,"important",true,"transition")]},
  {id:"wet-dry-wudu",title:"Wet-to-dry wudu journey",family:"Wudu",summary:"Arrival, footwear transition, accessible wudu choice and service access remain explicit.",review:"Verify fixture provision, transfers, drainage, waterproofing, slip evidence, ventilation and local requirements.",zones:[zone("Dry wudu arrival","circulation",4,4,"essential"),zone("Wudu area","wudu",8,6,"essential",true,"private"),zone("Accessible wudu position","wudu",3,3,"essential",true,"private"),zone("Wudu service edge","service",2,6,"important",false,"private")]},
  {id:"womens-equal-journey",title:"Women’s equal-quality journey",family:"Women + family",summary:"Same-level prayer, arrival, amenities and family support as connected—not residual—spaces.",review:"Test alternatives directly with women of varied ages, abilities and roles; do not infer acceptance from selection.",zones:[zone("Women’s prayer area","women",12,12,"essential",true,"transition"),zone("Women’s arrival and shoes","circulation",4,5,"essential"),zone("Family and quiet room","community",5,5,"important",true,"transition"),zone("Women’s amenity link","circulation",2.4,8,"essential")]},
  {id:"courtyard-threshold",title:"Courtyard climate threshold",family:"Climate + community",summary:"A shaded transition that can support circulation and community life without being counted as conditioned space.",review:"Review solar exposure, wind, rain, drainage, planting, night use, security and maintenance for the actual site.",zones:[zone("Courtyard","courtyard",12,12,"important",true,"public"),zone("Shaded arcade study","circulation",3,12,"important",true,"transition"),zone("Community threshold","community",6,6,"future",true,"public")]},
  {id:"qibla-wall-study",title:"Qibla wall element study",family:"Islamic architectural study",summary:"Coordinate mihrab, minbar, teaching, accessibility and services as a functional wall study.",review:"A mihrab or minbar is not universally required in one form. Review religious, cultural, access, acoustic and safety needs locally.",zones:[zone("Qibla wall study zone","qibla-study",18,3,"essential",true,"transition","Study mihrab, minbar, teaching position, accessibility, acoustics and service integration without decorative calligraphy."),zone("Imam and teaching access","circulation",2.4,6,"essential",true,"private")]},
  {id:"learning-majlis",title:"Learning and majlis cluster",family:"Climate + community",summary:"Flexible teaching and gathering rooms connected to storage and a legible public route.",review:"Confirm safeguarding, acoustic separation, furniture, technology, ventilation, accessible participation and operating hours.",zones:[zone("Flexible learning room","community",8,7,"important"),zone("Community majlis","community",8,7,"important"),zone("Shared storage","service",3,4,"important",true,"private"),zone("Learning route","circulation",2.4,10,"essential")]},
];
export const createSpacePlan=():SpacePlan=>({schema:INTEGRATED_SPACE_SCHEMA,status:"executable",updatedAt:"",zones:[],selectedKitIds:[],reviewNotes:""});
const finite=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max;
export function safeSpacePlan(value:unknown):SpacePlan|null{if(!value||typeof value!=="object")return null;const x=value as SpacePlan;if(x.schema!==INTEGRATED_SPACE_SCHEMA||x.status!=="executable"||!Array.isArray(x.zones)||x.zones.length>100||!Array.isArray(x.selectedKitIds)||x.selectedKitIds.length>20||typeof x.reviewNotes!=="string"||x.reviewNotes.length>5000)return null;for(const z of x.zones)if(!z||typeof z.id!=="string"||z.id.length>100||typeof z.name!=="string"||z.name.length>160||!["prayer","wudu","women","circulation","community","courtyard","qibla-study","service"].includes(z.kind)||!finite(z.widthM,.5,100)||!finite(z.depthM,.5,100)||!["essential","important","future"].includes(z.priority)||typeof z.accessibleJourney!=="boolean"||!["public","transition","private"].includes(z.privacy)||typeof z.notes!=="string"||z.notes.length>2000)return null;return x}
export function addKit(plan:SpacePlan,kit:SpaceKit,makeId=()=>crypto.randomUUID()):SpacePlan{const existing=new Set(plan.selectedKitIds);const zones=existing.has(kit.id)?plan.zones:[...plan.zones,...kit.zones.map(item=>({...item,id:makeId()}))];return{...plan,zones,selectedKitIds:[...existing,kit.id],updatedAt:new Date().toISOString()}}
export function removeKit(plan:SpacePlan,kit:SpaceKit):SpacePlan{const signatures=new Set(kit.zones.map(z=>`${z.name}:${z.kind}`));return{...plan,zones:plan.zones.filter(z=>!signatures.has(`${z.name}:${z.kind}`)),selectedKitIds:plan.selectedKitIds.filter(id=>id!==kit.id),updatedAt:new Date().toISOString()}}
export function spacePlanSummary(plan:SpacePlan){const totalAreaM2=Math.round(plan.zones.reduce((n,z)=>n+z.widthM*z.depthM,0)*10)/10;return{zones:plan.zones.length,totalAreaM2,essential:plan.zones.filter(z=>z.priority==="essential").length,accessible:plan.zones.filter(z=>z.accessibleJourney).length,missingNotes:plan.zones.filter(z=>!z.notes.trim()).length}}
export function spacePlanGaps(plan:SpacePlan){const kinds=new Set(plan.zones.map(z=>z.kind)),gaps:string[]=[];if(!kinds.has("prayer"))gaps.push("No main prayer zone recorded");if(!kinds.has("circulation"))gaps.push("No circulation zone recorded");if(kinds.has("wudu")&&!plan.zones.some(z=>z.kind==="wudu"&&z.accessibleJourney))gaps.push("No accessible wudu journey intent recorded");if(kinds.has("women")&&!plan.zones.some(z=>z.kind==="women"&&z.accessibleJourney))gaps.push("No accessible women’s prayer journey intent recorded");if(kinds.has("qibla-study")&&!plan.zones.some(z=>z.kind==="qibla-study"&&z.notes.trim()))gaps.push("Qibla wall study has no contextual review note");return gaps}
