export const INTERIOR_SYSTEMS_SCHEMA="mosque.build/interior-systems@1" as const;export const INTERIOR_SYSTEMS_KEY="mosque-build.interior-systems.v1";
export const interiorSystemKinds=["quran-shelf","rehal-rack","prayer-chair","cane-rack","shoe-storage","water-station","donation-point","prayer-display","audio-point","acoustic-panel","lighting-ring","mobile-partition","family-zone","sensory-zone","cleaning-store","chair-store","first-aid","welcome-point"]as const;
export type InteriorSystemKind=typeof interiorSystemKinds[number];export type EventMode="daily"|"jumuah"|"ramadan"|"eid"|"itikaf"|"learning"|"cleaning";
export type InteriorSystemItem={id:string;kind:InteriorSystemKind;label:string;roomId:string;quantity:number;position:[number,number,number];rotationDeg:number;dimensions:[number,number,number];selected:boolean;power:"none"|"review"|"required";water:"none"|"review"|"required";reviewState:"concept"|"needs-evidence"|"ready-for-review";sourceRef:string;ownerRole:string;carePlan:string;notes:string};
export type InteriorSystemsStudy={schema:typeof INTERIOR_SYSTEMS_SCHEMA;status:"executable";updatedAt:string;activeMode:EventMode;items:InteriorSystemItem[];storageAvailableM2:number;cleaningRouteM:number;operationsNotes:string};
type Template={kind:InteriorSystemKind;label:string;category:string;brief:string;dimensions:[number,number,number];marketQuery:string;checks:string[];power:InteriorSystemItem["power"];water:InteriorSystemItem["water"]};
export const interiorSystemTemplates:Template[]=[
 {kind:"quran-shelf",label:"Accessible Qur’an shelving",category:"Worship",brief:"Plan reach ranges, large-print and accessible editions without narrowing rows.",dimensions:[2.4,1.1,.35],marketQuery:"accessible mosque Quran bookshelf",checks:["Reach and transfer space","Capacity and language labels","Stability and fire strategy"],power:"none",water:"none"},
 {kind:"rehal-rack",label:"Rehal storage rack",category:"Worship",brief:"Keep stands stored, countable and clear of circulation.",dimensions:[1.5,1,.45],marketQuery:"mosque Quran stand storage rack",checks:["Stored and deployed footprint","Safe edges and stability","Cleaning access"],power:"none",water:"none"},
 {kind:"prayer-chair",label:"Integrated prayer-chair row",category:"Accessibility",brief:"Distribute dignified chair positions with equivalent hearing and sightlines.",dimensions:[.55,.9,.6],marketQuery:"stackable mosque prayer chair",checks:["Transfer and route clearance","Equivalent audio and sightline","Storage when not in use"],power:"none",water:"none"},
 {kind:"cane-rack",label:"Cane and walking-aid rack",category:"Accessibility",brief:"Place support storage within reach without creating trip hazards.",dimensions:[.8,.75,.3],marketQuery:"walking cane storage rack",checks:["Reach and identification","Tip stability","No route projection"],power:"none",water:"none"},
 {kind:"shoe-storage",label:"Ventilated shoe storage",category:"Arrival",brief:"Link capacity to attendance, wet footwear and overflow operations.",dimensions:[2.4,1.8,.45],marketQuery:"mosque shoe storage rack",checks:["Capacity scenario","Ventilation and odor","Bench and accessible reach"],power:"review",water:"none"},
 {kind:"water-station",label:"Accessible water station",category:"Welfare",brief:"Coordinate refill, cups, drainage and spill-resistant flooring.",dimensions:[1.2,1.1,.65],marketQuery:"accessible bottle filling station",checks:["Wheelchair approach","Drainage and spill route","Ramadan demand"],power:"review",water:"required"},
 {kind:"donation-point",label:"Low-prominence donation point",category:"Operations",brief:"Provide secure giving without obstructing movement or dominating worship space.",dimensions:[.7,1.1,.5],marketQuery:"secure donation box contactless terminal",checks:["Security and fixing","Accessible digital interface","Prayer-mode brightness"],power:"review",water:"none"},
 {kind:"prayer-display",label:"Prayer information display",category:"Technology",brief:"Use dimmable, legible information with a low-distraction prayer mode.",dimensions:[1.6,.7,.12],marketQuery:"dimmable mosque prayer time display",checks:["Viewing distance and contrast","Automatic dimming","Content ownership"],power:"required",water:"none"},
 {kind:"audio-point",label:"Distributed audio point",category:"Technology",brief:"Coordinate speech coverage, hearing assistance and discreet cable routes.",dimensions:[.3,.45,.25],marketQuery:"mosque column speaker hearing assistance",checks:["Acoustic prediction","Hearing assistance","Power, data and access"],power:"required",water:"none"},
 {kind:"acoustic-panel",label:"Replaceable acoustic panel",category:"Sensory",brief:"Treat speech clarity as measured performance, not visual decoration.",dimensions:[1.2,2.4,.08],marketQuery:"fire rated acoustic wall panel",checks:["Test evidence","Fire and emissions","Cleaning and replacement"],power:"none",water:"none"},
 {kind:"lighting-ring",label:"Serviceable lighting ring",category:"Lighting",brief:"Coordinate glare, suspension, dimming, emergency mode and high-level access.",dimensions:[4,.2,4],marketQuery:"dimmable mosque ring chandelier",checks:["Suspension engineering","Glare and controls","Cleaning and relamping access"],power:"required",water:"none"},
 {kind:"mobile-partition",label:"Stored mobile partition",category:"Flexibility",brief:"Test deployed and stored conditions against sound, routes and exits.",dimensions:[3,2,.4],marketQuery:"acoustic mobile partition system",checks:["Stored footprint","Stability and operation","Egress and acoustic evidence"],power:"none",water:"none"},
 {kind:"family-zone",label:"Family support zone",category:"Family",brief:"Coordinate caregiver seating, stroller parking, acoustics and visibility.",dimensions:[4,2.4,3],marketQuery:"family room mosque furnishings",checks:["Caregiver consultation","Acoustic and visual connection","Safe washable finishes"],power:"review",water:"none"},
 {kind:"sensory-zone",label:"Lower-stimulus prayer zone",category:"Inclusion",brief:"Offer lower sound, softer light, clear exit access and caregiver space.",dimensions:[3,2.4,2.5],marketQuery:"sensory room acoustic lighting equipment",checks:["Direct user review","Lighting and sound controls","Unobstructed exit"],power:"review",water:"none"},
 {kind:"cleaning-store",label:"Prayer-hall cleaning store",category:"Care",brief:"Store vacuum and carpet equipment with a safe cleaning route.",dimensions:[1.8,2.4,1.2],marketQuery:"commercial carpet cleaning storage cabinet",checks:["Equipment and outlet coverage","Chemical segregation","Drying and service route"],power:"required",water:"review"},
 {kind:"chair-store",label:"Stackable furniture store",category:"Storage",brief:"Size storage from actual event modes and handling routes.",dimensions:[2.4,2.4,2],marketQuery:"commercial stackable chair storage trolley",checks:["Deployed quantity","Trolley route","Manual handling"],power:"none",water:"none"},
 {kind:"first-aid",label:"Visible first-aid and AED point",category:"Safety",brief:"Coordinate visibility, access, inspection and emergency responsibility.",dimensions:[.8,1.5,.3],marketQuery:"public access AED cabinet first aid station",checks:["Emergency plan location","Inspection responsibility","Current local requirements"],power:"review",water:"none"},
 {kind:"welcome-point",label:"First-visit welcome point",category:"Welcome",brief:"Explain shoes, facilities and prayer orientation without visual clutter.",dimensions:[1.4,1.1,.6],marketQuery:"accessible welcome desk brochure display",checks:["Multilingual plain language","Accessible counter section","Posting and content policy"],power:"review",water:"none"}
];
export const eventModeBundles:Record<EventMode,InteriorSystemKind[]>={daily:["quran-shelf","rehal-rack","prayer-chair","cane-rack","shoe-storage"],jumuah:["prayer-chair","shoe-storage","audio-point","prayer-display","first-aid"],ramadan:["quran-shelf","rehal-rack","water-station","chair-store","cleaning-store"],eid:["shoe-storage","audio-point","water-station","first-aid","welcome-point"],itikaf:["quran-shelf","sensory-zone","water-station","mobile-partition","cleaning-store"],learning:["mobile-partition","chair-store","audio-point","welcome-point","family-zone"],cleaning:["cleaning-store","chair-store","mobile-partition"]};
export function createInteriorSystemItem(kind:InteriorSystemKind,index=0):InteriorSystemItem{const t=interiorSystemTemplates.find(x=>x.kind===kind)??interiorSystemTemplates[0];return{id:`interior-${kind}-${Date.now()}-${index}`,kind,label:t.label,roomId:"prayer-hall",quantity:1,position:[1.2+(index%5)*1.5,0,1.2+Math.floor(index/5)*1.5],rotationDeg:0,dimensions:[...t.dimensions],selected:true,power:t.power,water:t.water,reviewState:"concept",sourceRef:"",ownerRole:"",carePlan:"",notes:""}}
export function blankInteriorSystemsStudy():InteriorSystemsStudy{return{schema:INTERIOR_SYSTEMS_SCHEMA,status:"executable",updatedAt:new Date(0).toISOString(),activeMode:"daily",items:eventModeBundles.daily.map(createInteriorSystemItem),storageAvailableM2:0,cleaningRouteM:0,operationsNotes:""}}
const bounded=(n:unknown,fallback:number,min:number,max:number)=>typeof n==="number"&&Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;
export function safeInteriorSystemsStudy(value:unknown):InteriorSystemsStudy|null{if(!value||typeof value!=="object")return null;const x=value as Partial<InteriorSystemsStudy>;if(x.schema!==INTERIOR_SYSTEMS_SCHEMA||!Array.isArray(x.items)||x.items.length>100)return null;const items=x.items.filter(item=>item&&interiorSystemKinds.includes(item.kind)).map((item,index)=>{const base=createInteriorSystemItem(item.kind,index);return{...base,...item,id:typeof item.id==="string"?item.id.slice(0,120):base.id,label:typeof item.label==="string"?item.label.slice(0,120):base.label,quantity:Math.round(bounded(item.quantity,1,0,1000)),position:[bounded(item.position?.[0],0,-200,200),bounded(item.position?.[1],0,-20,100),bounded(item.position?.[2],0,-200,200)]as[number,number,number],dimensions:[bounded(item.dimensions?.[0],1,.05,50),bounded(item.dimensions?.[1],1,.05,50),bounded(item.dimensions?.[2],1,.05,50)]as[number,number,number],rotationDeg:bounded(item.rotationDeg,0,-360,360)}});return{...blankInteriorSystemsStudy(),...x,schema:INTERIOR_SYSTEMS_SCHEMA,status:"executable",activeMode:Object.keys(eventModeBundles).includes(x.activeMode??"")?x.activeMode as EventMode:"daily",items,storageAvailableM2:bounded(x.storageAvailableM2,0,0,10000),cleaningRouteM:bounded(x.cleaningRouteM,0,0,100000),operationsNotes:typeof x.operationsNotes==="string"?x.operationsNotes.slice(0,3000):""}}
export function applyEventMode(study:InteriorSystemsStudy,mode:EventMode){const existing=new Set(study.items.map(x=>x.kind)),added=eventModeBundles[mode].filter(kind=>!existing.has(kind)).map((kind,index)=>createInteriorSystemItem(kind,study.items.length+index));return{...study,activeMode:mode,items:[...study.items,...added],updatedAt:new Date().toISOString()}}
export function interiorSystemChecks(study:InteriorSystemsStudy){const selected=study.items.filter(x=>x.selected),gaps:string[]=[];if(!selected.length)gaps.push("select at least one operational component");if(selected.some(x=>!x.ownerRole))gaps.push("accountable owner roles");if(selected.some(x=>!x.sourceRef))gaps.push("product or performance evidence references");if(selected.some(x=>!x.carePlan))gaps.push("cleaning, inspection and replacement plans");if(selected.some(x=>x.power!=="none"))gaps.push("electrical, controls and fire coordination");if(selected.some(x=>x.water!=="none"))gaps.push("water, drainage and hygiene coordination");const stored=selected.filter(x=>["rehal-rack","cleaning-store","chair-store","mobile-partition"].includes(x.kind)).reduce((sum,x)=>sum+x.dimensions[0]*x.dimensions[2]*x.quantity,0);if(stored>study.storageAvailableM2)gaps.push("entered storage allowance is below selected storage footprint");return{selected:selected.length,quantity:selected.reduce((sum,x)=>sum+x.quantity,0),storageRequiredM2:Math.round(stored*10)/10,gaps}}
