import type {SchematicPlan} from "@/lib/schematic-plan";
export const DECORATION_SCHEMA="mosque.build/interior-decoration@1" as const;
export type PaletteId="mineral-calm"|"garden-muted"|"earth-timber"|"night-neutral";
export type DecorationRoom={roomId:string;palette:PaletteId;wallIntent:"light-mineral"|"warm-neutral"|"muted-green"|"deep-neutral";ceilingIntent:"quiet"|"timber-rhythm"|"acoustic-baffle-study"|"feature-zone-study";lighting:"balanced"|"warm-layered"|"daylight-led"|"low-glare-study";acoustic:"not-set"|"absorptive-zone-study"|"speech-review"|"quiet-room-review";furnishings:string[];wayfinding:"not-set"|"plain-language"|"multilingual-review"|"symbol-and-text-review";inscription:"none"|"placeholder-review-zone";mockup:"not-planned"|"sample-board"|"full-scale-zone"|"reviewed-user-record";notes:string};
export type DecorationStudy={schema:typeof DECORATION_SCHEMA;status:"executable";updatedAt:string;rooms:DecorationRoom[];reviewState:"draft"|"community-review"|"professional-review";requirements:string[]};
export const palettes={"mineral-calm":{name:"Mineral calm",colors:["#f4efe3","#d7cdbb","#8a9b91","#315f54"]},"garden-muted":{name:"Garden muted",colors:["#f3efe1","#b9c6af","#6f8e78","#315747"]},"earth-timber":{name:"Earth + timber",colors:["#f2e9db","#c9a77e","#8a6647","#3d594f"]},"night-neutral":{name:"Deep neutral",colors:["#ece8df","#a9aaa2","#4e5e59","#243b36"]}} satisfies Record<PaletteId,{name:string;colors:string[]}>;
export const furnishingNeeds=["Shoe storage","Accessible seating","Quran shelving","Teaching lectern","Classroom tables","Stackable seating","Library shelving","Mobile partition","Notice display","Waste and recycling point","Cleaning storage","Assistive-listening position"];
const defaults:DecorationRoom={roomId:"",palette:"mineral-calm",wallIntent:"light-mineral",ceilingIntent:"quiet",lighting:"balanced",acoustic:"not-set",furnishings:[],wayfinding:"not-set",inscription:"none",mockup:"not-planned",notes:""};
export function createDecorationStudy(plan:SchematicPlan,existing?:DecorationStudy):DecorationStudy{return {schema:DECORATION_SCHEMA,status:"executable",updatedAt:new Date().toISOString(),rooms:plan.rooms.map(room=>existing?.rooms.find(x=>x.roomId===room.id)??{...defaults,roomId:room.id,acoustic:room.kind==="prayer"?"speech-review":"not-set",furnishings:room.kind==="prayer"?["Quran shelving","Accessible seating"]:room.kind==="learning"?["Classroom tables","Stackable seating"]:[]}),reviewState:existing?.reviewState??"draft",requirements:existing?.requirements??["Physical sample board under intended light","Fire, emissions and cleaning evidence for every finish","Acoustic and AV coordination before fixing decorative layers","Accessible contrast, reach and circulation review","Exact inscription content, orthography, placement, rights and scholarly review"]}}
export function decorationGaps(room:DecorationRoom){const gaps:string[]=[];if(room.acoustic==="not-set")gaps.push("acoustic intent");if(room.wayfinding==="not-set")gaps.push("wayfinding intent");if(room.mockup==="not-planned")gaps.push("mockup plan");if(room.inscription==="placeholder-review-zone")gaps.push("inscription content review");return gaps}
export function safeDecorationStudy(value:unknown):DecorationStudy|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const x=value as Partial<DecorationStudy>;if(x.schema!==DECORATION_SCHEMA||x.status!=="executable"||!Array.isArray(x.rooms)||x.rooms.length>100||!Array.isArray(x.requirements)||x.requirements.length>30)return null;const valid=x.rooms.every(room=>room&&typeof room.roomId==="string"&&room.roomId.length<=100&&typeof room.notes==="string"&&room.notes.length<=1000&&Array.isArray(room.furnishings)&&room.furnishings.length<=30&&room.furnishings.every(v=>furnishingNeeds.includes(v))&&typeof room.palette==="string"&&room.palette in palettes);return valid?x as DecorationStudy:null}
