export const ISLAMIC_ARCHITECTURE_SCHEMA="mosque.build/islamic-architecture-framework@1" as const;
export const architectureLenses=["worship","arrival","community","learning","care","climate","water","light","sound","structure","craft","landscape","adaptation","operations"]as const;
export type Lens=typeof architectureLenses[number];export type ReviewState="not-started"|"question-framed"|"evidence-linked"|"ready-for-review"|"reviewed-user-record";
export type ArchitecturePrompt={id:string;lens:Lens;title:string;question:string;why:string;test:string;linkedWorkspace:"brief"|"site"|"floor-plan"|"structure"|"roof"|"interior"|"wudu"|"women"|"materials"|"operations";reviewGate:"community"|"religious"|"architect"|"engineer"|"specialist";sourceIds:string[];caution:string};
export type ArchitectureResponse={promptId:string;state:ReviewState;projectResponse:string;evidenceRef:string;ownerRole:string;reviewNotes:string;modelLayerRef:string;decisionRef:string};
export type ArchitectureOption={id:string;label:string;lineageIds:string[];principleIds:string[];siteResponse:string;spatialResponse:string;materialResponse:string;climateResponse:string;careResponse:string;tradeoffs:string;status:"concept"|"developed-user-record"|"reviewed-user-record"};
export type IslamicArchitectureState={schema:typeof ISLAMIC_ARCHITECTURE_SCHEMA;status:"executable";projectIntent:string;communityAuthorship:string;responses:ArchitectureResponse[];options:ArchitectureOption[];selectedOptionId:string;religiousReviewRole:string;architectReviewRole:string;localCraftReviewRole:string;updatedAt:string};
export type ArchitectureCheck={id:string;severity:"blocker"|"review";group:"authorship"|"worship"|"evidence"|"design"|"care"|"review";label:string;detail:string;promptId?:string};
export const architectureSources=[{id:"met-context",label:"The Metropolitan Museum of Art — Islamic Art historical context",url:"https://resources.metmuseum.org/resources/metpublications/pdf/Islamic_art_in_the_Metropolitan_Museum_the_historical_context.pdf",observedAt:"2026-09-09",rights:"Linked museum publication; mosque.build synthesis is original",confidence:"source_backed"},{id:"met-geometry",label:"The Metropolitan Museum of Art — Islamic Art and Geometric Design",url:"https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/islamic_art_and_geometric_design.pdf",observedAt:"2026-09-09",rights:"Linked museum educator resource; diagrams not reproduced",confidence:"source_backed"},{id:"unesco-isfahan",label:"UNESCO — Masjed-e Jame of Isfahan",url:"https://whc.unesco.org/en/list/1397/",observedAt:"2026-09-09",rights:"Linked UNESCO record; content not reproduced",confidence:"source_backed"},{id:"unesco-anatolia",label:"UNESCO — Wooden Hypostyle Mosques of Medieval Anatolia",url:"https://whc.unesco.org/en/list/1694/",observedAt:"2026-09-09",rights:"Linked UNESCO record; content not reproduced",confidence:"source_backed"},{id:"unesco-djenne",label:"UNESCO — Old Towns of Djenné",url:"https://whc.unesco.org/en/list/116/",observedAt:"2026-09-09",rights:"Linked UNESCO record; content not reproduced",confidence:"source_backed"},{id:"unesco-lamu",label:"UNESCO — Lamu Old Town",url:"https://whc.unesco.org/en/list/1055/",observedAt:"2026-09-09",rights:"Linked UNESCO record; content not reproduced",confidence:"source_backed"},{id:"archnet",label:"Archnet — open-access architecture library",url:"https://www.archnet.org/",observedAt:"2026-09-09",rights:"Linked research library; individual record rights vary",confidence:"source_backed"}]as const;
const seeds:Array<[Lens,string,string,string,string,ArchitecturePrompt["linkedWorkspace"],ArchitecturePrompt["reviewGate"],string[],string]>=[
["worship","Qibla legibility","How will people understand qibla direction through space rather than applied signs alone?","Orientation is both a worship requirement and a spatial coordination task.","Compare arrival, room geometry, saff direction, mihrab emphasis and accessible wayfinding.","floor-plan","religious",["met-context"],"Do not infer a religious ruling or exact qibla from a precedent."],
["worship","Prayer-row continuity","Where do columns, doors, furniture and level changes interrupt usable rows?","Structural and operational decisions shape congregational use.","Overlay structural grids, openings, accessible positions and peak circulation on saff studies.","floor-plan","architect",["unesco-anatolia"],"Do not optimize a numeric capacity at the expense of dignity, safety or varied bodies."],
["worship","Mihrab and minbar brief","What functions, visibility, audibility, craft and review does the qibla focus actually need?","The qibla wall needs an accountable worship and technical brief.","Mock up sightlines, sound, approach, maintenance and content before fabrication.","interior","religious",["met-context"],"Do not generate sacred text or copy a historic mihrab as decorative filler."],
["worship","Daily-to-Jumu’ah change","How does the building support intimate daily prayer and peak congregation without dead space?","Mosques operate across radically different attendance modes.","Test partitions, overflow, circulation, heating/cooling zones and stewardship for both modes.","floor-plan","community",["archnet"],"Do not treat maximum attendance as the only measure of a successful prayer space."],
["arrival","Civic threshold","How does arrival communicate welcome, worship, safety and neighborhood relationship?","Thresholds mediate public street, courtyard and prayer life.","Sequence public edge, shade, seating, shoes, information, security and step-free entry.","site","community",["unesco-lamu"],"Do not use monumentality to conceal confusing or exclusionary access."],
["arrival","Shoes and transition","Can shoe removal work at daily and peak loads without blocking accessible or emergency journeys?","A small operational threshold can determine dignity and congestion.","Prototype clean/dirty movement, storage reach, seating, drainage and overflow.","interior","architect",["archnet"],"Do not place storage into required circulation after design freeze."],
["arrival","Courtyard as room","Is a courtyard needed, and what worship, climate, gathering and maintenance work will it do?","Courtyards vary widely and are not a universal mosque requirement.","Compare shaded use hours, wind, rain, acoustics, routes, planting, water and event changeover.","site","architect",["unesco-isfahan","unesco-lamu"],"Do not add a courtyard as a stylistic label without performance and care evidence."],
["arrival","Minaret and public marker","What signaling, access, maintenance and local meaning is intended?","A minaret may be spatial, civic, acoustic, symbolic or unnecessary.","Record community intent, authority context, structure, lightning, maintenance and alternatives.","structure","religious",["met-context"],"Do not assume a minaret is required, permitted, structurally simple or culturally neutral."],
["community","Hospitality gradient","Where can visitors understand the building without entering private or worship-focused zones?","Legible gradients support welcome and safeguarding.","Map reception, waiting, information, tours, pastoral support and after-hours boundaries.","floor-plan","community",["unesco-lamu"],"Do not turn security zoning into social exclusion."],
["community","Multi-generational commons","Which spaces support elders, children, carers, youth and new Muslims together and separately?","Community life needs both encounter and refuge.","Test seating, play, quiet, visibility, acoustics, safeguarding and flexible scheduling.","brief","community",["archnet"],"Do not assume one demographic represents the entire community."],
["community","Women’s equal-quality journey","Are arrival, worship, learning, amenities and participation equal in quality?","Secondary or improvised provision embeds inequity.","Review routes, sightlines, sound, climate, capacity and governance directly with women.","women","community",["archnet"],"Do not prescribe one spatial arrangement or treat consultation as complete without evidence."],
["community","Care and pastoral privacy","Where can confidential, accessible and culturally appropriate support happen?","Mosques often support people beyond scheduled worship.","Test acoustic privacy, safeguarding, waiting, exits, records and after-hours use.","brief","community",["archnet"],"Do not collect personal case information in the design brief."],
["learning","Learning ecosystem","How do formal classes, informal study, library use and digital learning coexist?","Learning is spatial, acoustic, operational and curatorial.","Map age groups, furniture, storage, accessibility, safeguarding, daylight and changeover.","floor-plan","community",["archnet"],"Do not let classroom capacity overwrite prayer or community needs."],
["learning","Knowledge display","What may be displayed, who reviews it and how is it cared for?","Religious and historical content needs provenance and stewardship.","Define curator, scholarly review, rights, mounting, light exposure and replacement.","interior","religious",["met-context"],"Do not use sacred calligraphy as generic surface texture."],
["care","Dignified ablution sequence","Does wudu connect worship, privacy, dryness, accessibility and maintenance?","Wudu is a recurring ritual and demanding wet-service environment.","Test approach, seating, splash, drainage, drying, assistance and cleaning routes.","wudu","religious",["archnet"],"Do not infer universal ritual preferences; obtain qualified and community review."],
["care","Inclusive sanitary provision","Can varied bodies, carers and families use facilities with dignity?","Access is more than a nominal cubicle.","Review complete journeys, transfer, reach, privacy, alarms, changing and cleaning.","wudu","specialist",["archnet"],"Do not claim accessibility from fixture counts alone."],
["climate","Shade hierarchy","How do roof, arcade, screen, trees and thresholds create usable shade?","Shade can connect arrival, worship overflow and community life.","Map seasonal sun and occupied times before selecting form.","site","architect",["unesco-lamu"],"Do not copy an arcade without testing local sun, wind, rain and structure."],
["climate","Passive ventilation logic","When can openings, stack paths, mass and fans provide comfort safely?","Historic climate responses require current performance testing.","Model occupied modes, outdoor conditions, acoustics, security and backup operation.","roof","engineer",["unesco-lamu","unesco-djenne"],"Do not claim comfort or energy performance from precedent alone."],
["climate","Thermal zoning","Can daily prayer, Friday peaks and community rooms condition independently?","Operational zoning can reduce waste and improve resilience.","Link attendance modes to envelope, controls, ventilation and maintenance.","operations","engineer",["archnet"],"Do not promise savings without calibrated energy evidence."],
["climate","Rain and flood thresholds","How do roof, court, entrances and landscape keep safe routes usable?","Water behavior joins site, foundation, enclosure and operations.","Trace primary and exceedance routes, thresholds, sacrificial zones and recovery.","site","engineer",["unesco-djenne"],"Do not transfer flood risk to neighbors or inaccessible routes."],
["water","Water stewardship","How are potable water, wudu demand, leakage, reuse and drought continuity governed?","Water is both an operational necessity and environmental responsibility.","Meter end uses, define quality boundaries, inspect systems and plan outage modes.","wudu","engineer",["archnet"],"Do not treat collected water as safe for use without applicable treatment evidence."],
["light","Daylight for worship","How does daylight support orientation and calm without glare, heat or distraction?","Light changes by prayer time, season and material.","Study qibla wall, reading positions, screens, rooflights and electric-light transitions.","interior","architect",["unesco-isfahan"],"Do not reproduce a historic lighting effect without climate and glare analysis."],
["light","Night identity and safety","How does exterior lighting support arrival, neighbors, ecology and energy care?","Night use needs legibility without spectacle or nuisance.","Mock up route lighting, entrances, signs, dark-sky control and emergency modes.","site","specialist",["archnet"],"Do not equate brightness with welcome or safety."],
["sound","Speech and recitation clarity","How will unamplified and amplified sound remain clear across occupancy modes?","Prayer halls need coordinated room form, absorption and sound systems.","Measure reverberation targets, loudspeaker coverage, background noise and assistive listening.","interior","specialist",["archnet"],"Do not specify decorative surfaces before acoustic testing."],
["sound","Neighborhood sound relationship","How will arrivals, events, plant and amplified sound respect neighbors?","A mosque is part of a wider acoustic community.","Observe time-based sound, locate plant and entrances, and agree operational controls.","site","community",["archnet"],"Do not assume a legal limit alone resolves community relationships."],
["structure","Structure aligned with worship","Can spans, grids and lateral systems support rows, sightlines and future change?","Structural order strongly shapes prayer space.","Compare bay options with saff modules, expansion joints, services and construction capacity.","structure","engineer",["unesco-anatolia"],"Do not infer member sizes, fire resistance or seismic behavior from heritage precedent."],
["structure","Dome purpose and load path","If a dome is proposed, what spatial or environmental purpose justifies it?","Domes carry structural, acoustic, weather and maintenance consequences.","Compare dome and non-dome options for thrust, wind, water, sound, access and cost.","roof","engineer",["unesco-isfahan"],"Do not treat a dome as required or as a renderer-only object."],
["craft","Geometric pattern authorship","Who develops geometry, meaning, fabrication and attribution?","Pattern is a knowledge practice, not a downloadable skin.","Record source, construction logic, rights, maker, scale, substrate and mockup review.","materials","specialist",["met-geometry"],"Do not present generic geometry as belonging to a named culture without evidence."],
["craft","Local maker integration","How can local craft knowledge shape assemblies and maintenance?","Craft capacity affects buildability, authorship and long-term care.","Commission samples, name roles, test tolerances and fund documentation/training.","materials","community",["unesco-lamu","unesco-djenne"],"Do not romanticize unpaid community labor or extract motifs without consent."],
["craft","Calligraphy governance","Is text needed, which text, who authorizes it and who executes it?","Sacred and dedicatory text carries religious, linguistic and authorship responsibility.","Create a separate content approval, translation, placement, rights and fabrication workflow.","interior","religious",["met-context"],"Never generate sacred calligraphy as decorative filler."],
["landscape","Prayer beyond the enclosure","Can shaded external space support overflow, Eid or reflection without harming landscape systems?","Outdoor worship depends on ground, shade, routes, sound and operations.","Test orientation, surface, drainage, accessible route, setup and recovery.","site","community",["archnet"],"Do not designate outdoor capacity without heat, rain, access and emergency review."],
["adaptation","Adaptive reuse legibility","What existing fabric should remain visible and what interventions must be reversible?","Reuse can conserve resources and community memory while adding risk.","Map significance, structure, fire, access, services, moisture and reversible layers.","structure","architect",["archnet"],"Do not claim historical continuity or structural suitability from appearance."],
["adaptation","Phased growth grammar","Can early phases remain dignified, safe and complete while enabling growth?","Many communities build incrementally.","Define independent worship, water, access, fire, structure and landscape states for each phase.","floor-plan","architect",["archnet"],"Do not leave temporary conditions without ownership, expiry and inspection."],
["operations","Stewardship before ornament","Who will inspect, clean, repair and fund each distinctive feature?","Architecture succeeds through care, not completion photographs.","Attach access, interval, skills, spares, cost and accountable role to each feature.","operations","community",["unesco-djenne","unesco-anatolia"],"Do not specify labor-intensive heritage-inspired features without a funded care plan."],
["operations","Ramadan and event mode","How will extended hours, food, crowds, cleaning and transport change the building?","Seasonal use can exceed ordinary operational assumptions.","Run a full event-day scenario across site, prayer, food, waste, safeguarding and shutdown.","operations","community",["archnet"],"Do not rely on volunteers or informal overflow without safety and dignity planning."],
["operations","Feedback after opening","How will lived experience change space and operations?","Post-occupancy learning prevents repeated design mistakes.","Plan accessible feedback, seasonal reviews, measured performance and funded adjustments.","operations","community",["archnet"],"Do not treat opening day as the end of design."]];
export const architecturePrompts:ArchitecturePrompt[]=seeds.map((x,i)=>({id:`architecture-principle-${i+1}`,lens:x[0],title:x[1],question:x[2],why:x[3],test:x[4],linkedWorkspace:x[5],reviewGate:x[6],sourceIds:x[7],caution:x[8]}));
const response=(promptId:string):ArchitectureResponse=>({promptId,state:"not-started",projectResponse:"",evidenceRef:"",ownerRole:"",reviewNotes:"",modelLayerRef:"",decisionRef:""});
export function createIslamicArchitectureState():IslamicArchitectureState{return{schema:ISLAMIC_ARCHITECTURE_SCHEMA,status:"executable",projectIntent:"",communityAuthorship:"",responses:architecturePrompts.map(x=>response(x.id)),options:[],selectedOptionId:"",religiousReviewRole:"",architectReviewRole:"",localCraftReviewRole:"",updatedAt:""}}
export const newArchitectureOption=(n=1):ArchitectureOption=>({id:`architecture-option-${Date.now()}-${n}`,label:`Architecture option ${n}`,lineageIds:[],principleIds:[],siteResponse:"",spatialResponse:"",materialResponse:"",climateResponse:"",careResponse:"",tradeoffs:"",status:"concept"});
export function architectureChecks(s:IslamicArchitectureState):ArchitectureCheck[]{const c:ArchitectureCheck[]=[];const add=(severity:ArchitectureCheck["severity"],group:ArchitectureCheck["group"],label:string,detail:string,promptId?:string)=>c.push({id:`${group}:${label}:${promptId||"project"}`,severity,group,label,detail,promptId});if(!s.projectIntent||!s.communityAuthorship)add("blocker","authorship","Project authorship incomplete","Record project intent and how affected community voices author and review the direction.");if(!s.religiousReviewRole)add("review","review","Religious review role missing","Record the qualified role responsible for worship and sacred-content questions.");if(!s.architectReviewRole)add("review","review","Architectural review role missing","Record the accountable local architect role.");for(const r of s.responses){const p=architecturePrompts.find(x=>x.id===r.promptId);if(!p){add("blocker","evidence","Unknown principle reference","A response references a missing principle.",r.promptId);continue}if(["evidence-linked","ready-for-review","reviewed-user-record"].includes(r.state)&&!r.evidenceRef)add("blocker","evidence","Evidence reference missing",`${p.title} is advanced without evidence.`,p.id);if(["ready-for-review","reviewed-user-record"].includes(r.state)&&(!r.projectResponse||!r.ownerRole))add("blocker","design","Response ownership incomplete",`${p.title} needs a project response and accountable role.`,p.id);if(r.state==="reviewed-user-record"&&!r.reviewNotes)add("blocker","review","Review record incomplete",`${p.title} is marked reviewed without review notes.`,p.id)}for(const o of s.options){if(!o.principleIds.length||!o.spatialResponse||!o.tradeoffs)add("review","design","Architecture option incomplete",`${o.label} needs principles, spatial response and explicit tradeoffs.`);if(o.status==="reviewed-user-record"&&(!s.architectReviewRole||!s.religiousReviewRole))add("blocker","review","Unsupported option review",`${o.label} is reviewed without architectural and religious review roles.`);if(!o.careResponse)add("review","care","Care response missing",`${o.label} needs inspection, cleaning, repair, skills and funding implications.`)}if(s.selectedOptionId&&!s.options.some(x=>x.id===s.selectedOptionId))add("blocker","design","Selected option missing","The selected architecture option no longer exists.");return c}
export function architectureSummary(s:IslamicArchitectureState){const checks=architectureChecks(s),started=s.responses.filter(x=>x.state!=="not-started"),reviewed=s.responses.filter(x=>x.state==="reviewed-user-record");return{principles:architecturePrompts.length,started:started.length,reviewed:reviewed.length,evidenced:s.responses.filter(x=>x.evidenceRef).length,lenses:new Set(started.map(x=>architecturePrompts.find(p=>p.id===x.promptId)?.lens).filter(Boolean)).size,options:s.options.length,blockers:checks.filter(x=>x.severity==="blocker").length,reviews:checks.filter(x=>x.severity==="review").length}}
export function safeIslamicArchitectureState(value:unknown):IslamicArchitectureState|null{if(!value||typeof value!=="object")return null;const x=value as IslamicArchitectureState;if(x.schema!==ISLAMIC_ARCHITECTURE_SCHEMA||x.status!=="executable"||!Array.isArray(x.responses)||x.responses.length>100||!Array.isArray(x.options)||x.options.length>20)return null;if(!x.responses.every(r=>typeof r.promptId==="string"&&r.promptId.length<100&&["not-started","question-framed","evidence-linked","ready-for-review","reviewed-user-record"].includes(r.state)))return null;return x}
