export const KNOWLEDGE_LIBRARY_SCHEMA="mosque.build/knowledge-library@1";
export type KnowledgeKind="Quran / translation"|"Tafsir"|"Hadith"|"Fiqh"|"Seerah"|"Arabic learning"|"Children / youth"|"New Muslim"|"Reference"|"Equipment";
export type ReviewState="needs-curator-review"|"curator-reviewed"|"scholarly-review-required";
export type KnowledgeItem={id:string;title:string;kind:KnowledgeKind;language:string;audience:string;format:string;quantity:number;owned:number;priority:"essential"|"useful"|"future";reviewState:ReviewState;editionRef:string;sourceRef:string;notes:string;};
export type KnowledgeLibrary={schema:string;status:"executable";updatedAt:string;curatorRole:string;curriculum:string;languages:string[];audiences:string[];storage:"not-assessed"|"limited"|"adequate";circulation:"reference-only"|"lending"|"mixed"|"not-decided";items:KnowledgeItem[];};
export const kinds:KnowledgeKind[]=["Quran / translation","Tafsir","Hadith","Fiqh","Seerah","Arabic learning","Children / youth","New Muslim","Reference","Equipment"];
export const starterNeeds:{kind:KnowledgeKind;title:string;audience:string;format:string}[]=[
  {kind:"Quran / translation",title:"Community-requested Quran or translation edition",audience:"General",format:"Print"},
  {kind:"Arabic learning",title:"Arabic learning class set",audience:"Learners",format:"Print / workbook"},
  {kind:"Children / youth",title:"Age-reviewed children and youth collection",audience:"Children / youth",format:"Print"},
  {kind:"New Muslim",title:"Curator-reviewed new Muslim starter set",audience:"New Muslims",format:"Print / accessible digital"},
  {kind:"Reference",title:"Imam and teacher reference collection",audience:"Teachers",format:"Print / digital"},
  {kind:"Equipment",title:"Accessible shelving and cataloguing supplies",audience:"Library team",format:"Equipment"}
];
export function createKnowledgeLibrary():KnowledgeLibrary{return {schema:KNOWLEDGE_LIBRARY_SCHEMA,status:"executable",updatedAt:new Date().toISOString(),curatorRole:"",curriculum:"",languages:[],audiences:[],storage:"not-assessed",circulation:"not-decided",items:[]}}
const clean=(value:unknown,max=180)=>typeof value==="string"?value.trim().slice(0,max):"";
export function safeKnowledgeLibrary(value:unknown):KnowledgeLibrary|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const x=value as Partial<KnowledgeLibrary>;if(x.schema!==KNOWLEDGE_LIBRARY_SCHEMA||!Array.isArray(x.items)||x.items.length>200)return null;const items=x.items.flatMap((raw,index)=>{if(!raw||typeof raw!=="object")return [];const item=raw as Partial<KnowledgeItem>,kind=kinds.includes(item.kind as KnowledgeKind)?item.kind as KnowledgeKind:"Reference";return [{id:clean(item.id,80)||`restored-${index}`,title:clean(item.title),kind,language:clean(item.language,80),audience:clean(item.audience,80),format:clean(item.format,80),quantity:Math.max(1,Math.min(10_000,Number(item.quantity)||1)),owned:Math.max(0,Math.min(10_000,Number(item.owned)||0)),priority:["essential","useful","future"].includes(String(item.priority))?item.priority as KnowledgeItem["priority"]:"useful",reviewState:["needs-curator-review","curator-reviewed","scholarly-review-required"].includes(String(item.reviewState))?item.reviewState as ReviewState:"needs-curator-review",editionRef:clean(item.editionRef),sourceRef:clean(item.sourceRef,300),notes:clean(item.notes,500)}]});return {...createKnowledgeLibrary(),...x,curatorRole:clean(x.curatorRole),curriculum:clean(x.curriculum,500),languages:Array.isArray(x.languages)?x.languages.map(v=>clean(v,80)).filter(Boolean).slice(0,20):[],audiences:Array.isArray(x.audiences)?x.audiences.map(v=>clean(v,80)).filter(Boolean).slice(0,20):[],items}}
export function libraryMetrics(library:KnowledgeLibrary){const requested=library.items.reduce((n,x)=>n+x.quantity,0),owned=library.items.reduce((n,x)=>n+Math.min(x.owned,x.quantity),0),gaps=library.items.reduce((n,x)=>n+Math.max(0,x.quantity-x.owned),0),reviewed=library.items.filter(x=>x.reviewState==="curator-reviewed").length;return {requested,owned,gaps,reviewed,readiness:library.items.length?Math.round((reviewed/library.items.length)*100):0}}
export function createKnowledgeItem(seed:Partial<KnowledgeItem>={}):KnowledgeItem{return {id:`knowledge-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,title:"",kind:"Reference",language:"",audience:"General",format:"Print",quantity:1,owned:0,priority:"useful",reviewState:"needs-curator-review",editionRef:"",sourceRef:"",notes:"",...seed}}
