export const LAND_COST_SCHEMA="mosque.build/land-cost-study@1" as const;
export const LAND_COST_KEY="mosque-build.land-cost-study.v1";
export const areaUnits=["sqft","sqm","acre","hectare"]as const;export type AreaUnit=typeof areaUnits[number];
export type LandCandidate={id:string;label:string;area:number;areaUnit:AreaUnit;askingPrice:number;currency:string;purchaseTaxes:number;legalSurvey:number;dueDiligence:number;brokerFees:number;financeCarry:number;demolition:number;earthworks:number;remediation:number;utilityConnections:number;accessWorks:number;drainageWorks:number;landscapeRequirements:number;otherSiteCosts:number;contingencyPercent:number;usablePercent:number;maximumCoveragePercent:number;notes:string;sourceRef:string;observedAt:string;status:"screening"|"due-diligence"|"offer-review"};
export type LandCostStudy={schema:typeof LAND_COST_SCHEMA;status:"executable";candidates:LandCandidate[];updatedAt:string};
const uid=()=>`land-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
export const createLandCandidate=(label="Site option"):LandCandidate=>({id:uid(),label,area:0,areaUnit:"sqft",askingPrice:0,currency:"",purchaseTaxes:0,legalSurvey:0,dueDiligence:0,brokerFees:0,financeCarry:0,demolition:0,earthworks:0,remediation:0,utilityConnections:0,accessWorks:0,drainageWorks:0,landscapeRequirements:0,otherSiteCosts:0,contingencyPercent:0,usablePercent:100,maximumCoveragePercent:0,notes:"",sourceRef:"",observedAt:"",status:"screening"});
export const createLandCostStudy=():LandCostStudy=>({schema:LAND_COST_SCHEMA,status:"executable",candidates:[],updatedAt:""});
const factors:Record<AreaUnit,number>={sqft:1,sqm:10.7639104167,acre:43560,hectare:107639.104167};
export function areaInSqft(area:number,unit:AreaUnit){return Math.max(0,area)*factors[unit]}
export function areaInSqm(area:number,unit:AreaUnit){return areaInSqft(area,unit)/factors.sqm}
export const acquisitionItems=["purchaseTaxes","legalSurvey","dueDiligence","brokerFees","financeCarry"]as const;
export const siteItems=["demolition","earthworks","remediation","utilityConnections","accessWorks","drainageWorks","landscapeRequirements","otherSiteCosts"]as const;
export function landCostMetrics(candidate:LandCandidate,buildingFootprintSqm=0){const sqft=areaInSqft(candidate.area,candidate.areaUnit),sqm=areaInSqm(candidate.area,candidate.areaUnit),usableSqft=sqft*candidate.usablePercent/100,usableSqm=sqm*candidate.usablePercent/100,coverageSqft=candidate.maximumCoveragePercent?usableSqft*candidate.maximumCoveragePercent/100:0,acquisitionExtras=acquisitionItems.reduce((sum,key)=>sum+candidate[key],0),siteWorks=siteItems.reduce((sum,key)=>sum+candidate[key],0),subtotal=candidate.askingPrice+acquisitionExtras+siteWorks,contingency=subtotal*candidate.contingencyPercent/100,total=subtotal+contingency,buildingFootprintSqft=buildingFootprintSqm*factors.sqm;return{sqft,sqm,usableSqft,usableSqm,coverageSqft,acquisitionExtras,siteWorks,subtotal,contingency,total,askingPerSqft:sqft?candidate.askingPrice/sqft:0,allInPerSqft:sqft?total/sqft:0,allInPerUsableSqft:usableSqft?total/usableSqft:0,allInPerCoverageSqft:coverageSqft?total/coverageSqft:0,footprintCoveragePercent:usableSqm&&buildingFootprintSqm?buildingFootprintSqm/usableSqm*100:0,footprintFits:!coverageSqft||!buildingFootprintSqft||buildingFootprintSqft<=coverageSqft}}
const finite=(x:unknown,max=1e15)=>typeof x==="number"&&Number.isFinite(x)&&x>=0&&x<=max,text=(x:unknown,max=1000)=>typeof x==="string"&&x.length<=max;
export function safeLandCostStudy(value:unknown):LandCostStudy|null{if(!value||typeof value!=="object")return null;const x=value as LandCostStudy;if(x.schema!==LAND_COST_SCHEMA||x.status!=="executable"||!Array.isArray(x.candidates)||x.candidates.length>6)return null;const numeric=["area","askingPrice",...acquisitionItems,...siteItems,"contingencyPercent","usablePercent","maximumCoveragePercent"]as const;if(!x.candidates.every(c=>text(c.id,100)&&text(c.label,100)&&areaUnits.includes(c.areaUnit)&&numeric.every(k=>finite(c[k]))&&c.contingencyPercent<=100&&c.usablePercent<=100&&c.maximumCoveragePercent<=100&&text(c.currency,3)&&text(c.notes,4000)&&text(c.sourceRef,1000)&&text(c.observedAt,10)&&["screening","due-diligence","offer-review"].includes(c.status)))return null;return x}
export function landCostGaps(candidate:LandCandidate){const gaps:string[]=[];if(!candidate.area)gaps.push("site area");if(!candidate.askingPrice)gaps.push("asking price");if(!candidate.currency)gaps.push("currency");if(!candidate.sourceRef.trim())gaps.push("price source");if(!candidate.observedAt)gaps.push("observation date");if(candidate.usablePercent===100)gaps.push("verified usable-area deduction");if(!candidate.maximumCoveragePercent)gaps.push("verified coverage control");if(!candidate.dueDiligence)gaps.push("due-diligence allowance or confirmed zero");if(!candidate.utilityConnections)gaps.push("utility allowance or confirmed zero");if(!candidate.drainageWorks)gaps.push("drainage allowance or confirmed zero");return gaps}
