export const MATERIAL_SELECTION_SCHEMA="mosque.build/material-selection@1" as const;
export const materialStages=["candidate","sampling","mockup","review","selected","installed","accepted"] as const;
export const sampleStages=["not-requested","requested","received","reviewed","rejected"] as const;
export const decisionStatuses=["open","hold","ready-for-review","recorded"] as const;
export type MaterialStage=typeof materialStages[number];export type SampleStage=typeof sampleStages[number];export type DecisionStatus=typeof decisionStatuses[number];
export type MaterialRecord={id:string;title:string;assemblyGroup:string;area:string;application:string;stage:MaterialStage;sampleStage:SampleStage;decisionStatus:DecisionStatus;responsibleRole:string;exposures:string[];sourceRef:string;observedAt:string;rights:string;performanceEvidence:string;sampleRef:string;mockupRef:string;substrate:string;interfaceNotes:string;storagePlan:string;installationMethodRef:string;inspectionRef:string;maintenancePlan:string;spareStrategy:string;endOfLifePlan:string;substitutionReason:string;substitutionEvidence:string;decisionRef:string;notes:string;createdAt:string;updatedAt:string};
export type MaterialSelectionState={schema:typeof MATERIAL_SELECTION_SCHEMA;records:MaterialRecord[];updatedAt:string};
export const emptyMaterialSelection=():MaterialSelectionState=>({schema:MATERIAL_SELECTION_SCHEMA,records:[],updatedAt:""});
const text=(value:unknown,max:number)=>typeof value==="string"&&value.length<=max;const date=(value:unknown)=>value===""||(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value));
export function safeMaterialSelection(value:unknown):MaterialSelectionState|null{if(!value||typeof value!=="object")return null;const x=value as Partial<MaterialSelectionState>;if(x.schema!==MATERIAL_SELECTION_SCHEMA||!Array.isArray(x.records)||x.records.length>200)return null;const records=x.records.filter((r):r is MaterialRecord=>!!r&&typeof r==="object"&&text(r.id,100)&&text(r.title,200)&&text(r.assemblyGroup,100)&&text(r.area,160)&&text(r.application,500)&&materialStages.includes(r.stage)&&sampleStages.includes(r.sampleStage)&&decisionStatuses.includes(r.decisionStatus)&&text(r.responsibleRole,160)&&Array.isArray(r.exposures)&&r.exposures.length<=20&&r.exposures.every(v=>text(v,100))&&text(r.sourceRef,1000)&&date(r.observedAt)&&text(r.rights,500)&&text(r.performanceEvidence,2000)&&text(r.sampleRef,1000)&&text(r.mockupRef,1000)&&text(r.substrate,500)&&text(r.interfaceNotes,2000)&&text(r.storagePlan,1000)&&text(r.installationMethodRef,1000)&&text(r.inspectionRef,1000)&&text(r.maintenancePlan,2000)&&text(r.spareStrategy,1000)&&text(r.endOfLifePlan,1000)&&text(r.substitutionReason,1000)&&text(r.substitutionEvidence,2000)&&text(r.decisionRef,1000)&&text(r.notes,3000)&&text(r.createdAt,40)&&text(r.updatedAt,40));return records.length===x.records.length?{schema:MATERIAL_SELECTION_SCHEMA,records,updatedAt:typeof x.updatedAt==="string"?x.updatedAt:""}:null}
export function materialGaps(r:MaterialRecord){const gaps:string[]=[];if(!r.title.trim())gaps.push("material or system");if(!r.area.trim())gaps.push("location");if(!r.application.trim())gaps.push("intended application");if(!r.responsibleRole.trim())gaps.push("responsible role");if(!r.exposures.length)gaps.push("exposure review");if(!r.sourceRef.trim()||!r.observedAt||!r.rights.trim())gaps.push("source provenance");if(!r.performanceEvidence.trim())gaps.push("performance evidence");if(["mockup","review","selected","installed","accepted"].includes(r.stage)&&!r.sampleRef.trim())gaps.push("sample record");if(["review","selected","installed","accepted"].includes(r.stage)&&!r.mockupRef.trim())gaps.push("mockup record");if(["selected","installed","accepted"].includes(r.stage)&&(!r.substrate.trim()||!r.interfaceNotes.trim()||!r.maintenancePlan.trim()))gaps.push("interfaces and care plan");if(["installed","accepted"].includes(r.stage)&&(!r.storagePlan.trim()||!r.installationMethodRef.trim()))gaps.push("installation readiness");if(r.stage==="accepted"&&(!r.inspectionRef.trim()||!r.decisionRef.trim()))gaps.push("inspection and acceptance record");if(r.substitutionReason.trim()&&!r.substitutionEvidence.trim())gaps.push("substitution equivalence evidence");return gaps}
export function canAdvanceMaterial(r:MaterialRecord,next:MaterialStage){return materialStages.indexOf(next)<=materialStages.indexOf(r.stage)||materialGaps({...r,stage:next}).length===0}
export function materialSummary(records:MaterialRecord[]){const evidenced=records.filter(r=>r.sourceRef&&r.observedAt&&r.rights&&r.performanceEvidence),samples=records.filter(r=>["received","reviewed"].includes(r.sampleStage));return{total:records.length,evidenceCoverage:records.length?Math.round(evidenced.length/records.length*100):0,samples:samples.length,accepted:records.filter(r=>r.stage==="accepted").length,holds:records.filter(r=>r.decisionStatus==="hold").length,substitutions:records.filter(r=>r.substitutionReason.trim()).length}}
