export const MODEL_AUTHORING_SCHEMA="mosque.build/model-authoring@1" as const;
export const MODEL_AUTHORING_KEY="mosque-build.model-authoring.v1";
export const snapModes=["grid","endpoint","midpoint","face","perpendicular","parallel","module"] as const;
export const authoringViews=["iso","top","front","rear","left","right","qibla","reflected-ceiling","section"] as const;
export const optionTypes=["massing","circulation","roof","facade","courtyard","phase"] as const;
export type SnapMode=typeof snapModes[number];export type AuthoringView=typeof authoringViews[number];export type OptionType=typeof optionTypes[number];
export type FeatureStatus="concept"|"specified"|"scaffolded"|"executable"|"source_backed"|"beta"|"production_ready";
export type ModelOrigin={basis:"anonymous-local"|"documented-local"|"survey-reference"|"georeferenced";eastM:number;northM:number;elevationM:number;rotationDeg:number;sourceRef:string;observedAt:string;accuracy:string;reviewRole:string};
export type NamedView={id:string;name:string;view:AuthoringView;visibleLayers:string[];sectionHeightM:number;issueFilter:"all"|"open"|"blocker";notes:string;createdAt:string};
export type DesignOption={id:string;name:string;type:OptionType;description:string;baseOptionId:string;status:FeatureStatus;reviewRole:string;evidenceRef:string;createdAt:string};
export type ModelMeasurement={id:string;label:string;fromObjectId:string;toObjectId:string;kind:"centre-distance"|"clear-gap"|"vertical"|"entered";valueM:number;basis:"derived-concept"|"user-entered"|"documented"|"professionally-verified-user-record";sourceRef:string;notes:string;createdAt:string};
export type AuthoringAction={id:string;command:string;objectIds:string[];summary:string;at:string};
export type ModelAuthoringState={schema:typeof MODEL_AUTHORING_SCHEMA;status:"executable";grid:{spacingM:number;majorEvery:number;axes:string[];locked:boolean};snaps:Record<SnapMode,boolean>;moduleM:number;origin:ModelOrigin;views:NamedView[];options:DesignOption[];activeOptionId:string;measurements:ModelMeasurement[];selection:string[];lockedObjectIds:string[];hiddenObjectIds:string[];history:AuthoringAction[];historyIndex:number;updatedAt:string};
export type AuthoringGap={severity:"blocker"|"review";group:"coordinates"|"views"|"options"|"measurements"|"handoff";label:string;detail:string};
const id=(prefix:string)=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
export const createModelAuthoringState=():ModelAuthoringState=>({schema:MODEL_AUTHORING_SCHEMA,status:"executable",grid:{spacingM:1,majorEvery:5,axes:["A","B","C","1","2","3"],locked:false},snaps:{grid:true,endpoint:true,midpoint:true,face:false,perpendicular:false,parallel:false,module:true},moduleM:.3,origin:{basis:"anonymous-local",eastM:0,northM:0,elevationM:0,rotationDeg:0,sourceRef:"",observedAt:"",accuracy:"",reviewRole:""},views:[],options:[{id:"option-base",name:"Base scheme",type:"massing",description:"Current shared conceptual scheme",baseOptionId:"",status:"concept",reviewRole:"",evidenceRef:"",createdAt:new Date(0).toISOString()}],activeOptionId:"option-base",measurements:[],selection:[],lockedObjectIds:[],hiddenObjectIds:[],history:[],historyIndex:-1,updatedAt:""});
const finite=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max,txt=(v:unknown,n=2000)=>typeof v==="string"&&v.length<=n;
export function safeModelAuthoringState(value:unknown):ModelAuthoringState|null{if(!value||typeof value!=="object")return null;const x=value as ModelAuthoringState;if(x.schema!==MODEL_AUTHORING_SCHEMA||x.status!=="executable"||!x.grid||!x.origin||!x.snaps||!Array.isArray(x.views)||x.views.length>100||!Array.isArray(x.options)||x.options.length<1||x.options.length>50||!Array.isArray(x.measurements)||x.measurements.length>500||!Array.isArray(x.history)||x.history.length>200)return null;if(!finite(x.grid.spacingM,.01,100)||!finite(x.grid.majorEvery,1,100)||!finite(x.moduleM,.01,20)||!finite(x.origin.rotationDeg,-360,360)||!Object.values(x.snaps).every(v=>typeof v==="boolean"))return null;if(!x.views.every(v=>txt(v.id,100)&&txt(v.name,160)&&authoringViews.includes(v.view)&&finite(v.sectionHeightM,0,100)))return null;if(!x.options.every(v=>txt(v.id,100)&&txt(v.name,160)&&optionTypes.includes(v.type)))return null;if(!x.measurements.every(v=>txt(v.id,100)&&txt(v.label,160)&&finite(v.valueM,0,100000)))return null;if(!x.history.every(v=>txt(v.id,100)&&txt(v.command,100)&&Array.isArray(v.objectIds)&&v.objectIds.length<=100&&v.objectIds.every(y=>txt(y,100))&&txt(v.summary,300)&&txt(v.at,60)))return null;const historyIndex=Number.isInteger(x.historyIndex)?Math.max(-1,Math.min(x.history.length-1,x.historyIndex)):-1;return{...x,historyIndex}}
export function appendAuthoringAction(state:ModelAuthoringState,command:string,objectIds:string[],summary:string,now=new Date().toISOString()){const next=[...state.history.slice(0,state.historyIndex+1),{id:id("action"),command,objectIds:[...new Set(objectIds)].slice(0,100),summary:summary.slice(0,300),at:now}].slice(-200);return{...state,history:next,historyIndex:next.length-1}}
export function createNamedView(state:ModelAuthoringState,name:string,view:AuthoringView,now=new Date().toISOString()){const item:NamedView={id:id("view"),name:name.trim().slice(0,160)||`${view} view`,view,visibleLayers:["spaces","site","walls","openings","guides"],sectionHeightM:2.2,issueFilter:"all",notes:"",createdAt:now};return{...state,views:[item,...state.views].slice(0,100)}}
export function createDesignOption(state:ModelAuthoringState,name:string,type:OptionType,now=new Date().toISOString()){const item:DesignOption={id:id("option"),name:name.trim().slice(0,160)||`${type} option`,type,description:"",baseOptionId:state.activeOptionId,status:"concept",reviewRole:"",evidenceRef:"",createdAt:now};return{...state,options:[...state.options,item],activeOptionId:item.id}}
export function createMeasurement(state:ModelAuthoringState,label:string,valueM:number,fromObjectId="",toObjectId="",now=new Date().toISOString()){if(!Number.isFinite(valueM)||valueM<0||valueM>100000)return state;const item:ModelMeasurement={id:id("measure"),label:label.trim().slice(0,160)||"Working dimension",fromObjectId,toObjectId,kind:"entered",valueM,basis:"user-entered",sourceRef:"",notes:"",createdAt:now};return{...state,measurements:[item,...state.measurements].slice(0,500)}}
export function modelAuthoringGaps(state:ModelAuthoringState){const gaps:AuthoringGap[]=[];if(state.origin.basis!=="anonymous-local"&&(!state.origin.sourceRef||!state.origin.observedAt))gaps.push({severity:"blocker",group:"coordinates",label:"Coordinate evidence incomplete",detail:"Documented, surveyed or georeferenced origins require a dated source reference."});if(state.origin.basis==="survey-reference"&&!state.origin.reviewRole)gaps.push({severity:"review",group:"coordinates",label:"Survey review role missing",detail:"Record the accountable role; the selection itself does not verify survey credentials."});if(!state.views.length)gaps.push({severity:"review",group:"views",label:"No named coordination view",detail:"Save at least one purpose-led view with layers and notes."});if(!state.options.some(x=>x.id!=="option-base"))gaps.push({severity:"review",group:"options",label:"No alternative recorded",detail:"Preserve at least one genuine design alternative before a major commitment."});for(const m of state.measurements)if(m.basis!=="derived-concept"&&!m.sourceRef)gaps.push({severity:m.basis==="professionally-verified-user-record"?"blocker":"review",group:"measurements",label:`${m.label}: evidence missing`,detail:"User-entered or documented dimensions need a traceable source; professional verification remains a user record."});if(!state.history.length)gaps.push({severity:"review",group:"handoff",label:"No semantic command history",detail:"Record meaningful model operations so collaborators can understand what changed."});return gaps}
export function modelReadiness(state:ModelAuthoringState){const gaps=modelAuthoringGaps(state);return{status:state.options.every(x=>x.status==="production_ready")&&gaps.length===0?"production_ready":state.history.length&&state.views.length?"executable":"scaffolded",blockers:gaps.filter(x=>x.severity==="blocker").length,reviews:gaps.filter(x=>x.severity==="review").length,views:state.views.length,options:state.options.length,measurements:state.measurements.length,commands:state.history.length}}
