import type {RenderBox} from "@/lib/render-model";
export const MODEL_PLANNING_SCHEMA="mosque.build/model-planning@1";
export type Severity="note"|"review"|"blocker";
export type ModelIssue={id:string;title:string;roomId:string;severity:Severity;discipline:string;ownerRole:string;evidenceRef:string;status:"open"|"resolved-user-record";notes:string;createdAt:string};
export type PlanningState={schema:string;updatedAt:string;section:boolean;sectionHeight:number;xray:boolean;autoRotate:boolean;fromRoomId:string;toRoomId:string;issues:ModelIssue[]};
export const createPlanningState=():PlanningState=>({schema:MODEL_PLANNING_SCHEMA,updatedAt:new Date(0).toISOString(),section:false,sectionHeight:2.2,xray:false,autoRotate:false,fromRoomId:"",toRoomId:"",issues:[]});
export function safePlanningState(v:unknown){if(!v||typeof v!=="object"||(v as PlanningState).schema!==MODEL_PLANNING_SCHEMA)return null;const x=v as PlanningState,b=createPlanningState();return {...b,...x,section:Boolean(x.section),xray:Boolean(x.xray),autoRotate:Boolean(x.autoRotate),sectionHeight:Number.isFinite(x.sectionHeight)?Math.max(.2,Math.min(12,x.sectionHeight)):2.2,issues:Array.isArray(x.issues)?x.issues.filter(i=>i&&typeof i.id==="string"&&typeof i.title==="string").slice(0,200):[]} as PlanningState}
export function roomSeparation(a?:RenderBox,b?:RenderBox){if(!a||!b||a.id===b.id)return null;const dx=b.position[0]-a.position[0],dz=b.position[2]-a.position[2],centerM=Math.hypot(dx,dz),edgeX=Math.max(0,Math.abs(dx)-(a.size[0]+b.size[0])/2),edgeZ=Math.max(0,Math.abs(dz)-(a.size[2]+b.size[2])/2);return {centerM:Math.round(centerM*10)/10,clearGapM:Math.round(Math.hypot(edgeX,edgeZ)*10)/10,bearingDeg:Math.round((Math.atan2(dx,dz)*180/Math.PI+360)%360)}}
export function issueSummary(issues:ModelIssue[]){return {open:issues.filter(x=>x.status==="open").length,blockers:issues.filter(x=>x.status==="open"&&x.severity==="blocker").length,evidenced:issues.filter(x=>x.evidenceRef.trim()).length,resolved:issues.filter(x=>x.status==="resolved-user-record").length}}
