export const FIELD_SNAPSHOT_SCHEMA="mosque.build/field-snapshot@1",FIELD_SNAPSHOT_MAX_BYTES=512_000;
export type SiteEntry={id:string;date:string;area:string;type:string;progress:number;note:string;evidence:string;review:"unreviewed"|"reviewed"};
export type FieldSnapshot={schema:string;snapshotId:string;deviceLabel:string;exportedAt:string;entries:SiteEntry[];boundary:string};
export type EntryConflict={id:string;local:SiteEntry;incoming:SiteEntry};
const textFields=["id","date","area","type","note","evidence"] as const;
const plain=(value:unknown)=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value)&&(Object.getPrototypeOf(value)===Object.prototype||Object.getPrototypeOf(value)===null),limits={id:180,date:10,area:160,type:160,note:2000,evidence:1000};
const validDay=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const parsed=new Date(`${value}T00:00:00Z`);return !Number.isNaN(parsed.valueOf())&&parsed.toISOString().slice(0,10)===value};
export function isSiteEntry(value:unknown):value is SiteEntry{if(!plain(value))return false;const entry=value as Partial<SiteEntry>;return textFields.every(field=>typeof entry[field]==="string"&&entry[field]!.length<=limits[field])&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,179}$/.test(entry.id!)&&validDay(entry.date!)&&Boolean(entry.area!.trim())&&Boolean(entry.type!.trim())&&Boolean(entry.note!.trim())&&typeof entry.progress==="number"&&Number.isFinite(entry.progress)&&entry.progress>=0&&entry.progress<=100&&(entry.review==="unreviewed"||entry.review==="reviewed")}
export function safeSiteEntries(value:unknown){if(!Array.isArray(value))return[];const seen=new Set<string>(),safe:SiteEntry[]=[];for(const entry of value){if(!isSiteEntry(entry)||seen.has(entry.id))continue;seen.add(entry.id);safe.push(entry);if(safe.length===500)break}return safe}
export function validateFieldSnapshot(value:unknown):{ok:true;data:FieldSnapshot}|{ok:false;errors:string[]}{const errors:string[]=[];if(!value||typeof value!=="object")return {ok:false,errors:["The selected file is not a field snapshot."]};const snapshot=value as Partial<FieldSnapshot>;if(snapshot.schema!==FIELD_SNAPSHOT_SCHEMA)errors.push("Unsupported field snapshot schema.");if(typeof snapshot.snapshotId!=="string"||!snapshot.snapshotId)errors.push("Snapshot ID is missing.");if(typeof snapshot.deviceLabel!=="string"||!snapshot.deviceLabel.trim())errors.push("Device label is missing.");if(typeof snapshot.exportedAt!=="string"||!/^\d{4}-\d{2}-\d{2}T/.test(snapshot.exportedAt))errors.push("Export date is invalid.");if(!Array.isArray(snapshot.entries)||snapshot.entries.length>500||!snapshot.entries.every(isSiteEntry))errors.push("Site updates are invalid or exceed the 500-record limit.");if(errors.length)return {ok:false,errors};return {ok:true,data:snapshot as FieldSnapshot}}
const same=(a:SiteEntry,b:SiteEntry)=>textFields.every(field=>a[field]===b[field])&&a.progress===b.progress&&a.review===b.review;
export function compareFieldEntries(local:SiteEntry[],incoming:SiteEntry[]){const byId=new Map(local.map(entry=>[entry.id,entry])),additions:SiteEntry[]=[],conflicts:EntryConflict[]=[],identical:SiteEntry[]=[];for(const entry of incoming){const current=byId.get(entry.id);if(!current)additions.push(entry);else if(same(current,entry))identical.push(entry);else conflicts.push({id:entry.id,local:current,incoming:entry})}return {additions,conflicts,identical}}
export function mergeFieldEntries(local:SiteEntry[],incoming:SiteEntry[],resolutions:Record<string,"local"|"incoming"|"both">,copySuffix:string){const comparison=compareFieldEntries(local,incoming),merged=[...local,...comparison.additions];for(const conflict of comparison.conflicts){const resolution=resolutions[conflict.id];if(!resolution)continue;if(resolution==="incoming"){const index=merged.findIndex(entry=>entry.id===conflict.id);merged[index]=conflict.incoming}else if(resolution==="both")merged.push({...conflict.incoming,id:`${conflict.id}--${copySuffix}`,note:`Imported alternate record: ${conflict.incoming.note}`})}return {entries:merged.slice(0,500),unresolved:comparison.conflicts.filter(item=>!resolutions[item.id]).map(item=>item.id)}}
