export const PATTERN_MODEL_SCHEMA="mosque.build/pattern-model@1" as const;
export const PATTERN_MODEL_KEY="mosque-build.pattern-model.v1";
export const patternStudyIds=["iran-cross-star","mughal-jali","mamluk-star-woodwork","interlaced-circle-vocabulary","square-polygon-vocabulary","radial-polygon-vocabulary","near-east-carved-panel","nishapur-kite-dart","saff-carpet-lines","muqarnas-transition","anatolian-timber-bay","andalusi-arcade-rhythm","zellij-module-study"]as const;
export const patternSurfaces=["screen","wall-panel","ceiling-panel","paving-zone","door-panel","prayer-floor"]as const;
export type PatternSurface=typeof patternSurfaces[number];
export type PatternPoint=[number,number];
export type PatternSegment={from:PatternPoint;to:PatternPoint;role:"primary"|"secondary"|"frame"};
export type PatternPlacement={id:string;name:string;patternId:string;surface:PatternSurface;widthM:number;heightM:number;depthM:number;moduleM:number;rotationDeg:number;repetitions:number;phase:1|2|3;status:"concept"|"specified";sourceRef:string;authorRole:string;reviewRole:string;notes:string;createdAt:string;updatedAt:string};
export type PatternModelState={schema:typeof PATTERN_MODEL_SCHEMA;status:"executable";placements:PatternPlacement[];activeId:string;showFrame:boolean;showSecondary:boolean;updatedAt:string;boundary:string};
const ids=new Set<string>(patternStudyIds),finite=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=a&&x<=b,txt=(x:unknown,n:number)=>typeof x==="string"&&x.length<=n;
export function createPatternPlacement(index=1,patternId:string=patternStudyIds[0],now=new Date().toISOString()):PatternPlacement{return{id:`pattern-placement-${now.replace(/\W/g,"")}-${index}`,name:`Pattern study ${index}`,patternId:ids.has(patternId)?patternId:patternStudyIds[0],surface:"screen",widthM:4.8,heightM:3,depthM:.12,moduleM:.6,rotationDeg:0,repetitions:6,phase:2,status:"concept",sourceRef:"",authorRole:"",reviewRole:"",notes:"",createdAt:now,updatedAt:now}}
export function createPatternModelState(now=""):PatternModelState{return{schema:PATTERN_MODEL_SCHEMA,status:"executable",placements:[],activeId:"",showFrame:true,showSecondary:true,updatedAt:now,boundary:"Original parametric diagram only; not heritage reconstruction, sacred content, fabrication geometry, engineering, compliance or approval."}}
export function safePatternModelState(value:unknown):PatternModelState|null{if(!value||typeof value!=="object")return null;const x=value as PatternModelState;if(x.schema!==PATTERN_MODEL_SCHEMA||x.status!=="executable"||!Array.isArray(x.placements)||x.placements.length>40||typeof x.showFrame!=="boolean"||typeof x.showSecondary!=="boolean")return null;if(!x.placements.every(p=>txt(p.id,160)&&txt(p.name,160)&&ids.has(p.patternId)&&patternSurfaces.includes(p.surface)&&finite(p.widthM,.2,100)&&finite(p.heightM,.2,100)&&finite(p.depthM,.01,5)&&finite(p.moduleM,.05,10)&&finite(p.rotationDeg,-360,360)&&finite(p.repetitions,1,40)&&[1,2,3].includes(p.phase)&&["concept","specified"].includes(p.status)&&txt(p.sourceRef,1000)&&txt(p.authorRole,200)&&txt(p.reviewRole,200)&&txt(p.notes,3000)))return null;return x}
const add=(out:PatternSegment[],a:PatternPoint,b:PatternPoint,role:PatternSegment["role"]="primary")=>out.push({from:a,to:b,role});
export function createPatternSegments(style:string,repetitions:number):PatternSegment[]{const n=Math.max(1,Math.min(40,Math.round(repetitions))),out:PatternSegment[]=[];for(let row=0;row<n;row++)for(let col=0;col<n;col++){const x=(col+.5)/n-.5,y=(row+.5)/n-.5,r=.38/n;if(style==="saff"){if(col===0)add(out,[-.5,y],[.5,y],"primary");continue}if(style==="slats"){if(row===0)add(out,[x,-.5],[x,.5],col%2?"secondary":"primary");continue}if(style==="arches"){if(row%2===0){add(out,[x-r,y-r],[x-r,y]);add(out,[x-r,y],[x,y+r]);add(out,[x,y+r],[x+r,y]);add(out,[x+r,y],[x+r,y-r])}continue}if(style==="hex"||style==="lattice"){for(let k=0;k<6;k++){const a=Math.PI/3*k,b=Math.PI/3*(k+1);add(out,[x+Math.cos(a)*r,y+Math.sin(a)*r],[x+Math.cos(b)*r,y+Math.sin(b)*r],k%2?"secondary":"primary")}continue}if(style==="paving"||style==="diamond"||style==="threshold"){add(out,[x-r,y],[x,y+r]);add(out,[x,y+r],[x+r,y]);add(out,[x+r,y],[x,y-r]);add(out,[x,y-r],[x-r,y],"secondary");continue}const points=style==="rosette"?12:8;for(let k=0;k<points;k++){const a=Math.PI*2*k/points,b=Math.PI*2*(k+3)/points;add(out,[x+Math.cos(a)*r,y+Math.sin(a)*r],[x+Math.cos(b)*r,y+Math.sin(b)*r],k%2?"secondary":"primary")}}return out.slice(0,5000)}
export function patternModelGaps(state:PatternModelState){return state.placements.flatMap(p=>[!p.sourceRef?`${p.name}: source/reference basis missing`:"",!p.authorRole?`${p.name}: accountable author role missing`:"",!p.reviewRole?`${p.name}: cultural/application review role missing`:"",p.surface==="prayer-floor"&&!p.notes?`${p.name}: prayer-row and accessible-position coordination notes missing`:""].filter(Boolean))}
