import patternStudyIds from "../data/pattern-study-ids.json" with {type:"json"};
export const PATTERN_MODEL_SCHEMA="mosque.build/pattern-model@1" as const;
export const PATTERN_MODEL_KEY="mosque-build.pattern-model.v1";
export const patternSurfaces=["screen","wall-panel","ceiling-panel","paving-zone","door-panel","prayer-floor"]as const;
export type PatternSurface=typeof patternSurfaces[number];
export type PatternPoint=[number,number];
export type PatternSegment={from:PatternPoint;to:PatternPoint;role:"primary"|"secondary"|"frame"};
export type PatternPlacement={id:string;name:string;patternId:string;surface:PatternSurface;widthM:number;heightM:number;depthM:number;moduleM:number;rotationDeg:number;repetitions:number;phase:1|2|3;status:"concept"|"specified";sourceRef:string;authorRole:string;reviewRole:string;notes:string;createdAt:string;updatedAt:string};
export type PatternModelState={schema:typeof PATTERN_MODEL_SCHEMA;status:"executable";placements:PatternPlacement[];activeId:string;showFrame:boolean;showSecondary:boolean;updatedAt:string;boundary:string};
const ids=new Set<string>(patternStudyIds),finite=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=a&&x<=b,txt=(x:unknown,n:number)=>typeof x==="string"&&x.length<=n;
export function createPatternPlacement(index=1,patternId:string=patternStudyIds[0],now=new Date().toISOString()):PatternPlacement{return{id:`pattern-placement-${now.replace(/\W/g,"")}-${index}`,name:`Pattern study ${index}`,patternId:ids.has(patternId)?patternId:patternStudyIds[0],surface:"screen",widthM:4.8,heightM:3,depthM:.12,moduleM:.6,rotationDeg:0,repetitions:6,phase:2,status:"concept",sourceRef:"",authorRole:"",reviewRole:"",notes:"",createdAt:now,updatedAt:now}}
export function createPatternModelState(now=""):PatternModelState{return{schema:PATTERN_MODEL_SCHEMA,status:"executable",placements:[],activeId:"",showFrame:true,showSecondary:true,updatedAt:now,boundary:"Original parametric diagram only; not heritage reconstruction, sacred content, fabrication geometry, engineering, compliance or approval."}}
export function safePatternModelState(value:unknown):PatternModelState|null{if(!value||typeof value!=="object")return null;const x=value as PatternModelState;if(x.schema!==PATTERN_MODEL_SCHEMA||x.status!=="executable"||!Array.isArray(x.placements)||x.placements.length>40||typeof x.showFrame!=="boolean"||typeof x.showSecondary!=="boolean")return null;if(!x.placements.every(p=>txt(p.id,160)&&txt(p.name,160)&&ids.has(p.patternId)&&patternSurfaces.includes(p.surface)&&finite(p.widthM,.2,100)&&finite(p.heightM,.2,100)&&finite(p.depthM,.01,5)&&finite(p.moduleM,.05,10)&&finite(p.rotationDeg,-360,360)&&finite(p.repetitions,1,40)&&[1,2,3].includes(p.phase)&&["concept","specified"].includes(p.status)&&txt(p.sourceRef,1000)&&txt(p.authorRole,200)&&txt(p.reviewRole,200)&&txt(p.notes,3000)))return null;return x}
const add=(out:PatternSegment[],a:PatternPoint,b:PatternPoint,role:PatternSegment["role"]="primary")=>out.push({from:a,to:b,role});
const hash=(text:string)=>[...text].reduce((value,char)=>(value*31+char.charCodeAt(0))>>>0,2166136261);
const starCounts={five:5,six:6,seven:7,nine:9,ten:10,twelve:12,sixteen:16}as const;
const seeded=(seed:number)=>{let value=seed||1;return()=>((value=Math.imul(value^value>>>15,value|1))>>>0)/4294967296};
const radial=(out:PatternSegment[],points:number,step:number,rings:number)=>{for(let ring=1;ring<=rings;ring++){const radius=.46*ring/rings;for(let i=0;i<points;i++){const a=Math.PI*2*i/points,b=Math.PI*2*(i+step)/points;add(out,[Math.cos(a)*radius,Math.sin(a)*radius],[Math.cos(b)*radius,Math.sin(b)*radius],ring%2?"primary":"secondary")}}};
const voronoi=(out:PatternSegment[],style:string,n:number)=>{const random=seeded(hash(style)),sites=Array.from({length:Math.min(48,Math.max(8,n*n))},(_,i)=>{const angle=i*2.399963+random()*.18,radius=Math.sqrt((i+.5)/(Math.min(48,Math.max(8,n*n))))*.46,bias=style.includes("radial")?.72:1;return [Math.cos(angle)*radius*bias+(random()-.5)*.04,Math.sin(angle)*radius+(random()-.5)*.04]as PatternPoint});for(const [x,y]of sites){const nearest=sites.filter(point=>point[0]!==x||point[1]!==y).sort((a,b)=>Math.hypot(a[0]-x,a[1]-y)-Math.hypot(b[0]-x,b[1]-y)).slice(0,style.includes("delaunay")?5:3);for(const point of nearest)add(out,[x,y],point,style.includes("layered")?"secondary":"primary")}};
export function createPatternSegments(style:string,repetitions:number):PatternSegment[]{const n=Math.max(1,Math.min(40,Math.round(repetitions))),out:PatternSegment[]=[],seed=hash(style),starMatch=style.match(/star-(five|six|seven|nine|ten|twelve|sixteen)/),starPoints=starMatch?starCounts[starMatch[1]as keyof typeof starCounts]:0;
 if(style.includes("voronoi")||style.includes("delaunay")){voronoi(out,style,n);return out.slice(0,5000)}
 if(starPoints||style.includes("rosette")||style.includes("girih")||style.startsWith("quasi-")||style.includes("ammann")||style.includes("recursive-star")){radial(out,starPoints||(/24/.test(style)?24:style.includes("twelve")?12:style.includes("five")?5:style.includes("decagon")?10:8),style.includes("girih")?3:2,Math.min(8,Math.max(2,n)));return out.slice(0,5000)}
 if(style.includes("spiral")||style==="phyllotaxis"){const turns=style==="phyllotaxis"?2.399963:style.includes("log")?.42:.55,total=Math.min(900,n*n*3);let previous:PatternPoint=[0,0];for(let i=1;i<=total;i++){const t=i/total,r=.47*(style.includes("log")?(Math.exp(2.4*t)-1)/(Math.exp(2.4)-1):Math.sqrt(t)),point:[number,number]=[Math.cos(i*turns)*r,Math.sin(i*turns)*r];add(out,previous,point,i%3?"primary":"secondary");previous=point}return out}
 if(style.includes("circle")||style==="apollonian"||style==="vesica"||style==="ring-weave"){const rings=Math.min(12,n+2);for(let ring=1;ring<=rings;ring++){const pieces=12+ring*2,r=.46*ring/rings;for(let i=0;i<pieces;i++){const a=2*Math.PI*i/pieces,b=2*Math.PI*(i+1)/pieces;add(out,[Math.cos(a)*r,Math.sin(a)*r],[Math.cos(b)*r,Math.sin(b)*r],ring%2?"primary":"secondary")}}return out}
 for(let row=0;row<n;row++)for(let col=0;col<n;col++){const x=(col+.5)/n-.5,y=(row+.5)/n-.5,r=.38/n,variant=seed%5;if(style==="saff"){if(col===0)add(out,[-.5,y],[.5,y]);continue}if(style==="slats"){if(row===0)add(out,[x,-.5],[x,.5],col%2?"secondary":"primary");continue}if(style==="arches"){if(row%2===0){add(out,[x-r,y-r],[x-r,y]);add(out,[x-r,y],[x,y+r]);add(out,[x,y+r],[x+r,y]);add(out,[x+r,y],[x+r,y-r])}continue}if(style==="hex"||style==="lattice"||style.includes("hex")||style.includes("trihex")){for(let k=0;k<6;k++){const a=Math.PI/3*k,b=Math.PI/3*(k+1);add(out,[x+Math.cos(a)*r,y+Math.sin(a)*r],[x+Math.cos(b)*r,y+Math.sin(b)*r],k%2?"secondary":"primary")}continue}if(style.includes("truchet")){const flip=(row+col+variant)%2===0;add(out,[x-r,y+(flip?-r:r)],[x+(flip?r:-r),y-r]);add(out,[x+r,y+(flip?r:-r)],[x+(flip?-r:r),y+r],"secondary");continue}if(style.includes("weave")||style.includes("braid")||style.includes("knot")||style.includes("wave")){add(out,[x-r,y-r],[x+r,y+r]);add(out,[x-r,y+r],[x+r,y-r],(row+col)%2?"secondary":"primary");continue}if(style==="paving"||style==="diamond"||style==="threshold"||style.includes("rhomb")||style.includes("penrose")||style.includes("chevron")){add(out,[x-r,y],[x,y+r]);add(out,[x,y+r],[x+r,y]);add(out,[x+r,y],[x,y-r]);add(out,[x,y-r],[x-r,y],"secondary");continue}const points=style==="rosette"?12:variant+5;for(let k=0;k<points;k++){const a=Math.PI*2*k/points,b=Math.PI*2*(k+Math.max(2,variant))/points;add(out,[x+Math.cos(a)*r,y+Math.sin(a)*r],[x+Math.cos(b)*r,y+Math.sin(b)*r],k%2?"secondary":"primary")}}return out.slice(0,5000)}
export function patternModelGaps(state:PatternModelState){return state.placements.flatMap(p=>[!p.sourceRef?`${p.name}: source/reference basis missing`:"",!p.authorRole?`${p.name}: accountable author role missing`:"",!p.reviewRole?`${p.name}: cultural/application review role missing`:"",p.surface==="prayer-floor"&&!p.notes?`${p.name}: prayer-row and accessible-position coordination notes missing`:""].filter(Boolean))}
