import type{SchematicRoom}from"@/lib/schematic-plan";
export const PRAYER_OCCUPANCY_SCHEMA="mosque.build/prayer-occupancy-study@1" as const;
export const PRAYER_OCCUPANCY_KEY="mosque-build.prayer-occupancy.v1";
export type OccupantKind="standing"|"seated"|"wheelchair";
export type PrayerOccupancyStudy={schema:typeof PRAYER_OCCUPANCY_SCHEMA;status:"executable";updatedAt:string;attendance:number;personWidthM:number;rowPitchM:number;frontClearM:number;rearClearM:number;sideClearM:number;aisleCount:number;aisleWidthM:number;seatedPositions:number;wheelchairPositions:number;movementPercent:number;alignmentBasis:string;reviewState:"illustrative"|"community-reviewed"|"professionally-reviewed";reviewerRole:string;notes:string};
export type OccupantPoint={id:string;row:number;place:number;kind:OccupantKind;position:[number,number];feet:[[number,number],[number,number]]};
export type OccupancyLayout={schema:"mosque.build/prayer-occupancy-layout@1";roomId:string;room:{x:number;y:number;width:number;depth:number;heightM:number};rows:number;placesPerRow:number;capacity:number;requested:number;placed:number;overflow:number;areaPerPersonM2:number;volumePerPersonM3:number;points:OccupantPoint[];rowLines:Array<{row:number;from:[number,number];to:[number,number]}>;movementPercent:number};
export function blankPrayerOccupancyStudy():PrayerOccupancyStudy{return{schema:PRAYER_OCCUPANCY_SCHEMA,status:"executable",updatedAt:new Date(0).toISOString(),attendance:120,personWidthM:.65,rowPitchM:1.2,frontClearM:1.5,rearClearM:1.2,sideClearM:.8,aisleCount:1,aisleWidthM:1.2,seatedPositions:4,wheelchairPositions:4,movementPercent:100,alignmentBasis:"Confirm row and foot-alignment practice with the community and an accountable religious reviewer.",reviewState:"illustrative",reviewerRole:"",notes:""}}
const finite=(value:unknown,fallback:number,min:number,max:number)=>typeof value==="number"&&Number.isFinite(value)?Math.min(max,Math.max(min,value)):fallback;
export function safePrayerOccupancyStudy(value:unknown):PrayerOccupancyStudy{const base=blankPrayerOccupancyStudy();if(!value||typeof value!=="object")return base;const x=value as Partial<PrayerOccupancyStudy>;return{...base,...x,schema:PRAYER_OCCUPANCY_SCHEMA,status:"executable",attendance:Math.round(finite(x.attendance,base.attendance,0,5000)),personWidthM:finite(x.personWidthM,.65,.45,1.5),rowPitchM:finite(x.rowPitchM,1.2,.8,2.2),frontClearM:finite(x.frontClearM,1.5,0,10),rearClearM:finite(x.rearClearM,1.2,0,10),sideClearM:finite(x.sideClearM,.8,0,5),aisleCount:Math.round(finite(x.aisleCount,1,0,6)),aisleWidthM:finite(x.aisleWidthM,1.2,.6,4),seatedPositions:Math.round(finite(x.seatedPositions,4,0,500)),wheelchairPositions:Math.round(finite(x.wheelchairPositions,4,0,500)),movementPercent:finite(x.movementPercent,100,0,100),alignmentBasis:typeof x.alignmentBasis==="string"?x.alignmentBasis.slice(0,500):base.alignmentBasis,reviewState:["illustrative","community-reviewed","professionally-reviewed"].includes(x.reviewState??"")?x.reviewState as PrayerOccupancyStudy["reviewState"]:"illustrative",reviewerRole:typeof x.reviewerRole==="string"?x.reviewerRole.slice(0,120):"",notes:typeof x.notes==="string"?x.notes.slice(0,2000):""}}
export function createOccupancyLayout(room:SchematicRoom,raw:PrayerOccupancyStudy,heightM=4.8):OccupancyLayout{const s=safePrayerOccupancyStudy(raw),usableW=Math.max(0,room.width-s.sideClearM*2-s.aisleCount*s.aisleWidthM),usableD=Math.max(0,room.depth-s.frontClearM-s.rearClearM),placesPerRow=Math.max(0,Math.floor(usableW/s.personWidthM)),rows=Math.max(0,Math.floor(usableD/s.rowPitchM)),capacity=placesPerRow*rows,placed=Math.min(s.attendance,capacity),points:OccupantPoint[]=[],rowLines:OccupancyLayout["rowLines"]=[],blockWidth=placesPerRow*s.personWidthM+(s.aisleCount?s.aisleCount*s.aisleWidthM:0),startX=room.x+(room.width-blockWidth)/2,segments=s.aisleCount+1,placesPerSegment=placesPerRow?Math.ceil(placesPerRow/segments):0;let index=0;for(let row=0;row<rows;row++){const z=room.y+s.frontClearM+row*s.rowPitchM;rowLines.push({row:row+1,from:[room.x+s.sideClearM,z],to:[room.x+room.width-s.sideClearM,z]});for(let place=0;place<placesPerRow&&index<placed;place++,index++){const aisleOffset=Math.floor(place/Math.max(1,placesPerSegment))*s.aisleWidthM,x=startX+place*s.personWidthM+aisleOffset+s.personWidthM/2,kind=index<s.wheelchairPositions?"wheelchair":index<s.wheelchairPositions+s.seatedPositions?"seated":"standing",foot=.12;points.push({id:`occupant-${index+1}`,row:row+1,place:place+1,kind,position:[x,z],feet:[[x-foot,z],[x+foot,z]]})}}const area=room.width*room.depth,volume=area*heightM;return{schema:"mosque.build/prayer-occupancy-layout@1",roomId:room.id,room:{x:room.x,y:room.y,width:room.width,depth:room.depth,heightM},rows,placesPerRow,capacity,requested:s.attendance,placed,overflow:Math.max(0,s.attendance-capacity),areaPerPersonM2:placed?area/placed:0,volumePerPersonM3:placed?volume/placed:0,points,rowLines,movementPercent:s.movementPercent}}
export function occupancyGaps(study:PrayerOccupancyStudy,layout:OccupancyLayout){const gaps:string[]=[];if(study.reviewState==="illustrative")gaps.push("community review of row and alignment convention");if(!study.reviewerRole)gaps.push("accountable reviewer role");if(layout.overflow)gaps.push("overflow and alternate prayer-space plan");if(!study.wheelchairPositions)gaps.push("wheelchair positions and equivalent sightline review");if(!study.alignmentBasis.trim())gaps.push("alignment basis");return gaps}
