export type ScheduleStatus="not-started"|"in-progress"|"blocked"|"ready-for-review"|"complete";
export type ScheduleTask={id:string;name:string;phase:string;start:string;finish:string;progress:number;status:ScheduleStatus;dependsOn:string[];responsibleRole:string;evidenceRef:string;notes:string};
export type ScheduleState={schema:"mosque.build/project-schedule@1";baselineDate:string;tasks:ScheduleTask[];updatedAt:string};
export const scheduleStatuses:ScheduleStatus[]=["not-started","in-progress","blocked","ready-for-review","complete"];
const day=86_400_000,iso=(date:Date)=>date.toISOString().slice(0,10),add=(date:string,days:number)=>iso(new Date(new Date(`${date}T00:00:00Z`).getTime()+days*day));
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));
const durations=[14,28,42,35,21,84,56,21];
const templates=[
  ["brief","Project brief and governance","Brief",[]],["site","Site evidence and feasibility","Site",["brief"]],["design","Coordinated concept design","Design",["site"]],["approvals","Authority pathway and submissions","Approvals",["design"]],["procurement","Procurement packages","Procurement",["design"]],["build","Construction delivery","Construction",["approvals","procurement"]],["commission","Testing and commissioning","Handover",["build"]],["open","Opening readiness","Operations",["commission"]]
] as const;
export function createBaselineSchedule(baselineDate:string):ScheduleState{let cursor=baselineDate;const tasks:ScheduleTask[]=templates.map(([id,name,phase,dependsOn],index)=>{const start=cursor,finish=add(start,durations[index]-1);cursor=add(finish,1);return {id,name,phase,start,finish,progress:0,status:"not-started",dependsOn:[...dependsOn],responsibleRole:"",evidenceRef:"",notes:""}});return {schema:"mosque.build/project-schedule@1",baselineDate,tasks,updatedAt:new Date().toISOString()}}
export function durationDays(task:Pick<ScheduleTask,"start"|"finish">){if(!validDate(task.start)||!validDate(task.finish)||task.finish<task.start)return 0;const start=Date.parse(`${task.start}T00:00:00Z`),finish=Date.parse(`${task.finish}T00:00:00Z`);return Math.round((finish-start)/day)+1}
export function taskBlockers(task:ScheduleTask,tasks:ScheduleTask[]){return task.dependsOn.filter(id=>tasks.find(item=>item.id===id)?.status!=="complete")}
export function dependencyCycle(tasks:ScheduleTask[]){const graph=new Map(tasks.map(x=>[x.id,x.dependsOn])),visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string):boolean=>{if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);for(const next of graph.get(id)??[])if(graph.has(next)&&visit(next))return true;visiting.delete(id);visited.add(id);return false};return tasks.some(x=>visit(x.id))}
export function scheduleSummary(tasks:ScheduleTask[],today:string){const weight=tasks.reduce((sum,item)=>sum+durationDays(item),0),earned=tasks.reduce((sum,item)=>sum+durationDays(item)*item.progress/100,0);return {progress:weight?Math.round(earned/weight):0,blocked:tasks.filter(item=>taskBlockers(item,tasks).length||item.status==="blocked").length,overdue:tasks.filter(item=>item.status!=="complete"&&item.finish<today).length,ready:tasks.filter(item=>item.status==="ready-for-review").length,complete:tasks.filter(item=>item.status==="complete").length}}
export function scheduleGaps(task:ScheduleTask,tasks:ScheduleTask[]){const gaps:string[]=[];if(!task.name.trim())gaps.push("task name");if(!durationDays(task))gaps.push("valid dates");if(!task.responsibleRole.trim())gaps.push("responsible role");if(task.status==="complete"&&!task.evidenceRef.trim())gaps.push("completion evidence");if(task.dependsOn.includes(task.id)||task.dependsOn.some(id=>!tasks.some(item=>item.id===id))||dependencyCycle(tasks.map(x=>x.id===task.id?task:x)))gaps.push("valid dependencies");return gaps}
export function safeSchedule(value:unknown):ScheduleState|null{if(!value||typeof value!=="object")return null;const source=value as Partial<ScheduleState>;if(source.schema!=="mosque.build/project-schedule@1"||typeof source.baselineDate!=="string"||!Array.isArray(source.tasks)||source.tasks.length>200)return null;const tasks=source.tasks.filter((item):item is ScheduleTask=>!!item&&typeof item.id==="string"&&typeof item.name==="string"&&typeof item.phase==="string"&&typeof item.start==="string"&&typeof item.finish==="string"&&typeof item.progress==="number"&&item.progress>=0&&item.progress<=100&&scheduleStatuses.includes(item.status)&&Array.isArray(item.dependsOn)&&item.dependsOn.every(id=>typeof id==="string")&&typeof item.responsibleRole==="string"&&typeof item.evidenceRef==="string"&&typeof item.notes==="string");return tasks.length===source.tasks.length?{schema:source.schema,baselineDate:source.baselineDate,tasks,updatedAt:typeof source.updatedAt==="string"?source.updatedAt:""}:null}
