export const PROJECT_INTEGRITY_SCHEMA="mosque.build/project-integrity@1" as const;
export const PROJECT_INTEGRITY_KEY="mosque-build.project-integrity.v1";
export const decisionKinds=["appointment","procurement","variation","payment","inspection","asset-disposal"] as const;
export type DecisionKind=typeof decisionKinds[number];
export type ConflictState="pending"|"none-declared"|"declared-recused"|"declared-managed";
export type IntegrityDecision={id:string;title:string;kind:DecisionKind;packageRef:string;supplierRef:string;currency:string;amount:number;baselineAmount:number;decisionDate:string;requesterRole:string;reviewerRole:string;approverRole:string;quotesReceived:number;competitionException:boolean;exceptionReason:string;conflictState:ConflictState;evidenceRef:string;completionEvidenceRef:string;status:"draft"|"under-review"|"approved"|"closed";updatedAt:string};
export type CapabilityRecord={id:string;role:string;scope:string;requirement:string;evidenceRef:string;reviewState:"unreviewed"|"verified"|"limited"|"expired";validUntil:string;independentReviewerRole:string;updatedAt:string};
export type IntegrityPolicy={currency:string;competitionThreshold:number;requiredQuotes:number;retrospectiveReviewDays:number;complaintRoute:string};
export type ProjectIntegrityState={schema:typeof PROJECT_INTEGRITY_SCHEMA;status:"executable";policy:IntegrityPolicy;decisions:IntegrityDecision[];capabilities:CapabilityRecord[];updatedAt:string};
export type IntegritySignal={id:string;severity:"review"|"high";recordId:string;title:string;why:string;response:string};
export const defaultIntegrityPolicy=():IntegrityPolicy=>({currency:"",competitionThreshold:0,requiredQuotes:3,retrospectiveReviewDays:7,complaintRoute:""});
export const createProjectIntegrityState=():ProjectIntegrityState=>({schema:PROJECT_INTEGRITY_SCHEMA,status:"executable",policy:defaultIntegrityPolicy(),decisions:[],capabilities:[],updatedAt:""});
const same=(a:string,b:string)=>!!a.trim()&&a.trim().toLowerCase()===b.trim().toLowerCase();
const daysBetween=(a:string,b:string)=>Math.abs((new Date(a).getTime()-new Date(b).getTime())/86400000);
export function integritySignals(state:ProjectIntegrityState):IntegritySignal[]{const out:IntegritySignal[]=[];const push=(id:string,severity:IntegritySignal["severity"],recordId:string,title:string,why:string,response:string)=>out.push({id, severity,recordId,title,why,response});for(const d of state.decisions){const id=(suffix:string)=>`${d.id}:${suffix}`;if(same(d.requesterRole,d.approverRole)||same(d.reviewerRole,d.approverRole))push(id("duties"),"high",d.id,"Role-separation gap","The same role appears in preparation/review and approval.","Assign an independent approval role and preserve the decision record.");if(d.conflictState==="pending")push(id("conflict"),"review",d.id,"Conflict declaration pending","The decision can proceed without a recorded declaration.","Record no conflict, or record the conflict and recusal/management route.");if(d.amount>0&&state.policy.competitionThreshold>0&&d.amount>=state.policy.competitionThreshold&&d.quotesReceived<state.policy.requiredQuotes&&!d.competitionException)push(id("competition"),"high",d.id,"Competition policy gap",`This record exceeds the team-entered threshold but has ${d.quotesReceived} comparable offer(s).`,"Obtain the required comparisons or document and approve an exception.");if(d.competitionException&&!d.exceptionReason.trim())push(id("exception"),"high",d.id,"Unsupported competition exception","An exception is selected without a rationale.","Record the urgency, alternatives considered, approval and retrospective review.");if(!d.evidenceRef.trim())push(id("evidence"),"review",d.id,"Source evidence missing","The basis for the scope, selection or value is not referenced.","Attach or reference the scope, comparison, quotation, minutes or inspection evidence.");if(["payment","inspection"].includes(d.kind)&&["approved","closed"].includes(d.status)&&!d.completionEvidenceRef.trim())push(id("completion"),"high",d.id,"Completion evidence missing","Approval or closure is recorded without delivery/inspection evidence.","Hold release or closure until an independent check and evidence reference are recorded.");if(d.kind==="variation"&&d.baselineAmount<=0)push(id("baseline"),"review",d.id,"Variation has no baseline","The change cannot be compared with the approved baseline.","Reference the original scope/value and record the change cause and impact.");if(d.amount>0&&d.baselineAmount>0&&d.amount>d.baselineAmount*1.15)push(id("variance"),"review",d.id,"Entered value is over 15% above baseline","A material variance may indicate scope growth, estimating error or changed conditions—not misconduct.","Reconcile quantities, scope, approvals and contingency before commitment.")}
 for(let i=0;i<state.decisions.length;i++)for(let j=i+1;j<state.decisions.length;j++){const a=state.decisions[i],b=state.decisions[j],threshold=state.policy.competitionThreshold;if(threshold>0&&a.currency===b.currency&&a.supplierRef&&same(a.supplierRef,b.supplierRef)&&same(a.packageRef,b.packageRef)&&a.amount<threshold&&b.amount<threshold&&a.amount+b.amount>=threshold&&a.decisionDate&&b.decisionDate&&daysBetween(a.decisionDate,b.decisionDate)<=30)push(`pair:${a.id}:${b.id}`,"high",a.id,"Possible split-purchase pattern","Two same-supplier, same-package entries within 30 days jointly cross the team threshold. This is a review signal, not proof.","Review the combined need, approvals and competition route; document a justified outcome.")}
 const totals=new Map<string,{total:number;vendors:Map<string,number>}>();for(const d of state.decisions.filter(x=>x.kind==="procurement"&&x.amount>0&&x.currency)){const x=totals.get(d.currency)||{total:0,vendors:new Map<string,number>()};x.total+=d.amount;if(d.supplierRef)x.vendors.set(d.supplierRef,(x.vendors.get(d.supplierRef)||0)+d.amount);totals.set(d.currency,x)}for(const [currency,x] of totals)for(const [vendor,value] of x.vendors)if(x.total>=state.policy.competitionThreshold*2&&value/x.total>.7)push(`concentration:${currency}:${vendor}`,"review","portfolio","Supplier concentration needs review",`${Math.round(value/x.total*100)}% of entered ${currency} procurement value is associated with one supplier reference.`,"Check resilience, related-party declarations, pricing evidence and viable alternatives.");
 for(const c of state.capabilities){if(!c.evidenceRef.trim())push(`${c.id}:capability-evidence`,"review",c.id,"Capability evidence missing",`The ${c.role||"assigned"} role has no evidence reference for ${c.scope||"its scope"}.`,"Verify appointment, qualification, experience, authorization and limits with an independent reviewer.");if(c.reviewState==="expired"||(c.validUntil&&c.validUntil<new Date().toISOString().slice(0,10)))push(`${c.id}:capability-expired`,"high",c.id,"Capability evidence expired","The recorded validity date has passed.","Pause affected approvals until current evidence or supervised limitations are recorded.");if(same(c.role,c.independentReviewerRole))push(`${c.id}:capability-review`,"high",c.id,"Capability review is not independent","The assigned role is also the reviewer.","Assign an independent reviewer appropriate to the discipline and risk.")}
 return out}
export function integritySummary(state:ProjectIntegrityState){const signals=integritySignals(state);return{decisions:state.decisions.length,capabilities:state.capabilities.length,high:signals.filter(x=>x.severity==="high").length,review:signals.filter(x=>x.severity==="review").length,evidenceCoverage:state.decisions.length?Math.round(state.decisions.filter(x=>x.evidenceRef.trim()).length/state.decisions.length*100):0}}
const text=(v:unknown,max:number)=>typeof v==="string"&&v.length<=max,number=(v:unknown,max=1e12)=>typeof v==="number"&&Number.isFinite(v)&&v>=0&&v<=max,date=(v:unknown)=>text(v,10)&&(v===""||/^\d{4}-\d{2}-\d{2}$/.test(v as string));
export function safeProjectIntegrityState(value:unknown):ProjectIntegrityState|null{if(!value||typeof value!=="object")return null;const x=value as ProjectIntegrityState;if(x.schema!==PROJECT_INTEGRITY_SCHEMA||x.status!=="executable"||!x.policy||!Array.isArray(x.decisions)||x.decisions.length>500||!Array.isArray(x.capabilities)||x.capabilities.length>100)return null;if(!text(x.policy.currency,12)||!number(x.policy.competitionThreshold)||!number(x.policy.requiredQuotes,20)||!number(x.policy.retrospectiveReviewDays,365)||!text(x.policy.complaintRoute,500))return null;for(const d of x.decisions)if(!d||!text(d.id,100)||!text(d.title,240)||!decisionKinds.includes(d.kind)||!["draft","under-review","approved","closed"].includes(d.status)||!["pending","none-declared","declared-recused","declared-managed"].includes(d.conflictState)||![d.packageRef,d.supplierRef,d.currency,d.requesterRole,d.reviewerRole,d.approverRole,d.exceptionReason,d.evidenceRef,d.completionEvidenceRef].every(v=>text(v,1000))||!number(d.amount)||!number(d.baselineAmount)||!number(d.quotesReceived,100)||!date(d.decisionDate)||typeof d.competitionException!=="boolean"||!text(d.updatedAt,40))return null;for(const c of x.capabilities)if(!c||![c.id,c.role,c.scope,c.requirement,c.evidenceRef,c.independentReviewerRole].every(v=>text(v,1000))||!["unreviewed","verified","limited","expired"].includes(c.reviewState)||!date(c.validUntil)||!text(c.updatedAt,40))return null;return x}
