import {durationDays,taskBlockers,type ScheduleTask} from "@/lib/project-schedule";

export const PROJECT_PLANNING_SCHEMA="mosque.build/project-planning@1" as const;
export type MilestoneStatus="planned"|"at-risk"|"ready-for-review"|"accepted";
export type Milestone={id:string;title:string;targetDate:string;phase:string;ownerRole:string;status:MilestoneStatus;evidenceRef:string;acceptanceCriteria:string};
export type PlanningNote={id:string;kind:"decision"|"risk"|"assumption"|"constraint";title:string;ownerRole:string;dueDate:string;response:string;status:"open"|"monitoring"|"closed"};
export type ProjectPlanningState={schema:typeof PROJECT_PLANNING_SCHEMA;anchorDate:string;horizonDays:30|60|90;scenarioShiftDays:number;milestones:Milestone[];notes:PlanningNote[];updatedAt:string};
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));
export const addDays=(value:string,days:number)=>new Date(Date.parse(`${value}T00:00:00Z`)+days*86_400_000).toISOString().slice(0,10);
export function createProjectPlanning(anchorDate:string):ProjectPlanningState{return {schema:PROJECT_PLANNING_SCHEMA,anchorDate,horizonDays:30,scenarioShiftDays:0,milestones:[],notes:[],updatedAt:new Date().toISOString()}}
export function phaseRollups(tasks:ScheduleTask[]){return [...new Set(tasks.map(task=>task.phase))].map(phase=>{const items=tasks.filter(task=>task.phase===phase),weight=items.reduce((n,item)=>n+durationDays(item),0),earned=items.reduce((n,item)=>n+durationDays(item)*item.progress,0);return {phase,tasks:items.length,start:items.reduce((v,item)=>!v||item.start<v?item.start:v,""),finish:items.reduce((v,item)=>item.finish>v?item.finish:v,""),progress:weight?Math.round(earned/weight):0,blocked:items.filter(item=>item.status==="blocked"||taskBlockers(item,tasks).length).length,missingOwner:items.filter(item=>!item.responsibleRole.trim()).length,missingEvidence:items.filter(item=>item.status==="complete"&&!item.evidenceRef.trim()).length}})}
export function lookahead(tasks:ScheduleTask[],anchor:string,horizon:number){const finish=addDays(anchor,horizon);return tasks.filter(task=>task.finish>=anchor&&task.start<=finish).sort((a,b)=>a.start.localeCompare(b.start))}
export function roleLoad(tasks:ScheduleTask[]){const map=new Map<string,{role:string;tasks:number;days:number;blocked:number}>();for(const task of tasks){const role=task.responsibleRole.trim()||"Unassigned";const row=map.get(role)??{role,tasks:0,days:0,blocked:0};row.tasks++;row.days+=durationDays(task);if(task.status==="blocked"||taskBlockers(task,tasks).length)row.blocked++;map.set(role,row)}return [...map.values()].sort((a,b)=>b.days-a.days)}
export function milestoneGaps(item:Milestone){const gaps:string[]=[];if(!item.title.trim())gaps.push("title");if(!validDate(item.targetDate))gaps.push("target date");if(!item.ownerRole.trim())gaps.push("owner role");if(!item.acceptanceCriteria.trim())gaps.push("acceptance criteria");if(item.status==="accepted"&&!item.evidenceRef.trim())gaps.push("acceptance evidence");return gaps}
export function safeProjectPlanning(value:unknown):ProjectPlanningState|null{if(!value||typeof value!=="object")return null;const source=value as Partial<ProjectPlanningState>;if(source.schema!==PROJECT_PLANNING_SCHEMA||!validDate(source.anchorDate??"")||![30,60,90].includes(source.horizonDays??0)||typeof source.scenarioShiftDays!=="number"||source.scenarioShiftDays< -180||source.scenarioShiftDays>365||!Array.isArray(source.milestones)||source.milestones.length>100||!Array.isArray(source.notes)||source.notes.length>200)return null;const milestones=source.milestones.filter((x):x is Milestone=>!!x&&typeof x.id==="string"&&typeof x.title==="string"&&typeof x.targetDate==="string"&&typeof x.phase==="string"&&typeof x.ownerRole==="string"&&["planned","at-risk","ready-for-review","accepted"].includes(x.status)&&typeof x.evidenceRef==="string"&&typeof x.acceptanceCriteria==="string");const notes=source.notes.filter((x):x is PlanningNote=>!!x&&typeof x.id==="string"&&["decision","risk","assumption","constraint"].includes(x.kind)&&typeof x.title==="string"&&typeof x.ownerRole==="string"&&typeof x.dueDate==="string"&&typeof x.response==="string"&&["open","monitoring","closed"].includes(x.status));return milestones.length===source.milestones.length&&notes.length===source.notes.length?{schema:PROJECT_PLANNING_SCHEMA,anchorDate:source.anchorDate!,horizonDays:source.horizonDays as 30|60|90,scenarioShiftDays:source.scenarioShiftDays,milestones,notes,updatedAt:typeof source.updatedAt==="string"?source.updatedAt:""}:null}
