import{workflowNodes,type WorkflowNode,type WorkflowSignal}from"./workflow-integration";

export const PROJECT_ACTION_PLAN_SCHEMA="mosque.build/project-action-plan@1" as const;
export const PROJECT_ACTION_PLAN_KEY="mosque-build.project-action-plan.v1";
export type ActionPriority="critical"|"high"|"normal"|"later";
export type ActionState="open"|"in-progress"|"ready-for-review"|"deferred"|"closed-user-record";
export type ProjectActionDecision={nodeId:string;priority:ActionPriority;state:ActionState;ownerRole:string;targetDate:string;note:string;pinned:boolean;updatedAt:string};
export type ProjectAction={node:WorkflowNode;signal:WorkflowSignal;decision:ProjectActionDecision;reason:string;score:number;available:boolean;blockedBy:string[]};
export type ProjectActionPlan={schema:typeof PROJECT_ACTION_PLAN_SCHEMA;updatedAt:string;decisions:ProjectActionDecision[]};

const states=new Set<ActionState>(["open","in-progress","ready-for-review","deferred","closed-user-record"]),priorities=new Set<ActionPriority>(["critical","high","normal","later"]);
const text=(value:unknown,max=500)=>typeof value==="string"?value.trim().slice(0,max):"";
export function blankProjectActionPlan():ProjectActionPlan{return{schema:PROJECT_ACTION_PLAN_SCHEMA,updatedAt:new Date().toISOString(),decisions:[]}}
export function safeProjectActionPlan(value:unknown):ProjectActionPlan{if(!value||typeof value!=="object")return blankProjectActionPlan();const x=value as Record<string,unknown>,rows=Array.isArray(x.decisions)?x.decisions:[];return{schema:PROJECT_ACTION_PLAN_SCHEMA,updatedAt:text(x.updatedAt,40)||new Date().toISOString(),decisions:rows.slice(0,100).flatMap(row=>{if(!row||typeof row!=="object")return[];const d=row as Record<string,unknown>,nodeId=text(d.nodeId,80);if(!workflowNodes.some(n=>n.id===nodeId))return[];return[{nodeId,priority:priorities.has(d.priority as ActionPriority)?d.priority as ActionPriority:"normal",state:states.has(d.state as ActionState)?d.state as ActionState:"open",ownerRole:text(d.ownerRole,100),targetDate:/^\d{4}-\d{2}-\d{2}$/.test(text(d.targetDate,10))?text(d.targetDate,10):"",note:text(d.note),pinned:d.pinned===true,updatedAt:text(d.updatedAt,40)}]})}}
export function defaultDecision(nodeId:string):ProjectActionDecision{return{nodeId,priority:"normal",state:"open",ownerRole:"",targetDate:"",note:"",pinned:false,updatedAt:""}}
export function deriveProjectActions(signals:WorkflowSignal[],plan:ProjectActionPlan,now=new Date()):ProjectAction[]{const signalById=new Map(signals.map(s=>[s.id,s])),decisionById=new Map(plan.decisions.map(d=>[d.nodeId,d]));return workflowNodes.map(node=>{const signal=signalById.get(node.id)??{id:node.id,state:"no-record" as const,updatedAt:"",recordCount:0,stale:false,dependencyGaps:node.dependencies},decision=decisionById.get(node.id)??defaultDecision(node.id),blockedBy=signal.dependencyGaps.map(id=>workflowNodes.find(n=>n.id===id)?.label||id),available=signal.state!=="no-record"||blockedBy.length===0;let reason="Continue and review the local record.";let score=signal.state==="no-record"?60:25;if(signal.state==="no-record"&&available){reason="Ready to start; its upstream records are present.";score=80}else if(signal.state==="no-record"){reason=`Connect ${blockedBy.join(", ")} first.`;score=35}else if(signal.stale){reason="Review source and record freshness before relying on this work.";score=90}else if(signal.state==="started"){reason="Develop the initial record and prepare its review gate.";score=70}if(node.reviewGate==="authority"&&signal.state!=="no-record")score+=8;if(node.reviewGate==="professional"&&signal.state==="started")score+=5;if(decision.pinned)score+=100;if(decision.priority==="critical")score+=60;if(decision.priority==="high")score+=30;if(decision.priority==="later")score-=40;if(decision.targetDate){const days=(new Date(`${decision.targetDate}T23:59:59`).getTime()-now.getTime())/86400000;if(days<0&&decision.state!=="closed-user-record")score+=70;else if(days<=14)score+=25}if(decision.state==="deferred")score-=90;if(decision.state==="closed-user-record")score-=200;return{node,signal,decision,reason,score,available,blockedBy}}).sort((a,b)=>b.score-a.score||a.node.label.localeCompare(b.node.label))}
export function actionPlanSummary(actions:ProjectAction[],now=new Date()){return{open:actions.filter(a=>!["deferred","closed-user-record"].includes(a.decision.state)).length,active:actions.filter(a=>a.decision.state==="in-progress").length,review:actions.filter(a=>a.decision.state==="ready-for-review").length,blocked:actions.filter(a=>!a.available).length,stale:actions.filter(a=>a.signal.stale).length,overdue:actions.filter(a=>a.decision.targetDate&&new Date(`${a.decision.targetDate}T23:59:59`)<now&&!['deferred','closed-user-record'].includes(a.decision.state)).length,unowned:actions.filter(a=>a.decision.state!=="closed-user-record"&&!a.decision.ownerRole).length}}
export function actionDecisionGaps(action:ProjectAction){const gaps:string[]=[];if(!action.decision.ownerRole)gaps.push("responsible role");if(!action.decision.targetDate)gaps.push("target date");if(action.decision.state==="ready-for-review"&&!action.decision.note)gaps.push("review note or evidence reference");if(!action.available)gaps.push("upstream context");return gaps}
