import type {SchematicPlan,SchematicRoom} from "@/lib/schematic-plan";
import {createCulturalGuides,type CulturalGuide} from "@/lib/cultural-model-guides";
import {createTemplateMassing,type TemplateMassingStudy} from "@/lib/template-massing";
import type {DesignTemplate} from "@/lib/mosque-design-templates";
export type RenderMaterial="site"|SchematicRoom["kind"];
export type RenderBox={id:string;label:string;position:[number,number,number];size:[number,number,number];material:RenderMaterial;areaM2:number;level:0};
export type RenderWall={id:string;label:string;position:[number,number,number];size:[number,number,number];orientation:"north"|"east"|"south"|"west";external:true;level:0};
export type RenderOpening={id:string;label:string;kind:"entry";hostWallId:string;position:[number,number,number];size:[number,number];level:0;connectsRoomIds:string[];status:"concept"};
export type RenderAdjacency={id:string;roomIds:[string,string];boundaryLengthM:number;kind:"shared-edge"};
export type RenderModel={schemaVersion:"mosque.build/render-model@1";units:"m";status:"concept";footprint:[number,number];qiblaDeg:number;culturalContextId?:string;materialStudyIds:string[];templateMassing?:TemplateMassingStudy;boxes:RenderBox[];walls:RenderWall[];openings:RenderOpening[];adjacencies:RenderAdjacency[];guides:CulturalGuide[];reviewGate:string};
const heights:Record<SchematicRoom["kind"],number>={prayer:4.8,support:3.2,learning:3.4,circulation:3,courtyard:.12};
const rounded=(value:number)=>Math.round(value*1000)/1000;
function createAdjacencies(rooms:SchematicRoom[]):RenderAdjacency[]{const tolerance=.001,records:RenderAdjacency[]=[];for(let index=0;index<rooms.length;index++)for(const other of rooms.slice(index+1)){const room=rooms[index],vertical=Math.min(room.y+room.depth,other.y+other.depth)-Math.max(room.y,other.y),horizontal=Math.min(room.x+room.width,other.x+other.width)-Math.max(room.x,other.x),touchesX=Math.abs(room.x+room.width-other.x)<tolerance||Math.abs(other.x+other.width-room.x)<tolerance,touchesY=Math.abs(room.y+room.depth-other.y)<tolerance||Math.abs(other.y+other.depth-room.y)<tolerance,length=touchesX?vertical:touchesY?horizontal:0;if(length>tolerance){const roomIds=[room.id,other.id].sort() as [string,string];records.push({id:`adjacency:${roomIds.join(":")}`,roomIds,boundaryLengthM:rounded(length),kind:"shared-edge"})}}return records.sort((a,b)=>a.id.localeCompare(b.id))}
/** Renderer-neutral scene description for WebGL, glTF, or future adapters. */
export function createRenderModel(plan:SchematicPlan,culturalContextId?:string,materialStudyIds:string[]=[],template?:DesignTemplate):RenderModel{const {widthM,depthM,wallM}=plan.inputs,wallHeight=3.2,entryWidth=Math.min(2.4,Math.max(1.2,widthM*.08)),entryRoom=plan.rooms.find(room=>room.kind==="circulation")??plan.rooms.at(-1),entryX=rounded(Math.min(widthM-entryWidth/2-wallM,Math.max(entryWidth/2+wallM,(entryRoom?.x??0)+(entryRoom?.width??widthM)/2))),leftWidth=rounded(entryX-entryWidth/2),rightWidth=rounded(widthM-entryX-entryWidth/2);const boxes:RenderBox[]=[{id:"site",label:"Conceptual site plate",position:[widthM/2,-.12,depthM/2],size:[widthM+.8,.2,depthM+.8],material:"site",areaM2:plan.grossAreaM2,level:0}];for(const room of plan.rooms){const height=heights[room.kind];boxes.push({id:room.id,label:room.name,position:[room.x+room.width/2,height/2,room.y+room.depth/2],size:[room.width,height,room.depth],material:room.kind,areaM2:Math.round(room.width*room.depth*10)/10,level:0})}const wallCandidates:RenderWall[]=[{id:"wall:north",label:"North perimeter wall",position:[widthM/2,wallHeight/2,wallM/2],size:[widthM,wallHeight,wallM],orientation:"north",external:true,level:0},{id:"wall:east",label:"East perimeter wall",position:[widthM-wallM/2,wallHeight/2,depthM/2],size:[wallM,wallHeight,depthM],orientation:"east",external:true,level:0},{id:"wall:south-left",label:"South perimeter wall — left of entry",position:[leftWidth/2,wallHeight/2,depthM-wallM/2],size:[leftWidth,wallHeight,wallM],orientation:"south",external:true,level:0},{id:"wall:south-lintel",label:"South entry lintel study",position:[entryX,2.9,depthM-wallM/2],size:[entryWidth,.6,wallM],orientation:"south",external:true,level:0},{id:"wall:south-right",label:"South perimeter wall — right of entry",position:[entryX+entryWidth/2+rightWidth/2,wallHeight/2,depthM-wallM/2],size:[rightWidth,wallHeight,wallM],orientation:"south",external:true,level:0},{id:"wall:west",label:"West perimeter wall",position:[wallM/2,wallHeight/2,depthM/2],size:[wallM,wallHeight,depthM],orientation:"west",external:true,level:0}],walls=wallCandidates.filter(wall=>wall.size[0]>.01&&wall.size[2]>.01);const openings:RenderOpening[]=[{id:"opening:main-entry",label:"Conceptual main entry",kind:"entry",hostWallId:"wall:south",position:[entryX,1.2,depthM],size:[entryWidth,2.4],level:0,connectsRoomIds:entryRoom?[entryRoom.id]:[],status:"concept"}];return {schemaVersion:"mosque.build/render-model@1",units:"m",status:"concept",footprint:[widthM,depthM],qiblaDeg:plan.inputs.qiblaDeg,culturalContextId,materialStudyIds:[...new Set(materialStudyIds)].sort(),templateMassing:template?createTemplateMassing(template,widthM,depthM):undefined,boxes,walls,openings,adjacencies:createAdjacencies(plan.rooms),guides:createCulturalGuides(culturalContextId,widthM,depthM),reviewGate:plan.reviewGate}}
