export const SCHEDULE_BASELINES_SCHEMA="mosque.build/schedule-baselines@1",SCHEDULE_BASELINES_KEY="mosque-build.schedule-baselines.v1",SCHEDULE_BASELINES_MAX=30;
export type BaselineTask={id:string;name:string;phase:string;start:string;finish:string;progress:number;status:string;dependsOn:string[];responsibleRole:string;evidenceRef:string;notes:string};
export type BaselineSchedule={schema:string;baselineDate:string;tasks:BaselineTask[];updatedAt:string};
export type ScheduleBaseline={id:string;sequence:number;label:string;purpose:string;capturedAt:string;capturedByRole:string;evidenceRef:string;scheduleUpdatedAt:string;tasks:BaselineTask[]};
export type ScheduleBaselineRegister={schema:typeof SCHEDULE_BASELINES_SCHEMA;status:"executable";baselines:ScheduleBaseline[];updatedAt:string};
const plain=(x:unknown)=>Boolean(x)&&typeof x==="object"&&!Array.isArray(x)&&(Object.getPrototypeOf(x)===Object.prototype||Object.getPrototypeOf(x)===null),text=(x:unknown,n:number)=>typeof x==="string"&&x.length<=n,date=(x:unknown)=>typeof x==="string"&&/^\d{4}-\d{2}-\d{2}T/.test(x)&&!Number.isNaN(Date.parse(x)),day=(x:unknown)=>{if(typeof x!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(x))return false;const parsed=new Date(`${x}T00:00:00Z`);return!Number.isNaN(parsed.valueOf())&&parsed.toISOString().slice(0,10)===x},stableId=(x:unknown)=>typeof x==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,179}$/.test(x);
const safeTask=(x:unknown):x is BaselineTask=>plain(x)&&stableId((x as BaselineTask).id)&&text((x as BaselineTask).name,300)&&text((x as BaselineTask).phase,160)&&day((x as BaselineTask).start)&&day((x as BaselineTask).finish)&&(x as BaselineTask).finish>=(x as BaselineTask).start&&typeof(x as BaselineTask).progress==="number"&&(x as BaselineTask).progress>=0&&(x as BaselineTask).progress<=100&&text((x as BaselineTask).status,40)&&Array.isArray((x as BaselineTask).dependsOn)&&(x as BaselineTask).dependsOn.length<=200&&(x as BaselineTask).dependsOn.every(id=>stableId(id))&&text((x as BaselineTask).responsibleRole,200)&&text((x as BaselineTask).evidenceRef,1000)&&text((x as BaselineTask).notes,4000);
export const emptyScheduleBaselineRegister=():ScheduleBaselineRegister=>({schema:SCHEDULE_BASELINES_SCHEMA,status:"executable",baselines:[],updatedAt:""});
export function baselineCaptureGaps(schedule:BaselineSchedule|null,label:string,role:string,evidence:string){const gaps:string[]=[];if(!schedule||!Array.isArray(schedule.tasks)||!schedule.tasks.length)gaps.push("working schedule");if(!label.trim())gaps.push("baseline label");if(!role.trim())gaps.push("accountable role");if(!evidence.trim())gaps.push("decision or meeting evidence reference");if(schedule&&schedule.tasks.some(x=>!safeTask(x)))gaps.push("valid bounded activities");if(schedule&&new Set(schedule.tasks.map(x=>x.id)).size!==schedule.tasks.length)gaps.push("unique activity IDs");return gaps;}
export function captureScheduleBaseline(register:ScheduleBaselineRegister,schedule:BaselineSchedule,label:string,role:string,evidence:string,id:string,at:string){const gaps=baselineCaptureGaps(schedule,label,role,evidence);if(gaps.length)return{register,baseline:null,gaps};const sequence=(register.baselines.at(-1)?.sequence??0)+1,baseline:ScheduleBaseline={id,sequence,label:label.trim(),purpose:"Project-team schedule reference",capturedAt:at,capturedByRole:role.trim(),evidenceRef:evidence.trim(),scheduleUpdatedAt:schedule.updatedAt,tasks:structuredClone(schedule.tasks)};return{register:{...register,baselines:[...register.baselines,baseline].slice(-SCHEDULE_BASELINES_MAX),updatedAt:at},baseline,gaps:[]};}
const projectFinish=(tasks:BaselineTask[])=>tasks.reduce((max,x)=>x.finish>max?x.finish:max,tasks[0]?.finish??"1970-01-01");
export function baselineVariance(baseline:ScheduleBaseline,current:BaselineSchedule){const currentById=new Map(current.tasks.map(x=>[x.id,x])),baseById=new Map(baseline.tasks.map(x=>[x.id,x])),changed=baseline.tasks.flatMap(task=>{const now=currentById.get(task.id);if(!now)return[];const startDays=Math.round((Date.parse(`${now.start}T00:00:00Z`)-Date.parse(`${task.start}T00:00:00Z`))/86400000),finishDays=Math.round((Date.parse(`${now.finish}T00:00:00Z`)-Date.parse(`${task.finish}T00:00:00Z`))/86400000);return startDays||finishDays||now.name!==task.name?[{id:task.id,name:now.name,startDays,finishDays,renamed:now.name!==task.name}]:[]});return{added:current.tasks.filter(x=>!baseById.has(x.id)),removed:baseline.tasks.filter(x=>!currentById.has(x.id)),changed,finishVarianceDays:Math.round((Date.parse(`${projectFinish(current.tasks)}T00:00:00Z`)-Date.parse(`${projectFinish(baseline.tasks)}T00:00:00Z`))/86400000)};}
export function scheduleFromBaseline(baseline:ScheduleBaseline,current:BaselineSchedule,at:string):BaselineSchedule{return{...current,baselineDate:baseline.tasks.reduce((min,x)=>x.start<min?x.start:min,baseline.tasks[0]?.start??current.baselineDate),tasks:structuredClone(baseline.tasks).map(x=>({...x,progress:0,status:"not-started",evidenceRef:""})),updatedAt:at}}
export function safeScheduleBaselineRegister(value:unknown):ScheduleBaselineRegister|null{if(!plain(value))return null;const x=value as ScheduleBaselineRegister;if(x.schema!==SCHEDULE_BASELINES_SCHEMA||x.status!=="executable"||!Array.isArray(x.baselines)||x.baselines.length>SCHEDULE_BASELINES_MAX)return null;const seen=new Set<string>();let sequence=0;for(const b of x.baselines){if(!plain(b)||!stableId(b.id)||seen.has(b.id)||!Number.isInteger(b.sequence)||b.sequence<=sequence||!text(b.label,200)||!text(b.purpose,300)||!date(b.capturedAt)||!text(b.capturedByRole,200)||!text(b.evidenceRef,1000)||!text(b.scheduleUpdatedAt,60)||!Array.isArray(b.tasks)||!b.tasks.length||b.tasks.length>200||!b.tasks.every(safeTask)||new Set(b.tasks.map(task=>task.id)).size!==b.tasks.length)return null;seen.add(b.id);sequence=b.sequence}return structuredClone(x)}
export function exportScheduleBaselines(register:ScheduleBaselineRegister){return JSON.stringify({...register,boundary:"Immutable within this device-local workflow, but not tamper-proof, signed, contractual or server-authenticated."},null,2)}
