export const SHURA_SCHEMA="mosque.build/shura-workspace@1" as const;
export const decisionStatuses=["draft","consultation-open","review-ready","decision-recorded","reopened"] as const;
export const contributionKinds=["request","concern","objection","change","approval-note"] as const;
export const reviewDisciplines=["community","religious","accessibility","design","cost","operations","professional","authority"] as const;
export type DecisionStatus=typeof decisionStatuses[number];export type ContributionKind=typeof contributionKinds[number];export type ReviewDiscipline=typeof reviewDisciplines[number];
export type DecisionOption={id:string;label:string;benefits:string;tradeoffs:string;supportRoles:string[];concernRoles:string[]};
export type Contribution={id:string;kind:ContributionKind;summary:string;role:string;response:string;resolved:boolean;createdAt:string};
export type ReviewGate={discipline:ReviewDiscipline;state:"not-requested"|"requested"|"reviewed-user-record";reviewerRole:string;evidenceRef:string;note:string};
export type AuditEvent={id:string;at:string;actorRole:string;action:string;detail:string};
export type ShuraDecision={id:string;title:string;question:string;context:string;ownerRole:string;status:DecisionStatus;decisionDue:string;reviewDate:string;assumptions:string;sourceRefs:string;representedRoles:string[];options:DecisionOption[];contributions:Contribution[];reviews:ReviewGate[];selectedOptionId:string;outcome:string;events:AuditEvent[];createdAt:string;updatedAt:string};
export type ShuraWorkspace={schema:typeof SHURA_SCHEMA;status:"executable";updatedAt:string;decisions:ShuraDecision[]};
const reviewSeeds=():ReviewGate[]=>reviewDisciplines.map(discipline=>({discipline,state:"not-requested",reviewerRole:"",evidenceRef:"",note:""}));
export const createShuraWorkspace=():ShuraWorkspace=>({schema:SHURA_SCHEMA,status:"executable",updatedAt:"",decisions:[]});
export function createDecision(id:string,now:string,title="Untitled decision"):ShuraDecision{return{id,title,question:"",context:"",ownerRole:"",status:"draft",decisionDue:"",reviewDate:"",assumptions:"",sourceRefs:"",representedRoles:[],options:[],contributions:[],reviews:reviewSeeds(),selectedOptionId:"",outcome:"",events:[{id:`${id}:created`,at:now,actorRole:"Project team",action:"created",detail:"Decision record created."}],createdAt:now,updatedAt:now}}
const text=(v:unknown,max:number)=>typeof v==="string"&&v.length<=max,states=new Set(decisionStatuses),kinds=new Set(contributionKinds),disciplines=new Set(reviewDisciplines);
export function safeShuraWorkspace(value:unknown):ShuraWorkspace|null{if(!value||typeof value!=="object")return null;const x=value as ShuraWorkspace;if(x.schema!==SHURA_SCHEMA||x.status!=="executable"||!Array.isArray(x.decisions)||x.decisions.length>200)return null;for(const d of x.decisions){if(!d||!text(d.id,100)||!text(d.title,200)||!text(d.question,2000)||!text(d.context,5000)||!text(d.ownerRole,160)||!states.has(d.status)||!Array.isArray(d.representedRoles)||d.representedRoles.length>30||!Array.isArray(d.options)||d.options.length>12||!Array.isArray(d.contributions)||d.contributions.length>200||!Array.isArray(d.reviews)||d.reviews.length!==reviewDisciplines.length||!Array.isArray(d.events)||d.events.length>500||!text(d.outcome,5000))return null;for(const o of d.options)if(!text(o.id,100)||!text(o.label,300)||!text(o.benefits,3000)||!text(o.tradeoffs,3000)||!Array.isArray(o.supportRoles)||o.supportRoles.length>50||!Array.isArray(o.concernRoles)||o.concernRoles.length>50)return null;for(const c of d.contributions)if(!text(c.id,100)||!kinds.has(c.kind)||!text(c.summary,3000)||!text(c.role,160)||!text(c.response,3000)||typeof c.resolved!=="boolean")return null;for(const r of d.reviews)if(!disciplines.has(r.discipline)||!["not-requested","requested","reviewed-user-record"].includes(r.state)||!text(r.reviewerRole,160)||!text(r.evidenceRef,1000)||!text(r.note,3000))return null}return x}
export function decisionGaps(d:ShuraDecision){const gaps:string[]=[];if(!d.question.trim())gaps.push("decision question");if(!d.ownerRole.trim())gaps.push("accountable owner role");if(d.representedRoles.length<2)gaps.push("represented roles");if(d.options.length<2)gaps.push("at least two alternatives");if(d.options.some(o=>!o.tradeoffs.trim()))gaps.push("trade-offs for every alternative");if(d.contributions.some(c=>!c.resolved))gaps.push("unresolved contributions");if(!d.selectedOptionId)gaps.push("recorded selection");if(d.selectedOptionId&&!d.outcome.trim())gaps.push("decision rationale");if(d.status==="decision-recorded"&&d.reviews.some(r=>r.state==="requested"&&!r.evidenceRef.trim()))gaps.push("requested review evidence");return [...new Set(gaps)]}
export function shuraSummary(w:ShuraWorkspace){return{decisions:w.decisions.length,open:w.decisions.filter(d=>d.status!=="decision-recorded").length,recorded:w.decisions.filter(d=>d.status==="decision-recorded").length,unresolved:w.decisions.reduce((n,d)=>n+d.contributions.filter(c=>!c.resolved).length,0),reviewGaps:w.decisions.reduce((n,d)=>n+d.reviews.filter(r=>r.state==="requested"&&!r.evidenceRef.trim()).length,0)}}
export function appendEvent(d:ShuraDecision,actorRole:string,action:string,detail:string,id:string,now:string):ShuraDecision{if(action==="updated")return{...d,updatedAt:now};return{...d,updatedAt:now,events:[...d.events,{id,at:now,actorRole:actorRole.trim()||"Unassigned role",action,detail}].slice(-500)}}
export function canRecordDecision(d:ShuraDecision){return decisionGaps(d).filter(g=>!["unresolved contributions","requested review evidence"].includes(g)).length===0}
