export const SITE_INVESTIGATION_SCHEMA="mosque.build/site-investigation@1" as const;
export const investigationStatuses=["not-started","scoping","commissioned","fieldwork","evidence-received","reviewed-user-record","blocked"] as const;
export const investigationPriorities=["monitor","planned","priority","hold-point"] as const;
export type InvestigationStatus=typeof investigationStatuses[number];export type InvestigationPriority=typeof investigationPriorities[number];
export type InvestigationTask={id:string;category:string;title:string;purpose:string;gate:"community"|"professional"|"authority";priority:InvestigationPriority;status:InvestigationStatus;ownerRole:string;targetDate:string;evidenceRef:string;scopeNotes:string;outcomeNotes:string;nextAction:string;updatedAt:string};
export type HoldPoint={id:string;title:string;commitment:string;status:"not-ready"|"ready-for-review"|"released-user-record";ownerRole:string;decisionRef:string;conditions:string;dissent:string;targetDate:string;updatedAt:string};
export type InvestigationSnapshot={id:string;label:string;createdAt:string;basis:string;openTasks:number;holdPoints:number;reviewedTasks:number};
export type SiteInvestigation={schema:typeof SITE_INVESTIGATION_SCHEMA;status:"executable";tasks:InvestigationTask[];holdPoints:HoldPoint[];snapshots:InvestigationSnapshot[];updatedAt:string};
const taskSeeds=[
["Survey","Measured boundary and levels","Establish source, coordinate basis, tolerance and limitations of provisional site geometry.","professional"],["Legal","Title, rights and restrictions review","Record accountable legal-review scope without storing ownership or parcel identifiers here.","professional"],["Planning","Current use and development pathway","Identify current official sources and questions for the responsible authority.","authority"],["Fire","Emergency access and assembly review","Coordinate fire-service access, evacuation, assembly and authority questions.","authority"],["Ground","Ground investigation strategy","Define geotechnical, groundwater, fill, contamination and buried-obstruction scope.","professional"],["Water","Drainage and exceedance study","Test levels, outfalls, infiltration assumptions and safe exceedance routes using declared evidence.","professional"],["Utilities","Provider capacity enquiries","Track water, wastewater, power and communications evidence without assuming availability.","professional"],["Mobility","Multi-modal access study","Observe daily and peak walking, transit, cycling, drop-off, parking and servicing scenarios.","community"],["Accessibility","Complete-journey site review","Review step-free arrival, gradients, crossings, rest, wayfinding and emergency journeys with affected users.","community"],["Climate","Climate and hazard evidence brief","Gather current official layers and future-climate inputs for qualified interpretation.","professional"],["Ecology","Seasonal ecology and tree scope","Determine survey seasons, protected features and stewardship questions.","professional"],["Context","Neighbor and community observations","Record time-bounded noise, privacy, traffic, shared-space and relationship observations.","community"],["Heritage","Cultural and heritage context review","Identify designated and community-valued context requiring specialist and authority review.","authority"],["Existing building","Measured condition and adaptation audit","Coordinate structure, fabric, fire, accessibility, MEP, hazardous-material and heritage investigations.","professional"],["Delivery","Construction logistics feasibility","Test access, storage, lifting, welfare, temporary works, neighbor protection and phasing assumptions.","professional"],["Operations","Whole-life site operations brief","Connect staffing, security, maintenance, utilities, cleaning, emergency continuity and future change.","community"]] as const;
const holdSeeds=[["Before site shortlist","Do not narrow the shortlist until critical unknowns and community priorities are visible."],["Before offer or lease","Do not make a commercial commitment until legal, planning, survey and material risks have accountable review."],["Before design freeze","Do not freeze the site response until verified geometry, qibla, access, climate, utilities and authority pathways are coordinated."],["Before enabling works","Do not begin site works until permissions, safety, logistics, ground, utilities and environmental controls are evidenced."],["Before construction commitment","Do not commit until scope, approvals, professional designs, cost evidence, risks and responsibilities are reviewed."]] as const;
const now=()=>new Date().toISOString();
export function createSiteInvestigation():SiteInvestigation{const stamp=now();return{schema:SITE_INVESTIGATION_SCHEMA,status:"executable",updatedAt:stamp,tasks:taskSeeds.map(([category,title,purpose,gate],i)=>({id:`investigation-${i+1}`,category,title,purpose,gate,priority:"planned",status:"not-started",ownerRole:"",targetDate:"",evidenceRef:"",scopeNotes:"",outcomeNotes:"",nextAction:"",updatedAt:stamp})),holdPoints:holdSeeds.map(([title,commitment],i)=>({id:`hold-${i+1}`,title,commitment,status:"not-ready",ownerRole:"",decisionRef:"",conditions:"",dissent:"",targetDate:"",updatedAt:stamp})),snapshots:[]}}
export function taskGaps(x:InvestigationTask){const gaps:string[]=[];if(!x.ownerRole.trim())gaps.push("owner role");if(!x.scopeNotes.trim())gaps.push("scope");if(["commissioned","fieldwork","evidence-received","reviewed-user-record"].includes(x.status)&&!x.targetDate)gaps.push("target date");if(["evidence-received","reviewed-user-record"].includes(x.status)&&!x.evidenceRef.trim())gaps.push("evidence reference");if(x.status==="reviewed-user-record"&&!x.outcomeNotes.trim())gaps.push("review outcome");return gaps}
export function holdPointGaps(x:HoldPoint){const gaps:string[]=[];if(!x.ownerRole.trim())gaps.push("owner role");if(!x.conditions.trim())gaps.push("release conditions");if(x.status==="released-user-record"&&!x.decisionRef.trim())gaps.push("decision reference");return gaps}
export function investigationSummary(x:SiteInvestigation,today=new Date().toISOString().slice(0,10)){const reviewed=x.tasks.filter(v=>v.status==="reviewed-user-record").length,blocked=x.tasks.filter(v=>v.status==="blocked").length,evidenced=x.tasks.filter(v=>v.evidenceRef.trim()).length,owned=x.tasks.filter(v=>v.ownerRole.trim()).length,overdue=x.tasks.filter(v=>v.targetDate&&v.status!=="reviewed-user-record"&&v.targetDate<today).length,openHoldPoints=x.holdPoints.filter(v=>v.status!=="released-user-record").length,gaps=x.tasks.reduce((n,v)=>n+taskGaps(v).length,0)+x.holdPoints.reduce((n,v)=>n+holdPointGaps(v).length,0);return{reviewed,blocked,evidenced,owned,overdue,openHoldPoints,gaps,coverage:Math.round((reviewed+evidenced+owned)/(x.tasks.length*3)*100)}}
export function createInvestigationSnapshot(x:SiteInvestigation,label:string):InvestigationSnapshot{const s=investigationSummary(x);return{id:crypto.randomUUID(),label:label.trim().slice(0,80)||`Site review ${x.snapshots.length+1}`,createdAt:now(),basis:"User-entered investigation states and references; not approval, completed due diligence or a site recommendation.",openTasks:x.tasks.filter(v=>v.status!=="reviewed-user-record").length,holdPoints:s.openHoldPoints,reviewedTasks:s.reviewed}}
const bounded=(x:unknown,n:number)=>typeof x==="string"&&x.length<=n,dated=(x:string)=>!x||/^\d{4}-\d{2}-\d{2}$/.test(x);
export function safeSiteInvestigation(value:unknown):SiteInvestigation|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const x=value as Partial<SiteInvestigation>;if(x.schema!==SITE_INVESTIGATION_SCHEMA||x.status!=="executable"||!Array.isArray(x.tasks)||!Array.isArray(x.holdPoints)||!Array.isArray(x.snapshots)||x.tasks.length>40||x.holdPoints.length>12||x.snapshots.length>24)return null;const tasks=x.tasks.every(v=>v&&bounded(v.id,100)&&bounded(v.category,100)&&bounded(v.title,200)&&bounded(v.purpose,1000)&&["community","professional","authority"].includes(v.gate)&&investigationPriorities.includes(v.priority)&&investigationStatuses.includes(v.status)&&bounded(v.ownerRole,160)&&dated(v.targetDate)&&bounded(v.evidenceRef,1000)&&bounded(v.scopeNotes,4000)&&bounded(v.outcomeNotes,4000)&&bounded(v.nextAction,1000)&&bounded(v.updatedAt,40));const holds=x.holdPoints.every(v=>v&&bounded(v.id,100)&&bounded(v.title,200)&&bounded(v.commitment,1000)&&["not-ready","ready-for-review","released-user-record"].includes(v.status)&&bounded(v.ownerRole,160)&&bounded(v.decisionRef,1000)&&bounded(v.conditions,4000)&&bounded(v.dissent,2000)&&dated(v.targetDate)&&bounded(v.updatedAt,40));const snapshots=x.snapshots.every(v=>v&&bounded(v.id,100)&&bounded(v.label,80)&&bounded(v.createdAt,40)&&bounded(v.basis,500)&&Number.isInteger(v.openTasks)&&Number.isInteger(v.holdPoints)&&Number.isInteger(v.reviewedTasks));return tasks&&holds&&snapshots?x as SiteInvestigation:null}
