export const SITE_CONTEXT_SCHEMA="mosque.build/site-context-analysis@1" as const;
export const SITE_CONTEXT_KEY="mosque-build.site-context-analysis.v1";
export type ConfidenceMode="unknown"|"indicative"|"cross-checked"|"surveyed-override";
export type TerrainPoint={id:string;xM:number;zM:number;elevationM:number;sourceRef:string};
export type FloodZone={id:string;label:string;xM:number;zM:number;widthM:number;depthM:number;waterDepthM:number;designLevelM:number;sourceRef:string;observedAt:string;confidence:"unknown"|"screening"|"source-backed"};
export type SiteContextAnalysis={schema:typeof SITE_CONTEXT_SCHEMA;status:"executable";qibla:{bearingDeg:number;toleranceDeg:number;mode:ConfidenceMode;methodRef:string;reviewerRole:string};terrain:{datumLabel:string;sourceRef:string;observedAt:string;points:TerrainPoint[]};flood:{finishedFloorLevelM:number;freeboardInputM:number;sourceRef:string;zones:FloodZone[]};updatedAt:string};
const n=(value:number,min:number,max:number)=>Number.isFinite(value)?Math.max(min,Math.min(max,value)):min;
export const createSiteContextAnalysis=():SiteContextAnalysis=>({schema:SITE_CONTEXT_SCHEMA,status:"executable",qibla:{bearingDeg:0,toleranceDeg:10,mode:"unknown",methodRef:"",reviewerRole:""},terrain:{datumLabel:"Local working datum",sourceRef:"",observedAt:"",points:[]},flood:{finishedFloorLevelM:0,freeboardInputM:0,sourceRef:"",zones:[]},updatedAt:""});
export function addTerrainPoint(state:SiteContextAnalysis,point:Partial<TerrainPoint>={}):SiteContextAnalysis{return state.terrain.points.length>=100?state:{...state,terrain:{...state.terrain,points:[...state.terrain.points,{id:crypto.randomUUID(),xM:n(point.xM??0,0,500),zM:n(point.zM??0,0,500),elevationM:n(point.elevationM??0,-100,10000),sourceRef:String(point.sourceRef||"").slice(0,1000)}]}}}
export function terrainMetrics(points:TerrainPoint[]){if(!points.length)return{minimumM:0,maximumM:0,reliefM:0,maximumPairSlopePercent:0};const elevations=points.map(x=>x.elevationM),pairs=points.flatMap((a,i)=>points.slice(i+1).map(b=>{const run=Math.hypot(a.xM-b.xM,a.zM-b.zM);return run?Math.abs(a.elevationM-b.elevationM)/run*100:0}));return{minimumM:Math.min(...elevations),maximumM:Math.max(...elevations),reliefM:Math.max(...elevations)-Math.min(...elevations),maximumPairSlopePercent:Math.max(0,...pairs)}}
export function qiblaBounds(bearingDeg:number,toleranceDeg:number){const normalize=(x:number)=>(x%360+360)%360,t=n(toleranceDeg,0,90),b=normalize(bearingDeg);return{bearingDeg:b,toleranceDeg:t,minimumDeg:normalize(b-t),maximumDeg:normalize(b+t)}}
export function floodZoneResult(zone:FloodZone,finishedFloorLevelM:number,freeboardInputM:number){const required=zone.designLevelM+n(freeboardInputM,0,20),margin=finishedFloorLevelM-required;return{requiredLevelM:required,marginM:margin,state:!zone.sourceRef||zone.confidence==="unknown"?"needs-evidence" as const:margin<0?"below-entered-level" as const:"ready-for-review" as const}}
export function siteContextGaps(state:SiteContextAnalysis){const gaps:string[]=[];if(state.qibla.mode==="unknown")gaps.push("qibla confidence mode");if(!state.qibla.methodRef.trim())gaps.push("qibla method reference");if(!state.qibla.reviewerRole.trim())gaps.push("qibla reviewer role");if(state.terrain.points.length<3)gaps.push("at least three terrain samples");if(!state.terrain.sourceRef.trim())gaps.push("terrain source reference");if(!state.terrain.observedAt)gaps.push("terrain observation date");if(!state.flood.zones.length)gaps.push("flood screening zone or documented non-applicability");if(!state.flood.sourceRef.trim())gaps.push("flood source reference");for(const zone of state.flood.zones)if(floodZoneResult(zone,state.flood.finishedFloorLevelM,state.flood.freeboardInputM).state!=="ready-for-review")gaps.push(`${zone.label||"flood zone"} level/evidence review`);return[...new Set(gaps)]}
const text=(v:unknown,max:number)=>typeof v==="string"&&v.length<=max,num=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max,date=(v:unknown)=>text(v,10)&&(v===""||/^\d{4}-\d{2}-\d{2}$/.test(v as string));
export function safeSiteContextAnalysis(value:unknown):SiteContextAnalysis|null{if(!value||typeof value!=="object")return null;const x=value as SiteContextAnalysis;if(x.schema!==SITE_CONTEXT_SCHEMA||x.status!=="executable"||!x.qibla||!x.terrain||!x.flood||!Array.isArray(x.terrain.points)||x.terrain.points.length>100||!Array.isArray(x.flood.zones)||x.flood.zones.length>30)return null;if(!num(x.qibla.bearingDeg,0,359.999)||!num(x.qibla.toleranceDeg,0,90)||!["unknown","indicative","cross-checked","surveyed-override"].includes(x.qibla.mode)||!text(x.qibla.methodRef,1000)||!text(x.qibla.reviewerRole,160)||!text(x.terrain.datumLabel,160)||!text(x.terrain.sourceRef,1000)||!date(x.terrain.observedAt)||!num(x.flood.finishedFloorLevelM,-100,10000)||!num(x.flood.freeboardInputM,0,20)||!text(x.flood.sourceRef,1000))return null;for(const p of x.terrain.points)if(!text(p.id,100)||!num(p.xM,0,500)||!num(p.zM,0,500)||!num(p.elevationM,-100,10000)||!text(p.sourceRef,1000))return null;for(const z of x.flood.zones)if(!text(z.id,100)||!text(z.label,160)||![z.xM,z.zM,z.widthM,z.depthM].every(v=>num(v,0,500))||!num(z.waterDepthM,0,100)||!num(z.designLevelM,-100,10000)||!text(z.sourceRef,1000)||!date(z.observedAt)||!["unknown","screening","source-backed"].includes(z.confidence))return null;return x}
