export const SOLAR_DESIGN_SCHEMA="mosque.build/solar-design@1" as const;
export type ReviewState="not-assessed"|"needs-evidence"|"ready-for-review";
export type RoofZone={id:string;label:string;areaM2:number;usablePercent:number;shadePercent:number;orientationDeg:number;tiltDeg:number;state:ReviewState;structureRef:string;notes:string};
export type SolarDesign={schema:typeof SOLAR_DESIGN_SCHEMA;status:"executable";updatedAt:string;annualDemandKwh:number;criticalDailyKwh:number;peakCriticalKw:number;pvKw:number;batteryNominalKwh:number;batteryUsablePercent:number;solarResourceHours:number;systemLossPercent:number;modulePowerW:number;moduleAreaM2:number;resourceRef:string;resourceObservedAt:string;loadEvidenceRef:string;tariffRef:string;interconnectionRef:string;ownerRole:string;roofZones:RoofZone[];checks:Record<string,ReviewState>;notes:string};
export const checkGroups=[
 {group:"Evidence",items:["Twelve-month electricity baseline","Peak and interval load evidence","User-entered solar resource source","Tariff and export terms","Future load and efficiency plan"]},
 {group:"Roof + site",items:["Measured roof geometry","Structural capacity and condition","Drainage and waterproofing","Fire access and setbacks","Shade and horizon survey","Wind, snow and seismic actions","Safe maintenance access","Lightning and earthing context"]},
 {group:"Electrical",items:["Single-line concept","Utility interconnection route","Inverter operating mode","Protection and isolation","Cable routes and voltage drop","Metering and monitoring","Surge and lightning protection","Emergency shutdown labeling"]},
 {group:"Storage + resilience",items:["Critical-load register","Required outage duration","Battery location and separation","Fire detection and response","Ventilation and thermal conditions","Island-mode transfer strategy","Black-start and restart procedure","End-of-life and incident plan"]},
 {group:"Delivery + care",items:["Installer competence evidence","Product certificates and warranties","Procurement substitutions process","Commissioning test plan","As-built and handover records","Cleaning and inspection plan","Performance review baseline","Decommissioning and recycling plan"]},
] as const;
export const solarSources=[
 {label:"NREL — PVWatts Calculator",url:"https://pvwatts.nrel.gov/",observedAt:"2026-09-09",use:"Use an accountable location-specific result for preliminary grid-connected PV production; do not copy defaults invisibly.",rights:"Linked public tool; no source data reproduced."},
 {label:"World Bank — Global Solar Atlas",url:"https://www.worldbank.org/en/topic/energy/publication/solar-photovoltaic-power-potential-by-country",observedAt:"2026-09-09",use:"Use for preliminary resource context and retain the dataset, resolution, date and license with any value entered here.",rights:"Original mosque.build guidance; linked source not reproduced."},
 {label:"U.S. DOE — Solar and Resilience Basics",url:"https://www.energy.gov/cmei/systems/solar-and-resilience-basics",observedAt:"2026-09-09",use:"Solar alone should not be presented as outage power; verify inverter, storage, switching and protection design.",rights:"Original mosque.build summary; linked public guidance not reproduced."},
 {label:"U.S. DOE — Severe Weather Resilience in Solar PV Design",url:"https://www.energy.gov/cmei/femp/severe-weather-resilience-solar-photovoltaic-system-design",observedAt:"2026-09-09",use:"Carry site hazards into racking, attachments, wiring, drainage, access and inspection requirements.",rights:"Original mosque.build summary; linked public guidance not reproduced."},
] as const;
export function blankSolarDesign():SolarDesign{return{schema:SOLAR_DESIGN_SCHEMA,status:"executable",updatedAt:new Date(0).toISOString(),annualDemandKwh:0,criticalDailyKwh:0,peakCriticalKw:0,pvKw:0,batteryNominalKwh:0,batteryUsablePercent:80,solarResourceHours:0,systemLossPercent:14,modulePowerW:0,moduleAreaM2:0,resourceRef:"",resourceObservedAt:"",loadEvidenceRef:"",tariffRef:"",interconnectionRef:"",ownerRole:"",roofZones:[{id:"zone-a",label:"Roof zone A",areaM2:0,usablePercent:70,shadePercent:0,orientationDeg:0,tiltDeg:0,state:"not-assessed",structureRef:"",notes:""}],checks:{},notes:""}}
const finite=(value:unknown,min:number,max:number)=>typeof value==="number"&&Number.isFinite(value)?Math.min(max,Math.max(min,value)):min;
export function safeSolarDesign(value:unknown):SolarDesign{const base=blankSolarDesign();if(!value||typeof value!=="object")return base;const x=value as Partial<SolarDesign>;return{...base,...x,schema:SOLAR_DESIGN_SCHEMA,status:"executable",annualDemandKwh:finite(x.annualDemandKwh,0,10_000_000),criticalDailyKwh:finite(x.criticalDailyKwh,0,100_000),peakCriticalKw:finite(x.peakCriticalKw,0,100_000),pvKw:finite(x.pvKw,0,100_000),batteryNominalKwh:finite(x.batteryNominalKwh,0,1_000_000),batteryUsablePercent:finite(x.batteryUsablePercent,1,100),solarResourceHours:finite(x.solarResourceHours,0,12),systemLossPercent:finite(x.systemLossPercent,0,99),modulePowerW:finite(x.modulePowerW,0,2000),moduleAreaM2:finite(x.moduleAreaM2,0,20),roofZones:Array.isArray(x.roofZones)?x.roofZones.slice(0,20).map((z,i)=>({...base.roofZones[0],...z,id:typeof z.id==="string"?z.id:`zone-${i+1}`,areaM2:finite(z.areaM2,0,1_000_000),usablePercent:finite(z.usablePercent,0,100),shadePercent:finite(z.shadePercent,0,100),orientationDeg:finite(z.orientationDeg,0,359),tiltDeg:finite(z.tiltDeg,0,90)})):base.roofZones,checks:x.checks&&typeof x.checks==="object"?x.checks:{}}}
export function solarSummary(s:SolarDesign){const grossAnnual=s.pvKw*s.solarResourceHours*365,netAnnual=grossAnnual*(1-s.systemLossPercent/100),demandCoverage=s.annualDemandKwh>0?netAnnual/s.annualDemandKwh*100:0,moduleCount=s.modulePowerW>0?Math.ceil(s.pvKw*1000/s.modulePowerW):0,arrayArea=moduleCount*s.moduleAreaM2,usableRoof=s.roofZones.reduce((sum,z)=>sum+z.areaM2*z.usablePercent/100*(1-z.shadePercent/100),0),usableBattery=s.batteryNominalKwh*s.batteryUsablePercent/100,averageCriticalKw=s.criticalDailyKwh/24,staticBackupHours=averageCriticalKw>0?usableBattery/averageCriticalKw:0;return{grossAnnual,netAnnual,demandCoverage,moduleCount,arrayArea,usableRoof,roofGap:Math.max(0,arrayArea-usableRoof),usableBattery,staticBackupHours}}
export function solarGaps(s:SolarDesign){const gaps:string[]=[];if(!s.loadEvidenceRef)gaps.push("load evidence");if(!s.resourceRef||!s.resourceObservedAt||!s.solarResourceHours)gaps.push("dated solar resource evidence");if(!s.pvKw||!s.modulePowerW||!s.moduleAreaM2)gaps.push("PV and module assumptions");if(!s.roofZones.some(z=>z.areaM2&&z.structureRef))gaps.push("measured roof and structure reference");if(!s.ownerRole)gaps.push("accountable owner role");if(s.batteryNominalKwh&&!s.criticalDailyKwh)gaps.push("critical-load evidence");return gaps}
