import raw from"../data/waqf-books.json" with{type:"json"};
export const WAQF_CATALOG_SCHEMA="mosque.build/waqf-acquisition-catalog@1" as const;
export type WaqfBook={id:string;title:string;author_or_compiler:string;language:string;shelf_category:string;school_of_thought_or_madhhab:string;aqidah_orientation_or_tradition:string;contains_transliteration:boolean;priority_tier:string;recommended_copies_for_waqf_library:number;authenticity_basis:string;publisher_or_edition_family:string|null;official_or_publisher_url:string|null;purchase_links:{amazon_search:string;abebooks_search:string};curation_notes:string};
export type WaqfCatalog={catalog_name:string;version:string;curation_date:string;scope_note:string;theology_note:string;quran_note:string;purchase_link_policy:string;languages_included:string[];books:WaqfBook[]};
export const waqfCatalog=raw as WaqfCatalog;
export const catalogProvenance={source:"User-supplied acquisition catalog",sourceLabel:"waqf_library_100_authentic_sunni_books_multilingual.json",observedAt:waqfCatalog.curation_date,rights:"Metadata reuse rights not supplied; verify before redistribution",confidence:"unreviewed",reviewStatus:"scholarly-review-required"} as const;
export type WaqfCatalogBook=WaqfBook&{provenance:typeof catalogProvenance};
export const waqfBooks:WaqfCatalogBook[]=waqfCatalog.books.map(book=>({...book,provenance:catalogProvenance}));
export const catalogFacets={languages:[...new Set(waqfBooks.map(book=>book.language))].sort(),categories:[...new Set(waqfBooks.map(book=>book.shelf_category))].sort(),priorities:[...new Set(waqfBooks.map(book=>book.priority_tier))].sort(),madhhabs:[...new Set(waqfBooks.map(book=>book.school_of_thought_or_madhhab))].sort(),traditions:[...new Set(waqfBooks.map(book=>book.aqidah_orientation_or_tradition))].sort()};
export function normalizeCatalogText(value:unknown){return String(value??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}]+/gu," ").trim().toLocaleLowerCase()}
export function bookSearchText(book:WaqfBook){return normalizeCatalogText([book.id,book.title,book.author_or_compiler,book.language,book.shelf_category,book.school_of_thought_or_madhhab,book.aqidah_orientation_or_tradition,book.publisher_or_edition_family,book.authenticity_basis,book.curation_notes].filter(Boolean).join(" "))}
export function bookMatchesQuery(book:WaqfBook,query:string){const terms=normalizeCatalogText(query).split(" ").filter(Boolean);const haystack=bookSearchText(book);return terms.every(term=>haystack.includes(term))}
export function safeBookIds(value:unknown,max=100){return Array.isArray(value)?[...new Set(value.filter((id):id is string=>typeof id==="string"&&waqfBooks.some(book=>book.id===id)))].slice(0,max):[]}
export function catalogSummary(books:WaqfBook[]){return{titles:books.length,copies:books.reduce((sum,book)=>sum+book.recommended_copies_for_waqf_library,0),languages:new Set(books.map(book=>book.language)).size,categories:new Set(books.map(book=>book.shelf_category)).size}}
export function safeCatalogUrl(value:unknown){if(typeof value!=="string")return null;try{const url=new URL(value);return url.protocol==="https:"?url.toString():null}catch{return null}}
export type CatalogQualityFlag="edition-reference-missing"|"publisher-link-missing"|"curation-note-missing"|"rights-unverified"|"scholarly-review-required";
export function catalogQualityFlags(book:WaqfCatalogBook):CatalogQualityFlag[]{const flags:CatalogQualityFlag[]=[];if(!book.publisher_or_edition_family?.trim())flags.push("edition-reference-missing");if(!safeCatalogUrl(book.official_or_publisher_url))flags.push("publisher-link-missing");if(!book.curation_notes.trim())flags.push("curation-note-missing");if(book.provenance.rights.includes("not supplied"))flags.push("rights-unverified");if(book.provenance.reviewStatus==="scholarly-review-required")flags.push("scholarly-review-required");return flags}
export function groupCatalogBy(books:WaqfCatalogBook[],field:"language"|"shelf_category"|"priority_tier"){return [...books.reduce((map,book)=>map.set(book[field],(map.get(book[field])??0)+1),new Map<string,number>())].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label))}
export function createAcquisitionBrief(ids:unknown){const selected=new Set(safeBookIds(ids));return{schema:"mosque.build/waqf-acquisition-brief@1",createdAt:new Date().toISOString(),status:"concept" as const,reviewStatus:"scholarly-review-required" as const,notice:"Acquisition candidates only. Verify the exact work, edition, ISBN, translator/editor, publisher, rights, seller, price, condition, availability and suitability before acquisition.",items:waqfBooks.filter(book=>selected.has(book.id)).map(book=>({id:book.id,title:book.title,authorOrCompiler:book.author_or_compiler,language:book.language,subject:book.shelf_category,workingCopies:book.recommended_copies_for_waqf_library,editionFamily:book.publisher_or_edition_family,source:book.official_or_publisher_url,qualityFlags:catalogQualityFlags(book)}))}}
