export const WORKFLOW_INTEGRATION_SCHEMA="mosque.build/workflow-integration@1" as const;
export const workflowStages=["Define","Understand","Design","Approve + resource","Build","Open + care"] as const;
export type WorkflowNode={id:string;label:string;description:string;stage:typeof workflowStages[number];key:string;href:string;dependencies:string[];reviewGate:"community"|"professional"|"authority"|"project-team"};
export type WorkflowSignal={id:string;state:"no-record"|"started"|"developed";updatedAt:string;recordCount:number;stale:boolean;dependencyGaps:string[]};
export const workflowNodes:WorkflowNode[]=[
 {id:"brief",label:"Project brief",description:"Needs, constraints, decision roles and project foundation.",stage:"Define",key:"mosque-build.project-draft.v2",href:"/start",dependencies:[],reviewGate:"community"},
 {id:"controls",label:"Project controls",description:"Scenario, responsibility and control assumptions.",stage:"Define",key:"mosque-build.control-center.v1",href:"/my-project",dependencies:["brief"],reviewGate:"project-team"},
 {id:"siteAnalysis",label:"Site due diligence",description:"Anonymous candidate evidence and investigation gaps.",stage:"Understand",key:"mosque-build.site-analysis.v1",href:"/design",dependencies:["brief"],reviewGate:"professional"},
 {id:"campusPlanning",label:"Campus movement and programme",description:"Coordinate pedestrian zones, roads, parking, courtyards, recreation, school, daycare and madrasa spaces.",stage:"Design",key:"mosque-build.campus-planning.v1",href:"/design#campus-title",dependencies:["siteAnalysis","roomProgram"],reviewGate:"professional"},
 {id:"communityNeeds",label:"Community needs study",description:"Aggregate service-area evidence, uncertainty, anonymous survey summaries and programme demand without individual records.",stage:"Define",key:"mosque-build.community-needs.v1",href:"/design#community-needs-title",dependencies:["brief"],reviewGate:"community"},
 {id:"siteContextAnalysis",label:"Site context overlays",description:"Qibla uncertainty, anonymous terrain samples and sourced flood-level comparisons.",stage:"Understand",key:"mosque-build.site-context-analysis.v1",href:"/design",dependencies:["brief","siteAnalysis"],reviewGate:"professional"},
 {id:"climate",label:"Climate resilience",description:"Hazard scenarios and evidence questions.",stage:"Understand",key:"mosque-build.climate-resilience.v1",href:"/design",dependencies:["siteAnalysis"],reviewGate:"professional"},
 {id:"solar",label:"Solar design",description:"Demand, resource, roof, resilience and delivery evidence.",stage:"Design",key:"mosque-build.solar-design.v1",href:"/design",dependencies:["siteAnalysis","climate"],reviewGate:"professional"},
 {id:"prayerDaylight",label:"Prayer-time daylight study",description:"Entered prayer-moment sun angles, conceptual shadows and source-review gaps.",stage:"Design",key:"mosque-build.prayer-daylight.v1",href:"/design#prayer-daylight",dependencies:["siteAnalysis","schematic"],reviewGate:"professional"},
 {id:"prayerOccupancy",label:"Prayer row and occupancy study",description:"Entered congregation, accessible positions, alignment guides, movement and spatial-volume prompts.",stage:"Design",key:"mosque-build.prayer-occupancy.v1",href:"/design#prayer-occupancy",dependencies:["schematic","roomProgram"],reviewGate:"community"},
 {id:"qiblaWallPerformance",label:"Qibla wall performance",description:"Coordinate mihrab, minbar, daylight, speech, access, content, material and maintenance questions.",stage:"Design",key:"mosque-build.qibla-wall-performance.v1",href:"/design#qibla-studio-title",dependencies:["schematic","prayerDaylight","prayerOccupancy","interior"],reviewGate:"professional"},
 {id:"energyScenario",label:"Energy scenarios",description:"Monthly evidence, mosque loads and PV/storage option comparisons.",stage:"Design",key:"mosque-build.energy-scenario.v1",href:"/design",dependencies:["solar"],reviewGate:"professional"},
 {id:"permit",label:"Approval pathway",description:"Likely applicable requirements and authority sources.",stage:"Approve + resource",key:"mosque-build.permits-pathway.v1",href:"/permits",dependencies:["brief","siteAnalysis"],reviewGate:"authority"},
 {id:"designIntelligence",label:"Design strategy",description:"Worship, community and phased planning direction.",stage:"Design",key:"mosque-build.masjid-intelligence.v1",href:"/design",dependencies:["brief"],reviewGate:"community"},
 {id:"architectureFeaturePlan",label:"Architecture feature plan",description:"Prioritized, owned and evidence-linked delivery plan for the 100-feature architecture backlog.",stage:"Design",key:"mosque-build.architecture-feature-plan.v1",href:"/design",dependencies:["brief","siteAnalysis"],reviewGate:"professional"},
 {id:"designTemplate",label:"Constraint-led design template",description:"Editable lineage studies compared against project, site, climate, affordability, delivery and craft inputs.",stage:"Design",key:"mosque-build.design-template.v1",href:"/design#template-title",dependencies:["brief"],reviewGate:"community"},
 {id:"patternModel",label:"Editable pattern study",description:"Place source-linked patterns, adjust their scale and surface, and record authorship and cultural review.",stage:"Design",key:"mosque-build.pattern-model.v1",href:"/patterns#pattern-model-title",dependencies:["brief","islamicArchitectureFramework"],reviewGate:"community"},
 {id:"islamicGeometry",label:"Geometry construction study",description:"Original non-calligraphic repeat geometry with symmetry, crossings, vector exchange and cultural-review boundaries.",stage:"Design",key:"mosque-build.islamic-geometry.v1",href:"/patterns#geometry-studio-title",dependencies:["brief","islamicArchitectureFramework"],reviewGate:"community"},
 {id:"architectureKit",label:"Mosque element library",description:"Compare domes, minarets, arcades, prayer-space guides, purification areas and accessible routes in the 3D view.",stage:"Design",key:"mosque-build.architecture-kit.v1",href:"/design#architecture-kit-title",dependencies:["brief","schematic"],reviewGate:"professional"},
 {id:"islamicArchitectureFramework",label:"Architecture framework",description:"Community-authored worship, climate, care, craft and precedent decisions with explicit evidence and review gates.",stage:"Design",key:"mosque-build.islamic-architecture-framework.v1",href:"/patterns#architecture-framework-title",dependencies:["brief","siteAnalysis","designIntelligence"],reviewGate:"community"},
 {id:"schematic",label:"Schematic plan",description:"Provisional footprint, qibla and room geometry.",stage:"Design",key:"mosque-build.schematic-plan.v1",href:"/design",dependencies:["siteAnalysis","designIntelligence"],reviewGate:"professional"},
 {id:"modelAuthoring",label:"Drawing and model setup",description:"Set grids, coordinates, named views, design options and working dimensions for the project.",stage:"Design",key:"mosque-build.model-authoring.v1",href:"/design#authoring-title",dependencies:["schematic"],reviewGate:"professional"},
 {id:"floorPlan",label:"Detailed floor plan",description:"Levels, spaces, openings, relationships and checks.",stage:"Design",key:"mosque-build.floor-plan.v1",href:"/design",dependencies:["schematic"],reviewGate:"professional"},
 {id:"structuralFoundation",label:"Structure and foundations",description:"Ground evidence, foundation options, grids, load paths, hazards, temporary works and inspection holds.",stage:"Design",key:"mosque-build.structural-foundation.v1",href:"/design",dependencies:["siteAnalysis","floorPlan"],reviewGate:"professional"},
 {id:"openingDesign",label:"Doors and gates",description:"Room-linked openings, clear passage, hardware, safety, performance, evidence and handoff.",stage:"Design",key:"mosque-build.opening-design.v1",href:"/design",dependencies:["floorPlan"],reviewGate:"professional"},
 {id:"buildingSystems",label:"Building systems",description:"Room-linked water, drainage, ventilation, electrical, fire, data and rainwater coordination.",stage:"Design",key:"mosque-build.building-systems.v1",href:"/design",dependencies:["floorPlan","solar"],reviewGate:"professional"},
 {id:"roofDesign",label:"Roof and dome design",description:"Roof form, assembly, wind zones, drainage, climate, solar and construction coordination.",stage:"Design",key:"mosque-build.roof-design.v1",href:"/design",dependencies:["floorPlan","solar","buildingSystems"],reviewGate:"professional"},
 {id:"roomProgram",label:"Room program",description:"Purpose, accessibility and adjacency requirements.",stage:"Design",key:"mosque-build.room-program.v1",href:"/design",dependencies:["schematic"],reviewGate:"community"},
 {id:"interior",label:"Interior study",description:"Prayer rows, floors, transitions and quantities.",stage:"Design",key:"mosque-build.interior-study.v1",href:"/design",dependencies:["schematic","roomProgram"],reviewGate:"professional"},
 {id:"interiorSystems",label:"Interior systems",description:"Mosque-specific equipment, event modes, placement, storage, care and sourcing requirements.",stage:"Design",key:"mosque-build.interior-systems.v1",href:"/design#interior-systems",dependencies:["interior","roomProgram"],reviewGate:"professional"},
 {id:"materials",label:"Material decisions",description:"Evidence, samples, mockups and installation readiness.",stage:"Approve + resource",key:"mosque-build.material-selection.v1",href:"/construction",dependencies:["floorPlan","interior"],reviewGate:"professional"},
 {id:"regionalMaterialCost",label:"Regional material cost plan",description:"Quantity-linked local rates, source evidence, logistics, indices and low/base/high scenarios.",stage:"Approve + resource",key:"mosque-build.regional-material-cost.v1",href:"/construction",dependencies:["materials","schedule"],reviewGate:"professional"},
 {id:"landCost",label:"Land and site cost",description:"Normalized area, acquisition, usable envelope and abnormal site costs.",stage:"Understand",key:"mosque-build.land-cost-study.v1",href:"/design",dependencies:["siteAnalysis"],reviewGate:"professional"},
 {id:"costRules",label:"Cost-control rules",description:"Applicability, trade-offs, evidence and design coordination.",stage:"Design",key:"mosque-build.cost-saving-rules.v1",href:"/construction",dependencies:["brief","landCost"],reviewGate:"professional"},
 {id:"costControlIntegration",label:"Cost-control coordination",description:"Carry applicable strategies into design, quantity, procurement, schedule, construction and operations review.",stage:"Build",key:"mosque-build.cost-control-integration.v1",href:"/construction",dependencies:["costRules","regionalMaterialCost","procurement","schedule"],reviewGate:"professional"},
 {id:"costOptionComparison",label:"Baseline and alternative costs",description:"Compare selected same-currency entered cost lines with scope, source, date and review gaps visible.",stage:"Approve + resource",key:"mosque-build.cost-option-comparison.v1",href:"/construction",dependencies:["costRules","regionalMaterialCost"],reviewGate:"professional"},
 {id:"procurement",label:"Procurement",description:"Requirements, comparisons and landed-cost inputs.",stage:"Approve + resource",key:"mosque-build.procurement.v1",href:"/marketplace",dependencies:["materials","costRules"],reviewGate:"project-team"},
 {id:"projectIntegrity",label:"Integrity and value controls",description:"Role separation, competition, conflicts, capability evidence and explainable review signals.",stage:"Approve + resource",key:"mosque-build.project-integrity.v1",href:"/marketplace",dependencies:["brief","procurement"],reviewGate:"project-team"},
 {id:"funding",label:"Funding pathway",description:"Funding and waqf decisions with evidence boundaries.",stage:"Approve + resource",key:"mosque-build.funding-pathway.v1",href:"/funding",dependencies:["brief"],reviewGate:"project-team"},
 {id:"schedule",label:"Integrated schedule",description:"Dependencies, ownership, dates and evidence gates.",stage:"Build",key:"mosque-build.project-schedule.v1",href:"/construction",dependencies:["brief","permit","procurement"],reviewGate:"project-team"},
 {id:"constructionControls",label:"Construction controls",description:"Track site questions, product approvals, inspections, changes and risks.",stage:"Build",key:"mosque-build.construction-controls.v1",href:"/construction",dependencies:["schedule","materials","projectIntegrity"],reviewGate:"professional"},
 {id:"constructionDocumentControl",label:"Revision and review control",description:"Controlled revisions, issue purposes, review outcomes and distribution.",stage:"Build",key:"mosque-build.construction-document-control.v1",href:"/construction",dependencies:["constructionControls"],reviewGate:"professional"},
 {id:"constructionSequence",label:"Four-dimensional build coordination",description:"BIM element sequencing, activity mapping and evidence-based compliance gates.",stage:"Build",key:"mosque-build.construction-sequence.v1",href:"/construction",dependencies:["floorPlan","schedule","constructionControls","permit"],reviewGate:"authority"},
 {id:"assets",label:"Asset handover",description:"Commissioning, manuals, warranties and maintenance.",stage:"Open + care",key:"mosque-build.asset-register.v1",href:"/operations",dependencies:["constructionControls"],reviewGate:"professional"},
 {id:"workOrders",label:"Operations work orders",description:"Evidence-linked maintenance and issue closure.",stage:"Open + care",key:"mosque-build.work-orders.v1",href:"/operations",dependencies:["assets"],reviewGate:"project-team"},
 {id:"emergency",label:"Emergency continuity",description:"Disaster and utility-outage dependencies, operating states, stop conditions, accessible communications, drills and recovery records.",stage:"Open + care",key:"mosque-build.emergency-readiness.v1",href:"/operations#continuity-title",dependencies:["climate","brief","buildingSystems","energyScenario","openingDesign"],reviewGate:"project-team"}
];
function recordCount(value:unknown){if(Array.isArray(value))return value.length;if(!value||typeof value!=="object")return 1;const x=value as Record<string,unknown>;for(const key of["records","items","candidates","activities","assets","orders","spaces","requirements","updates"]){if(Array.isArray(x[key]))return x[key].length}return Object.keys(x).filter(k=>!["schema","schemaVersion","status","updatedAt"].includes(k)).length}
function dateOf(value:unknown){if(!value||typeof value!=="object")return"";const x=value as Record<string,unknown>;for(const key of["updatedAt","createdAt","observedAt"]){if(typeof x[key]==="string")return x[key]}return""}
export function deriveWorkflowSignals(read:(key:string)=>string|null,now=new Date()){const parsed=new Map<string,unknown>();for(const node of workflowNodes){const raw=read(node.key);if(!raw)continue;try{parsed.set(node.id,JSON.parse(raw))}catch{}}return workflowNodes.map(node=>{const value=parsed.get(node.id),count=value===undefined?0:recordCount(value),updatedAt=dateOf(value),age=updatedAt?now.getTime()-new Date(updatedAt).getTime():0,dependencyGaps=node.dependencies.filter(id=>!parsed.has(id));return{id:node.id,state:value===undefined?"no-record" as const:count>1?"developed" as const:"started" as const,updatedAt,recordCount:count,stale:!!updatedAt&&Number.isFinite(age)&&age>1000*60*60*24*90,dependencyGaps}})}
export function workflowSummary(signals:WorkflowSignal[]){return{started:signals.filter(x=>x.state!=="no-record").length,developed:signals.filter(x=>x.state==="developed").length,blocked:signals.filter(x=>x.dependencyGaps.length).length,stale:signals.filter(x=>x.stale).length,total:signals.length}}
export function nextWorkflowNodes(signals:WorkflowSignal[]){const byId=new Map(signals.map(x=>[x.id,x]));return workflowNodes.filter(n=>byId.get(n.id)?.state==="no-record"&&n.dependencies.every(id=>byId.get(id)?.state!=="no-record")).slice(0,4)}
