export const WORKFLOW_INTEGRATION_SCHEMA="mosque.build/workflow-integration@1" as const;
export const workflowStages=["Define","Understand","Design","Approve + resource","Build","Open + care"] as const;
export type WorkflowNode={id:string;label:string;description:string;stage:typeof workflowStages[number];key:string;href:string;dependencies:string[];reviewGate:"community"|"professional"|"authority"|"project-team"};
export type WorkflowSignal={id:string;state:"no-record"|"started"|"developed";updatedAt:string;recordCount:number;stale:boolean;dependencyGaps:string[]};
export const workflowNodes:WorkflowNode[]=[
 {id:"brief",label:"Project brief",description:"Needs, constraints, decision roles and project foundation.",stage:"Define",key:"mosque-build.project-draft.v2",href:"/start",dependencies:[],reviewGate:"community"},
 {id:"controls",label:"Project controls",description:"Scenario, responsibility and control assumptions.",stage:"Define",key:"mosque-build.control-center.v1",href:"/my-project",dependencies:["brief"],reviewGate:"project-team"},
 {id:"siteAnalysis",label:"Site due diligence",description:"Anonymous candidate evidence and investigation gaps.",stage:"Understand",key:"mosque-build.site-analysis.v1",href:"/design",dependencies:["brief"],reviewGate:"professional"},
 {id:"climate",label:"Climate resilience",description:"Hazard scenarios and evidence questions.",stage:"Understand",key:"mosque-build.climate-resilience.v1",href:"/design",dependencies:["siteAnalysis"],reviewGate:"professional"},
 {id:"solar",label:"Solar design",description:"Demand, resource, roof, resilience and delivery evidence.",stage:"Design",key:"mosque-build.solar-design.v1",href:"/design",dependencies:["siteAnalysis","climate"],reviewGate:"professional"},
 {id:"energyScenario",label:"Energy scenarios",description:"Monthly evidence, mosque loads and PV/storage option comparisons.",stage:"Design",key:"mosque-build.energy-scenario.v1",href:"/design",dependencies:["solar"],reviewGate:"professional"},
 {id:"permit",label:"Approval pathway",description:"Likely applicable requirements and authority sources.",stage:"Approve + resource",key:"mosque-build.permits-pathway.v1",href:"/permits",dependencies:["brief","siteAnalysis"],reviewGate:"authority"},
 {id:"designIntelligence",label:"Design strategy",description:"Worship, community and phased planning direction.",stage:"Design",key:"mosque-build.masjid-intelligence.v1",href:"/design",dependencies:["brief"],reviewGate:"community"},
 {id:"schematic",label:"Schematic plan",description:"Provisional footprint, qibla and room geometry.",stage:"Design",key:"mosque-build.schematic-plan.v1",href:"/design",dependencies:["siteAnalysis","designIntelligence"],reviewGate:"professional"},
 {id:"floorPlan",label:"Detailed floor plan",description:"Levels, spaces, openings, relationships and checks.",stage:"Design",key:"mosque-build.floor-plan.v1",href:"/design",dependencies:["schematic"],reviewGate:"professional"},
 {id:"roomProgram",label:"Room program",description:"Purpose, accessibility and adjacency requirements.",stage:"Design",key:"mosque-build.room-program.v1",href:"/design",dependencies:["schematic"],reviewGate:"community"},
 {id:"interior",label:"Interior study",description:"Prayer rows, floors, transitions and quantities.",stage:"Design",key:"mosque-build.interior-study.v1",href:"/design",dependencies:["schematic","roomProgram"],reviewGate:"professional"},
 {id:"materials",label:"Material decisions",description:"Evidence, samples, mockups and installation readiness.",stage:"Approve + resource",key:"mosque-build.material-selection.v1",href:"/construction",dependencies:["floorPlan","interior"],reviewGate:"professional"},
 {id:"procurement",label:"Procurement",description:"Requirements, comparisons and landed-cost inputs.",stage:"Approve + resource",key:"mosque-build.procurement.v1",href:"/marketplace",dependencies:["materials"],reviewGate:"project-team"},
 {id:"funding",label:"Funding pathway",description:"Funding and waqf decisions with evidence boundaries.",stage:"Approve + resource",key:"mosque-build.funding-pathway.v1",href:"/funding",dependencies:["brief"],reviewGate:"project-team"},
 {id:"schedule",label:"Integrated schedule",description:"Dependencies, ownership, dates and evidence gates.",stage:"Build",key:"mosque-build.project-schedule.v1",href:"/construction",dependencies:["brief","permit","procurement"],reviewGate:"project-team"},
 {id:"constructionControls",label:"Construction controls",description:"RFIs, submittals, inspections, changes and risks.",stage:"Build",key:"mosque-build.construction-controls.v1",href:"/construction",dependencies:["schedule","materials"],reviewGate:"professional"},
 {id:"constructionDocumentControl",label:"Revision and review control",description:"Controlled revisions, issue purposes, review outcomes and distribution.",stage:"Build",key:"mosque-build.construction-document-control.v1",href:"/construction",dependencies:["constructionControls"],reviewGate:"professional"},
 {id:"assets",label:"Asset handover",description:"Commissioning, manuals, warranties and maintenance.",stage:"Open + care",key:"mosque-build.asset-register.v1",href:"/operations",dependencies:["constructionControls"],reviewGate:"professional"},
 {id:"workOrders",label:"Operations work orders",description:"Evidence-linked maintenance and issue closure.",stage:"Open + care",key:"mosque-build.work-orders.v1",href:"/operations",dependencies:["assets"],reviewGate:"project-team"},
 {id:"emergency",label:"Emergency readiness",description:"Climate response, drills and recovery records.",stage:"Open + care",key:"mosque-build.emergency-readiness.v1",href:"/operations",dependencies:["climate","brief"],reviewGate:"project-team"}
];
function recordCount(value:unknown){if(Array.isArray(value))return value.length;if(!value||typeof value!=="object")return 1;const x=value as Record<string,unknown>;for(const key of["records","items","candidates","activities","assets","orders","spaces","requirements","updates"]){if(Array.isArray(x[key]))return x[key].length}return Object.keys(x).filter(k=>!["schema","schemaVersion","status","updatedAt"].includes(k)).length}
function dateOf(value:unknown){if(!value||typeof value!=="object")return"";const x=value as Record<string,unknown>;for(const key of["updatedAt","createdAt","observedAt"]){if(typeof x[key]==="string")return x[key]}return""}
export function deriveWorkflowSignals(read:(key:string)=>string|null,now=new Date()){const parsed=new Map<string,unknown>();for(const node of workflowNodes){const raw=read(node.key);if(!raw)continue;try{parsed.set(node.id,JSON.parse(raw))}catch{}}return workflowNodes.map(node=>{const value=parsed.get(node.id),count=value===undefined?0:recordCount(value),updatedAt=dateOf(value),age=updatedAt?now.getTime()-new Date(updatedAt).getTime():0,dependencyGaps=node.dependencies.filter(id=>!parsed.has(id));return{id:node.id,state:value===undefined?"no-record" as const:count>1?"developed" as const:"started" as const,updatedAt,recordCount:count,stale:!!updatedAt&&Number.isFinite(age)&&age>1000*60*60*24*90,dependencyGaps}})}
export function workflowSummary(signals:WorkflowSignal[]){return{started:signals.filter(x=>x.state!=="no-record").length,developed:signals.filter(x=>x.state==="developed").length,blocked:signals.filter(x=>x.dependencyGaps.length).length,stale:signals.filter(x=>x.stale).length,total:signals.length}}
export function nextWorkflowNodes(signals:WorkflowSignal[]){const byId=new Map(signals.map(x=>[x.id,x]));return workflowNodes.filter(n=>byId.get(n.id)?.state==="no-record"&&n.dependencies.every(id=>byId.get(id)?.state!=="no-record")).slice(0,4)}
