export const WUDU_PLAN_SCHEMA="mosque.build/wudu-plan@1";
export type Review="not-assessed"|"needs-review"|"reviewed-user-record";
export type Check={id:string;group:"journey"|"technical"|"operations";title:string;prompt:string;status:Review;ownerRole:string;evidenceRef:string;notes:string};
export type WuduPlan={schema:string;updatedAt:string;brief:{peakUsers:number;peakWindow:number;useShare:number;minutesPerUse:number;standardPositions:number;accessiblePositions:number;areaM2:number;waterPerUseL:number;outageMinutes:number;review:Review};layout:{entranceSide:string;wetDryTransition:boolean;accessibleRoute:boolean;privacyScreen:boolean;cleaningStore:boolean;plantAccess:boolean;notes:string};checks:Check[]};
const seeds:Array<[Check["group"],string,string]>=[
["journey","Arrival to wudu","Trace a step-free, legible route from relevant entrances without vehicle or wet-floor conflicts."],["journey","Shoes and wet/dry threshold","Test storage, queues and mobility aids without narrowing the continuous accessible route."],["journey","Choice and dignity","Provide equitable choices without isolating accessible positions."],["journey","Accessible transfer and reach","Review approach, clearances, supports, controls, stability and assistance preferences with disabled users."],["journey","Exit to prayer","Trace a dry route to integrated prayer positions without bottlenecks or backtracking."],
["technical","Supply and simultaneous demand","Define a peak-use scenario, pressure, temperature, isolation and accountable plumbing calculation."],["technical","Drainage and falls","Coordinate outlets, channels, gradients, traps, cleanouts and downstream capacity without barriers."],["technical","Waterproofing continuity","Detail substrates, upstands, corners, penetrations, joints, thresholds and a recorded test."],["technical","Slip and surface evidence","Verify wet-use slip evidence, barefoot comfort, contrast, cleanability and chemical compatibility."],["technical","Ventilation and moisture","Review extract, make-up air, condensation, odour, drying time, controls and access."],["technical","Lighting and electrical safety","Review glare, shadow, emergency lighting, controls and electrical separation."],
["operations","Cleaning without closure","Plan safe cleaning zones, storage, signage and an accessible alternative during closure."],["operations","Inspection and maintenance","Assign checks for leaks, supports, sealants, traps, valves, finishes and ventilation."],["operations","Water interruption mode","Document dignified accessible alternatives for outage, scarcity or contamination."],["operations","Commissioning and user trial","Test peak flow, drainage, splash, temperature, accessibility and cleaning with users and reviewers."]];
export const createWuduPlan=():WuduPlan=>({schema:WUDU_PLAN_SCHEMA,updatedAt:new Date(0).toISOString(),brief:{peakUsers:0,peakWindow:20,useShare:60,minutesPerUse:4,standardPositions:0,accessiblePositions:0,areaM2:0,waterPerUseL:0,outageMinutes:0,review:"not-assessed"},layout:{entranceSide:"north",wetDryTransition:false,accessibleRoute:false,privacyScreen:false,cleaningStore:false,plantAccess:false,notes:""},checks:seeds.map(([group,title,prompt],i)=>({id:`wudu-${group}-${i+1}`,group,title,prompt,status:"not-assessed",ownerRole:"",evidenceRef:"",notes:""}))});
const n=(v:unknown,min:number,max:number,fallback:number)=>typeof v==="number"&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):fallback;
export function safeWuduPlan(value:unknown){if(!value||typeof value!=="object"||(value as WuduPlan).schema!==WUDU_PLAN_SCHEMA)return null;const base=createWuduPlan(),v=value as WuduPlan,b=v.brief||base.brief,incoming=new Map(Array.isArray(v.checks)?v.checks.map(x=>[x.id,x]):[]);return {...base,...v,brief:{...base.brief,...b,peakUsers:n(b.peakUsers,0,100000,0),peakWindow:n(b.peakWindow,1,1440,20),useShare:n(b.useShare,0,100,60),minutesPerUse:n(b.minutesPerUse,.5,60,4),standardPositions:n(b.standardPositions,0,10000,0),accessiblePositions:n(b.accessiblePositions,0,10000,0),areaM2:n(b.areaM2,0,100000,0),waterPerUseL:n(b.waterPerUseL,0,1000,0),outageMinutes:n(b.outageMinutes,0,100000,0)},layout:{...base.layout,...v.layout},checks:base.checks.map(x=>({...x,...incoming.get(x.id),id:x.id,group:x.group,title:x.title,prompt:x.prompt}))} as WuduPlan}
export function wuduDemand(b:WuduPlan["brief"]){const users=Math.ceil(b.peakUsers*b.useShare/100),positionPrompt=Math.ceil(users*b.minutesPerUse/b.peakWindow),provided=b.standardPositions+b.accessiblePositions;return {users,positionPrompt,provided,gap:Math.max(0,positionPrompt-provided),surplus:Math.max(0,provided-positionPrompt),waterPromptL:b.waterPerUseL?Math.round(users*b.waterPerUseL):null}}
export function wuduCoverage(p:WuduPlan){const reviewed=p.checks.filter(x=>x.status==="reviewed-user-record").length,evidenced=p.checks.filter(x=>x.evidenceRef.trim()).length,owned=p.checks.filter(x=>x.ownerRole.trim()).length,layout=Object.values(p.layout).filter(x=>x===true).length;return {reviewed,evidenced,owned,layout,percent:Math.round((reviewed+evidenced+owned+layout)/(p.checks.length*3+5)*100)}}
