"use client";
import {useState} from "react";

const views=[
  {id:"design",label:"Design",title:"Compare prayer-hall options",metric:"3 options",action:"Review room relationships",choices:["Community courtyard","Compact urban","Phased campus"],impact:"Capacity · access · cost implications"},
  {id:"permits",label:"Permits",title:"Prepare the approval pathway",metric:"Sources needed",action:"Choose a jurisdiction",choices:["Planning context","Building review","Fire and occupancy"],impact:"Likely requirements · verify with authority"},
  {id:"budget",label:"Budget",title:"Balance the working plan",metric:"100% assigned",action:"Review assumptions",choices:["Site and design","Construction","Opening and reserve"],impact:"Currency · date · source · confidence"},
  {id:"build",label:"Build",title:"Keep delivery evidence together",metric:"6 phases",action:"Record a site update",choices:["Progress evidence","Questions and changes","Handover records"],impact:"Owner · date · evidence · review"}
] as const;

export function HeroWorkspacePreview(){
  const [active,setActive]=useState(0);const [choice,setChoice]=useState(0);const view=views[active];
  const selectView=(index:number)=>{setActive(index);setChoice(0)};
  return <div className="heroVisual"><div className="heroGlow"/><div className="browserCard interactiveHeroDemo"><div className="browserBar"><i/><i/><i/><span>My Mosque · Project workspace</span></div><div className="mockShell"><aside><b>mosque.build</b><span>Overview</span>{views.map((item,index)=><button type="button" className={index===active?"active":""} aria-pressed={index===active} onClick={()=>selectView(index)} key={item.id}>{item.label}</button>)}</aside><section><div className="mockTop"><div><small>COMMUNITY PROJECT</small><h3>{view.title}</h3></div><button type="button" onClick={()=>setChoice(value=>(value+1)%view.choices.length)}>{view.action}</button></div><div className="mockMetrics"><div><small>Current view</small><strong>{view.label}</strong></div><div><small>Working state</small><strong>{view.metric}</strong></div><div><small>Selected</small><strong>{view.choices[choice]}</strong></div></div><div className="mockCanvas"><div className={`floor heroPlan heroPlan-${view.id}`} aria-label={`${view.label} project diagram`}><div className="qiblaLine"/><div className="rows"/><div className="roomTag">{view.choices[choice]}</div><span className="planBlock pb1"/><span className="planBlock pb2"/><span className="planBlock pb3"/></div><div className="mockPanel"><small>{view.label.toUpperCase()} OPTIONS</small><h4>Choose what to explore</h4>{view.choices.map((item,index)=><button type="button" className={`choice${choice===index?" activeChoice":""}`} aria-pressed={choice===index} onClick={()=>setChoice(index)} key={item}>{item}<b>{choice===index?"Selected":"Compare"}</b></button>)}<div className="impact">{view.impact}</div></div></div></section></div></div><div className="floatCard fc1"><small>NEXT ACTION</small><b>{view.action}</b><span>Your project stays connected</span></div><div className="floatCard fc2"><small>TRY THE PREVIEW</small><b>Choose a stage or option</b><span>Keyboard · touch · mouse</span></div></div>;
}
