"use client";
import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import{deriveWorkflowSignals,nextWorkflowNodes,workflowNodes,workflowStages,workflowSummary,type WorkflowSignal}from"@/lib/workflow-integration";
import"./hero-workspace-preview.css";

const statusLabel={"no-record":"Not started",started:"Started",developed:"Developed"}as const;

export function HeroWorkspacePreview(){
 const[stage,setStage]=useState<(typeof workflowStages)[number]>("Design"),[signals,setSignals]=useState<WorkflowSignal[]>(()=>workflowNodes.map(node=>({id:node.id,state:"no-record",updatedAt:"",recordCount:0,stale:false,dependencyGaps:node.dependencies})));
 useEffect(()=>{const refresh=()=>setSignals(deriveWorkflowSignals(key=>localStorage.getItem(key)));refresh();addEventListener("mosque-build:project-change",refresh);return()=>removeEventListener("mosque-build:project-change",refresh)},[]);
 const summary=useMemo(()=>workflowSummary(signals),[signals]),signalById=new Map(signals.map(signal=>[signal.id,signal])),visible=workflowNodes.filter(node=>node.stage===stage),next=nextWorkflowNodes(signals)[0];
 return <section className="liveWorkspace" aria-labelledby="live-workspace-title"><header><div><small>YOUR PRIVATE PROJECT</small><h3 id="live-workspace-title">See the whole journey</h3></div><Link href="/my-project">Open my project</Link></header><div className="liveMetrics" aria-label="Project progress summary"><div><strong>{summary.started}</strong><span>steps started</span></div><div><strong>{summary.developed}</strong><span>steps with detail</span></div><div><strong>{summary.blocked}</strong><span>missing earlier steps</span></div></div><nav aria-label="Project stages">{workflowStages.map(item=><button type="button" key={item} aria-pressed={stage===item} onClick={()=>setStage(item)}>{item}</button>)}</nav><div className="liveModuleList">{visible.map(node=>{const signal=signalById.get(node.id);return <article key={node.id} data-state={signal?.state}><div><small>{node.reviewGate} review</small><h4>{node.label}</h4><p>{node.description}</p></div><div className="liveModuleState"><span>{statusLabel[signal?.state??"no-record"]}</span>{signal?.dependencyGaps.length?<small>{signal.dependencyGaps.length} earlier step{signal.dependencyGaps.length===1?"":"s"} needed</small>:<small>Ready to continue</small>}<Link href={node.href}>{signal?.state==="no-record"?"Start":"Continue"}</Link></div></article>})}</div><footer><div><small>A USEFUL NEXT STEP</small><b>{next?.label??"Review your project"}</b></div><Link href={next?.href??"/my-project"}>{next?"Start next step":"Review project"}</Link></footer><p className="liveBoundary">Progress reflects work saved in this browser. It does not mean a step is complete, compliant, approved or professionally reviewed.</p></section>;
}
