"use client";
import{useEffect,useState}from"react";
import{ELEMENT_COST_KEY,elementCostGaps,elementCostTotals,formatEstimate,safeElementCosts}from"@/lib/element-cost-estimate";
import{costSummary,safeCostPlan}from"@/lib/regional-material-cost";

type Snapshot={label:string;detail:string;ready:boolean};
const empty:Snapshot={label:"Estimate not set",detail:"Add measured quantities and sourced rates in the planner.",ready:false};
function readSnapshot():Snapshot{try{const raw=localStorage.getItem("mosque-build.regional-material-cost.v1");if(raw){const plan=safeCostPlan(JSON.parse(raw));if(plan){const summary=costSummary(plan),entries=Object.entries(summary.base).filter(([,value])=>value>0);if(entries.length===1){const [currency,total]=entries[0];return{label:formatEstimate(total,currency),detail:`Project working estimate · ${summary.priced}/${summary.lines} lines priced · ${summary.blockers} evidence blockers`,ready:summary.blockers===0}}if(entries.length>1)return{label:`${entries.length} currencies`,detail:"Review currencies separately; no exchange rate is inferred.",ready:false}}}const items=Object.values(safeElementCosts(JSON.parse(localStorage.getItem(ELEMENT_COST_KEY)||"{}"))).filter(item=>elementCostGaps(item).length===0);if(!items.length)return empty;const currencies=[...new Set(items.map(item=>item.currency.toUpperCase()))];if(currencies.length!==1)return{label:`${currencies.length} currencies`,detail:`${items.length} element estimates saved; no conversion is inferred.`,ready:false};const total=items.reduce((sum,item)=>sum+elementCostTotals(item).base,0);return{label:formatEstimate(total,currencies[0]),detail:`${items.length} sourced element estimate${items.length===1?"":"s"} · user-entered planning basis`,ready:true}}catch{return empty}}
export function HeroCostSummary(){const[snapshot,setSnapshot]=useState<Snapshot>(empty);useEffect(()=>{const refresh=()=>setSnapshot(readSnapshot());refresh();addEventListener("storage",refresh);addEventListener("mosque-build-cost-update",refresh);return()=>{removeEventListener("storage",refresh);removeEventListener("mosque-build-cost-update",refresh)}},[]);return <aside className="heroCostSummary" data-ready={snapshot.ready}><span>Cost check</span><strong>{snapshot.label}</strong><small>{snapshot.detail}</small><a href="/construction#regional-cost-title">Open cost planner</a></aside>}
