"use client";
import {useEffect,useRef,useState} from "react";import "./hero-build-timelapse.css";
const stages=[
 {id:"site",label:"Site",detail:"Context, qibla, access and risk"},
 {id:"foundation",label:"Foundations",detail:"Ground, grid and load-path concept"},
 {id:"structure",label:"Structure",detail:"Columns, beams and prayer-hall span"},
 {id:"enclosure",label:"Enclosure",detail:"Walls, openings and climate layers"},
 {id:"roof",label:"Roof + dome",detail:"Weather, drainage and skyline"},
 {id:"interior",label:"Interior",detail:"Prayer rows, wudu and inclusive space"},
 {id:"commission",label:"Commission",detail:"Systems, evidence and handover"},
 {id:"care",label:"Open + care",detail:"Landscape, assets and maintenance"}
] as const;
type Api={stage:(value:number)=>void;view:()=>void;dispose:()=>void};
export function HeroBuildTimelapse(){const host=useRef<HTMLDivElement>(null),api=useRef<Api|null>(null),[stage,setStage]=useState(0),[playing,setPlaying]=useState(false),[status,setStatus]=useState("Loading the 3D build sequence…");useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;setPlaying(!reduced);let dead=false;void(async()=>{try{const T=await import("three");if(dead||!host.current)return;const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0x000000,0);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute("aria-label","Conceptual mosque construction sequence in three dimensions");host.current.replaceChildren(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,300);camera.position.set(28,21,32);const root=new T.Group();root.rotation.y=-.45;scene.add(root,new T.HemisphereLight(0xfff6df,0x18372f,2.2));const sun=new T.DirectionalLight(0xffe4a8,3);sun.position.set(-12,26,14);scene.add(sun);const groups=stages.map(()=>new T.Group());groups.forEach(g=>root.add(g));const mat=(color:number,opacity=1)=>new T.MeshStandardMaterial({color,roughness:.72,metalness:.02,transparent:opacity<1,opacity}),box=(g:import("three").Group,size:[number,number,number],pos:[number,number,number],color:number,opacity=1)=>{const m=new T.Mesh(new T.BoxGeometry(...size),mat(color,opacity));m.position.set(...pos);g.add(m);return m},cylinder=(g:import("three").Group,rt:number,rb:number,h:number,pos:[number,number,number],color:number,segments=24)=>{const m=new T.Mesh(new T.CylinderGeometry(rt,rb,h,segments),mat(color));m.position.set(...pos);g.add(m);return m};
 // Site and orientation
 box(groups[0],[28,.35,23],[0,-.35,0],0xbcae8d);box(groups[0],[4,.12,17],[-11,-.1,0],0xd6b263);const q=new T.Mesh(new T.BoxGeometry(.16,.08,12),mat(0xf1cc78));q.position.set(0,.05,-1);q.rotation.y=-.17;groups[0].add(q);
 // Footings and slab
 for(const x of[-8,-4,0,4,8])for(const z of[-7,0,7])box(groups[1],[1.4,.7,1.4],[x,.1,z],0x93815d);box(groups[1],[19,.35,15],[0,.48,0],0xc6bda8);
 // Frame
 for(const x of[-8,-4,0,4,8])for(const z of[-7,7])cylinder(groups[2],.28,.34,7,[x,4,z],0xd8c8a6,12);for(const z of[-7,7])box(groups[2],[18,.38,.38],[0,7.4,z],0xbda985);for(const x of[-8,8])box(groups[2],[.38,.38,14],[x,7.4,0],0xbda985);
 // Walls and arch openings
 box(groups[3],[19,5,.45],[0,3,-7],0xe4d6b8);box(groups[3],[.45,5,14],[-9.5,3,0],0xd8c8a6);box(groups[3],[.45,5,14],[9.5,3,0],0xd8c8a6);box(groups[3],[6,5,.45],[-6.5,3,7],0xe4d6b8);box(groups[3],[6,5,.45],[6.5,3,7],0xe4d6b8);box(groups[3],[2,1.1,.45],[0,5.1,7],0xe4d6b8);
 // Roof, dome and minaret
 box(groups[4],[19.7,.45,14.7],[0,7.7,0],0x315f53);const dome=new T.Mesh(new T.SphereGeometry(4,32,18,0,Math.PI*2,0,Math.PI/2),mat(0xd2aa58));dome.position.set(0,7.8,0);groups[4].add(dome);cylinder(groups[4],.65,.9,11,[8.2,6.1,-5.5],0xd8c8a6,20);const cap=new T.Mesh(new T.ConeGeometry(1,2.4,20),mat(0xd2aa58));cap.position.set(8.2,12.8,-5.5);groups[4].add(cap);
 // Interior rows, qibla wall and wudu bank
 for(let z=-5;z<=4;z+=1.25)box(groups[5],[15,.035,.055],[0,.72,z],0xe7c877);box(groups[5],[4,2,.18],[0,2,-6.7],0x956d3f);for(let x=-7;x<=-3;x+=1)cylinder(groups[5],.16,.2,.7,[x,1,5.8],0x78a89b,12);
 // Systems and commissioning indicators
 for(const x of[-6,-2,2,6]){const lamp=new T.Mesh(new T.SphereGeometry(.16,12,8),mat(0xffdb76));lamp.position.set(x,6.7,0);groups[6].add(lamp)}box(groups[6],[3,.3,2],[5.7,8.15,1],0x315c88);box(groups[6],[3,.3,2],[2.3,8.15,1],0x315c88);
 // Landscape and operational care
 for(const [x,z] of[[-11,-8],[-11,8],[11,-8],[11,8]] as [number,number][]){cylinder(groups[7],.13,.18,2.2,[x,.9,z],0x715a39,10);const crown=new T.Mesh(new T.SphereGeometry(1.1,12,8),mat(0x4f8261));crown.position.set(x,2.5,z);groups[7].add(crown)}box(groups[7],[1.5,.08,1],[6,.05,8.5],0xd2aa58);
 const apply=(value:number)=>groups.forEach((g,i)=>{g.visible=i<=value});apply(0);const resize=()=>{if(!host.current)return;renderer.setSize(host.current.clientWidth,host.current.clientHeight,false);camera.aspect=host.current.clientWidth/Math.max(1,host.current.clientHeight);camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host.current);resize();let frame=0,last=performance.now();const animate=(time:number)=>{frame=requestAnimationFrame(animate);if(!reduced)root.rotation.y+=Math.min(.0025,(time-last)/20000);last=time;renderer.render(scene,camera)};animate(last);api.current={stage:value=>{apply(value);renderer.render(scene,camera)},view:()=>{root.rotation.y=-.45;camera.position.set(28,21,32);camera.lookAt(0,4,0)},dispose:()=>{cancelAnimationFrame(frame);observer.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const m=o.material as import("three").Material;m.dispose()}});renderer.dispose()}};camera.lookAt(0,4,0);setStatus("Interactive mosque build sequence ready")}catch(error){setStatus(error instanceof Error?`3D preview unavailable: ${error.message}`:"3D preview unavailable")}})();return()=>{dead=true;api.current?.dispose()}},[]);useEffect(()=>{api.current?.stage(stage)},[stage]);useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStage(value=>(value+1)%stages.length),1650);return()=>clearInterval(timer)},[playing]);const choose=(value:number)=>{setStage(value);setPlaying(false)};return <div className="buildTimelapse"><div className="buildViewport"><div className="buildTop"><span><i/> Mosque build sequence</span><b>{String(stage+1).padStart(2,"0")} / {String(stages.length).padStart(2,"0")}</b></div><div ref={host} className="buildCanvas"/><div className="buildCaption"><small>NOW BUILDING</small><strong>{stages[stage].label}</strong><span>{stages[stage].detail}</span></div><p className="srOnly" role="status" aria-live="polite">{status}. Stage {stage+1}: {stages[stage].label}. {stages[stage].detail}.</p></div><div className="buildControls"><div><button type="button" onClick={()=>setPlaying(value=>!value)} aria-pressed={playing}>{playing?"Pause":"Play"} sequence</button><button type="button" onClick={()=>api.current?.view()}>Reset view</button></div><label>Construction stage<input type="range" min="0" max={stages.length-1} value={stage} onChange={e=>choose(Number(e.target.value))}/></label><ol>{stages.map((item,index)=><li key={item.id}><button type="button" aria-current={stage===index?"step":undefined} onClick={()=>choose(index)}><span>{String(index+1).padStart(2,"0")}</span>{item.label}</button></li>)}</ol></div><p className="buildBoundary">Illustrative sequence—not construction instructions, certified progress or a buildable model.</p></div>}
