"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {createGeometryWorkspace,generateIslamicGeometry,geometryFamilies,geometryOrders,geometryToSvg,GEOMETRY_STORAGE_KEY,safeGeometryWorkspace,symmetryGroups,type GeometryParameters,type GeometryWorkspace} from "@/lib/islamic-geometry-engine";
import "./islamic-geometry-studio.css";

const pretty=(s:string)=>s.replaceAll("-"," ");
const download=(name:string,data:string,type:string)=>{const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)};

export function IslamicGeometryStudio(){
  const [workspace,setWorkspace]=useState<GeometryWorkspace>(()=>createGeometryWorkspace()),[ready,setReady]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{try{const saved=safeGeometryWorkspace(JSON.parse(localStorage.getItem(GEOMETRY_STORAGE_KEY)||"null"));if(saved)setWorkspace(saved)}catch{}setReady(true)},[]);
  const result=useMemo(()=>generateIslamicGeometry(workspace.parameters),[workspace.parameters]);
  const commit=(next:GeometryWorkspace,text="Geometry study saved on this device.")=>{const value={...next,updatedAt:new Date().toISOString()};setWorkspace(value);try{localStorage.setItem(GEOMETRY_STORAGE_KEY,JSON.stringify(value));dispatchEvent(new Event("mosque-build:project-change"));setMessage(text)}catch{setMessage("This browser could not save the geometry study.")}};
  const update=(patch:Partial<GeometryParameters>)=>commit({...workspace,parameters:{...workspace.parameters,...patch}});
  const updateMeta=(patch:Partial<GeometryWorkspace>)=>commit({...workspace,...patch});
  if(!ready)return <section className="geometryStudio" role="status">Preparing geometry tools…</section>;
  return <section className="geometryStudio" aria-labelledby="geometry-studio-title">
    <header><div><span className="eyebrow dark">GEOMETRY LABORATORY</span><h2 id="geometry-studio-title">Construct a repeat from first principles.</h2><p>Build an original non-calligraphic study, inspect its repeat cell and crossings, then carry a clearly bounded vector into design review.</p></div><div className="geometryScore" aria-label="Geometry summary"><b>{result.metrics.segmentCount}</b><span>segments</span><small>{result.metrics.crossingCount} crossings · ~{result.metrics.estimatedOpenAreaPercent}% open</small></div></header>
    <div className="geometryLayout"><aside className="geometryControls" aria-label="Geometry parameters">
      <label>Construction family<select value={workspace.parameters.family} onChange={e=>update({family:e.target.value as GeometryParameters["family"]})}>{geometryFamilies.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></label>
      <label>Symmetry study<select value={workspace.parameters.symmetry} onChange={e=>update({symmetry:e.target.value as GeometryParameters["symmetry"]})}>{symmetryGroups.map(x=><option key={x} value={x}>{x}</option>)}</select></label>
      <label>Rotational order<select value={workspace.parameters.order} onChange={e=>update({order:Number(e.target.value) as GeometryParameters["order"]})}>{geometryOrders.map(x=><option key={x} value={x}>{x}-fold</option>)}</select></label>
      <label>Concentric rings <output>{workspace.parameters.rings}</output><input type="range" min="1" max="6" value={workspace.parameters.rings} onChange={e=>update({rings:Number(e.target.value)})}/></label>
      <label>Inner radius <output>{workspace.parameters.innerRatio.toFixed(2)}</output><input type="range" min=".2" max=".8" step=".01" value={workspace.parameters.innerRatio} onChange={e=>update({innerRatio:Number(e.target.value)})}/></label>
      <div className="geometrySplit"><label>Columns<input type="number" min="1" max="10" value={workspace.parameters.repeatX} onChange={e=>update({repeatX:Number(e.target.value)})}/></label><label>Rows<input type="number" min="1" max="10" value={workspace.parameters.repeatY} onChange={e=>update({repeatY:Number(e.target.value)})}/></label></div>
      <label>Strap width <output>{Math.round(workspace.parameters.strapWidthM*1000)} mm</output><input type="range" min=".002" max=".08" step=".002" value={workspace.parameters.strapWidthM} onChange={e=>update({strapWidthM:Number(e.target.value)})}/></label>
      <div className="geometrySplit"><label>Panel width (m)<input type="number" min=".2" max="30" step=".1" value={workspace.parameters.panelWidthM} onChange={e=>update({panelWidthM:Number(e.target.value)})}/></label><label>Height (m)<input type="number" min=".2" max="20" step=".1" value={workspace.parameters.panelHeightM} onChange={e=>update({panelHeightM:Number(e.target.value)})}/></label></div>
      <label>Panel boundary<select value={workspace.parameters.clip} onChange={e=>update({clip:e.target.value as GeometryParameters["clip"]})}><option value="rectangle">Rectangle</option><option value="circle">Circle / medallion</option></select></label>
      <label className="geometryCheck"><input type="checkbox" checked={workspace.parameters.interlace} onChange={e=>update({interlace:e.target.checked})}/> Inspect over-under crossings</label>
    </aside><div className="geometryWork"><GeometryCanvas workspace={workspace}/><dl className="geometryMetrics"><div><dt>Repeat cell</dt><dd>{result.repeatCell.widthM.toFixed(2)} × {result.repeatCell.heightM.toFixed(2)} m</dd></div><div><dt>Shortest segment</dt><dd>{result.metrics.shortestSegmentM.toFixed(3)} m</dd></div><div><dt>Detail mode</dt><dd>{result.metrics.segmentCount>900?"Simplify for mobile":"Vector"}</dd></div></dl></div></div>
    <section className="geometryReview" aria-labelledby="geometry-review-title"><div><h3 id="geometry-review-title">Validation and handoff</h3>{result.validation.length?<ul>{result.validation.map(x=><li key={x.code} data-level={x.level}><b>{x.level}</b> {x.message}</li>)}</ul>:<p className="geometryPass">No immediate geometric warnings. Professional and fabrication review are still required.</p>}</div><div className="geometryMeta"><label>Study name<input maxLength={160} value={workspace.name} onChange={e=>updateMeta({name:e.target.value})}/></label><label>Source or design basis<input maxLength={1000} value={workspace.sourceBasis} onChange={e=>updateMeta({sourceBasis:e.target.value})}/></label><label>Author role<input maxLength={200} value={workspace.authorRole} onChange={e=>updateMeta({authorRole:e.target.value})}/></label><label>Cultural/application reviewer role<input maxLength={200} value={workspace.reviewRole} onChange={e=>updateMeta({reviewRole:e.target.value})}/></label></div></section>
    <div className="geometryActions"><button type="button" onClick={()=>download("mosque-build-geometric-study.svg",geometryToSvg(result,workspace.name),"image/svg+xml")}>Export bounded SVG</button><button type="button" onClick={()=>download("mosque-build-geometric-study.json",JSON.stringify({...workspace,result},null,2),"application/json")}>Export geometry JSON</button><button type="button" className="quiet" onClick={()=>{const fresh=createGeometryWorkspace();commit(fresh,"Parameters reset to the original study defaults.")}}>Reset parameters</button></div>
    <p className="geometryMessage" role="status" aria-live="polite">{message}</p><footer><b>Responsible-use boundary</b><p>{result.boundary} Symmetry labels describe mathematical operations only. They do not assert regional, dynastic or religious provenance.</p></footer>
  </section>
}

function GeometryCanvas({workspace}:{workspace:GeometryWorkspace}){
  const result=useMemo(()=>generateIslamicGeometry(workspace.parameters),[workspace.parameters]),svg=useMemo(()=>geometryToSvg(result,workspace.name),[result,workspace.name]),host=useRef<HTMLDivElement>(null),[mode,setMode]=useState<"vector"|"relief">("vector");
  useEffect(()=>{if(mode!=="relief"||!host.current)return;let stopped=false,dispose=()=>{};void(async()=>{const T=await import("three"),{OrbitControls}=await import("three/examples/jsm/controls/OrbitControls.js");if(stopped||!host.current)return;const renderer=new T.WebGLRenderer({antialias:true,powerPreference:"low-power"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor(0xeee9da);host.current.replaceChildren(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute("aria-label","Interactive relief view of the generated geometric study");const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100),controls=new OrbitControls(camera,renderer.domElement),group=new T.Group(),positions:number[]=[];result.segments.forEach(s=>positions.push((s.from[0])*workspace.parameters.panelWidthM,(s.from[1])*workspace.parameters.panelHeightM,.03,(s.to[0])*workspace.parameters.panelWidthM,(s.to[1])*workspace.parameters.panelHeightM,.03));const geometry=new T.BufferGeometry();geometry.setAttribute("position",new T.Float32BufferAttribute(positions,3));const lines=new T.LineSegments(geometry,new T.LineBasicMaterial({color:0x0a5749})),panel=new T.Mesh(new T.BoxGeometry(workspace.parameters.panelWidthM,workspace.parameters.panelHeightM,.08),new T.MeshStandardMaterial({color:0xe9dfc7,roughness:.82}));group.add(panel,lines);scene.add(group,new T.HemisphereLight(0xffffff,0x345d54,2.7));camera.position.set(0,workspace.parameters.panelHeightM*.25,Math.max(workspace.parameters.panelWidthM,workspace.parameters.panelHeightM)*1.5);controls.enableDamping=!matchMedia("(prefers-reduced-motion: reduce)").matches;const resize=()=>{if(!host.current)return;renderer.setSize(host.current.clientWidth,host.current.clientHeight,false);camera.aspect=host.current.clientWidth/Math.max(1,host.current.clientHeight);camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host.current);resize();let frame=0;const draw=()=>{frame=requestAnimationFrame(draw);controls.update();renderer.render(scene,camera)};draw();dispose=()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();geometry.dispose();(lines.material as import("three").Material).dispose();panel.geometry.dispose();panel.material.dispose();renderer.dispose();renderer.domElement.remove()}})();return()=>{stopped=true;dispose()}},[mode,result,workspace.parameters.panelHeightM,workspace.parameters.panelWidthM]);
  return <section className="geometryCanvas"><header><div><small>LIVE CONSTRUCTION</small><h3>{pretty(workspace.parameters.family)}</h3></div><div role="group" aria-label="Preview mode"><button type="button" aria-pressed={mode==="vector"} onClick={()=>setMode("vector")}>Vector</button><button type="button" aria-pressed={mode==="relief"} onClick={()=>setMode("relief")}>Relief</button></div></header>{mode==="vector"?<div className="geometrySvg" dangerouslySetInnerHTML={{__html:svg}}/>:<div className="geometryThree" ref={host}/>}<p>Drag the relief view to orbit. The preview batches all linework into one geometry; exported SVG remains the editable interchange layer.</p></section>
}
