"use client";

import {useEffect,useMemo,useState} from "react";
import lineages from "@/data/architecture-lineages.json";
import {architectureChecks,architectureLenses,architecturePrompts,architectureSources,architectureSummary,createIslamicArchitectureState,newArchitectureOption,safeIslamicArchitectureState,type ArchitectureOption,type ArchitectureResponse,type IslamicArchitectureState,type Lens} from "@/lib/islamic-architecture-framework";
import "./islamic-architecture-framework.css";

const storageKey="mosque-build.islamic-architecture-framework.v1";
const states:ArchitectureResponse["state"][]=["not-started","question-framed","evidence-linked","ready-for-review","reviewed-user-record"];
const label=(value:string)=>value.replaceAll("-"," ").replace(/^./,x=>x.toUpperCase());

export function IslamicArchitectureFramework(){
 const[state,setState]=useState<IslamicArchitectureState>(createIslamicArchitectureState),[tab,setTab]=useState<"principles"|"options"|"review"|"sources">("principles"),[lens,setLens]=useState<"all"|Lens>("all"),[query,setQuery]=useState(""),[activeId,setActiveId]=useState(architecturePrompts[0].id),[activeOptionId,setActiveOptionId]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{try{const saved=safeIslamicArchitectureState(JSON.parse(localStorage.getItem(storageKey)||"null"));if(saved)setState(saved)}catch{}},[]);
 const filtered=useMemo(()=>architecturePrompts.filter(p=>(lens==="all"||p.lens===lens)&&(p.title+" "+p.question+" "+p.why+" "+p.test).toLowerCase().includes(query.toLowerCase())),[lens,query]);
 const active=architecturePrompts.find(p=>p.id===activeId)??filtered[0]??architecturePrompts[0],response=state.responses.find(r=>r.promptId===active.id)!;
 const option=state.options.find(o=>o.id===activeOptionId)??state.options[0],summary=architectureSummary(state),checks=architectureChecks(state);
 const patchState=(next:Partial<IslamicArchitectureState>)=>setState(current=>({...current,...next,updatedAt:new Date().toISOString()}));
 const patchResponse=(next:Partial<ArchitectureResponse>)=>patchState({responses:state.responses.map(r=>r.promptId===active.id?{...r,...next}:r)});
 const patchOption=(next:Partial<ArchitectureOption>)=>{if(!option)return;patchState({options:state.options.map(o=>o.id===option.id?{...o,...next}:o)})};
 const persist=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state));dispatchEvent(new Event("mosque-build:project-change"));setMessage("Architecture framework saved to this project on this device.")}catch{setMessage("This browser could not save the framework.")}};
 const exportJson=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...state,checks,summary,boundary:"Project-authored design reasoning, not an authenticity finding, religious ruling, engineered design or professional approval."},null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="mosque-build-islamic-architecture-framework.json";a.click();URL.revokeObjectURL(url);setMessage("Architecture framework exported with evidence and review boundaries.")};
 const addOption=()=>{const next=newArchitectureOption(state.options.length+1);patchState({options:[...state.options,next]});setActiveOptionId(next.id);setTab("options")};
 const togglePrinciple=(id:string)=>patchOption({principleIds:option?.principleIds.includes(id)?option.principleIds.filter(x=>x!==id):[...(option?.principleIds??[]),id]});
 const toggleLineage=(id:string)=>patchOption({lineageIds:option?.lineageIds.includes(id)?option.lineageIds.filter(x=>x!==id):[...(option?.lineageIds??[]),id]});
 return <section className="architectureFramework" aria-labelledby="architecture-framework-title">
  <header><div><span className="eyebrow">PROJECT ARCHITECTURE</span><h2 id="architecture-framework-title">Translate lineage into accountable design.</h2><p>Frame worship, climate, care, structure and craft decisions; compare options; record evidence; and route each decision to the right reviewer.</p></div><div className="architecturePulse"><b>{summary.started}/{summary.principles}</b><span>questions framed</span><small>{summary.blockers} blockers · {summary.options} options</small></div></header>
  <div className="architectureTabs" role="tablist" aria-label="Architecture framework views">{(["principles","options","review","sources"]as const).map(x=><button role="tab" aria-selected={tab===x} key={x} onClick={()=>setTab(x)}>{label(x)}</button>)}</div>
  {tab==="principles"&&<><div className="architectureFilters"><label>Search questions<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search shade, wudu, acoustics…"/></label><label>Design lens<select value={lens} onChange={e=>setLens(e.target.value as "all"|Lens)}><option value="all">All lenses</option>{architectureLenses.map(x=><option key={x}>{x}</option>)}</select></label><span aria-live="polite">{filtered.length} questions</span></div><div className="architectureQuestionLayout"><nav aria-label="Architecture questions">{filtered.map(p=>{const r=state.responses.find(x=>x.promptId===p.id)!;return <button key={p.id} aria-current={p.id===active.id?"true":undefined} onClick={()=>setActiveId(p.id)}><small>{p.lens} · {label(r.state)}</small><b>{p.title}</b></button>})}</nav><article className="architectureResponse"><span className="miniTag">{active.lens} · {active.reviewGate} review</span><h3>{active.title}</h3><p className="architectureQuestion">{active.question}</p><p>{active.why}</p><aside><b>Test in the project</b><p>{active.test}</p></aside><label>Working state<select value={response.state} onChange={e=>patchResponse({state:e.target.value as ArchitectureResponse["state"]})}>{states.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Project response<textarea rows={4} maxLength={1400} value={response.projectResponse} onChange={e=>patchResponse({projectResponse:e.target.value})} placeholder="Describe the spatial response and why it fits this community and place."/></label><div className="architectureFieldGrid"><label>Evidence or drawing reference<input maxLength={240} value={response.evidenceRef} onChange={e=>patchResponse({evidenceRef:e.target.value})} placeholder="Study, survey, drawing or source ID"/></label><label>Accountable owner role<input maxLength={120} value={response.ownerRole} onChange={e=>patchResponse({ownerRole:e.target.value})} placeholder="Role, not personal contact details"/></label><label>Model layer / element reference<input maxLength={160} value={response.modelLayerRef} onChange={e=>patchResponse({modelLayerRef:e.target.value})} placeholder="Optional renderer-neutral ID"/></label><label>Decision register reference<input maxLength={160} value={response.decisionRef} onChange={e=>patchResponse({decisionRef:e.target.value})} placeholder="Optional decision ID"/></label></div><label>Review record<textarea rows={2} maxLength={800} value={response.reviewNotes} onChange={e=>patchResponse({reviewNotes:e.target.value})} placeholder="Who reviewed what, when, and what remains open?"/></label><div className="architectureCaution"><b>Boundary</b><p>{active.caution}</p></div></article></div></>}
  {tab==="options"&&<><div className="optionToolbar"><div><h3>Compare complete architectural responses</h3><p>Options combine principles and precedents without claiming that resemblance proves suitability or authenticity.</p></div><button onClick={addOption}>+ Add option</button></div>{state.options.length?<div className="optionLayout"><nav aria-label="Architecture options">{state.options.map(o=><button key={o.id} aria-current={o.id===(option?.id)?"true":undefined} onClick={()=>setActiveOptionId(o.id)}><b>{o.label}</b><small>{label(o.status)} · {o.principleIds.length} principles</small></button>)}</nav>{option&&<article><div className="architectureFieldGrid"><label>Option name<input maxLength={100} value={option.label} onChange={e=>patchOption({label:e.target.value})}/></label><label>Status<select value={option.status} onChange={e=>patchOption({status:e.target.value as ArchitectureOption["status"]})}><option value="concept">Concept</option><option value="developed-user-record">Developed user record</option><option value="reviewed-user-record">Reviewed user record</option></select></label></div><fieldset><legend>Principles carried by this option</legend><div className="architectureChoices">{architecturePrompts.map(p=><label key={p.id}><input type="checkbox" checked={option.principleIds.includes(p.id)} onChange={()=>togglePrinciple(p.id)}/><span>{p.title}<small>{p.lens}</small></span></label>)}</div></fieldset><fieldset><legend>Precedents used as questions—not templates</legend><div className="architectureChoices compact">{lineages.map(x=><label key={x.id}><input type="checkbox" checked={option.lineageIds.includes(x.id)} onChange={()=>toggleLineage(x.id)}/><span>{x.title}<small>{x.region}</small></span></label>)}</div></fieldset>{([['siteResponse','Site + arrival response'],['spatialResponse','Worship + community spatial response'],['materialResponse','Structure, material + craft response'],['climateResponse','Climate, water, light + sound response'],['careResponse','Care, adaptation + operations response'],['tradeoffs','Trade-offs, exclusions + unresolved questions']]as const).map(([key,title])=><label key={key}>{title}<textarea rows={3} maxLength={1200} value={option[key]} onChange={e=>patchOption({[key]:e.target.value})}/></label>)}<button className="selectOption" aria-pressed={state.selectedOptionId===option.id} onClick={()=>patchState({selectedOptionId:state.selectedOptionId===option.id?"":option.id})}>{state.selectedOptionId===option.id?"Selected for development":"Select for development"}</button></article>}</div>:<div className="architectureEmpty"><h3>No project options yet</h3><p>Create an option to connect architectural principles, sourced precedents and project-specific trade-offs.</p><button onClick={addOption}>Create first option</button></div>}</>}
  {tab==="review"&&<><div className="architectureReviewGrid"><label>Project intent<textarea rows={3} maxLength={800} value={state.projectIntent} onChange={e=>patchState({projectIntent:e.target.value})} placeholder="What should this architecture enable and protect?"/></label><label>Community authorship record<textarea rows={3} maxLength={800} value={state.communityAuthorship} onChange={e=>patchState({communityAuthorship:e.target.value})} placeholder="Whose experiences shaped it, and how can they challenge it?"/></label><label>Religious review role<input maxLength={120} value={state.religiousReviewRole} onChange={e=>patchState({religiousReviewRole:e.target.value})}/></label><label>Local architect review role<input maxLength={120} value={state.architectReviewRole} onChange={e=>patchState({architectReviewRole:e.target.value})}/></label><label>Local craft / stewardship review role<input maxLength={120} value={state.localCraftReviewRole} onChange={e=>patchState({localCraftReviewRole:e.target.value})}/></label></div><div className="architectureMetrics">{Object.entries(summary).map(([k,v])=><span key={k}><b>{v}</b><small>{label(k)}</small></span>)}</div><div className="architectureChecks">{checks.length?checks.map(c=><article key={c.id} data-severity={c.severity}><small>{c.severity} · {c.group}</small><b>{c.label}</b><p>{c.detail}</p>{c.promptId&&<button onClick={()=>{setActiveId(c.promptId!);setTab("principles")}}>Open question</button>}</article>):<p>No current integrity checks. Professional and community review still remain required.</p>}</div></>}
  {tab==="sources"&&<><div className="sourceBoundary"><b>How to use sources</b><p>These references support questions about historical systems. They do not prove local suitability, authenticity, religious correctness, structural performance or approval. Individual Archnet record rights vary; no source imagery is reproduced here.</p></div><div className="architectureSources">{architectureSources.map(s=><article key={s.id}><small>{s.confidence} · observed {s.observedAt}</small><h3>{s.label}</h3><p>{s.rights}</p><a href={s.url} target="_blank" rel="noopener noreferrer">Read institutional source <span aria-hidden="true">↗</span></a></article>)}</div></>}
  <footer><div><b>Design and religious boundary</b><p>This workspace records project reasoning. It is not a religious ruling, authenticity certificate, technical design, code check or professional approval. Never use sacred calligraphy as generated decoration.</p></div><div><button onClick={persist}>Save framework</button><button className="secondary" onClick={exportJson}>Export record</button><p role="status" aria-live="polite">{message}</p></div></footer>
 </section>
}
