"use client";

import {useEffect,useMemo,useState} from "react";
import guides from "@/data/jurisdiction-guides.json";
import "./jurisdiction-workflow.css";

type Mode="permits"|"funding";type CheckState="not-reviewed"|"investigating"|"evidence-added"|"authority-confirmed";
type SavedState={selected:string;checks:Record<string,CheckState>;notes:Record<string,string>;updatedAt:string};
const labels:Record<CheckState,string>={"not-reviewed":"Not reviewed",investigating:"Investigating","evidence-added":"Evidence added","authority-confirmed":"Authority confirmed by project team"};
const empty:SavedState={selected:"",checks:{},notes:{},updatedAt:""};

function Flag({code,country}:{code:string;country:string}){return <img className="inlineFlag" src={`/flags/${code.toLowerCase()}.svg`} alt={`${country} flag`} width="36" height="24"/>}
const itemKey=(record:string,title:string)=>`${record}:${title}`;

export function JurisdictionExplorer({mode}:{mode:Mode}){
  const data=guides[mode],storageKey=`mosque-build.${mode}-pathway.v1`,[state,setState]=useState<SavedState>(empty),[ready,setReady]=useState(false),[query,setQuery]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem(storageKey)||"null");if(stored&&typeof stored==="object")setState({...empty,...stored,checks:stored.checks||{},notes:stored.notes||{}})}catch{}setReady(true)},[storageKey]);
  const selected=state.selected&&data.some(item=>item.id===state.selected)?state.selected:data[0].id,current=data.find(item=>item.id===selected)??data[0];
  const filtered=useMemo(()=>data.filter(item=>`${item.country} ${item.region}`.toLowerCase().includes(query.toLowerCase().trim())),[data,query]),options=query.trim()?[current,...filtered.filter(item=>item.id!==current.id)]:data;
  const persist=(patch:Partial<SavedState>)=>{const next={...state,...patch,updatedAt:new Date().toISOString()};setState(next);try{localStorage.setItem(storageKey,JSON.stringify(next));dispatchEvent(new Event("mosque-build:project-change"))}catch{setMessage("This browser could not save the pathway. Export your work before leaving.")}};
  const setCheck=(key:string,value:CheckState)=>{persist({checks:{...state.checks,[key]:value}});setMessage(value==="authority-confirmed"?"Recorded as project-team supplied confirmation; mosque.build has not verified it.":"Pathway progress saved on this device.")};
  const exportPathway=()=>{const payload={schemaVersion:`mosque.build/${mode}-pathway@1`,status:"executable",exportedAt:new Date().toISOString(),jurisdiction:{id:current.id,country:current.country,region:current.region,observedAt:current.observedAt,confidence:current.confidence,rights:current.rights},items:current.items.map(item=>{const key=itemKey(current.id,item.title);return {...item,projectState:state.checks[key]||"not-reviewed",projectNote:state.notes[key]||""}}),boundary:"Project-team working record only. States and notes are not authority decisions, legal advice, permit approval or a complete requirements list."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=`mosque-build-${mode}-${current.id}.json`;link.click();URL.revokeObjectURL(url);setMessage("Source-preserving pathway exported.")};
  if(!ready)return <div className="jurisdictionExplorer" role="status">Preparing jurisdiction pathways…</div>;
  const reviewed=current.items.filter(item=>(state.checks[itemKey(current.id,item.title)]||"not-reviewed")!=="not-reviewed").length;
  return <div className="jurisdictionExplorer"><div className="jurisdictionSelect"><label htmlFor={`${mode}-search`}>Find a country or jurisdiction</label><input id={`${mode}-search`} type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search available pathways"/><label htmlFor={`${mode}-jurisdiction`}>Choose a country and jurisdiction</label><div><Flag code={current.flag} country={current.country}/><select id={`${mode}-jurisdiction`} value={selected} onChange={event=>{persist({selected:event.target.value});setMessage("Jurisdiction saved for this pathway.")}}>{options.map(item=><option key={item.id} value={item.id}>{item.country} — {item.region}</option>)}</select></div>{filtered.length===0?<p role="status">No available jurisdiction matches “{query}”. Clear the search to see all {data.length} pathways.</p>:<p>{data.length} jurisdictions · {current.items.length} sourced starting points · reviewed {current.observedAt} · {current.confidence.replace("_"," ")}</p>}</div><section className="jurisdictionResult" aria-live="polite" aria-atomic="false"><header><Flag code={current.flag} country={current.country}/><div><small>{current.country}</small><h2>{current.region}</h2><p>{current.summary}</p></div><div className="pathwayProgress"><b>{reviewed}/{current.items.length}</b><span>reviewed</span><button type="button" onClick={exportPathway}>Export pathway</button></div></header><div className="requirementGrid">{current.items.map((item,index)=>{const key=itemKey(current.id,item.title),value=state.checks[key]||"not-reviewed";return <article key={item.title} data-state={value}><span>{String(index+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.when}</p><label>Project review state<select value={value} onChange={event=>setCheck(key,event.target.value as CheckState)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Evidence or question<textarea rows={3} value={state.notes[key]||""} onChange={event=>persist({notes:{...state.notes,[key]:event.target.value}})} placeholder="Reference, responsible role, open question or authority response"/></label><dl><div><dt>Verify with</dt><dd>{item.authority}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div></dl><a href={item.url} target={item.url.startsWith("http")?"_blank":undefined} rel={item.url.startsWith("http")?"noopener noreferrer":undefined}>View source {item.url.startsWith("http")?"↗":"→"}</a></article>})}</div>{message?<p className="builderMessage" role="status" aria-live="polite">{message}</p>:null}<aside><b>Decision boundary</b><p>These requirements are likely applicable starting points, not approvals or a complete legal checklist. “Authority confirmed” is a project-team record, not verification by mosque.build. Confirm current scope, site, thresholds and submission route with the named authority and qualified local professionals.</p><small>Reuse note: {current.rights}</small></aside></section></div>;
}
