import Link from"next/link";
import{HeroWorkspacePreview}from"./hero-workspace-preview";
import{LandingFeatureThree,type LandingScene}from"./landing-feature-three";
import"./landing-product-showcase.css";
const examples:{number:string;title:string;body:string;facts:string[];href:string;scene:LandingScene}[]=[
 {number:"01",title:"Understand the site",body:"Bring qibla direction, terrain, flood risk, access and unanswered questions into one clear site study.",facts:["Qibla confidence","Terrain and flood layers","Private location controls"],href:"/design",scene:"site"},
 {number:"02",title:"Plan the prayer experience",body:"Shape rooms and review prayer rows, inclusive positions, daylight, wudu journeys and essential building services.",facts:["Editable room plan","Prayer-day scenarios","Walk-through view"],href:"/design",scene:"prayer"},
 {number:"03",title:"Control cost and construction",body:"Connect quantities and sourced rates with the programme, decisions, evidence, changes and site progress.",facts:["Location-aware cost options","Evidence before approval","Construction sequence"],href:"/construction",scene:"build"},
 {number:"04",title:"Prepare to open and care",body:"Turn handover information into maintenance plans, work orders, emergency readiness and responsible operations.",facts:["Building asset register","Upcoming maintenance","Emergency plans"],href:"/operations",scene:"care"},
];
export function LandingProductShowcase(){return <section className="landingShowcase section" aria-labelledby="product-showcase-title"><header><div><div className="eyebrow dark">SEE MOSQUE.BUILD IN ACTION</div><h2 id="product-showcase-title">Move each decision into the next stage.</h2><p>Explore live model views to see what your project contains, what information is still needed and which working tool to open next—not screenshots or decorative mockups.</p></div><Link href="/my-project" className="secondaryButton">Open my project</Link></header><div className="showcaseDemo"><HeroWorkspacePreview/></div><div className="showcaseGrid">{examples.map(example=><Link href={example.href} key={example.number}><LandingFeatureThree scene={example.scene}/><small>{example.number} · LIVE FEATURE VIEW</small><h3>{example.title}</h3><p>{example.body}</p><ul>{example.facts.map(x=><li key={x}>{x}</li>)}</ul><b>Open working tools ↗</b></Link>)}</div><p className="showcaseBoundary">The animated geometry demonstrates product interactions and relationships. It is not surveyed context, measured analysis, construction geometry, certified progress or an operational inspection.</p></section>}
