"use client";
import{useEffect,useRef,useState}from"react";
import type{Group,Material}from"three";
export type LandingScene="site"|"prayer"|"build"|"care";
const labels:Record<LandingScene,string>={site:"Site, access and qibla study",prayer:"Prayer space and daylight study",build:"Construction sequence and cost coordination",care:"Asset care and operations network"};
export function LandingFeatureThree({scene}:{scene:LandingScene}){const host=useRef<HTMLDivElement>(null),[status,setStatus]=useState("Preparing interactive preview…");useEffect(()=>{if(!host.current)return;let dispose=()=>{},cancelled=false;void(async()=>{try{const T=await import("three");if(cancelled||!host.current)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:"low-power"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0,0);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute("aria-label",labels[scene]);host.current.replaceChildren(renderer.domElement);const world=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,100),root=new T.Group(),mat=(color:number,opacity=1)=>new T.MeshStandardMaterial({color,roughness:.72,transparent:opacity<1,opacity}),box=(group:Group,size:[number,number,number],position:[number,number,number],color:number,opacity=1)=>{const mesh=new T.Mesh(new T.BoxGeometry(...size),mat(color,opacity));mesh.position.set(...position);group.add(mesh);return mesh},cylinder=(group:Group,r:number,h:number,position:[number,number,number],color:number)=>{const mesh=new T.Mesh(new T.CylinderGeometry(r,r,h,18),mat(color));mesh.position.set(...position);group.add(mesh);return mesh};world.add(root,new T.HemisphereLight(0xfff8e8,0x173e36,2.7));const sun=new T.DirectionalLight(0xffdfa0,2.2);sun.position.set(-8,16,10);world.add(sun);camera.position.set(15,12,18);camera.lookAt(0,1,0);
 if(scene==="site"){box(root,[16,.25,12],[0,0,0],0xb9c7ad);for(let i=0;i<5;i++){const line=box(root,[12-i*1.2,.04,.08],[-1+i*.3,.25+i*.16,-4+i*1.7],0x6d9578);line.rotation.y=-.08}box(root,[3,.12,10],[-5,.25,0],0x68777a);box(root,[2,.15,10],[4.5,.3,0],0xe1bb63);const q=box(root,[.1,.08,10],[0,.45,0],0xf2d275);q.rotation.y=-.42}
 if(scene==="prayer"){box(root,[14,.25,11],[0,0,0],0x2e6558);box(root,[14,4,.25],[0,2,-5.5],0xd8c9a8);for(let z=-4;z<=4;z+=1.15)box(root,[11,.035,.06],[0,.2,z],0xeacb75);for(let x=-4.5;x<=4.5;x+=1.5)cylinder(root,.11,.08,[x,.32,-4.65],0xf3dfab);for(let x=-5;x<=5;x+=2){const ray=box(root,[.22,.04,7],[x,3,-1],0xffd878,.38);ray.rotation.x=-.28}}
 if(scene==="build"){box(root,[15,.35,11],[0,0,0],0xb8a77f);for(const x of[-5,-1.7,1.7,5])for(const z of[-3.5,3.5])cylinder(root,.26,5,[x,2.6,z],0xd8c7a4);box(root,[13,.35,8],[0,5.1,0],0x315f53);const dome=new T.Mesh(new T.SphereGeometry(2.7,22,12,0,Math.PI*2,0,Math.PI/2),mat(0xd4ac56));dome.position.y=5.25;root.add(dome);for(let i=0;i<4;i++)box(root,[2.4,.24,.55],[-4.7+i*3.15,.45+i*.65,5],i<3?0xd7b663:0x79958d)}
 if(scene==="care"){box(root,[12,.3,9],[0,0,0],0xc8d1bd);box(root,[8,3.8,6],[0,2,0],0xdccfb2);for(const [x,z,color]of[[-5,-4,0xd3a94e],[5,-4,0x6f9a83],[-5,4,0x7693a6],[5,4,0xb47f61]]as[number,number,number][]){const node=cylinder(root,.65,.25,[x,.5,z],color);const points=[new T.Vector3(x,.55,z),new T.Vector3(0,2,0)],geometry=new T.BufferGeometry().setFromPoints(points);root.add(new T.Line(geometry,new T.LineBasicMaterial({color:0xb38b42})));node.rotation.x=Math.PI/2}}
 let visible=true,frame=0,start=performance.now();const observer=new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting??false},{rootMargin:"120px"});observer.observe(host.current);const resize=()=>{if(!host.current)return;renderer.setSize(host.current.clientWidth,host.current.clientHeight,false);camera.aspect=host.current.clientWidth/Math.max(1,host.current.clientHeight);camera.updateProjectionMatrix()},resizeObserver=new ResizeObserver(resize);resizeObserver.observe(host.current);resize();const draw=(time:number)=>{frame=requestAnimationFrame(draw);if(!visible)return;if(!reduced){root.rotation.y=-.35+Math.sin((time-start)/2500)*.12;if(scene==="build")root.children.forEach((object,index)=>{if(index>8)object.position.y+=Math.sin((time-start)/700+index)*.0008})}renderer.render(world,camera)};draw(start);setStatus(`${labels[scene]} ready`);dispose=()=>{cancelAnimationFrame(frame);observer.disconnect();resizeObserver.disconnect();world.traverse(object=>{if(object instanceof T.Mesh||object instanceof T.Line){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach((material:Material)=>material.dispose())}});renderer.dispose();renderer.domElement.remove()}}catch(error){setStatus(error instanceof Error?`Preview unavailable: ${error.message}`:"Preview unavailable")}})();return()=>{cancelled=true;dispose()}},[scene]);return <div className="landingFeatureThree" data-scene={scene}><div ref={host}/><span>{labels[scene]}</span><p className="srOnly" role="status" aria-live="polite">{status}</p></div>}
