"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Draft={name?:string;type?:string;location?:string;stage?:string;land?:string;attendance?:string;budget?:string;currency?:string;needs?:string[];constraints?:string[];owner?:string;team?:string[]};
type Task={id:string;title:string;detail:string;area:string;gate?:string};
const draftKey="mosque-build.project-draft.v2";const progressKey="mosque-build.project-progress.v1";

function buildTasks(draft:Draft):Task[]{
  const tasks:Task[]=[{id:"confirm-brief",title:"Confirm the community brief",detail:"Review needs, representation, decision authority and unresolved assumptions with accountable stakeholders.",area:"Brief"}];
  if(!draft.land||["Not yet","Site under consideration"].includes(draft.land))tasks.push({id:"screen-site",title:"Complete site screening",detail:"Record access, utilities, planning context, parking, drainage, climate and expansion questions before design lock-in.",area:"Site",gate:"Site conclusions require verified evidence and professional review."});
  if(draft.constraints?.includes("Planning / permit uncertainty"))tasks.push({id:"permit-path",title:"Build the likely permit path",detail:"Collect current authority sources and record likely applicable requirements without presenting them as approvals.",area:"Permits",gate:"Verify with authority or professional."});
  if(!draft.team?.includes("Architect"))tasks.push({id:"appoint-architect",title:"Prepare an architect appointment brief",detail:"Define scope, deliverables, coordination, review gates, information ownership and handover expectations.",area:"Team"});
  if(!draft.team?.some(item=>item.includes("cost professional")))tasks.push({id:"cost-baseline",title:"Establish a cost baseline",detail:"Document geography, currency, date, source, maturity, confidence, exclusions and contingency basis.",area:"Budget",gate:"A working range is not a quotation or final cost."});
  if(!draft.budget)tasks.push({id:"affordability",title:"Set an affordability range",detail:"Agree a responsible working range before publishing targets or selecting a design scenario.",area:"Funding"});
  if(draft.needs?.includes("Accessibility"))tasks.push({id:"access-review",title:"Plan an accessibility review",detail:"Include disabled worshippers and qualified accessibility input in routes, wudu, prayer, learning and facility reviews.",area:"Inclusion"});
  tasks.push({id:"decision-log",title:"Record the first project decision",detail:"Capture the decision, owner, date, evidence used, alternatives and next review point.",area:"Governance"});return tasks;
}

export function LocalProjectWorkspace(){
  const [draft,setDraft]=useState<Draft|null>(null);const [ready,setReady]=useState(false);const [completed,setCompleted]=useState<string[]>([]);const [filter,setFilter]=useState<"all"|"open"|"complete">("all");
  useEffect(()=>{try{const raw=localStorage.getItem(draftKey);if(raw){const value=JSON.parse(raw);if(value&&typeof value==="object")setDraft(value)}const saved=localStorage.getItem(progressKey);if(saved){const value=JSON.parse(saved);setCompleted(Array.isArray(value)?value.filter(item=>typeof item==="string"):[])}}catch{setCompleted([])}finally{setReady(true)}},[]);
  const tasks=useMemo(()=>draft?buildTasks(draft):[],[draft]);const visible=tasks.filter(task=>filter==="all"||(filter==="complete")===completed.includes(task.id));const percent=tasks.length?Math.round(completed.filter(id=>tasks.some(task=>task.id===id)).length/tasks.length*100):0;
  const toggle=(id:string)=>setCompleted(current=>{const next=current.includes(id)?current.filter(item=>item!==id):[...current,id];try{localStorage.setItem(progressKey,JSON.stringify(next))}catch{}return next});
  if(!ready)return <section className="workspaceState" role="status"><span className="loadingPulse"/><h1>Loading your local project…</h1></section>;
  if(!draft?.name)return <section className="workspaceState"><div className="eyebrow dark">MY PROJECT</div><h1>Build a brief before opening the workspace.</h1><p>This workspace continues the private project saved on this device. Nothing is uploaded by the current public site.</p><Link className="button" href="/start">Start the guided brief</Link></section>;
  return <><section className="workspaceHero"><div><div className="eyebrow gold">PRIVATE ON-DEVICE WORKSPACE</div><h1>{draft.name}</h1><p>{draft.type} · {draft.location||"Location to confirm"}</p><div className="workspaceBadges"><span>{draft.stage||"Stage to confirm"}</span><span>{draft.land||"Site to confirm"}</span><span>{draft.owner?`Owner: ${draft.owner}`:"Owner needed"}</span></div></div><div className="workspaceProgress"><strong>{percent}%</strong><span>first-plan actions complete</span><div aria-label={`${percent}% complete`} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><i style={{width:`${percent}%`}}/></div></div></section><section className="section projectWorkspace"><div className="workspaceSummary"><article><small>JUMU’AH</small><b>{draft.attendance||"Estimate needed"}</b></article><article><small>WORKING BUDGET</small><b>{draft.budget?`${draft.currency||""} ${draft.budget}`:"Range needed"}</b></article><article><small>PROGRAM NEEDS</small><b>{draft.needs?.length||0}</b></article><article><small>TEAM ROLES</small><b>{draft.team?.length||0}</b></article></div><div className="workspaceHeading"><div><div className="eyebrow dark">FIRST ACTION PLAN</div><h2>Move the project forward without hiding uncertainty.</h2></div><div className="taskFilters" aria-label="Filter actions">{(["all","open","complete"] as const).map(value=><button type="button" key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div></div><div className="taskList">{visible.length?visible.map(task=>{const done=completed.includes(task.id);return <article className={done?"taskComplete":""} key={task.id}><button type="button" aria-pressed={done} onClick={()=>toggle(task.id)}><span aria-hidden="true">{done?"✓":""}</span><span className="srOnly">{done?"Mark incomplete":"Mark complete"}</span></button><div><small>{task.area}</small><h3>{task.title}</h3><p>{task.detail}</p>{task.gate&&<div className="taskGate">Review gate · {task.gate}</div>}</div></article>}):<div className="workspaceEmpty"><h3>No actions in this view.</h3><p>Change the filter or mark an action incomplete to bring it back.</p></div>}</div><aside className="workspaceBoundary"><b>Local workspace boundary</b><p>Progress is saved only in this browser. It is not collaboration, cloud backup, an authority record, professional approval or verified external evidence.</p><div><Link href="/start">Edit project brief</Link><Link href="/sources">Research source records</Link><Link href="/pwa-guide">Install and offline guide</Link></div></aside></section></>;
}
