"use client";

import {useEffect,useMemo,useState} from "react";
import {marketplaceCandidates,marketplaceDataset} from "@/lib/marketplace-candidates";
import {createSelection,evidenceGaps,groupSelectionSummary,MARKETPLACE_PLAN_SCHEMA,procurementStages,projectPriorities,safeMarketplacePlan,selectionReadiness,type CandidateSelection} from "@/lib/marketplace-planning";

const storageKey="mosque-build.marketplace-candidates.v1";
const PAGE_SIZE=12,ids=new Set(marketplaceCandidates.map(item=>item.id));
const stageLabels={research:"Research",sample:"Sample requested",technical_review:"Technical review",quote:"Quote requested",approved_alternative:"Approved alternative"};

export function MarketplaceCandidateCatalog(){
  const [query,setQuery]=useState(""),[category,setCategory]=useState("All"),[evidence,setEvidence]=useState("All"),[selections,setSelections]=useState<CandidateSelection[]>([]),[compare,setCompare]=useState<string[]>([]),[limit,setLimit]=useState(PAGE_SIZE),[message,setMessage]=useState("");
  useEffect(()=>{try{setSelections(safeMarketplacePlan(JSON.parse(localStorage.getItem(storageKey)||"{}"),ids).selections)}catch{}},[]);
  const persist=(next:CandidateSelection[])=>{setSelections(next);try{localStorage.setItem(storageKey,JSON.stringify({schema:MARKETPLACE_PLAN_SCHEMA,selections:next,updatedAt:new Date().toISOString()}));dispatchEvent(new Event("mosque-build:project-change"))}catch{setMessage("This browser could not save the sourcing plan.")}};
  const categories=["All",...new Set(marketplaceCandidates.map(item=>item.category))];
  const filtered=useMemo(()=>marketplaceCandidates.filter(item=>{const text=`${item.name} ${item.vendor} ${item.category} ${item.subcategory} ${item.use} ${item.attributes.join(" ")} ${item.model}`.toLowerCase(),gaps=evidenceGaps(item);return (category==="All"||item.category===category)&&(evidence==="All"||evidence==="CAD / BIM gap"&&gaps.some(g=>g.includes("CAD"))||evidence==="Exact product gap"&&gaps.some(g=>g.includes("Exact")))&&text.includes(query.trim().toLowerCase())}),[query,category,evidence]);
  const selectedRecords=selections.map(row=>({row,item:marketplaceCandidates.find(item=>item.id===row.id)!})).filter(value=>value.item),summary=groupSelectionSummary(selections,marketplaceCandidates),compared=compare.map(id=>marketplaceCandidates.find(item=>item.id===id)!).filter(Boolean);
  const updateFilter=(fn:()=>void)=>{fn();setLimit(PAGE_SIZE)};
  const toggle=(id:string)=>{const exists=selections.some(value=>value.id===id),next=exists?selections.filter(value=>value.id!==id):[...selections,createSelection(id)];persist(next);setMessage(exists?"Removed from the sourcing plan.":"Added to the sourcing plan. Add a zone and requirements before review.")};
  const updateSelection=(id:string,change:Partial<CandidateSelection>)=>persist(selections.map(row=>row.id===id?{...row,...change}:row));
  const toggleCompare=(id:string)=>{if(compare.includes(id)){setCompare(compare.filter(value=>value!==id));return}if(compare.length>=3){setMessage("Compare up to three candidates at a time.");return}setCompare([...compare,id])};
  const exportPlan=()=>{const payload={schema:"mosque.build/marketplace-candidate-brief@2",status:"specified",exportedAt:new Date().toISOString(),dataset:marketplaceDataset,notice:marketplaceDataset.notice,summary:{units:summary.units,categories:[...summary.categories],zones:[...summary.zones]},records:selectedRecords.map(({row,item})=>({selection:row,candidate:item,evidenceGaps:evidenceGaps(item),readiness:selectionReadiness(row,item)}))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="mosque-build-sourcing-plan.json";link.click();URL.revokeObjectURL(url);setMessage(`Exported ${selections.length} candidate ${selections.length===1?"record":"records"} with requirements and evidence gaps.`)};
  return <section className="candidateCatalog" aria-labelledby="candidate-catalog-title">
    <header className="candidateCatalogIntro"><div><small>CANDIDATE SOURCE LIBRARY</small><h2 id="candidate-catalog-title">Build a traceable sourcing plan.</h2><p>{marketplaceDataset.curatedRows} entries span {categories.length-1} project categories, curated from {marketplaceDataset.sourceRows} supplied research rows. Compare planning fit, record requirements and expose missing evidence before requesting a quote.</p></div><div className="candidateDataset"><b>Needs review</b><span>Observed {marketplaceDataset.observedAt}</span><span>No price or availability assumed</span></div></header>
    <div className="candidateFilters"><label><span>Search candidates</span><input type="search" value={query} onChange={event=>updateFilter(()=>setQuery(event.target.value))} placeholder="Try wudu, carpet, audio or accessibility"/></label><label><span>Category</span><select value={category} onChange={event=>updateFilter(()=>setCategory(event.target.value))}>{categories.map(value=><option key={value}>{value}</option>)}</select></label><label><span>Evidence filter</span><select value={evidence} onChange={event=>updateFilter(()=>setEvidence(event.target.value))}><option>All</option><option>CAD / BIM gap</option><option>Exact product gap</option></select></label></div>
    <div className="candidateResultBar"><p aria-live="polite"><b>{filtered.length}</b> candidates match · <b>{selections.length}</b> planned · <b>{compare.length}/3</b> compared</p><button type="button" disabled={!selections.length} onClick={exportPlan}>Export sourcing plan ({selections.length})</button></div>
    {filtered.length?<div className="candidateGrid">{filtered.slice(0,limit).map(item=>{const gaps=evidenceGaps(item),selected=selections.some(value=>value.id===item.id);return <article key={item.id}><div className="candidateCardTop"><span>{item.category}</span><small>{item.id}</small></div><h3>{item.name}</h3><p className="candidateVendor">{item.vendor} · {item.subcategory}</p><p>{item.use}</p><details><summary>Specification prompts ({item.attributes.length})</summary><ul>{item.attributes.map(value=><li key={value}>{value}</li>)}</ul></details><details><summary>Evidence gaps ({gaps.length})</summary><ul>{gaps.map(value=><li key={value}>{value}</li>)}</ul></details><dl><div><dt>Model planning</dt><dd>{item.model}</dd></div><div><dt>CAD / BIM evidence</dt><dd>{item.cadBim}</dd></div></dl><div className="candidateWarning">Verify product, documents, region, price and availability.</div><div className="candidateActions three"><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Review source ↗</a><button type="button" aria-pressed={compare.includes(item.id)} onClick={()=>toggleCompare(item.id)}>{compare.includes(item.id)?"Comparing ✓":"Compare"}</button><button type="button" aria-pressed={selected} onClick={()=>toggle(item.id)}>{selected?"Planned ✓":"Add to plan"}</button></div></article>})}</div>:<div className="workspaceEmpty"><h3>No candidates match.</h3><p>Try a broader term or clear the filters.</p><button type="button" onClick={()=>{setQuery("");setCategory("All");setEvidence("All")}}>Clear filters</button></div>}
    {limit<filtered.length?<button className="candidateMore" type="button" onClick={()=>setLimit(value=>value+PAGE_SIZE)}>Show {Math.min(PAGE_SIZE,filtered.length-limit)} more</button>:null}
    {compared.length?<section className="candidateCompare" aria-labelledby="candidate-compare-title"><header><div><small>FIT COMPARISON</small><h3 id="candidate-compare-title">Compare requirements and evidence.</h3></div><button type="button" onClick={()=>setCompare([])}>Clear</button></header><div role="table" aria-label="Candidate comparison"><div role="row"><b role="columnheader">Field</b>{compared.map(item=><b role="columnheader" key={item.id}>{item.name}</b>)}</div>{[["Vendor",(item:typeof compared[number])=>item.vendor],["Use",(item:typeof compared[number])=>item.use],["3D approach",(item:typeof compared[number])=>item.model],["CAD / BIM",(item:typeof compared[number])=>item.cadBim],["Open evidence gaps",(item:typeof compared[number])=>String(evidenceGaps(item).length)]].map(([label,get])=><div role="row" key={String(label)}><b role="rowheader">{String(label)}</b>{compared.map(item=><span role="cell" key={item.id}>{(get as (x:typeof item)=>string)(item)}</span>)}</div>)}</div></section>:null}
    {selectedRecords.length?<section className="candidatePlan" aria-labelledby="candidate-plan-title"><header><div><small>SOURCING PLAN</small><h3 id="candidate-plan-title">Turn candidates into reviewable requirements.</h3><p>{summary.units} planned units across {summary.categories.size} categories and {summary.zones.size} project zones.</p></div></header><div className="candidatePlanList">{selectedRecords.map(({row,item})=>{const readiness=selectionReadiness(row,item);return <article key={row.id}><div><h4>{item.name}</h4><span className={readiness.ready?"ready":"incomplete"}>{readiness.ready?"Ready for review":`Needs ${readiness.missing.join(", ")}`}</span></div><div className="candidatePlanFields"><label>Quantity<input type="number" min="1" max="10000" value={row.quantity} onChange={event=>updateSelection(row.id,{quantity:Math.min(10000,Math.max(1,Number(event.target.value)||1))})}/></label><label>Project zone<input value={row.zone} maxLength={80} onChange={event=>updateSelection(row.id,{zone:event.target.value})} placeholder="Prayer hall, wudu, foyer…"/></label><label>Priority<select value={row.priority} onChange={event=>updateSelection(row.id,{priority:event.target.value as CandidateSelection["priority"]})}>{projectPriorities.map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><label>Review stage<select value={row.stage} onChange={event=>updateSelection(row.id,{stage:event.target.value as CandidateSelection["stage"]})}>{procurementStages.map(value=><option key={value} value={value}>{stageLabels[value]}</option>)}</select></label><label className="candidatePlanNotes">Requirements and exclusions<textarea value={row.notes} maxLength={500} onChange={event=>updateSelection(row.id,{notes:event.target.value})} placeholder="Performance, sample, installation, maintenance and exclusions…"/></label></div><button type="button" onClick={()=>toggle(row.id)}>Remove</button></article>})}</div></section>:null}
    <footer><p>{marketplaceDataset.provenance} {marketplaceDataset.rights}</p></footer><p role="status" aria-live="polite">{message}</p>
  </section>
}
