"use client";
import {useEffect,useMemo,useState} from "react";
import {createMasjidIntelligence,type MasjidBriefInputs} from "@/lib/masjid-intelligence";
const key="mosque-build.masjid-intelligence.v1";
const initial:MasjidBriefInputs={daily:120,jummah:420,ramadan:560,growth:3,siteArea:1800,priority:"community",climate:"unknown"};
type StrategyId="worship"|"community"|"phased";
export function MasjidIntelligenceWorkbench(){
 const [inputs,setInputs]=useState(initial),[selected,setSelected]=useState<StrategyId>("community"),[ready,setReady]=useState(false),[message,setMessage]=useState("");const result=useMemo(()=>createMasjidIntelligence(inputs),[inputs]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||"null");if(saved?.inputs)setInputs({...initial,...saved.inputs});if(["worship","community","phased"].includes(saved?.selected))setSelected(saved.selected)}catch{}setReady(true)},[]);
 const persist=(nextInputs:MasjidBriefInputs,nextSelected:StrategyId)=>{try{localStorage.setItem(key,JSON.stringify({schemaVersion:"mosque.build/masjid-intelligence@1",status:"executable",inputs:nextInputs,selected:nextSelected,reviewGate:result.reviewGate}));window.dispatchEvent(new Event("mosque-build:project-change"))}catch{}};
 const update=(patch:Partial<MasjidBriefInputs>)=>setInputs(current=>{const next={...current,...patch};persist(next,selected);return next});const choose=(id:StrategyId)=>{setSelected(id);persist(inputs,id)};
 const useInSchematic=()=>{window.dispatchEvent(new CustomEvent("mosque-build:strategy-to-schematic",{detail:{strategy:selected}}));document.querySelector(".schematicTool")?.scrollIntoView({behavior:"smooth",block:"start"});setMessage(`${result.strategies.find(item=>item.id===selected)?.title} sent to the schematic as a starting form.`)};
 if(!ready)return <section className="intelligenceWorkbench" role="status">Preparing design intelligence…</section>;
 return <section className="intelligenceWorkbench" aria-labelledby="intelligence-title"><header><div><div className="eyebrow dark">PARAMETRIC MASJID BRIEF</div><h2 id="intelligence-title">Change the brief. See the trade-offs move.</h2><p>Compare three planning directions from the same community inputs. Every indicator exposes its reasoning and stays separate from professional calculations.</p></div><div className="intelligencePeak"><small>LARGEST ATTENDANCE INPUT</small><b>{result.peakInput.toLocaleString()}</b><span>people · user supplied</span></div></header>
 <div className="intelligenceInputs"><label>Daily attendance<input type="number" min="1" max="100000" value={inputs.daily} onChange={e=>update({daily:Number(e.target.value)})}/></label><label>Jumu&apos;ah attendance<input type="number" min="1" max="100000" value={inputs.jummah} onChange={e=>update({jummah:Number(e.target.value)})}/></label><label>Ramadan peak<input type="number" min="1" max="100000" value={inputs.ramadan} onChange={e=>update({ramadan:Number(e.target.value)})}/></label><label>Annual growth prompt<input type="number" min="0" max="15" step=".5" value={inputs.growth} onChange={e=>update({growth:Number(e.target.value)})}/><span>%</span></label><label>Site area input<input type="number" min="100" max="1000000" step="50" value={inputs.siteArea} onChange={e=>update({siteArea:Number(e.target.value)})}/><span>m²</span></label><label>Climate prompt<select value={inputs.climate} onChange={e=>update({climate:e.target.value as MasjidBriefInputs["climate"]})}><option value="unknown">Not selected</option><option value="hot_humid">Hot and humid</option><option value="hot_dry">Hot and dry</option><option value="cold">Cold</option><option value="temperate">Temperate</option></select></label><label>Primary emphasis<select value={inputs.priority} onChange={e=>update({priority:e.target.value as MasjidBriefInputs["priority"]})}><option value="worship">Worship capacity</option><option value="community">Community program</option><option value="phasing">Phased growth</option></select></label></div>
 <div className="strategyTabs" role="tablist" aria-label="Planning strategies">{result.strategies.map(item=><button key={item.id} type="button" role="tab" aria-selected={selected===item.id} aria-controls={`strategy-${item.id}`} onClick={()=>choose(item.id)}><b>{item.title}</b><span>{item.summary}</span></button>)}</div>
 {result.strategies.filter(item=>item.id===selected).map(item=><article key={item.id} id={`strategy-${item.id}`} role="tabpanel"><header><div><small>SELECTED DIRECTION</small><h3>{item.title}</h3><p>{item.summary}</p></div><span>10-year arithmetic prompt: <b>{result.planningHorizon.toLocaleString()}</b></span></header><div className="indicatorGrid">{item.indicators.map(metric=><section key={metric.id}><div><b>{metric.label}</b><output>{metric.value}</output></div><div className="indicatorBar" role="progressbar" aria-label={metric.label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={metric.value}><i style={{width:`${metric.value}%`}}/></div><p>{metric.explanation}</p></section>)}</div><aside><b>Questions to carry forward</b><ul>{item.prompts.map(prompt=><li key={prompt}>{prompt}</li>)}</ul></aside><div className="strategyHandoff"><button className="button" type="button" onClick={useInSchematic}>Use as schematic starting point</button><p role="status" aria-live="polite">{message}</p></div></article>)}
 <footer><b>Interpretation boundary</b><p>{result.reviewGate}</p></footer></section>;
}
