"use client";

import Image from "next/image";
import {useEffect,useMemo,useState} from "react";
import {applyBuildingPreset,BUILDING_KEY,buildingErrors,buildingLimits,buildingPresets,buildingToFloorPlan,createBuilding,defaultBuilding,safeBuilding,type BuildingParameters} from "@/lib/parametric-building";
import {newFloorPlan,safeFloorPlan} from "@/lib/floor-plan-workspace";
import {exportBuildingIfc} from "@/lib/building-ifc";
import references from "@/data/architecture-image-references.json";
import {ParametricBuildingView} from "./parametric-building-view";
import "./parametric-building-studio.css";

const labels:Record<keyof typeof buildingLimits,string>={widthM:"Hall width (m)",depthM:"Hall depth (m)",heightM:"Wall height (m)",wallM:"Wall thickness (m)",slabM:"Slab / shell thickness (m)",doorWidthM:"Door clear width (m)",doorHeightM:"Door clear height (m)",bays:"Window / arcade bays",domeRiseM:"Dome rise (m)"};
function download(name:string,type:string,contents:string) {
  const url=URL.createObjectURL(new Blob([contents],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function ParametricBuildingStudio() {
  const [parameters,setParameters]=useState(defaultBuilding),[draft,setDraft]=useState(defaultBuilding),[status,setStatus]=useState("Adjust the dimensions, then apply them to the model."),[selected,setSelected]=useState("wall-entry"),[imageFailed,setImageFailed]=useState(false),[ready,setReady]=useState(false);
  const model=useMemo(()=>createBuilding(parameters),[parameters]),errors=buildingErrors(draft),dirty=JSON.stringify(parameters)!==JSON.stringify(draft);
  const preset=buildingPresets.find(p=>p.id===parameters.presetId)!,reference=references.find(r=>r.lineageId===preset.lineageId),element=model.elements.find(e=>e.id===selected);
  useEffect(()=>{try{const stored=localStorage.getItem(BUILDING_KEY);if(stored){const saved=safeBuilding(JSON.parse(stored));if(saved){setParameters(saved);setDraft(saved);setStatus("Saved building study restored.");}else setStatus("The saved study could not be read. A new study is shown; your stored file has not been changed.");}}catch{setStatus("Saved data is unavailable. You can still edit and export this study.");}setReady(true);},[]);
  useEffect(()=>setImageFailed(false),[reference?.imageUrl]);
  useEffect(()=>{const choose=(event:Event)=>{const id=(event as CustomEvent<unknown>).detail;if(typeof id!=="string"||!buildingPresets.some(p=>p.id===id))return;setDraft(p=>applyBuildingPreset(p,id));setStatus("Template loaded into the dimension editor. Review and apply it to update your model.");};addEventListener("mosque-build:building-preset",choose);return()=>removeEventListener("mosque-build:building-preset",choose);},[]);
  const save=()=>{try{localStorage.setItem(BUILDING_KEY,JSON.stringify(parameters));dispatchEvent(new Event("mosque-build:project-change"));setStatus("Building study saved on this device and included in your project package.");}catch{setStatus("Could not save on this device. Export the editable study to keep your changes.");}};
  const seedFloor=()=>{try{const raw=localStorage.getItem("mosque-build.floor-plan.v1"),existing=raw?safeFloorPlan(JSON.parse(raw)):newFloorPlan();if(!existing)throw new Error("Your saved floor plan could not be read. Export a project backup before changing it.");const next=buildingToFloorPlan(parameters,existing);localStorage.setItem("mosque-build.floor-plan.v1",JSON.stringify(next));dispatchEvent(new Event("mosque-build:floor-plan-change"));dispatchEvent(new Event("mosque-build:project-change"));setStatus("Hall, arrival, courtyard and openings copied where present. Continue adding rooms in the floor-plan workspace; later edits stay independent.");}catch(error){setStatus(error instanceof Error?error.message:"The floor plan could not be saved. Export the study to keep your work.");}};
  const totalDepth=parameters.depthM+(["maghrebi-court","mughal-garden-court"].includes(parameters.presetId)?11.8:parameters.arcade?3.8:0),pad=3;
  return <section className="buildingStudio" id="building-geometry" aria-labelledby="building-geometry-title">
    <header><div className="eyebrow dark">BUILDING GEOMETRY</div><h2 id="building-geometry-title">Turn a mosque reference into a dimensioned building study.</h2><p>Start with a hall, courtyard or central-volume template. Edit the actual building dimensions, inspect openings and roof construction, then share geometry with your architect.</p></header>
    <div className="buildingWorkspace"><form className="buildingControls" onSubmit={e=>{e.preventDefault();if(errors.length){setStatus("Correct the dimensions before applying.");return;}setParameters({...draft});setStatus("Dimensions applied. Save the study to keep these changes.");}}>
      <label>Architectural starting point<select value={draft.presetId} onChange={e=>setDraft(p=>applyBuildingPreset(p,e.target.value))}>{buildingPresets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <p className="buildingHint">Changing style keeps your dimensions and updates the roof and arrival arcade. These are original studies informed by references, not measured replicas.</p>
      <div className="buildingFields">{Object.entries(buildingLimits).map(([key,[min,max,step]])=><label key={key}>{labels[key as keyof typeof buildingLimits]}<input type="number" min={min} max={max} step={step} required value={Number.isNaN(draft[key as keyof typeof buildingLimits])?"":draft[key as keyof typeof buildingLimits]} onChange={e=>setDraft(p=>({...p,[key]:e.target.valueAsNumber}))}/></label>)}</div>
      <label>Roof form<select value={draft.roof} onChange={e=>setDraft(p=>({...p,roof:e.target.value as BuildingParameters["roof"]}))}><option value="flat">Flat roof</option><option value="pitched">Pitched roof</option><option value="dome">Dome with open roof deck</option></select></label>
      <label className="buildingCheck"><input type="checkbox" checked={draft.arcade} onChange={e=>setDraft(p=>({...p,arcade:e.target.checked}))}/>Covered arrival arcade</label>
      <label>Reference observations<textarea maxLength={2000} rows={3} value={draft.referenceNotes} placeholder="Record what you want to study: court proportions, arcade rhythm, daylight…" onChange={e=>setDraft(p=>({...p,referenceNotes:e.target.value}))}/></label>
      {errors.length?<ul className="buildingErrors" role="alert">{errors.map(error=><li key={error}>{error}</li>)}</ul>:null}
      <button className="buildingPrimary" type="submit" disabled={!ready}>Apply dimensions</button><p>{dirty?"Unapplied changes — preview and exports use the last applied dimensions.":"Preview and exports match the applied dimensions."}</p>
    </form><div className="buildingOutput">
      <div className="buildingMetrics"><span><b>{model.internalHallAreaM2.toFixed(1)} m²</b>Inside wall faces</span><span><b>{model.elements.filter(e=>e.role!=="opening").length}</b>Building elements</span><span><b>{model.elements.filter(e=>e.role==="opening").length}</b>Hosted openings</span></div>
      <div className="buildingPlan"><svg viewBox={`${-pad} ${-pad} ${parameters.widthM+pad*2} ${totalDepth+pad*2}`} role="img" aria-labelledby="building-plan-title building-plan-desc"><title id="building-plan-title">{`Dimensioned ${preset.name} plan`}</title><desc id="building-plan-desc">{`Horizontal section at 1.5 metres with an entrance gap, side windows and arrival columns. Width ${parameters.widthM} metres, hall depth ${parameters.depthM} metres. Site north and qibla orientation are not assigned.`}</desc>
        <rect x="0" y="0" width={parameters.widthM} height={totalDepth} fill="#f4f0e5" stroke="#bbb69f" strokeWidth=".06"/>
        {model.elements.flatMap(item=>item.solids.map((solid,i)=>{
          if(solid.kind!=="extrusion"||solid.axis!=="z"||item.role==="roof"||item.role==="opening"||solid.origin[2]>1.5||solid.origin[2]+solid.depth<1.5)return null;
          return <polygon key={`${item.id}-${i}`} points={solid.profile.map(([x,y])=>`${x+solid.origin[0]},${y+solid.origin[1]}`).join(" ")} fill={selected===item.id?"#a87424":"#254c40"}/>;
        }))}
        <text x={parameters.widthM/2} y="-1" textAnchor="middle">{parameters.widthM.toFixed(1)} m · prayer-focus wall</text>
        <text x={parameters.widthM/2} y={parameters.depthM/2} textAnchor="middle">Prayer hall</text>
        <text x={parameters.widthM/2} y={parameters.depthM/2+1.2} textAnchor="middle">{parameters.widthM} × {parameters.depthM} m outside walls</text>
        <text x={parameters.widthM/2} y={totalDepth+1.6} textAnchor="middle">Entrance · {parameters.doorWidthM.toFixed(1)} m clear</text>
      </svg><p><b>Hall {parameters.widthM} × {parameters.depthM} m</b> outside walls · {parameters.doorWidthM} m clear entrance</p><small>Plan section at 1.5 m. Site north and qibla orientation still need to be established.</small></div>
      <ParametricBuildingView model={model} selected={selected} onSelect={setSelected}/>
      <label>Inspect an element<select value={element?.id??""} onChange={e=>setSelected(e.target.value)}>{!element?<option value="">Select an element</option>:null}{model.elements.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
      {element?<p className="buildingElement"><b>{element.name}</b> · {element.ifcClass} · {element.solids.length} {element.role==="opening"?"opening volume(s)":"solid(s)"}{element.hostId?` · Hosted by ${element.hostId}`:""}</p>:null}
      <div className="buildingActions"><button type="button" disabled={!ready||dirty} onClick={save}>Save building study</button><button type="button" onClick={()=>{try{download("mosque-build-study.ifc","application/x-step",exportBuildingIfc(model));setStatus("IFC4 exported. Check geometry and categories in your target BIM application.");}catch{setStatus("IFC export failed. Export the editable study and try again.");}}}>Export IFC4</button><button type="button" onClick={()=>download("mosque-build-building.json","application/json",JSON.stringify(parameters,null,2))}>Export editable study</button></div>
      {dirty?<p>Apply your changes before saving. Exports contain the currently displayed model.</p>:null}
      <button type="button" disabled={!ready||dirty} onClick={seedFloor}>Start a floor plan from this building</button><p className="buildingHint">Copies into an empty floor-plan workspace only. Existing rooms are preserved. This creates a starting layout; the two editors remain independent afterward.</p>
      <label className="buildingImport">Restore an exported study<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>20000){setStatus("Choose a building study JSON smaller than 20 KB.");return;}try{const restored=safeBuilding(JSON.parse(await file.text()));if(!restored)throw new Error();setDraft(restored);setStatus("Imported settings are ready to review. Apply dimensions to update the model.");}catch{setStatus("This file is not a valid building study. Your current model has been kept.");}}}/></label>
      <p className="buildingStatus" role="status" aria-live="polite">{status}</p>
    </div></div>
    {reference?<figure className="buildingReference">{imageFailed?<div>Reference photograph unavailable. Open the original source below.</div>:<Image unoptimized src={reference.imageUrl} alt={reference.exampleName} width={640} height={420} sizes="(max-width: 720px) 100vw, 320px" onError={()=>setImageFailed(true)}/>}<figcaption><h3>{reference.exampleName}</h3><p>{reference.classificationFocus}</p><p>{reference.relationship}</p><a href={reference.sourcePage} target="_blank" rel="noreferrer">Photograph: {reference.creator}</a><a href={reference.licenseUrl} target="_blank" rel="noreferrer">{reference.license}</a><small>Reference record checked {reference.observedAt}. Dimensions in this editor are user inputs, not measurements from this photograph.</small><a href={`/patterns#architecture`}>Explore architectural references</a></figcaption></figure>:null}
    <details><summary>What the architect receives</summary><p>IFC4 contains metre-based geometry, a site/building/storey hierarchy, walls, slabs, columns, arcade members and hosted openings. Most geometry uses extruded profiles; the hollow dome is a faceted boundary representation. A GLB carries the visual model. The editable study preserves the parameters used here.</p><p>Use a supported IFC workflow in Revit and check units, orientation and element categories. This export does not create native Revit families or an RVT file. The template includes a hall and arrival study; wudu, women’s spaces, services and the full room program still need coordination. Structure, drainage, egress, thermal performance and buildability require professional design.</p><a href="https://autodesk.ifc-manual.com/revit/using-ifc-files-in-revit/open-ifc" target="_blank" rel="noreferrer">Autodesk IFC import guidance</a></details>
  </section>;
}
