"use client";

import {useEffect,useMemo,useState} from "react";

export type PriorityFeature={id:string;title:string;description:string;domain:string;domains:string[];status:string;wave:number;score:number;professionalGate:boolean;external:boolean;ai:boolean;sourceCount:number;developmentComplexity:number;provenanceBurden:number};
const savedKey="mosque-build.priority-100.shortlist";
const waves=[0,1,2,3,4,5,6,7];

export function PriorityFeatureExplorer({features,startIndex=1}:{features:PriorityFeature[];startIndex?:number}){
  const [query,setQuery]=useState("");const [domain,setDomain]=useState("all");const [wave,setWave]=useState("all");const [status,setStatus]=useState("all");const [dependency,setDependency]=useState("all");const [sort,setSort]=useState("priority");const [density,setDensity]=useState("comfortable");const [gateOnly,setGateOnly]=useState(false);const [saved,setSaved]=useState<string[]>([]);const [savedOnly,setSavedOnly]=useState(false);const [ready,setReady]=useState(false);const [message,setMessage]=useState("");

  useEffect(()=>{const params=new URLSearchParams(location.search);setQuery(params.get("q")||"");setDomain(params.get("domain")||"all");setWave(params.get("wave")||"all");setStatus(params.get("status")||"all");setDependency(params.get("dependency")||"all");setSort(params.get("sort")||"priority");setDensity(params.get("view")||"comfortable");setGateOnly(params.get("gate")==="1");setSavedOnly(params.get("saved")==="1");try{const parsed=JSON.parse(localStorage.getItem(savedKey)||"[]");setSaved(Array.isArray(parsed)?parsed:[])}catch{setSaved([])}setReady(true)},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(savedKey,JSON.stringify(saved))}catch{}const params=new URLSearchParams();if(query)params.set("q",query);if(domain!=="all")params.set("domain",domain);if(wave!=="all")params.set("wave",wave);if(status!=="all")params.set("status",status);if(dependency!=="all")params.set("dependency",dependency);if(sort!=="priority")params.set("sort",sort);if(density!=="comfortable")params.set("view",density);if(gateOnly)params.set("gate","1");if(savedOnly)params.set("saved","1");history.replaceState(null,"",`${location.pathname}${params.size?`?${params}`:""}`)},[query,domain,wave,status,dependency,sort,density,gateOnly,savedOnly,saved,ready]);

  const domains=useMemo(()=>[...new Set(features.map(item=>item.domain))].sort(),[features]);const statuses=useMemo(()=>[...new Set(features.map(item=>item.status))].sort(),[features]);
  const visible=useMemo(()=>features.filter(item=>(!query||`${item.title} ${item.description} ${item.domains.join(" ")} ${item.id}`.toLowerCase().includes(query.toLowerCase()))&&(domain==="all"||item.domain===domain)&&(wave==="all"||String(item.wave)===wave)&&(status==="all"||item.status===status)&&(dependency==="all"||(dependency==="external"&&item.external)||(dependency==="ai"&&item.ai)||(dependency==="professional"&&item.professionalGate))&&(!gateOnly||item.professionalGate)&&(!savedOnly||saved.includes(item.id))).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="wave"?a.wave-b.wave||b.score-a.score:b.score-a.score||a.title.localeCompare(b.title)),[features,query,domain,wave,status,dependency,sort,gateOnly,savedOnly,saved]);
  const batchSaved=useMemo(()=>features.filter(item=>saved.includes(item.id)),[features,saved]);
  const toggle=(id:string)=>setSaved(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const clear=()=>{setQuery("");setDomain("all");setWave("all");setStatus("all");setDependency("all");setSort("priority");setGateOnly(false);setSavedOnly(false)};
  const records=batchSaved.map(({id,title,domains:featureDomains,status,wave:recommendedWave,score:priorityScore,professionalGate:professionalOrAuthorityGate,external:externalServicesLikely,ai:usesAI,sourceCount:sourceReferenceCount,developmentComplexity,provenanceBurden})=>({id,title,domains:featureDomains.join(" | "),status,recommendedWave,priorityScore,professionalOrAuthorityGate,externalServicesLikely,usesAI,sourceReferenceCount,developmentComplexity,provenanceBurden}));
  const download=(content:string,type:string,extension:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=`mosque-build-shortlist-${startIndex}-${startIndex+features.length-1}.${extension}`;link.click();URL.revokeObjectURL(url)};
  const exportJson=()=>{download(JSON.stringify({product:"mosque.build",kind:"feature-planning-shortlist",exportedAt:new Date().toISOString(),notice:"Planning candidates only. Verify status and review gates before delivery claims.",records},null,2),"application/json","json");setMessage(`${records.length} shortlisted records exported as JSON.`)};
  const exportCsv=()=>{const columns=Object.keys(records[0]);const escape=(value:unknown)=>`"${String(value).replaceAll('"','""')}"`;download([columns.join(","),...records.map(record=>columns.map(column=>escape(record[column as keyof typeof record])).join(","))].join("\n"),"text/csv;charset=utf-8","csv");setMessage(`${records.length} shortlisted records exported as CSV.`)};
  const copyView=async()=>{try{await navigator.clipboard.writeText(location.href);setMessage("Shareable filtered URL copied.")}catch{setMessage("Copy the current browser URL to share this view.")}};

  return <div className={`featureExplorer ${density==="compact"?"compactExplorer":""}`}>
    <div className="explorerToolbar"><label className="searchField"><span>Search this batch</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search title, ID or domain"/></label><label><span>Domain</span><select value={domain} onChange={event=>setDomain(event.target.value)}><option value="all">All domains</option>{domains.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Wave</span><select value={wave} onChange={event=>setWave(event.target.value)}><option value="all">All waves</option>{waves.map(item=><option key={item} value={item}>Wave {item}</option>)}</select></label><label><span>Status</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Dependency</span><select value={dependency} onChange={event=>setDependency(event.target.value)}><option value="all">All dependencies</option><option value="external">External service likely</option><option value="ai">Uses AI</option><option value="professional">Professional / authority</option></select></label><label><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="priority">Priority</option><option value="title">Title</option><option value="wave">Wave</option></select></label><label><span>View</span><select value={density} onChange={event=>setDensity(event.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="checkFilter"><input type="checkbox" checked={gateOnly} onChange={event=>setGateOnly(event.target.checked)}/><span>Professional gate</span></label><label className="checkFilter"><input type="checkbox" checked={savedOnly} onChange={event=>setSavedOnly(event.target.checked)}/><span>Shortlist ({saved.length})</span></label></div>
    <div className="explorerResults"><p role="status" aria-live="polite"><b>{visible.length}</b> of {features.length} records shown</p><div><span className="urlState">Filters update this page’s shareable URL.</span><button type="button" onClick={copyView}>Copy filtered URL</button><button type="button" onClick={clear}>Clear filters</button></div></div>
    {batchSaved.length>0?<aside className="shortlistSummary" aria-label="Shortlist summary"><div><b>{batchSaved.length} shortlisted in this batch</b><span>{batchSaved.filter(item=>item.professionalGate).length} gated · {batchSaved.filter(item=>item.external).length} external-service candidates</span></div><div className="shortlistExports"><button type="button" onClick={exportJson}>Export JSON</button><button type="button" onClick={exportCsv}>Export CSV</button></div></aside>:null}<p className="srOnly" role="status" aria-live="polite">{message}</p>
    {visible.length?<div className="priorityFeatureGrid">{visible.map(item=>{const number=features.findIndex(feature=>feature.id===item.id)+startIndex;return <article key={item.id}><div className="featureCardTop"><span>#{String(number).padStart(3,"0")}</span><button type="button" className={saved.includes(item.id)?"saved":""} aria-pressed={saved.includes(item.id)} onClick={()=>toggle(item.id)}>{saved.includes(item.id)?"★ Shortlisted":"☆ Shortlist"}</button></div><h2>{item.title}</h2><p>{item.description||"Canonical capability record; acceptance criteria remain in repository context."}</p><div className="featureMeta"><span>{item.domain.replaceAll("_"," ")}</span><span>Wave {item.wave}</span><span>Priority {item.score}</span><span>{item.status}</span></div><details><summary>Delivery + evidence details <span aria-hidden="true">+</span></summary><dl><div><dt>Canonical ID</dt><dd>{item.id}</dd></div><div><dt>Source references</dt><dd>{item.sourceCount}</dd></div><div><dt>Development complexity</dt><dd>{item.developmentComplexity} / 5</dd></div><div><dt>Data provenance burden</dt><dd>{item.provenanceBurden} / 5</dd></div><div><dt>External services likely</dt><dd>{item.external?"Yes — verify provider and current terms":"No known requirement"}</dd></div><div><dt>AI dependency</dt><dd>{item.ai?"Yes — human validation required":"No"}</dd></div><div><dt>Professional / authority gate</dt><dd>{item.professionalGate?"Required":"Not flagged in registry"}</dd></div></dl></details></article>})}</div>:<div className="explorerEmpty"><b>No records match these filters.</b><p>Clear filters or broaden your search.</p><button type="button" className="secondaryButton" onClick={clear}>Show all 100</button></div>}
  </div>;
}
