"use client";

import {useEffect,useMemo,useState} from "react";
import items from "@/data/procurement-items.json";
import needs from "@/data/procurement-needs.json";
import {QuoteComparison} from "@/components/quote-comparison";

const key="mosque-build.procurement.v1";
const regions={global:{label:"Global search",amazon:"www.amazon.com"},us:{label:"United States",amazon:"www.amazon.com"},gb:{label:"United Kingdom",amazon:"www.amazon.co.uk"},ca:{label:"Canada",amazon:"www.amazon.ca"},au:{label:"Australia",amazon:"www.amazon.com.au"},de:{label:"Germany",amazon:"www.amazon.de"},ae:{label:"United Arab Emirates",amazon:"www.amazon.ae"},sa:{label:"Saudi Arabia",amazon:"www.amazon.sa"}} as const;
type RegionId=keyof typeof regions;
const platformLinks=(search:string,region:RegionId)=>[
  {id:"amazon",label:"Amazon",mark:"a",href:`https://${regions[region].amazon}/s?k=${encodeURIComponent(search)}`},
  {id:"temu",label:"Temu",mark:"t",href:`https://www.temu.com/search_result.html?search_key=${encodeURIComponent(search)}`},
  {id:"ebay",label:"eBay",mark:"e",href:`https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(search)}`},
  {id:"alibaba",label:"Alibaba",mark:"A",href:`https://www.alibaba.com/trade/search?SearchText=${encodeURIComponent(search)}`}
];

export function ProcurementWorkspace(){
  const [query,setQuery]=useState(""),[category,setCategory]=useState("All"),[compare,setCompare]=useState<string[]>([]),[pack,setPack]=useState<string[]>([]),[region,setRegion]=useState(""),[marketRegion,setMarketRegion]=useState<RegionId>("global"),[quantity,setQuantity]=useState(""),[notes,setNotes]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||"{}"),handoff=JSON.parse(localStorage.getItem("mosque-build.marketplace-handoff.v1")||"null");setCompare(Array.isArray(saved.compare)?saved.compare:[]);setPack(Array.isArray(saved.pack)?saved.pack:[]);setRegion(typeof saved.region==="string"?saved.region:"");setMarketRegion(saved.marketRegion in regions?saved.marketRegion:"global");setQuantity(typeof handoff?.quantity==="string"?handoff.quantity:typeof saved.quantity==="string"?saved.quantity:"");setNotes(typeof handoff?.notes==="string"?handoff.notes:typeof saved.notes==="string"?saved.notes:"");if(typeof handoff?.query==="string"){setQuery(handoff.query);setCategory(typeof handoff.category==="string"?handoff.category:"All");setMessage(handoff.source==="knowledge-library"?"Knowledge-library gap brief loaded. Verify editions, content review and every marketplace result.":handoff.source==="interior-decoration"?"Interior furnishing brief loaded. Verify dimensions, samples and every marketplace result.":"Interior specification loaded. Verify measurements and every marketplace result.");localStorage.removeItem("mosque-build.marketplace-handoff.v1")}}catch{}},[]);
  const persist=(next:Partial<{compare:string[];pack:string[];region:string;marketRegion:RegionId;quantity:string;notes:string}>)=>{const value={compare,pack,region,marketRegion,quantity,notes,...next};try{localStorage.setItem(key,JSON.stringify(value));dispatchEvent(new Event("mosque-build:project-change"))}catch{}};
  const categories=["All",...new Set(needs.map(item=>item.category))];
  const visibleNeeds=useMemo(()=>needs.filter(item=>(category==="All"||item.category===category)&&`${item.name} ${item.category} ${item.brief} ${item.search}`.toLowerCase().includes(query.toLowerCase().trim())),[query,category]);
  const visibleItems=useMemo(()=>items.filter(item=>`${item.name} ${item.vendor} ${item.category} ${item.use}`.toLowerCase().includes(query.toLowerCase().trim())),[query]);
  const compared=compare.map(id=>items.find(item=>item.id===id)).filter(Boolean) as typeof items;
  const toggleCompare=(id:string)=>{const next=compare.includes(id)?compare.filter(item=>item!==id):compare.length<3?[...compare,id]:compare;setCompare(next);persist({compare:next});if(compare.length>=3&&!compare.includes(id))setMessage("Compare up to three observed records at a time.")};
  const togglePack=(id:string)=>{const next=pack.includes(id)?pack.filter(item=>item!==id):[...pack,id];setPack(next);persist({pack:next})};
  const exportBrief=()=>{const payload={schemaVersion:"mosque.build/procurement-scope@1",status:"executable",exportedAt:new Date().toISOString(),notice:"Planning brief only. No quote, order, approval, availability or supplier commitment.",deliveryRegion:region||"Not specified",quantityOrScope:quantity||"Not specified",requirements:notes||"Not specified",records:pack.map(id=>items.find(item=>item.id===id)).filter(Boolean)};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download="mosque-build-procurement-brief.json";link.click();URL.revokeObjectURL(url);setMessage("Planning brief exported as JSON.")};
  return <section className="procurementWorkspace">
    <div className="sectionHeading"><div><div className="eyebrow dark">DISCOVER + VERIFY + COMPARE</div><h2>Build a procurement brief before contacting suppliers.</h2><p>Start from common mosque needs, compare observed supplier records where available, and verify suitability, documentation, landed cost and availability directly.</p></div><div className="procurementCounts"><b>{compare.length}/3</b><span>compared</span><b>{pack.length}</b><span>in scope brief</span></div></div>
    <div className="procurementTools"><label><span>Search needs and records</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try wudu, accessibility, safety or carpet"/></label><label><span>Need category</span><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label></div>
    <section className="needsCatalog" aria-labelledby="needs-heading"><header><div><small>NEEDS CATALOG</small><h3 id="needs-heading">Define the requirement, then search marketplaces.</h3><p>Lookup buttons open live platform searches. Results are unverified and may include unsuitable, unavailable or misleading listings.</p></div><label>Marketplace region<select value={marketRegion} onChange={event=>{const next=event.target.value as RegionId;setMarketRegion(next);persist({marketRegion:next})}}>{Object.entries(regions).map(([id,value])=><option key={id} value={id}>{value.label}</option>)}</select></label></header>
      {visibleNeeds.length?<div className="needGrid">{visibleNeeds.map(need=><article key={need.id}><div className="needIcon" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M10 17h28l-2 23H12L10 17Z"/><path d="M17 19v-5a7 7 0 0 1 14 0v5"/></svg></div><small>{need.category}</small><h4>{need.name}</h4><p>{need.brief}</p><details><summary>Brief checks</summary><ul>{need.checks.map(check=><li key={check}>{check}</li>)}</ul></details><div className="marketLinks" aria-label={`Search marketplaces for ${need.name}`}>{platformLinks(need.search,marketRegion).map(platform=><a key={platform.id} data-platform={platform.id} href={platform.href} target="_blank" rel="noopener noreferrer" aria-label={`Search ${platform.label} for ${need.name}`}><span aria-hidden="true">{platform.mark}</span>{platform.label}</a>)}</div></article>)}</div>:<div className="workspaceEmpty"><h3>No needs match this search.</h3><p>Clear the filters or try a broader project requirement.</p><button type="button" onClick={()=>{setQuery("");setCategory("All")}}>Show every need</button></div>}
    </section>
    <section className="observedProducts" aria-labelledby="observed-heading"><div className="sectionHeading"><div><small>SOURCED RECORDS</small><h3 id="observed-heading">Compare evidence, not marketplace ranking.</h3><p>{visibleItems.length} of {items.length} repository records shown. These are observations, not recommendations, availability claims, technical approvals or current quotes.</p></div></div><div className="procurementGrid">{visibleItems.map(item=><article key={item.id}><div><small>{item.category} · {item.status.replace("_"," ")}</small><h3>{item.name}</h3><p>{item.vendor}</p></div><p>{item.use}</p><ul>{item.technical.map(point=><li key={point}>{point}</li>)}</ul><dl><div><dt>Observed</dt><dd>{item.observedAt}</dd></div><div><dt>Price evidence</dt><dd>{item.price?`${item.price.currency} ${item.price.amount} · ${item.price.scope}`:"No sourced price"}</dd></div></dl><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Open observed source ↗</a><div className="procurementActions"><button type="button" aria-pressed={compare.includes(item.id)} onClick={()=>toggleCompare(item.id)}>{compare.includes(item.id)?"Comparing ✓":"Compare"}</button><button type="button" aria-pressed={pack.includes(item.id)} onClick={()=>togglePack(item.id)}>{pack.includes(item.id)?"In brief ✓":"Add to brief"}</button></div></article>)}</div></section>
    <p role="status" aria-live="polite">{message}</p>
    {compared.length?<section className="compareTray"><div className="sectionHeading"><div><small>COMPARISON</small><h3>Compare recorded evidence.</h3></div><button type="button" onClick={()=>{setCompare([]);persist({compare:[]})}}>Clear comparison</button></div><div className="compareTable" role="table" aria-label="Product comparison"><div role="row"><b role="columnheader">Field</b>{compared.map(item=><b role="columnheader" key={item.id}>{item.name}</b>)}</div>{[["Vendor",(item:typeof items[number])=>item.vendor],["Category",(item:typeof items[number])=>item.category],["Observed",(item:typeof items[number])=>item.observedAt],["Price evidence",(item:typeof items[number])=>item.price?`${item.price.currency} ${item.price.amount}`:"Not recorded"],["Verification",(item:typeof items[number])=>item.verification.replaceAll("_"," ")]].map(([label,get])=><div role="row" key={String(label)}><b role="rowheader">{String(label)}</b>{compared.map(item=><span role="cell" key={item.id}>{(get as (x:typeof items[number])=>string)(item)}</span>)}</div>)}</div></section>:null}
    <section className="scopeBrief"><div><small>RFQ / SCOPE PREPARATION</small><h3>Package the question before requesting a quote.</h3><p>This export stays on your device until you choose to share it.</p></div><div><label>Delivery geography<input value={region} onChange={event=>{setRegion(event.target.value);persist({region:event.target.value})}} placeholder="Country, city or site"/></label><label>Quantity or scope<input value={quantity} onChange={event=>{setQuantity(event.target.value);persist({quantity:event.target.value})}} placeholder="Describe quantity or measured scope"/></label><label>Requirements and exclusions<textarea value={notes} onChange={event=>{setNotes(event.target.value);persist({notes:event.target.value})}} placeholder="Performance, samples, documents, installation, exclusions…"/></label><button type="button" disabled={!pack.length} onClick={exportBrief}>Export scope brief ({pack.length})</button></div></section>
    <QuoteComparison/>
  </section>
}
