"use client";

import Link from "next/link";import {useEffect,useMemo,useState} from "react";import guides from "@/data/jurisdiction-guides.json";
type Tab="design"|"permits"|"budget"|"build";type State={scenario:string;permitJurisdiction:string;permitDone:string[];allocations:Record<string,number>;phases:Record<string,number>;activity:{text:string;at:string}[]};
const key="mosque-build.control-center.v1";const initial:State={scenario:"community",permitJurisdiction:"ke-nairobi",permitDone:[],allocations:{Site:15,Design:10,Approvals:5,Construction:55,Opening:5,Reserve:10},phases:{Brief:70,Site:25,Design:10,Approvals:0,Construction:0,Handover:0},activity:[]};
const scenarios=[{id:"compact",title:"Compact urban",detail:"Prioritize essential worship and support spaces within a constrained footprint.",capacity:"Lower",phasing:"Simple"},{id:"courtyard",title:"Courtyard mosque",detail:"Organize prayer, learning and community spaces around a shared outdoor room.",capacity:"Medium",phasing:"Flexible"},{id:"community",title:"Community campus",detail:"Plan a broader program with deliberate future phases and operational demands.",capacity:"Higher",phasing:"Complex"}];
const tabs:[Tab,string][]=[["design","Design options"],["permits","Permit record"],["budget","Budget allocation"],["build","Build progress"]];
export function ProjectControlCenter(){const [tab,setTab]=useState<Tab>("design");const [state,setState]=useState<State>(initial);const [ready,setReady]=useState(false);useEffect(()=>{try{const parsed=JSON.parse(localStorage.getItem(key)||"null");if(parsed)setState({...initial,...parsed})}catch{}setReady(true)},[]);const commit=(next:State,message:string)=>{const value={...next,activity:[{text:message,at:new Date().toISOString()},...next.activity].slice(0,12)};setState(value);try{localStorage.setItem(key,JSON.stringify(value))}catch{}};const permits=guides.permits.find(item=>item.id===state.permitJurisdiction)||guides.permits[0];const allocationTotal=Object.values(state.allocations).reduce((sum,value)=>sum+value,0);const phaseAverage=Math.round(Object.values(state.phases).reduce((sum,value)=>sum+value,0)/Object.keys(state.phases).length);const selectedScenario=scenarios.find(item=>item.id===state.scenario)!;
if(!ready)return <div className="controlLoading" role="status">Preparing your project controls…</div>;
return <section className="controlCenter"><div className="controlHeader"><div><div className="eyebrow dark">PROJECT CONTROL CENTER</div><h2>Turn the mockup workflows into project decisions.</h2><p>Private planning state on this device. Nothing here is an approval, quotation, professional calculation or construction record.</p></div><div className="controlSummary"><span><b>{selectedScenario.title}</b>design option</span><span><b>{state.permitDone.length}/{permits.items.length}</b>permit prompts reviewed</span><span><b>{phaseAverage}%</b>average phase input</span></div></div><div className="controlTabs" role="tablist" aria-label="Project controls">{tabs.map(([id,label])=><button key={id} type="button" role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
{tab==="design"?<div className="controlPanel"><div className="panelIntro"><small>OPTION STUDY</small><h3>Compare project forms before committing.</h3><p>These are planning prompts derived from the design mockups, not generated architecture.</p></div><div className="scenarioGrid">{scenarios.map(item=><button type="button" key={item.id} aria-pressed={state.scenario===item.id} onClick={()=>commit({...state,scenario:item.id},`Selected ${item.title} for comparison`)}><span className={`scenarioSketch scenario-${item.id}`} aria-hidden="true"/><small>{item.capacity} capacity · {item.phasing} phasing</small><b>{item.title}</b><p>{item.detail}</p></button>)}</div><div className="panelActions"><Link href="/patterns">Add Islamic pattern studies</Link><Link href="/design">Open full design workflow</Link></div></div>:null}
{tab==="permits"?<div className="controlPanel"><div className="panelIntro"><small>SOURCE-BACKED STARTING POINTS</small><h3>Track what the team has reviewed.</h3><label>Jurisdiction<select value={state.permitJurisdiction} onChange={event=>commit({...state,permitJurisdiction:event.target.value,permitDone:[]},"Changed permit jurisdiction and reset review prompts")}>{guides.permits.map(item=><option key={item.id} value={item.id}>{item.country} — {item.region}</option>)}</select></label></div><div className="permitControlList">{permits.items.map(item=>{const done=state.permitDone.includes(item.title);return <article key={item.title}><button type="button" aria-pressed={done} onClick={()=>commit({...state,permitDone:done?state.permitDone.filter(value=>value!==item.title):[...state.permitDone,item.title]},`${done?"Reopened":"Reviewed"} permit prompt: ${item.title}`)}><span aria-hidden="true">{done?"✓":""}</span></button><div><small>{item.authority}</small><h4>{item.title}</h4><p>{item.when}</p><a href={item.url} target="_blank" rel="noopener noreferrer">Verify source ↗</a></div></article>})}</div><div className="controlBoundary">Reviewed means the team opened or discussed the prompt. It does not mean submitted, compliant or approved. <Link href="/permits">Open permit explorer →</Link></div></div>:null}
{tab==="budget"?<div className="controlPanel"><div className="panelIntro"><small>USER-DEFINED ALLOCATION</small><h3>Give every part of the budget a purpose.</h3><p>Adjust planning percentages. Enter actual cost evidence only in a professionally reviewed cost plan.</p></div><div className="allocationGrid">{Object.entries(state.allocations).map(([name,value])=><label key={name}><span><b>{name}</b><output>{value}%</output></span><input type="range" min="0" max="70" step="1" value={value} onChange={event=>setState({...state,allocations:{...state.allocations,[name]:Number(event.target.value)}})} onPointerUp={()=>commit(state,`Updated ${name} budget allocation`)} onKeyUp={()=>commit(state,`Updated ${name} budget allocation`)}/><i style={{width:`${value}%`}}/></label>)}</div><div className={`allocationTotal${allocationTotal===100?" valid":""}`}><b>{allocationTotal}% allocated</b><span>{allocationTotal===100?"Allocation balances to 100%.":"Adjust the categories until the planning allocation equals 100%."}</span></div><div className="panelActions"><Link href="/funding">Explore funding + waqf structures</Link></div></div>:null}
{tab==="build"?<div className="controlPanel"><div className="panelIntro"><small>PHASE INPUTS</small><h3>Update progress without hiding the evidence gap.</h3><p>These sliders are local planning notes, not certified progress or payment evidence.</p></div><div className="phaseGrid">{Object.entries(state.phases).map(([name,value])=><label key={name}><span><b>{name}</b><output>{value}%</output></span><input type="range" min="0" max="100" step="5" value={value} onChange={event=>setState({...state,phases:{...state.phases,[name]:Number(event.target.value)}})} onPointerUp={()=>commit(state,`Updated ${name} phase progress input`)} onKeyUp={()=>commit(state,`Updated ${name} phase progress input`)}/><i style={{width:`${value}%`}}/></label>)}</div><div className="controlBoundary">Progress needs dated evidence, responsible-party review and separation from payment certification. <Link href="/construction">Open construction workflow →</Link></div></div>:null}
<aside className="activityLog"><div><b>Recent local activity</b><button type="button" onClick={()=>{const next={...state,activity:[]};setState(next);try{localStorage.setItem(key,JSON.stringify(next))}catch{}}}>Clear log</button></div>{state.activity.length?<ol>{state.activity.slice(0,5).map(item=><li key={`${item.at}-${item.text}`}><span>{item.text}</span><time dateTime={item.at}>{new Date(item.at).toLocaleString()}</time></li>)}</ol>:<p>No changes recorded yet. Choose an option or update a control to begin.</p>}</aside></section>}
