"use client";

import {useCallback,useEffect,useState} from "react";
type Diagnostic={label:string;value:string;detail:string;state:"good"|"attention"|"neutral"};

export function PwaDiagnostics(){
  const [items,setItems]=useState<Diagnostic[]>([]);const [checked,setChecked]=useState("");
  const run=useCallback(async()=>{const installed=window.matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone===true;let offlineReady=false;try{offlineReady="serviceWorker" in navigator&&!!(await navigator.serviceWorker.getRegistration())}catch{}let storage="Unavailable";try{if(navigator.storage?.estimate){const estimate=await navigator.storage.estimate();storage=estimate.quota?`${Math.round((estimate.usage||0)/1048576)} MB used of ${Math.round(estimate.quota/1048576)} MB available`:"Available"}}catch{storage="Unavailable in this browser"}setItems([{label:"Connection",value:navigator.onLine?"Online":"Offline",detail:navigator.onLine?"New pages and updates can load.":"Only pages already saved for offline use are expected to open.",state:navigator.onLine?"good":"attention"},{label:"How it opened",value:installed?"From your device":"In a browser tab",detail:installed?"The site is open in its focused app view.":"Use your browser’s install action when available.",state:installed?"good":"neutral"},{label:"Offline access",value:offlineReady?"Ready":process.env.NODE_ENV==="production"?"Not ready yet":"Checked only on the live site",detail:offlineReady?"Previously visited public pages can open without a connection.":process.env.NODE_ENV==="production"?"Reconnect, reload once, and check again.":"Local previews do not keep pages for offline use.",state:offlineReady?"good":"neutral"},{label:"Device storage",value:storage,detail:"Project briefs and feature shortlists stay on this device unless you explicitly export them.",state:"neutral"}]);setChecked(new Date().toLocaleTimeString())},[]);
  useEffect(()=>{void run();const update=()=>void run();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update)}},[run]);
  return <section className="diagnosticPanel" aria-labelledby="diagnostic-heading"><div className="diagnosticHeading"><div><div className="eyebrow dark">LIVE DEVICE CHECK</div><h2 id="diagnostic-heading">What this browser can use now.</h2></div><button type="button" className="secondaryButton" onClick={()=>void run()}>Check again</button></div><div className="diagnosticGrid">{items.map(item=><article key={item.label} data-state={item.state}><span>{item.label}</span><b>{item.value}</b><p>{item.detail}</p></article>)}</div><p className="diagnosticTime" role="status" aria-live="polite">{checked?`Last checked at ${checked}.`:"Checking this device…"}</p></section>
}
