"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {resourceLibrary,resourceStages,type ResourceStage} from "@/data/resource-library";

const savedKey="mosque-build.resource-plan.v1";
export function ResourceHub(){
  const [query,setQuery]=useState("");const [stage,setStage]=useState<"All"|ResourceStage>("All");const [kind,setKind]=useState("All");const [saved,setSaved]=useState<string[]>([]);const [onlySaved,setOnlySaved]=useState(false);const [ready,setReady]=useState(false);
  useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem(savedKey)||"[]"))}catch{}setReady(true)},[]);
  const persist=(next:string[])=>{setSaved(next);try{localStorage.setItem(savedKey,JSON.stringify(next))}catch{}};
  const toggle=(id:string)=>persist(saved.includes(id)?saved.filter(item=>item!==id):[...saved,id]);
  const results=useMemo(()=>{const needle=query.trim().toLowerCase();return resourceLibrary.filter(item=>(stage==="All"||item.stage===stage)&&(kind==="All"||item.kind===kind)&&(!onlySaved||saved.includes(item.id))&&(!needle||`${item.title} ${item.summary} ${item.tags.join(" ")}`.toLowerCase().includes(needle)))},[query,stage,kind,onlySaved,saved]);
  const next=resourceLibrary.find(item=>saved.includes(item.id)===false);
  const reset=()=>{setQuery("");setStage("All");setKind("All");setOnlySaved(false)};
  return <section className="resourceHub" aria-busy={!ready}><div className="resourceToolbar"><label><span>Search the library</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search site, permits, cost, handover…"/></label><label><span>Project stage</span><select value={stage} onChange={event=>setStage(event.target.value as "All"|ResourceStage)}><option>All</option>{resourceStages.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Resource type</span><select value={kind} onChange={event=>setKind(event.target.value)}><option>All</option>{["Guide","Checklist","Tool","Reference"].map(item=><option key={item}>{item}</option>)}</select></label><button type="button" aria-pressed={onlySaved} onClick={()=>setOnlySaved(value=>!value)}>Saved plan · {saved.length}</button></div><div className="resourceResultLine" role="status" aria-live="polite"><span><b>{results.length}</b> of {resourceLibrary.length} resources</span>{next&&saved.length?<span>Suggested next: <b>{next.title}</b></span>:null}</div>{results.length?<div className="workingResourceGrid">{results.map(item=>{const selected=saved.includes(item.id);return <article key={item.id}><header><small>{item.stage} · {item.kind}</small><button type="button" aria-pressed={selected} onClick={()=>toggle(item.id)}><span aria-hidden="true">{selected?"✓":"+"}</span>{selected?"Saved":"Add to plan"}</button></header><h2>{item.title}</h2><p>{item.summary}</p>{item.gate?<div className="resourceGate">Review gate · {item.gate}</div>:null}<div className="resourceTags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div><Link href={item.href}>Open working tool →</Link></article>})}</div>:<div className="galleryEmpty"><h2>No resources match.</h2><p>Change a filter or search term. Your saved plan has not been changed.</p><button type="button" onClick={reset}>Reset filters</button></div>}<aside className="resourcePlanBoundary"><div><b>Your working plan stays on this device.</b><p>Saving a resource records intent only. It does not complete a task, verify evidence or close a professional or authority gate.</p></div>{saved.length?<button type="button" onClick={()=>persist([])}>Clear saved plan</button>:null}</aside></section>
}
