"use client";

import Image from "next/image";import Link from "next/link";import {useMemo,useState} from "react";import frames from "@/data/frame-registry.json";
const families=["All",...new Set(frames.map(frame=>frame.family))];

export function ScreenGallery(){
  const [query,setQuery]=useState("");const [family,setFamily]=useState("All");
  const visible=useMemo(()=>frames.filter(frame=>(family==="All"||frame.family===family)&&`${frame.title} ${frame.family} ${frame.feature_tags.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())),[query,family]);
  const grouped=family==="All"?[...new Set(visible.map(frame=>frame.family))]:[family];
  return <div className="section screenLibrary"><section className="screenTools" aria-label="Concept gallery controls"><label><span>Search concepts</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search design, permits, funding…"/></label><div><span>Project stage</span><div className="screenFilters">{families.map(item=><button type="button" key={item} aria-pressed={family===item} onClick={()=>setFamily(item)}>{item.replaceAll("-"," ")}</button>)}</div></div><p role="status" aria-live="polite"><b>{visible.length}</b> of {frames.length} concepts shown</p></section>{grouped.map(group=>{const items=visible.filter(frame=>frame.family===group);return items.length?<section key={group} className="screenFamily"><header><div><small>PROJECT CONCEPTS</small><h2>{group.replaceAll("-"," ")}</h2></div><span>{items.length} {items.length===1?"concept":"concepts"}</span></header><div className="screenGrid">{items.map((frame,index)=><Link key={frame.id} href={frame.prototype_route} className="screenCard"><div className="screenThumb"><Image src={frame.asset_path} alt={`${frame.title} mosque project concept`} width={frame.width||1536} height={frame.height||1024} sizes="(max-width: 760px) 88vw, (max-width: 1100px) 45vw, 30vw" priority={index===0&&group===grouped[0]}/><span>See concept</span></div><div className="screenCardCopy"><span className="miniTag">{frame.orientation} · visual idea</span><h3>{frame.title}</h3><div className="screenTags">{frame.feature_tags.slice(0,4).map(tag=><i key={tag}>{tag.replaceAll("_"," ")}</i>)}</div><b>Explore what it shows <span aria-hidden="true">↗</span></b></div></Link>)}</div></section>:null})}{!visible.length?<div className="galleryEmpty"><h2>No matching concepts</h2><p>Try another term or choose a different project stage.</p><button type="button" onClick={()=>{setQuery("");setFamily("All")}}>Reset gallery</button></div>:null}</div>
}
