import Link from "next/link";
const socials=[
{name:"X",href:"https://x.com/ummahbuild",path:<path d="M5 4l14 16M19 4L5 20"/>},
{name:"LinkedIn",href:"https://www.linkedin.com/company/ummah-build",path:<><path d="M6 9v11M6 5v.01M10 20V9m0 5a5 5 0 0 1 10 0v6"/></>},
{name:"GitHub",href:"https://github.com/ummahbuild",path:<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7.4A5.8 5.8 0 0 0 19.3 3 5.4 5.4 0 0 0 19.1 0S17.9-.4 15 1.5a14 14 0 0 0-7 0C5.1-.4 3.9 0 3.9 0a5.4 5.4 0 0 0-.2 3A5.8 5.8 0 0 0 2.2 7.1c0 5.8 3.5 7 6.8 7.4A4.8 4.8 0 0 0 8 18v4m0-3c-3 .9-3-1.5-4-2"/>},
{name:"Medium",href:"https://medium.com/@ummahbuild",path:<><path d="M3 6h4l5 11 5-11h4M5 6v12M19 6v12"/></>},
{name:"YouTube",href:"https://www.youtube.com/@ummah_build",path:<><path d="M22 12s0-4-1-5-3-1-6-1-6 0-6 0-4 1-5 1-1 5-1 5 0 4 1 5 3 1 6 1s3 0 6-1c1-1 1-5 1-5Z"/><path d="m10 9 5 3-5 3Z"/></>},
{name:"Substack",href:"https://ummahbuild.substack.com/",path:<><path d="M4 6h16M4 10h16M6 14h12v7l-6-4-6 4Z"/></>}
] as const;
export function SiteFooter(){return <footer className="footer"><div className="footerTop"><Link className="brand footerBrand" href="/"><span className="brandMark" aria-hidden="true">⌂</span><span>mosque<span className="brandDot">.</span>build</span></Link><p>Plan. Design. Approve. Fund. Build. Open. Care.</p></div><div className="footerGrid"><div><b>Your project</b><Link href="/features">How it works</Link><Link href="/my-project">My project</Link><Link href="/design">Design workspace</Link><Link href="/permits">Approval pathway</Link><Link href="/funding">Funding and waqf</Link></div><div><b>Build and operate</b><Link href="/marketplace">Sourcing</Link><Link href="/construction">Construction</Link><Link href="/operations">Opening and operations</Link><Link href="/waqf-library">Qurans and books</Link></div><div><b>Learn and explore</b><Link href="/resources">Working guides</Link><Link href="/patterns">Islamic pattern studies</Link><Link href="/sources">Sources</Link><Link href="/prototypes">Project concepts</Link><Link href="/trust">How information is checked</Link><Link href="/privacy">Privacy</Link><Link href="/accessibility">Accessibility</Link></div><div><b>Get started</b><Link href="/start">Create project brief</Link><a href="mailto:hello@mosque.build">hello@mosque.build</a><Link href="/terms">Terms</Link><Link href="/open-source">Contribute</Link></div></div><div className="footerAttribution"><a className="builtBy" href="https://ummah.build" target="_blank" rel="noopener noreferrer">Built by <b>ummah.build</b></a><nav className="socialLinks" aria-label="ummah.build social channels">{socials.map(social=><a key={social.name} href={social.href} target="_blank" rel="noopener noreferrer" aria-label={`${social.name} — ummah.build`}><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{social.path}</svg></a>)}</nav></div><div className="footerBottom"><span>© mosque.build</span><span>Build the institution, not only the building.</span></div></footer>}
