"use client";
import {useEffect,useRef,useState} from "react";
import {coordinationSummary,createSiteCoordinationModel,modelGaps,type SiteCoordinationInputs,type SiteCoordinationModel,type SiteLayer} from "@/lib/site-coordination-model";
import "./site-three-coordination.css";

declare namespace T { type Material=import("three").Material;type MeshStandardMaterial=import("three").MeshStandardMaterial }

const layers:SiteLayer[]=["site","building","access","solar","constraints","bim"];
const colors:Record<SiteLayer,number>={site:0xb9c5b8,building:0x2f7665,access:0xd39d3e,solar:0x315c88,constraints:0xa9493d,bim:0x725c8c};
function stored(key:string){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
function readInputs():Partial<SiteCoordinationInputs>{
 const q=stored("mosque-build.site-qibla-evidence.v1")||{},plan=stored("mosque-build.schematic-plan.v1")||{},access=stored("mosque-build.site-access-environment.v1")||{},solar=stored("mosque-build.solar-design.v1")||{},floor=stored("mosque-build.floor-plan.v1")||{},analysis=stored("mosque-build.site-analysis.v1")||{};
 return {siteWidthM:Number(q.width)||Math.max(48,Number(plan.widthM)||0),siteDepthM:Number(q.depth)||Math.max(64,Number(plan.depthM)||0),buildingWidthM:Number(plan.widthM)||30,buildingDepthM:Number(plan.depthM)||36,qiblaDeg:Number(q.qiblaBearing)||Number(plan.qiblaDeg)||0,qiblaRef:q.reference||"",boundaryRef:q.reference||"",accessibleRouteRef:access.access?.find((x:{id:string})=>x.id==="access-5")?.evidenceRef||"",parkingSpaces:Number(access.parking?.plannedSpaces)||0,accessibleSpaces:Number(access.parking?.accessibleSpaces)||0,solarZones:Array.isArray(solar.roofZones)?solar.roofZones:[],constraints:Array.isArray(analysis.candidates)?analysis.candidates.flatMap((c:{criteria?:Record<string,{evidenceRef?:string}>})=>Object.entries(c.criteria||{}).filter(([,v])=>v.evidenceRef).slice(0,3).map(([id,v])=>({id,label:id.replaceAll("-"," "),sourceRef:v.evidenceRef||""}))).slice(0,12):[],bimElementCount:Array.isArray(floor.spaces)?floor.spaces.length:0};
}
function download(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="mosque-build-site-coordination.json";a.click();URL.revokeObjectURL(url)}

export function SiteThreeCoordination(){
 const host=useRef<HTMLDivElement>(null),api=useRef<{layer:(l:SiteLayer,on:boolean)=>void;view:(top:boolean)=>void;snapshot:()=>void}|null>(null);
 const [model,setModel]=useState<SiteCoordinationModel|null>(null),[visible,setVisible]=useState<Record<SiteLayer,boolean>>({site:true,building:true,access:true,solar:true,constraints:true,bim:true}),[selected,setSelected]=useState(""),[status,setStatus]=useState("Preparing site coordination model…");
 useEffect(()=>{let disposed=false,clean=()=>{};
  void(async()=>{try{
   const T=await import("three"),{OrbitControls}=await import("three/examples/jsm/controls/OrbitControls.js");if(disposed||!host.current)return;
   const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf4f1e9);renderer.outputColorSpace=T.SRGBColorSpace;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute("aria-label","Interactive conceptual site coordination model");host.current.replaceChildren(renderer.domElement);
   const scene=new T.Scene(),camera=new T.PerspectiveCamera(45,1,.1,1000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=!matchMedia("(prefers-reduced-motion: reduce)").matches;scene.add(new T.HemisphereLight(0xffffff,0x385147,2));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(-30,70,25);scene.add(sun);
   let group=new T.Group(),current=createSiteCoordinationModel(readInputs());
   const drawFeature=(f:SiteCoordinationModel["features"][number])=>{const material=new T.MeshStandardMaterial({color:colors[f.layer],roughness:.72,transparent:true,opacity:f.evidence==="unknown"?.46:.82});let mesh:import("three").Mesh;if(f.kind==="area"){const [a,b]=f.points;mesh=new T.Mesh(new T.BoxGeometry(Math.max(.1,b[0]-a[0]),Math.max(.05,f.heightM),Math.max(.1,b[2]-a[2])),material);mesh.position.set((a[0]+b[0])/2,a[1]+f.heightM/2,(a[2]+b[2])/2)}else if(f.kind==="route"||f.kind==="axis"){const curve=new T.CatmullRomCurve3(f.points.map(p=>new T.Vector3(...p)));mesh=new T.Mesh(new T.TubeGeometry(curve,Math.max(2,f.points.length*8),f.kind==="axis"?.11:.22,8,false),material)}else{const p=f.points[0];mesh=new T.Mesh(new T.CylinderGeometry(.35,.35,f.heightM,12),material);mesh.position.set(p[0],p[1]+f.heightM/2,p[2])}mesh.userData={...f};group.add(mesh)};
   const load=()=>{scene.remove(group);group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose()}});group=new T.Group();current=createSiteCoordinationModel(readInputs());current.features.forEach(drawFeature);scene.add(group);setModel(current);setSelected("");setStatus("Site, access, solar and BIM coordination study ready")};load();
   const fit=(top=false)=>{const box=new T.Box3().setFromObject(group),center=box.getCenter(new T.Vector3()),size=Math.max(...box.getSize(new T.Vector3()).toArray(),10);controls.target.copy(center);camera.position.copy(top?new T.Vector3(center.x,center.y+size*1.7,center.z+.01):new T.Vector3(center.x+size,center.y+size*.8,center.z+size));camera.up.set(0,1,top?-1:0);camera.far=size*10;camera.updateProjectionMatrix();controls.update()};fit();
   const ray=new T.Raycaster(),pointer=new T.Vector2(),pick=(e:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(group.children).find(x=>x.object.visible);group.traverse(o=>{if(o instanceof T.Mesh)(o.material as T.MeshStandardMaterial).emissive.setHex(o===hit?.object?0x5a4310:0)});setSelected(hit?.object.userData.id||"");setStatus(hit?`${hit.object.userData.label} selected`:"Selection cleared")};renderer.domElement.addEventListener("pointerdown",pick);
   const resize=()=>{if(!host.current)return;renderer.setSize(host.current.clientWidth,host.current.clientHeight,false);camera.aspect=host.current.clientWidth/Math.max(1,host.current.clientHeight);camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host.current);resize();let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)};animate();
   api.current={layer:(l,on)=>{group.children.forEach(o=>{if(o.userData.layer===l)o.visible=on});setStatus(`${l} layer ${on?"shown":"hidden"}`)},view:fit,snapshot:()=>{renderer.render(scene,camera);const a=document.createElement("a");a.href=renderer.domElement.toDataURL("image/png");a.download="mosque-build-site-coordination.png";a.click();setStatus("Coordination image exported")}};
   const refresh=()=>load();addEventListener("mosque-build:project-change",refresh);clean=()=>{removeEventListener("mosque-build:project-change",refresh);cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener("pointerdown",pick);controls.dispose();group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose()}});renderer.dispose()};
  }catch(e){setStatus(e instanceof Error?`Site model unavailable: ${e.message}`:"Site model unavailable")}})();return()=>{disposed=true;clean()}},[]);
 const summary=model&&coordinationSummary(model),chosen=model?.features.find(f=>f.id===selected);
 return <section className="siteThree" aria-labelledby="site-three-title"><header><div><div className="eyebrow dark">SITE + BUILDING COORDINATION</div><h2 id="site-three-title">See access, solar and BIM context together.</h2><p>A shared anonymous local origin reveals relationships without requesting coordinates or claiming measured geometry.</p></div><div className="siteThreePulse"><b>{summary?.features||0}</b><span>coordination features</span><small>{summary?.referenced||0} referenced · {summary?.unknown||0} unknown</small></div></header><div className="siteThreeLayout"><div><div ref={host} className="siteThreeCanvas"/><p role="status" aria-live="polite">{status}</p><div className="siteViewButtons"><button type="button" onClick={()=>api.current?.view(false)}>Isometric</button><button type="button" onClick={()=>api.current?.view(true)}>Site plan</button><button type="button" onClick={()=>api.current?.snapshot()}>Export image</button><button type="button" disabled={!model} onClick={()=>model&&download({...model,summary,gaps:modelGaps(model)})}>Export model</button></div></div><aside><h3>Coordination layers</h3>{layers.map(layer=><label key={layer}><input type="checkbox" checked={visible[layer]} onChange={e=>{const next={...visible,[layer]:e.target.checked};setVisible(next);api.current?.layer(layer,e.target.checked)}}/><span><b>{layer}</b><small>{summary?.byLayer[layer]||0} features</small></span></label>)}{chosen?<dl><dt>Selected</dt><dd>{chosen.label}</dd><dt>Evidence</dt><dd>{chosen.evidence}</dd><dt>Source reference</dt><dd>{chosen.sourceRef||"Not recorded"}</dd></dl>:<p>Select a feature to inspect its evidence state.</p>}</aside></div>{model&&<div className="siteThreeGaps"><b>Evidence still needed</b><p>{modelGaps(model).length?modelGaps(model).join(" · "):"Core references are present; professional review still applies."}</p></div>}<footer><b>Coordination boundary</b><p>Routes are planning polylines, solar areas are study overlays, markers are prompts and BIM is mapping preparation. Verify survey control, gradients, clearances, accessible parking, shading, structure, drainage, fire access, energy performance and exchange deliverables with qualified reviewers.</p></footer></section>
}
