"use client";

import {useMemo,useState} from "react";

export type SourceRecord={id:string;name:string;url:string;status:string;type:string;uses:string[];rightsNote:string;sourceFile:string};
export type PartnerBrief={id:string;region:string;category:string;targetCount:number;status:string;required:string;sourceFile:string};

export function SourcePartnerGallery({sources,partners}:{sources:SourceRecord[];partners:PartnerBrief[]}){
  const [view,setView]=useState<"sources"|"partners">("sources");const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");
  const options=useMemo(()=>view==="sources"?[...new Set(sources.map(item=>item.status))].sort():[...new Set(partners.map(item=>item.region))].sort(),[view,sources,partners]);
  const visibleSources=useMemo(()=>sources.filter(item=>(filter==="all"||item.status===filter)&&(!query||`${item.name} ${item.type} ${item.uses.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[sources,filter,query]);
  const visiblePartners=useMemo(()=>partners.filter(item=>(filter==="all"||item.region===filter)&&(!query||`${item.region} ${item.category}`.toLowerCase().includes(query.toLowerCase()))),[partners,filter,query]);
  const count=view==="sources"?visibleSources.length:visiblePartners.length;
  const changeView=(next:"sources"|"partners")=>{setView(next);setFilter("all");setQuery("")};
  return <div className="sourceGallery"><div className="galleryTabs" role="tablist" aria-label="Gallery type"><button type="button" role="tab" aria-selected={view==="sources"} onClick={()=>changeView("sources")}>Named sources <span>{sources.length}</span></button><button type="button" role="tab" aria-selected={view==="partners"} onClick={()=>changeView("partners")}>Partner discovery briefs <span>{partners.length}</span></button></div><div className="galleryFilters"><label><span>Search {view}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={view==="sources"?"Name, type or use":"Region or goods category"}/></label><label><span>{view==="sources"?"Recorded status":"Region"}</span><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All {view==="sources"?"statuses":"regions"}</option>{options.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label></div><div className="galleryCount" role="status" aria-live="polite"><b>{count}</b> records shown</div>{view==="sources"?<div className="sourceCardGrid">{visibleSources.map(item=><article key={`${item.sourceFile}:${item.id}`}><div className="recordTop"><span>{item.type.replaceAll("_"," ")}</span><b>{item.status.replaceAll("_"," ")}</b></div><h2>{item.name}</h2><div className="recordTags">{item.uses.slice(0,4).map(use=><span key={use}>{use.replaceAll("_"," ")}</span>)}</div><p>{item.rightsNote}</p><details><summary>Provenance details</summary><dl><div><dt>Record ID</dt><dd>{item.id}</dd></div><div><dt>Repository source</dt><dd>{item.sourceFile}</dd></div></dl></details><a href={item.url} target="_blank" rel="noopener noreferrer">Open recorded source <span className="srOnly">for {item.name} (opens in a new tab)</span> ↗</a></article>)}</div>:<div className="partnerCardGrid">{visiblePartners.map(item=><article key={item.id}><div className="recordTop"><span>{item.region}</span><b>{item.status.replaceAll("_"," ")}</b></div><h2>{item.category.replaceAll("_"," ")}</h2><p>Research target: up to {item.targetCount} candidate records. This is not a verified partner listing or endorsement.</p><div className="verificationBox"><b>Required before listing</b><span>{item.required}</span></div><details><summary>Queue provenance</summary><dl><div><dt>Brief ID</dt><dd>{item.id}</dd></div><div><dt>Repository source</dt><dd>{item.sourceFile}</dd></div></dl></details></article>)}</div>}{count===0&&<div className="explorerEmpty"><b>No records match.</b><p>Clear the search or select a broader filter.</p><button type="button" className="secondaryButton" onClick={()=>{setQuery("");setFilter("all")}}>Show all records</button></div>}</div>
}
