"use client";

import Link from "next/link";
import {useEffect, useMemo, useRef, useState} from "react";

type Draft={name:string;type:string;location:string;stage:string;land:string;attendance:string;budget:string;currency:string;timeline:string;needs:string[];priorities:string[];constraints:string[];governance:string;owner:string;team:string[];funding:string[];notes:string;email:string};
const key="mosque-build.project-draft.v2";
const stepKey="mosque-build.project-step.v1";
const steps=["Project","Community","Site + constraints","Team + funding","Review","First plan"];
const needs=["Prayer hall","Women / family","Wudu","Madrasa / classrooms","Youth","Community hall","Janazah","Accessibility","Library","Kitchen / iftar","Parking","Waqf / income-generating space"];
const priorities=["Clarity on next steps","Community brief","Site feasibility","Design options","Permit path","Cost reality","Fundraising structure","Products / suppliers","Construction control","Opening + operations"];
const constraints=["No known constraints yet","Site not secured","Planning / permit uncertainty","Limited budget evidence","Fundraising not started","Professional team not appointed","Utilities unknown","Access / parking concern","Existing building condition unknown"];
const roles=["Community lead","Trustee / board","Imam / religious reviewer","Architect","Engineer","Quantity surveyor / cost professional","Planner / permit professional","Fundraising lead","Operations lead"];
const funding=["Community donations","Major gifts","Monthly pledges","Grants","Qard hasan","Waqf income","Asset sale","Institutional finance","Not decided"];
const defaults:Draft={name:"",type:"New mosque",location:"",stage:"Idea / community need",land:"Not yet",attendance:"",budget:"",currency:"",timeline:"Not set",needs:["Prayer hall","Wudu"],priorities:["Clarity on next steps"],constraints:["Site not secured","Limited budget evidence","Professional team not appointed"],governance:"Informal working group",owner:"",team:["Community lead"],funding:["Community donations","Not decided"],notes:"",email:""};
const toggle=(list:string[],item:string)=>list.includes(item)?list.filter(value=>value!==item):[...list,item];

function Choices({legend,options,value,onChange}:{legend:string;options:string[];value:string[];onChange:(value:string[])=>void}){return <fieldset className="choiceFieldset"><legend>{legend}</legend><div className="needGrid compactChoices">{options.map(item=><button type="button" key={item} aria-pressed={value.includes(item)} className={value.includes(item)?"selected":""} onClick={()=>onChange(toggle(value,item))}>{value.includes(item)?"✓ ":""}{item}</button>)}</div></fieldset>}

export function StartProjectWizard(){
  const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(defaults);const [ready,setReady]=useState(false);const [saved,setSaved]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{try{const raw=localStorage.getItem(key)??localStorage.getItem("mosquebuild.projectDraft");if(raw){const parsed=JSON.parse(raw);const restored={...defaults,...parsed,name:parsed.name??parsed.projectName??"",type:parsed.type??parsed.projectType??defaults.type};setDraft(restored);const stored=Number(localStorage.getItem(stepKey));const complete=!!(restored.name.trim()&&restored.location.trim()&&restored.needs.length&&restored.priorities.length&&restored.constraints.length&&restored.owner.trim()&&restored.team.length&&restored.funding.length);setStep(complete?5:Number.isInteger(stored)?Math.max(0,Math.min(5,stored)):0)}}catch{}finally{setReady(true)}},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(key,JSON.stringify(draft));setSaved(true);const timer=setTimeout(()=>setSaved(false),1000);return()=>clearTimeout(timer)}catch{}},[draft,ready]);
  const set=<K extends keyof Draft>(field:K,value:Draft[K])=>setDraft(current=>({...current,[field]:value}));
  const completion=useMemo(()=>Math.round([draft.name,draft.location,draft.attendance,draft.budget,draft.needs.length,draft.priorities.length,draft.constraints.length,draft.owner,draft.team.length,draft.funding.length].filter(Boolean).length/10*100),[draft]);
  const actions=useMemo(()=>{const list:string[]=[];if(!draft.owner.trim())list.push("Name the accountable community decision-maker and record how decisions will be approved.");if(["Not yet","Site under consideration"].includes(draft.land))list.push("Complete a site-screening brief before detailed design or publishing a fundraising rendering.");if(draft.constraints.includes("Planning / permit uncertainty"))list.push("Create a source-backed list of likely applicable requirements, then verify it with the relevant authority or professional.");if(!draft.team.includes("Architect"))list.push("Prepare an architect appointment brief covering scope, deliverables, review gates and information ownership.");if(!draft.team.some(x=>x.includes("cost professional")))list.push("Establish a cost baseline with geography, currency, date, source, maturity, confidence and exclusions.");if(!draft.budget.trim())list.push("Set a working affordability range before selecting a design scenario or fundraising target.");if(draft.needs.includes("Accessibility"))list.push("Include disabled worshippers and an accessibility professional in program and route reviews.");if(draft.funding.includes("Waqf income"))list.push("Separate waqf governance and jurisdiction-specific legal review from general fundraising.");return list.slice(0,7)},[draft]);
  const gates=["Permit requirements are likely applicable until verified with the authority or a qualified professional.","Structural, MEP and fire outputs remain conceptual until qualified professional review.","Costs require geography, currency, date, source, maturity, confidence and exclusions.","Religious content and decisions require source metadata and qualified review."];
  const brief={schema:"mosque.build/project-brief@1",status:"scaffolded",generatedAt:new Date().toISOString(),project:draft,completion,recommendations:actions,reviewGates:gates};
  const can=[!!(draft.name.trim()&&draft.location.trim()),!!(draft.needs.length&&draft.priorities.length),draft.constraints.length>0,!!(draft.owner.trim()&&draft.team.length&&draft.funding.length),true,true][step];
  const missing=useMemo(()=>{
    const items:string[]=[];
    if(step===0){if(!draft.name.trim())items.push("project name");if(!draft.location.trim())items.push("city, region or country")}
    if(step===1){if(!draft.needs.length)items.push("at least one required space or program");if(!draft.priorities.length)items.push("at least one first priority")}
    if(step===2&&!draft.constraints.length)items.push("at least one known constraint, or “No known constraints yet”")
    if(step===3){if(!draft.owner.trim())items.push("accountable decision-maker");if(!draft.team.length)items.push("at least one team role");if(!draft.funding.length)items.push("at least one funding path")}
    return items;
  },[step,draft]);
  const stepComplete=[!!(draft.name.trim()&&draft.location.trim()),!!(draft.needs.length&&draft.priorities.length),draft.constraints.length>0,!!(draft.owner.trim()&&draft.team.length&&draft.funding.length),true,step===5];
  const move=(next:number)=>{const value=Math.max(0,Math.min(steps.length-1,next));setStep(value);try{localStorage.setItem(stepKey,String(value))}catch{}requestAnimationFrame(()=>heading.current?.focus())};
  const download=()=>{const blob=new Blob([JSON.stringify(brief,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${(draft.name||"mosque-build-project").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-brief.json`;a.click();URL.revokeObjectURL(url)};
  const reset=()=>{if(!window.confirm("Reset this local project brief? This cannot be undone."))return;localStorage.removeItem(key);localStorage.removeItem("mosquebuild.projectDraft");localStorage.removeItem("mosque-build.project-progress.v1");localStorage.removeItem(stepKey);setDraft(defaults);move(0)};
  if(!ready)return <div className="wizard wizardLoading" role="status" aria-live="polite"><div><span className="loadingPulse" aria-hidden="true"/><b>Loading your private project brief…</b><p>Checking for a draft saved on this device.</p></div></div>;
  return <div className="wizard"><aside className="wizardRail" aria-label="Project brief progress"><div><b>mosque.build project brief</b><p>{completion}% complete · saved only on this device</p><div className="progressTrack" aria-hidden="true"><span style={{width:`${completion}%`}}/></div></div>{steps.map((label,index)=><button type="button" key={label} className={index===step?"active":stepComplete[index]?"complete":""} aria-current={index===step?"step":undefined} aria-label={`${label}: ${index===step?"current step":stepComplete[index]?"requirements complete":"needs information"}`} onClick={()=>move(index)}><span>{stepComplete[index]&&index!==step?"✓":index+1}</span><span className="wizardStepLabel">{label}<small>{index===step?"Current":stepComplete[index]?"Ready":"Needs information"}</small></span></button>)}<small aria-live="polite">{saved?"Draft saved locally":"Private draft · not submitted"}</small></aside><div className="wizardMain">
    {step===0&&<section><div className="eyebrow dark">01 · PROJECT</div><h2 ref={heading} tabIndex={-1}>Name the project and its current reality.</h2><p className="sectionLead">A clear brief starts with what is known now—not with an assumed building solution.</p><div className="fieldGrid"><label>Project name<input required value={draft.name} onChange={e=>set("name",e.target.value)} placeholder="e.g. Community Mosque Project"/></label><label>Project type<select value={draft.type} onChange={e=>set("type",e.target.value)}><option>New mosque</option><option>Mosque expansion</option><option>Adaptive reuse / conversion</option><option>Prayer room / musalla</option><option>Mosque + madrasa</option><option>Community center</option><option>Phased campus</option></select></label><label>City / region / country<input required value={draft.location} onChange={e=>set("location",e.target.value)} placeholder="Enter only the location detail needed for planning" autoComplete="off"/></label><label>Current stage<select value={draft.stage} onChange={e=>set("stage",e.target.value)}><option>Idea / community need</option><option>Searching for site</option><option>Site identified</option><option>Design started</option><option>Permitting</option><option>Fundraising</option><option>Construction</option><option>Existing mosque / operations</option></select></label></div></section>}
    {step===1&&<section><div className="eyebrow dark">02 · COMMUNITY</div><h2 ref={heading} tabIndex={-1}>Define who and what the mosque must serve.</h2><div className="fieldGrid"><label>Expected Jumu’ah attendance<input inputMode="numeric" value={draft.attendance} onChange={e=>set("attendance",e.target.value)} placeholder="e.g. 350"/></label></div><Choices legend="Required programs and spaces" options={needs} value={draft.needs} onChange={value=>set("needs",value)}/><Choices legend="First priorities" options={priorities} value={draft.priorities} onChange={value=>set("priorities",value)}/></section>}
    {step===2&&<section><div className="eyebrow dark">03 · SITE + CONSTRAINTS</div><h2 ref={heading} tabIndex={-1}>Record uncertainty before it becomes rework.</h2><div className="fieldGrid"><label>Land / building status<select value={draft.land} onChange={e=>set("land",e.target.value)}><option>Not yet</option><option>Site under consideration</option><option>Land owned</option><option>Existing building</option><option>Existing mosque</option></select></label><label>Target timeline<select value={draft.timeline} onChange={e=>set("timeline",e.target.value)}><option>Not set</option><option>Under 12 months</option><option>1–2 years</option><option>2–5 years</option><option>More than 5 years</option><option>Phased / ongoing</option></select></label><label>Working budget<input value={draft.budget} onChange={e=>set("budget",e.target.value)} placeholder="Enter a planning range or unknown"/></label><label>Currency<select required value={draft.currency} onChange={e=>set("currency",e.target.value)}><option value="">Select currency</option><option>USD</option><option>GBP</option><option>EUR</option><option>AED</option><option>SAR</option><option>Other / mixed</option></select></label></div><Choices legend="Known constraints" options={constraints} value={draft.constraints} onChange={value=>set("constraints",value)}/><div className="infoBox"><b>Verification boundary</b><p>Any permit items are <strong>likely applicable / verify with authority or professional</strong>. Site, structural, MEP and fire conclusions remain conceptual until qualified review.</p></div></section>}
    {step===3&&<section><div className="eyebrow dark">04 · TEAM + FUNDING</div><h2 ref={heading} tabIndex={-1}>Make accountability visible early.</h2><div className="fieldGrid"><label>Governance state<select value={draft.governance} onChange={e=>set("governance",e.target.value)}><option>Informal working group</option><option>Registered charity / nonprofit</option><option>Mosque board / trustees</option><option>Existing institution</option><option>Waqf structure under review</option><option>Other / not decided</option></select></label><label>Accountable decision-maker<input required value={draft.owner} onChange={e=>set("owner",e.target.value)} placeholder="Name or role"/></label><label>Email for handoff (optional)<input type="email" value={draft.email} onChange={e=>set("email",e.target.value)} placeholder="you@example.com"/></label></div><Choices legend="Roles already involved" options={roles} value={draft.team} onChange={value=>set("team",value)}/><Choices legend="Funding paths being considered" options={funding} value={draft.funding} onChange={value=>set("funding",value)}/></section>}
    {step===4&&<section><div className="eyebrow dark">05 · REVIEW</div><h2 ref={heading} tabIndex={-1}>Add local knowledge and review the brief.</h2><label className="notesField">Context, concerns, commitments or open questions<textarea rows={7} value={draft.notes} onChange={e=>set("notes",e.target.value)} placeholder="What would a new architect, trustee or community reviewer need to know?"/></label><div className="reviewGrid"><article><small>PROJECT</small><b>{draft.name||"Name needed"}</b><span>{draft.type} · {draft.location||"Location needed"}</span></article><article><small>COMMUNITY</small><b>{draft.attendance||"?"} Jumu’ah</b><span>{draft.needs.length} program needs</span></article><article><small>DELIVERY</small><b>{draft.stage}</b><span>{draft.team.length} roles involved</span></article><article><small>AFFORDABILITY</small><b>{draft.budget?`${draft.currency} ${draft.budget}`:"Range needed"}</b><span>{draft.funding.length} funding paths</span></article></div><div className="infoBox"><b>Before relying on this brief</b><p>Confirm representation, site facts, governance authority, privacy expectations and professional appointments. This local draft has not been submitted or externally verified.</p></div></section>}
    {step===5&&<section><div className="eyebrow dark">06 · FIRST PLAN</div><h2 ref={heading} tabIndex={-1}>{draft.name||"Your mosque project"}</h2><div className="briefGrid"><div><small>Location</small><b>{draft.location||"To confirm"}</b></div><div><small>Stage</small><b>{draft.stage}</b></div><div><small>Site</small><b>{draft.land}</b></div><div><small>Jumu’ah</small><b>{draft.attendance||"To estimate"}</b></div><div><small>Brief</small><b>{completion}% complete</b></div></div><h3>Recommended next actions</h3><ol className="actionPlan">{actions.length?actions.map(item=><li key={item}>{item}</li>):<li>Review and confirm this brief with accountable community and professional stakeholders.</li>}</ol><h3>Review gates</h3><div className="gateList">{gates.map(gate=><p key={gate}><span aria-hidden="true">!</span>{gate}</p>)}</div><div className="downloadActions"><Link className="button" href="/my-project">Open my project workspace →</Link><button type="button" className="secondaryButton" onClick={download}>Download structured brief</button><button type="button" className="secondaryButton" onClick={()=>window.print()}>Print / save as PDF</button><button type="button" className="textDanger" onClick={reset}>Reset local draft</button></div></section>}
    <div className="wizardActionArea">{step<steps.length-1&&<div id="step-requirements" className={`wizardRequirement ${can?"ready":"blocked"}`} role="status" aria-live="polite"><span aria-hidden="true">{can?"✓":"!"}</span><p>{can?<><b>Ready to continue.</b> You can still return and refine this step.</>:<><b>Complete this step to continue:</b> {missing.join(", ")}.</>}</p></div>}<div className="wizardActions"><div><button type="button" className="secondaryButton" disabled={step===0} aria-describedby={step===0?"back-explanation":undefined} onClick={()=>move(step-1)}>Back</button>{step===0&&<small id="back-explanation">You are at the first step.</small>}</div>{step<steps.length-1&&<button type="button" className="button" disabled={!can} aria-describedby="step-requirements" onClick={()=>move(step+1)}>{step===steps.length-2?"Build first plan →":"Continue →"}</button>}</div></div>
  </div></div>
}
