"use client";

import {useEffect,useId,useRef,useState} from "react";
import {createSchematicPlan,type SchematicInputs} from "@/lib/schematic-plan";
import {createRenderModel,type RenderBox} from "@/lib/render-model";
import "./three-schematic-viewer.css";
import "./three-model-inspector.css";

type Api={view:(mode:"iso"|"top"|"front")=>void;select:(id:string)=>void;explode:(n:number)=>void;wire:(on:boolean)=>void;save:()=>void;restore:()=>void;snapshot:()=>void;glb:()=>void};
const planKey="mosque-build.schematic-plan.v1",viewKey="mosque-build.model-view.v1";
const initial:SchematicInputs={scenario:"community",widthM:30,depthM:36,wallM:.25,qiblaDeg:58,verification:"user_estimate"};

export function ThreeSchematicViewer(){
  const titleId=useId(),host=useRef<HTMLDivElement>(null),api=useRef<Api|null>(null);
  const [status,setStatus]=useState("Preparing interactive model…"),[rooms,setRooms]=useState<RenderBox[]>([]),[selected,setSelected]=useState<RenderBox|null>(null),[explode,setExplode]=useState(0),[wire,setWire]=useState(false);
  useEffect(()=>{let dead=false,cleanup=()=>{};void(async()=>{try{
    const T=await import("three"),{OrbitControls}=await import("three/examples/jsm/controls/OrbitControls.js"),{GLTFExporter}=await import("three/examples/jsm/exporters/GLTFExporter.js"),{buildThreeGroup,disposeThreeTree}=await import("@/lib/three-scene-adapter");if(dead||!host.current)return;
    const renderer=new T.WebGLRenderer({antialias:true,powerPreference:"high-performance",preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf4f1e9);renderer.shadowMap.enabled=true;renderer.outputColorSpace=T.SRGBColorSpace;host.current.replaceChildren(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute("aria-label","Interactive conceptual mosque model. Select rooms using pointer or the room list.");
    const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,300),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=8;controls.maxDistance=140;scene.add(new T.HemisphereLight(0xffffff,0x385147,2),new T.GridHelper(140,70,0x789086,0xcbd5d0));const sun=new T.DirectionalLight(0xfff2d0,3);sun.position.set(-25,45,-20);sun.castShadow=true;scene.add(sun);
    let group:ReturnType<typeof buildThreeGroup>|null=null,modelRooms:RenderBox[]=[];const raycaster=new T.Raycaster(),pointer=new T.Vector2();
    const select=(id:string)=>{if(!group)return;group.traverse(object=>{if(!(object instanceof T.Mesh))return;const material=object.material as import("three").MeshStandardMaterial,active=object.userData.sourceId===id;material.emissive.setHex(active?0x735515:0);material.emissiveIntensity=active?.35:0});const room=modelRooms.find(item=>item.id===id)??null;setSelected(room);setStatus(room?`${room.label} selected`:"Selection cleared")};
    const load=()=>{if(group){scene.remove(group);disposeThreeTree(group)}let stored={},lineageId:string|undefined;try{stored=JSON.parse(localStorage.getItem(planKey)||"{}")??{};lineageId=JSON.parse(localStorage.getItem("mosque-build.architecture-direction.v1")||"null")?.lineageId}catch{}const model=createRenderModel(createSchematicPlan({...initial,...stored}),lineageId);modelRooms=model.boxes.filter(box=>box.id!=="site");setRooms(modelRooms);setSelected(null);group=buildThreeGroup(model);scene.add(group);controls.target.set(model.footprint[0]/2,0,model.footprint[1]/2);camera.position.set(model.footprint[0]*1.25,Math.max(30,model.footprint[1]),model.footprint[1]*1.35);controls.update()};load();
    const frameModel=()=>{if(!group)return null;const bounds=new T.Box3().setFromObject(group);return {center:bounds.getCenter(new T.Vector3()),distance:Math.max(...bounds.getSize(new T.Vector3()).toArray())*1.3}};
    const view=(mode:"iso"|"top"|"front")=>{const frame=frameModel();if(!frame)return;const {center,distance:d}=frame;controls.target.copy(center);camera.up.set(0,mode==="top"?0:1,mode==="top"?-1:0);camera.position.set(mode==="top"?center.x:mode==="front"?center.x:center.x+d,mode==="top"?d*1.5:center.y+(mode==="front"?d*.1:d),mode==="top"?center.z:center.z+d);controls.update();setStatus(`${mode} view applied`)};
    const pick=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(group?.children??[]).find(result=>typeof result.object.userData.sourceId==="string"&&result.object.userData.sourceId!=="site");if(hit)select(hit.object.userData.sourceId)};renderer.domElement.addEventListener("pointerdown",pick);
    const resize=()=>{if(!host.current)return;const w=host.current.clientWidth,h=host.current.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host.current);resize();let animation=0;const draw=()=>{animation=requestAnimationFrame(draw);controls.update();renderer.render(scene,camera)};draw();
    api.current={view,select,explode:n=>{group?.children.forEach((child,index)=>{if(child.userData.sourceId!=="site")child.position.y=Number(child.userData.baseY)+(index%3)*n*.8});setStatus(n?`Volumes separated by ${n} study steps`:"Volumes returned to plan level")},wire:on=>{group?.traverse(object=>{if(object instanceof T.Mesh)(object.material as import("three").MeshStandardMaterial).wireframe=on});setStatus(on?"Edge study enabled":"Solid study enabled")},save:()=>{localStorage.setItem(viewKey,JSON.stringify({position:camera.position.toArray(),target:controls.target.toArray()}));setStatus("Viewpoint saved on this device")},restore:()=>{try{const saved=JSON.parse(localStorage.getItem(viewKey)||"null");if(!saved)throw new Error();camera.position.fromArray(saved.position);controls.target.fromArray(saved.target);controls.update();setStatus("Saved viewpoint restored")}catch{setStatus("No saved viewpoint yet")}},snapshot:()=>{renderer.render(scene,camera);const link=document.createElement("a");link.href=renderer.domElement.toDataURL("image/png");link.download="mosque-build-model-view.png";link.click();setStatus("Model image exported")},glb:()=>{if(!group)return;new GLTFExporter().parse(group,result=>{const url=URL.createObjectURL(new Blob([result as ArrayBuffer],{type:"model/gltf-binary"})),link=document.createElement("a");link.href=url;link.download="mosque-build-concept-massing.glb";link.click();setTimeout(()=>URL.revokeObjectURL(url),0);setStatus("GLB model exported")},error=>setStatus(`Export unavailable: ${error.message}`),{binary:true,onlyVisible:true})}};
    const refresh=()=>{load();setStatus("Model updated from the plan")};addEventListener("mosque-build:schematic-change",refresh);setStatus("Interactive conceptual model ready");cleanup=()=>{removeEventListener("mosque-build:schematic-change",refresh);renderer.domElement.removeEventListener("pointerdown",pick);cancelAnimationFrame(animation);observer.disconnect();controls.dispose();if(group)disposeThreeTree(group);renderer.dispose();renderer.domElement.remove();api.current=null};
  }catch(error){setStatus(error instanceof Error?`3D view unavailable: ${error.message}`:"3D view unavailable. Use the room list below.")}})();return()=>{dead=true;cleanup()}},[]);
  return <section className="threeViewer" aria-labelledby={titleId}><header><div><div className="eyebrow dark">INTERACTIVE MODEL WORKSPACE</div><h2 id={titleId}>Inspect the plan in three dimensions.</h2><p>Select spaces, separate volumes, save a viewpoint and export an exchange model. All geometry remains a conceptual coordination study.</p></div><div className="threeToolbar" aria-label="Model view controls"><button type="button" onClick={()=>api.current?.view("iso")}>Isometric</button><button type="button" onClick={()=>api.current?.view("top")}>Top</button><button type="button" onClick={()=>api.current?.view("front")}>Elevation</button></div></header><div className="modelWorkbench"><div><div ref={host} className="threeCanvas"/><p className="threeStatus" role="status" aria-live="polite">{status}</p></div><aside className="modelInspector"><h3>Model inspector</h3>{selected?<dl><dt>Space</dt><dd>{selected.label}</dd><dt>Use</dt><dd>{selected.material}</dd><dt>Width × height × depth</dt><dd>{selected.size.map(value=>value.toFixed(1)).join(" × ")} m</dd><dt>Concept area</dt><dd>{selected.areaM2.toFixed(1)} m²</dd></dl>:<p>Select a volume or use the room list.</p>}<label>Separate volumes <output>{explode}</output><input type="range" min="0" max="5" value={explode} onChange={event=>{const value=Number(event.target.value);setExplode(value);api.current?.explode(value)}}/></label><label className="modelCheck"><input type="checkbox" checked={wire} onChange={event=>{setWire(event.target.checked);api.current?.wire(event.target.checked)}}/> Edge study</label><div className="inspectorActions"><button type="button" onClick={()=>api.current?.save()}>Save view</button><button type="button" onClick={()=>api.current?.restore()}>Restore</button><button type="button" onClick={()=>api.current?.snapshot()}>Export image</button><button type="button" onClick={()=>api.current?.glb()}>Export GLB</button></div></aside></div><details open><summary>Room model ({rooms.length} spaces)</summary><div className="roomPicker">{rooms.map(room=><button type="button" key={room.id} aria-pressed={selected?.id===room.id} onClick={()=>api.current?.select(room.id)}><b>{room.label}</b><span>{room.size[0].toFixed(1)} × {room.size[2].toFixed(1)} m · {room.areaM2.toFixed(1)} m²</span></button>)}</div></details><aside className="modelBoundary"><b>Coordination boundary</b><p>GLB and images are visual exchange only. Validate dimensions, accessibility, qibla, structure, fire, services and local requirements with qualified professionals.</p></aside></section>;
}
