"use client";
import {useEffect,useMemo,useState} from "react";
import {catalogQualityFlags,createAcquisitionBrief,groupCatalogBy,safeBookIds,waqfBooks} from "@/lib/waqf-catalog";
const KEY="mosque-build.waqf-book-favorites.v1";
const download=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0)};

export function WaqfCatalogInsights(){
 const[favorites,setFavorites]=useState<string[]>([]),[view,setView]=useState<"language"|"shelf_category"|"priority_tier">("language"),[message,setMessage]=useState("");
 useEffect(()=>{const read=()=>{try{setFavorites(safeBookIds(JSON.parse(localStorage.getItem(KEY)||"[]")))}catch{setFavorites([])}};read();addEventListener("mosque-build:project-change",read);addEventListener("storage",read);return()=>{removeEventListener("mosque-build:project-change",read);removeEventListener("storage",read)}},[]);
 const groups=useMemo(()=>groupCatalogBy(waqfBooks,view),[view]),issues=useMemo(()=>waqfBooks.reduce((sum,book)=>sum+catalogQualityFlags(book).length,0),[]);
 const exportFavorites=(format:"json"|"csv")=>{const brief=createAcquisitionBrief(favorites);if(!brief.items.length){setMessage("Favorite books before creating an acquisition brief.");return}if(format==="json")download("mosque-build-waqf-favorites.json",JSON.stringify(brief,null,2),"application/json");else{const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;download("mosque-build-waqf-favorites.csv",[["ID","Title","Author or compiler","Language","Subject","Working copies","Edition family","Source","Review flags"],...brief.items.map(x=>[x.id,x.title,x.authorOrCompiler,x.language,x.subject,x.workingCopies,x.editionFamily,x.source,x.qualityFlags.join("; ")])].map(row=>row.map(cell).join(",")).join("\n"),"text/csv")}setMessage(`${brief.items.length}-title review-required acquisition brief exported.`)};
 return <section className="catalogInsights" aria-labelledby="catalog-insights-title"><header><div><div className="eyebrow dark">COLLECTION INTELLIGENCE</div><h2 id="catalog-insights-title">See coverage before acquiring copies.</h2><p>Counts describe this supplied candidate list—not community demand, completeness, authenticity or approval. Use them to identify questions for curators and community consultation.</p></div><div className="insightMetrics"><span><b>{favorites.length}</b> favorites</span><span><b>{issues}</b> open metadata and review flags</span></div></header><nav aria-label="Catalog coverage view">{([['language','Languages'],['shelf_category','Subjects'],['priority_tier','Acquisition tiers']] as const).map(([id,label])=><button type="button" key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="coverageBars">{groups.map(group=><div key={group.label}><span><b>{group.label}</b><i>{group.count} titles</i></span><progress max={waqfBooks.length} value={group.count}>{group.count}</progress></div>)}</div><aside className="reviewChecklist"><h3>Before a favorite becomes a purchase</h3><ol><li>Confirm the exact work and intended audience.</li><li>Record translator, editor, publisher, edition, ISBN and volume completeness.</li><li>Complete accountable curator and qualified scholarly review.</li><li>Verify rights, seller, condition, landed cost and current availability.</li><li>Confirm shelf space, circulation, safeguarding and accessibility needs.</li></ol><div><button type="button" disabled={!favorites.length} onClick={()=>exportFavorites("json")}>Export favorite brief</button><button type="button" disabled={!favorites.length} onClick={()=>exportFavorites("csv")}>Export favorite CSV</button></div><p role="status" aria-live="polite">{message}</p></aside></section>
}
