import Link from "next/link";
import {PwaDiagnostics} from "@/components/pwa-diagnostics";
import {SiteFooter} from "@/components/site-footer";
import {SiteHeader} from "@/components/site-header";

export const metadata={title:"Install + offline guide",description:"Installation, offline, update, privacy and troubleshooting guidance for mosque.build."};
const capabilities=[["Add to your device","Add mosque.build to a supported home screen or app launcher. Browser support and wording vary by device."],["Work offline","Previously visited public pages can open offline. Unvisited pages, external sources and fresh updates still require a connection."],["Keep drafts local","The guided project brief and shortlists stay in this browser and are not uploaded by the current public site."],["Apply updates","When an update is ready, the site offers an action and reloads after it is applied."]];

export default function Page(){return <><SiteHeader/><main><section className="areaHero pwaGuideHero compactHero"><div><div className="eyebrow gold">INSTALL + OFFLINE GUIDE</div><h1>Know what works on this device.</h1><p className="heroLead">A practical guide to adding mosque.build to your device, working offline, keeping local drafts and receiving updates.</p><div className="heroActions"><Link className="button" href="/start">Create a local project brief</Link><Link className="secondaryButton lightButton" href="/resources">Browse all resources</Link></div></div></section><section className="section"><PwaDiagnostics/><div className="pwaCapabilityGrid">{capabilities.map(([title,detail],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h2>{title}</h2><p>{detail}</p></article>)}</div><section className="pwaSteps"><div><div className="eyebrow dark">ADD TO YOUR DEVICE</div><h2>Use your browser’s install option.</h2></div><ol><li>Open mosque.build in a supported browser.</li><li>Choose “Install app” or “Add to Home Screen” when offered.</li><li>Open the new icon and confirm the focused app view appears.</li></ol></section><section className="pwaSteps"><div><div className="eyebrow dark">RECOVERY</div><h2>If content looks out of date.</h2></div><ol><li>Reconnect and reopen the site.</li><li>Accept the update prompt when it appears.</li><li>If needed, close all windows and reopen once.</li><li>Clearing browser data removes local drafts and shortlists; export important records first.</li></ol></section><div className="methodBox"><b>Current boundary</b><p>Offline access covers previously saved public pages, not complete project synchronization. Notifications, shared team projects and automatic merging of changes are not available yet.</p></div></section></main><SiteFooter/></>}
